### ISSUE TITLE
Integration tests that need the apt plugin should run in right environment

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#1000]
**Describe the bug**

Some tests rely on a working tedge apt plugin.
However, in the current integration-test-workflow.yml the plugin is not installed (currently on purpose).

Until the release, I propose to run the tests manually and disable them temporarily. Afterwards, we should prepare the right environment for the tests afterwards.

This report was created to document that the tests are disabled.

Soon after the release 0.6 should do one of these:
a) Install the plugin in the workflow
b) Move the tests to a test-job where we have tedge installed (yet to be created) (e.g. a integration- or system-test crate)

https://github.com/thin-edge/thin-edge.io/pull/999

**To Reproduce**

cargo test -p tedge_apt_plugin --features integration-test 

**Expected behavior**

All green, no blocked CI

**Screenshots**

![image](https://user-images.githubusercontent.com/75477722/158436763-98f3d19c-416b-49e6-8df8-df8efc9183f6.png)

**Comment by rina23q** [comment]
Move those tests to system tests (add one step to system-test-workflow so that it can run also Rust tests)
