### ISSUE TITLE
Software list not reported for a new device on armv7

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#1002]
**Describe the bug**
A new registered device doesn't have software list.

![Screenshot from 2022-03-15 19-15-30](https://user-images.githubusercontent.com/18257209/158444793-26e6a8c9-9013-4404-8001-6ab17087049f.png)

The device installed apt and apama plugins.
There are no errors recorded either in tedge-mapper-c8y or tedge-agent services.

A software list request was sent by tedge-mapper-c8y.
```
tedge/commands/req/software/list {"id":"YnXehS3mXH9XHjl3ocPlQ"}
```
However, no reply from tedge-agent. 

A workaround is to restart tedge-mapper-c8y.
```
sudo systemctl restart tedge-mapper-c8y.service
```

Then, the device will have software list.

**To Reproduce**
- Register the device newly in Cumulocity.
- See the "Software" tab

**Expected behavior**
See the software list.

**Environment (please complete the following information):**
 - OS 
 - Hardware [Raspberry Pi 4]
 - System-Architecture [Linux raspberrypi 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux]
 - thin-edge.io version [0.6.0]

**Additional context**
I doubt the list request doesn't reach to tedge-agent.

**Comment by initard** [comment]
Seems to be working fine on my raspi

**Comment by initard** [comment]
Hi Rina, 

- what tenant were you using? which instance of Cumulocity was it? (latest, basic)

**Comment by rina23q** [comment]
The mosquitto version was older (1.5.7) than we support (1.6). After upgrading the mosquitto to 2.0.12, software list didn't get published by tedge_mapper only right after the new certificate is registered. The list has been created at most of attempts of `tedge connect c8y`. Therefore, we can close the issue.
