### ISSUE TITLE
Port invalid_device_id pysys test to rust

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#1012]
Port tests/Pysys/misc_features/invalid_device_id pysys test to rust.

The test creates the certificates using `tedge` and the `device-id` that contains the `invalid/unsupported` characters.
Assert on the error messages.

**Describe the solution you'd like**
Once the test is ported successfully, it should be able to run using `cargo test`

**Describe alternatives you've considered**

**Additional context**

**Comment by rina23q** [comment]
I think we can just remove the test, for me, it is duplicating integration test.

**Comment by rina23q** [comment]
We already have unit tests to check characters used in device ID. https://github.com/thin-edge/thin-edge.io/blob/main/crates/common/certificate/src/device_id.rs

While we work on moving from pysys to the new system test framework, we will decide if we should keep this test as system test or not. Therefore, I would close the issue.
