### ISSUE TITLE
Port mqtt port set/unset pysys tests to rust

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#1013]
Port the test that is present in tests/Pysys/misc_tests/mqtt_port_set/unset tests to rust.

The tests 
Validate changing the mqtt port using the tedge command
When `mqtt.port` is set using `tedge config mqtt.port set`
When the `tedge config is listed` and searched for the port that has been set
When the `tedge config mqtt.port unset` and searching for the `default port`

**Describe the solution you'd like**
Should run this test using `cargo test`

**Describe alternatives you've considered**

**Additional context**
use `tedge --config-dir` for setting and unsettling the port.

**Comment by rina23q** [comment]
I believe that this test can be addressed as integration test. Checking all default configs are back after unset. Currently, we don't have such tests in integration tests.
