### ISSUE TITLE
Automate apama installation in system test workflow

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#1018]
**Describe the bug**

Apama installation should be part of the system test workflow definition so that the tests can reliably run on those. Earlier we were manually installing Apama on all test slaves, which was okay with just 4 slaves, but not scalable.

**Comment by rina23q** [comment]
Update ancible playbook to install apama to RPi runners. No change on system test workflow.

**Comment by abelikt** [comment]
Added the Apama installation to the Ansible playbook that we use to update and setup our Pis. I believe the installation is better located here than in the system test workflow.

https://github.com/thin-edge/thin-edge.io_qa/tree/main/Ansible
