### ISSUE TITLE
Update supported platforms

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#1024]
**Is your feature request related to a problem? Please describe.**

We are still officially supporting Debian 10 and not Debian 11.
Even Raspberry Pi OS is using Debian 11.
To replicate our supported setup users have to download the Raspberry Pi OS Legacy Image.

https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/supported-platforms.md

Links:
https://www.raspberrypi.com/software/operating-systems/
https://ubuntu.com/#download
https://www.debian.org/News/

**Describe the solution you'd like**

Keep support for both versions or advance to the newer versions.
Our test infrastructure uses the official supported versions. Means, we have little test coverage for Debian 11.

**Comment by rina23q** [comment]
- Add RPi OS 11 to Level 2 support
- Spend 0.5 days to add a runner with RPi OS 11 image. If success, add the OS to Level1, otherwise keep it to Level 2.

**Comment by rina23q** [comment]
We added RPi OS 11 to Level 2 support. They are currently tested in other repository. We will soon add it level 1 once we add RPi  OS 11 device to our self-hosted runner.
