### ISSUE TITLE
Failed to connect Cumulocity Cloud.

### ISSUE THREAD

**Issue by Aseem90** [thin-edge/thin-edge.io#1029]
Hi,
I am trying to connect to Cumulocity cloud with Thin-Edge IO. I have followed all the installation steps as per documentation and uploaded the certificate in my Cumulocity Agent as per _tedge cert upload c8y --user <User name>_ command.
Please refer the config list as below:

![Config_List](https://user-images.githubusercontent.com/33744074/160061998-17db02a3-6f7a-42f2-8987-04de2206ec12.jpg)

Now, when I am trying to connect to cloud using _tedge connect c8y_ command but getting the error consistently. Please refer the screenshot.

![Connect_Error](https://user-images.githubusercontent.com/33744074/160062002-db894896-c136-4f8c-897a-ead57f0c5781.jpg)

The error suggested that "Broker is rejected with not authorized as the reason". Also error is suggested that I am failed to connect to the cloud. 
I would like to understand this issue that whether device authentication is failing with cloud or there is any problem in establishing the communication and want to know that when we use _cert upload_ command, will it always upload the CA cert? 
Any help around this will be much appreciated.

**Comment by albinsuresh** [comment]
> The error suggested that "Broker is rejected with not authorized as the reason". Also error is suggested that I am failed to connect to the cloud.

Could you please check if a device with the same `external id` exists already? This error can happen when you're trying to connect to an exitsing device that's already created by some other means.

> I would like to understand this issue that whether device authentication is failing with cloud or there is any problem in establishing the communication and want to know that when we use _cert upload_ command, will it always upload the CA cert? Any help around this will be much appreciated. If yes, try deleting it first and then try `tedge conect c8y`.

The cert upload will succeed irrespective of the device status, as long as you provide the tenant credentials right, while uploading the cert.

**Comment by makr11st** [comment]
Hi @Aseem90, welcome to the community.

Could you please help us with some additional infomration about the platform you are using, please provide us with following:
OS you are on,
hardware (x86/arm64/arm)
mosquitto version (`mosquitto --version`)
thin-edge.io version (`tedge --version`)

**Comment by Aseem90** [comment]
Hi @makr11st ,
Below are the information what you have asked:
OS - Ubuntu 18.04
Hardware - X86
Mosquitto version - 1.4.15
Thin-edge version - 0.5.4

I have installed thing edge and other dependencies using below script:
curl -fsSL https://raw.githubusercontent.com/thin-edge/thin-edge.io/main/get-thin-edge_io.sh | sudo sh -s 

Let me know if any other information is required.

**Comment by albinsuresh** [comment]
> Could you please check if a device with the same `external id` exists already? This error can happen when you're trying to connect to an exitsing device that's already created by some other means.

@Aseem90 Could you please confirm if this isn't the case?

**Comment by Aseem90** [comment]
Hi @albinsuresh , 
no, There is no device with the same id exist in IOT cloud.

**Comment by albinsuresh** [comment]
> Hi @makr11st , Below are the information what you have asked: OS - Ubuntu 18.04 Hardware - X86 Mosquitto version - 1.4.15 Thin-edge version - 0.5.4
> 
> I have installed thing edge and other dependencies using below script: curl -fsSL https://raw.githubusercontent.com/thin-edge/thin-edge.io/main/get-thin-edge_io.sh | sudo sh -s
> 
> Let me know if any other information is required.

I notice some issues with that setup. Neither Ubuntu v18.04 nor Mosquitto v1.4 are officially supported. Our [minimum required platform](https://thin-edge.github.io/thin-edge.io/html/supported-platforms.html#thin-edgeio-platform-support) even mandates mosquitto v1.6. So, could you please update at least your mosquitto version to the latest 1.x version so that we can rule out such incompatibilities.

**Comment by Aseem90** [comment]
> > Hi @makr11st , Below are the information what you have asked: OS - Ubuntu 18.04 Hardware - X86 Mosquitto version - 1.4.15 Thin-edge version - 0.5.4
> > I have installed thing edge and other dependencies using below script: curl -fsSL https://raw.githubusercontent.com/thin-edge/thin-edge.io/main/get-thin-edge_io.sh | sudo sh -s
> > Let me know if any other information is required.
> 
> I notice some issues with that setup. Neither Ubuntu v18.04 nor Mosquitto v1.4 are officially supported. Our [minimum required platform](https://thin-edge.github.io/thin-edge.io/html/supported-platforms.html#thin-edgeio-platform-support) even mandates mosquitto v1.6. So, could you please update at least your mosquitto version to the latest 1.x version so that we can rule out such incompatibilities.

Thanks @albinsuresh for input. Below is the update:
I have tried upgrading my "mosquitto"  to latest version but still running into the same issue.
The mosquitto is now at version 2.0.14. I have re-installed the tedge and tedge-mapper again to 0.5.4.
Let me know if anything else I can try with.

**Comment by albinsuresh** [comment]
It looks like a user permission issue. The user that you used to upload certificate may not have had enough permission to upload the certificate. I successfully managed to to connect my thin-edge device to the hillrom Cumulocity instance after granting my user the right set of permissions, primarily the role of ROLE_TENANT_ADMIN.

**Comment by Aseem90** [comment]
Sure Albin.
Thank you for your support.
