### ISSUE TITLE
As a device I want to configure thin-edge devices from Cloud

### ISSUE THREAD

**Issue by cstoidner** [thin-edge/thin-edge.io#1030]
As a device owner I want to configure thin-edge devices from Cloud.

Therfore configuration management shall be implemented as defined in specification https://github.com/thin-edge/thin-edge.io/blob/ec55002a07d24daefdb4b73075e6ce50e125c391/docs/src/references/c8y-configuration-management.md

Implement the plugin that:
- makes uses thin-edge operation plugin interface
- services C8Y filebased configuration management operations
- uploads and downloads configuration files from/to Cloud, on request by C8Y operations
- sends notification messages over MQTT per each received configuration update from the Cloud
   NOTE: Topic to be decided.
- consumes a configuration file by it-self that defines which files from filesystem to provide to C8Y 
- reports to the cloud list of all provided configuration files

For more details use the spec as referenced on top.

**Major Open Decisions:**
1) How to launch the plugin. As daemon or by the mapper on operation request? -> As daemon
2) When to send config-file list to the cloud? -> When starting the daemon
     
Details for both see spec section "Internals".
   

AC:
  1) plugin is implemented as specified
  2) plugin is available in the thin-edge repository
  3) focus of the implementation is by now restricted to C8Y

**Comment by rina23q** [comment]
- [ ] Implement upload to cloud from device (incl. declaration of config types) -> One PR
- [ ] Implement download from cloud to device -> Another PR
- [ ] Implement notifying to external services that config is updated -> Another PR
