### ISSUE TITLE
Create a "How-to install thin-edge on a device without any package manager"

### ISSUE THREAD

**Issue by cstoidner** [thin-edge/thin-edge.io#1046]
As device owner I want to be able to install thin-edge on an Embedded Linux device that does not feature any package manager.

That new "how-to" shall contain all needed instructions.

Assumptions for the customer device:
   - no package manager at all provided
   - no systemd (starting service with commandline by hand)
   - rest of root filesystem is compatible to debian

Installation of mosquitto is out of scope.

Aim of creating that "how-to" is:
   - providing that how-to to customers who want to install thin-edge manually, or want re-package it for another package manager
   - investigating any difficulties that make manual installation much complex or even impossible
     NOTE: Solving investigated difficulties is not part of that ticket.

AC:
  - list of investigated difficulties is available
  - how-to document is available
  NOTE: If it turns out that investigated difficulties make manual installation to complex, how-to document shall not be published, but difficulties solved first. Solving those difficulties is out of scope of that ticket, but shall be part of a follow-up one.

**Comment by didier-wenzek** [comment]
This issue is related to:
* This [example docker image](https://github.com/thin-edge/thin-edge.io_examples/pull/23) that can be used as a blue print of the different steps.
* [Install thin-edge with debian](https://github.com/thin-edge/thin-edge.io/issues/760)
* [Install thin-edge from source](https://github.com/thin-edge/thin-edge.io/issues/712)

**Comment by phcrb** [comment]
Hi @didier-wenzek @cstoidner,
here is a simple script I wrote that downloads from the github releases the .deb packages for a given version and a given architecture. It extracts the necessary (mostly binaries + conf), adds the daemon start scripts (no systemd) from my "scripts" folder and generates a zip to upload and unpack to the target.
It can be used as it and may be improved. 
Beaware of some hardcoded paths (/opt/tedge)
[get-tedge.txt](https://github.com/thin-edge/thin-edge.io/files/8416756/get-tedge.txt)
[scripts.zip](https://github.com/thin-edge/thin-edge.io/files/8416766/scripts.zip)

**Comment by rina23q** [comment]
Provide how-to-guide
- Build from sources
- Make it all components work without using package manager or init systems
- Identify the difficulties and write them down to improve thin-edge.io installation capabilities (don't spend efforts to solve the difficulties in this ticket) 

We should work on https://github.com/thin-edge/thin-edge.io/issues/1031 (merging all users to tedge) before this ticket.

**Comment by didier-wenzek** [comment]
There are currently 2 howto pages along these lines:

* [How to install thin-edge.io manually with OpenRC](https://thin-edge.github.io/thin-edge.io/html/howto-guides/026_how_to_install_thin_edge_manually.html)
* [How to install thin-edge.io on any Linux OS (no deb support)?](https://thin-edge.github.io/thin-edge.io/html/howto-guides/015_installation_without_deb_support.html#how-to-install-thin-edgeio-on-any-linux-os-no-deb-support)

However, these pages can be merged and improved, now that thin-edge is also released as a tarball (`*.tgz`).

**Comment by reubenmiller** [comment]
The instructions and the package formats have been extended to cover this scenario:
* [install-guide](https://thin-edge.github.io/thin-edge.io/next/install/)
* [init-system guide](https://thin-edge.github.io/thin-edge.io/next/operate/installation/init_systems/)
