### ISSUE TITLE
docker/docker-compose images are always pruned

### ISSUE THREAD

**Issue by TheNeikos** [thin-edge/thin-edge.io#1047]
**Describe the bug**

In the lifecycle of the docker plugin, the finalize step calls ['docker image prune --all --force'](https://github.com/thin-edge/thin-edge.io/blob/main/plugins/tedge_docker_plugin/tedge_docker_plugin.sh#L106) which would unconditionally remove all unused docker images whenever the docker plugin is asked to 'install/remove' something.

**Expected behavior**

ThinEdge should **not** remove things it was not asked about.

---

The same is true for the docker-compose plugin.

**Comment by didier-wenzek** [comment]
I agree that pruning *all* the images on install/remove is a cause of bad surprises.

I also wonder if this is the right place for these Docker and Docker Compose plugins. They are examples after all.

**Comment by rina23q** [comment]
AC
* Fix the reported issue.
* Then move docker and docker-compose plugins to the example repo.
* Update tests using docker and docker-compose plugins from the example repo.

**Comment by reubenmiller** [comment]
A new sm-plugin has already been created to support container management, see the [tedge-container-plugin](https://github.com/thin-edge/tedge-container-plugin) repository.

So all that is left is to remove the docker and docker-compose plugins from the project.

**Comment by reubenmiller** [comment]
Closed as the `docker` and `docker-compose` plugins have been removed from the project #2016
