### ISSUE TITLE
Enable thin-edge devices to use SmartREST 2 custom templates

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#1051]
**Is your feature request related to a problem? Please describe.**

Customers requesting for this feature: Mettler-Toledo, Hans Turck

Customer Requirements:

* The custom operation received from the cloud must be available on the local MQTT broker so that their custom operation handler can consume the same. Having all those operation messages on `c8y/s/us` topic is sufficient for now. Getting operations per child device on child device specific topics is not a requirement for now. But might come later.
* Add support for new custom operations via custom SmartREST templates (eg. an operation that can control the weighing machine settings from the cloud, in case of Mettler-Toledo)
* They use only a handful of templates, mostly just one per deployment. They don't foresee frequent additions of newer templates very often. Even if some have to be added, it won't be happening so frequently on a daily or even weekly basis.
* Whenever a new template has to be added (when a new type of sensor/device gets attached to the thin-edge device itself), they'll be physically attaching it to the device. So, manually reconfiguring the thin-edge also to accommodate the new template is acceptable. They'd like to do the same from the cloud in future (using a remote shell or something), but not an immediate requirement.

**Current solution available on thin-edge**

thin-edge.io currently doesn't have a mechanism to use a custom SmartREST 2 templates. Even though thin-edge subscribes to the `s/dc/#` topic in the hope of subscribing to "all custom templates", it doesn't work as Cumulocity doesn't support such wildcard subscriptions to "all templates". So, expose some other way so that users can use their custom templates.

**Describe the solution you'd like**

Provide a way for users to declare the interested templates via a tedge configuration like `tedge config set c8y.smartrest.templates template-1,template-2` which can be set before the user performs initial `tedge connect c8y`. The mosquitto bridge configuration will be updated to subscribe to these new template endpoints (`s/dc/template-1`, `s/dc/template-2` etc) during this connect phase.

If he wants to add more templates in future, he'll have to do `tedge disconnect c8y` first, run `tedge tedge config set c8y.smartrest.templates template-1,template-2,new-template-3` and then `tedge connect c8y` again.

**Comment by rina23q** [comment]
So the `tedge.toml` file will look like this?

```toml
[c8y]
url = 'test.cumulocity.com'
root_cert_path = '/etc/ssl/certs'
[c8y.smartrest]
templates = ['template-1', 'template-2', 'template-3']
```

I assume that `tedge config unset c8y.smartrest.template` will remove all templates. After `unset`,

```toml
[c8y.smartrest]
templates = []
```

**Comment by albinsuresh** [comment]
> So the `tedge.toml` file will look like this?
> 
> ```toml
> [c8y]
> url = 'test.cumulocity.com'
> root_cert_path = '/etc/ssl/certs'
> [c8y.smartrest]
> templates = ['template-1', 'template-2', 'template-3']
> ```

I see that my usage of dot-separated `c8y.smartrest.templates` as the key caused that confusion. I'm still not sure whether to use toml tables as in `[c8y.smartrest]` or just keep it simple with a single key named `smartrest_templates` in `[c8y]` table. Might go with the latter if there isn't a compelling reason for the former.

> I assume that `tedge config unset c8y.smartrest.template` will remove all templates. After `unset`,
> 
> ```toml
> [c8y.smartrest]
> templates = []
> ```

When it's a simple key, I expect it to get removed. Otherwise yes, as you've show here, if removing the whole `[c8y.smartrest]` table itself is tricky/harder.

**Comment by rina23q** [comment]
The background of this issue: https://github.com/thin-edge/thin-edge.io/issues/932

**Comment by rina23q** [comment]
Ah I forgot that we did a kind of small conversion, such as `c8y.root_cert_path` -> `c8y.root.cert.path` as our tedge config key.
Then I think this would be the best. The tedge config key will be `c8y.smartrest.templates`. 

```toml
[c8y]
url = 'test.cumulocity.com'
root_cert_path = '/etc/ssl/certs'
smartrest_templates = ['template-1', 'template-2', 'template-3']
```

**Comment by rina23q** [comment]
We will implement to manage smartrest custom templates by tedge config.

e.g. 
```
tedge config set c8y.smartrest.templates template-1,template-2,new-template-3
```

The template names should be translated to a valid bridge topic.
template-1 will be translated to
c8y/s/dc/template-1 (out to localhost),  s/dc/template-1 (in from c8y)
c8y/s/uc/template-1 (in from localhost), s/uc/template-1 (out to c8y)

After applying the addition of new templates, mosquitto needs to be restarted. We will document to ask user to run `tedge disconnect c8y`, then `tedge connect c8y` again.
