### ISSUE TITLE
Permission issue when updating / removing an Apama project

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#1052]
**Describe the bug**

A sequence of Apama project installations leads to a permission issue upon project removal.

```
Removing existing project at /etc/tedge/apama/project
ERROR: Directory not empty (os error 39)
```

**To Reproduce**

... see also screenshot below:

```
/usr/bin/sudo /etc/tedge/sm-plugins/apama install LimitedBandwidth::project --file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/Input/limitedbandwidth.zip

/usr/bin/sudo /etc/tedge/sm-plugins/apama install LimitedBandwidth::project --file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/Input/quickstart.zip

/usr/bin/sudo /etc/tedge/sm-plugins/apama install LimitedBandwidth::project --file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/Input/quickstart.zip
```

or run the system test:

`pysys.py run -v DEBUG "apama_plugin_update" -XmyPlatform=container`

**Expected behavior**

works :)

**Screenshots**

![image](https://user-images.githubusercontent.com/75477722/161548566-830fd5f0-d199-4687-bdeb-8983bf7eda99.png)

**Environment (please complete the following information):**
 - OS Debian buster
 - Mythic Beasts Rpi 3b+

**Additional context**

context

**Comment by rina23q** [comment]
I feel the test steps are wrong.
- Using `LimitedBandwidth::project` as the type for both LimitedBandwidth.zip and quickstart.zip
- Shouldn't you call `/usr/bin/sudo /etc/tedge/sm-plugins/apama remove LimitedBandwidth::project` before upgrading?

**Comment by rina23q** [comment]
@reubenmiller 
Shall we close this issue as `tedge_apama_plugin` is now supported by Apama Team? Regarding https://github.com/thin-edge/thin-edge.io/issues/1584

**Comment by reubenmiller** [comment]
Yes I think we can park this issue for the moment, and close it once we get confirmation about apama plugin ownership transition.

**Comment by reubenmiller** [comment]
Closing as the APAMA team has taken ownership of the plugin.
