### ISSUE TITLE
Publishing many measurements and series at once to c8y

### ISSUE THREAD

**Issue by simeonthefirst** [thin-edge/thin-edge.io#1056]
Hi,
i'm not sure if its really a thinedge bug or a Cumulocity IoT Bug, but i have to start somewhere.

**Describe the bug**
When publishing 30 measurements with **20** series each, with python paho-mqtt to the thinedge broker, they get displayed in Cumulocity IoT shortly after.
When publishing 30 measurements with **30** series each, they never appear in Cumulocity IoT. When I then try to restart (disconnect/connect) tedge then i get a connection error (see below).

The only way to get it working again for me, was to completely remove and reinstall thinedge.

**Reconnect Error**
```
sudo tedge connect c8y
The system config file '/etc/tedge/system.toml' doesn't exist. Use '/bin/systemctl' as a service manager.
Checking if systemd is available.
Checking if configuration for requested bridge already exists.
Validating the bridge certificates.
Creating the device in Cumulocity cloud.
Saving configuration for requested bridge.
Restarting mosquitto service.
Awaiting mosquitto to start. This may take up to 5 seconds.
Enabling mosquitto service on reboots.
Successfully created bridge connection!
Sending packets to check connection. This may take up to 2 seconds.
ERROR: Local MQTT publish has timed out.
Warning: Bridge has been configured, but Cumulocity connection check failed.
Checking if tedge-mapper is installed.
Starting tedge-mapper-c8y service.
Persisting tedge-mapper-c8y on reboot.
tedge-mapper-c8y service successfully started and enabled!
Local MQTT publish has timed out.
The request has been sent, however, no response.
Failed to get the connected tenant URL from Cumulocity.
Enabling software management.
Checking if tedge-agent is installed.
Starting tedge-agent service.
Persisting tedge-agent on reboot.
tedge-agent service successfully started and enabled!
```

**Environment:**
- Raspberry Pi 3
- Operating System: Debian GNU/Linux 11 (bullseye)
- Kernel: Linux 5.10.103-v8+
- Architecture: arm64
- thin-edge.io version 0.6.0
- local mosquitto broker 2.0.11
-
- Cumulocity IoT Backend 1011.0.19

**Additional context**
Is there a maximum of measurements/series somewhere defined? I only know the MQTT payload maximum of Cumulocity IoT which is 16184 bytes. (The payload in the tests i did was smaller )

**Comment by makr11st** [comment]
Hi @simeonthefirst, welcome to thin-edge.io.

There are no hard limits on the throughput of thin-edge in your local environment, but there may be a throttling applied to your cloud tenant though.

Would you mind sharing the script you are using to publish the messages on local bus as it would help us determine what is going on?

**Comment by simeonthefirst** [comment]
Hi @makr11st, thank you for your fast response.

this is the script i used (sorry for the added complexity for splitting the messages when the message size limit is reached):

```
import json
import socket
import sys
from datetime import datetime

import paho.mqtt.client as mqtt

port = 1883
broker_address = "localhost"
device_name = socket.gethostname()
numMeasurements = 30
numSeries = 20 #failed when set from 20 to 30


def send_measurement_to_thinedge(payload: dict):

    # C8Y:maximum accepted payload size is 16184 bytes
    # split payload
    time_saved = payload["time"]
    del payload["time"]

    pl_tmp = dict()
    # pl_tmp["time"] = time_saved

    for key in payload.keys():

        pl_done = pl_tmp.copy()
        pl_tmp[key] = payload[key]
        print("sys.getsizeof(json.dumps(pl_tmp): ",sys.getsizeof(json.dumps(pl_tmp)))

        if sys.getsizeof(json.dumps(pl_tmp)) > 16180:
            client.publish("tedge/measurements", json.dumps(pl_done))
            # print("published part: " + json.dumps(pl_done))
            print("published part: " + str(pl_done.keys()))

            # new package
            pl_tmp = dict()
            # pl_tmp["time"] = time_saved
            pl_tmp[key] = payload[key]

    client.publish("tedge/measurements", json.dumps(pl_tmp))
    # print("published: " + json.dumps(pl_tmp))
    # print("published rest: " + str(pl_tmp.keys()))  

    return


def build_mockup_measurements(numMeasurements, numSeries, value=5):
    """
    produces dict 
    when numMeasurements=2 and numSeries=2:
    {"measurement_0": {"series_0": 5, "series_1": 5}, "measurement_1": {"series_0": 5, "series_1": 5},"time":}
    
    """
    d = {}
    ser = {}
    for s in range(numSeries):
        ser["series_" + str(s)] = value
    for m in range(numMeasurements):
        d["measurement_" + str(m)] = ser
    d["time"] = datetime.now().isoformat()

    return d


if __name__ == "__main__":
    client = mqtt.Client(device_name)
    client.connect(broker_address, port)

    j = build_mockup_measurements(numMeasurements, numSeries)

    send_measurement_to_thinedge(j)

```

**Comment by simeonthefirst** [comment]
Actually, I think checking the size and splitting the MQTT Message in chunks on that place (as i did) does not make much sense, because the mapper adds some stuff to the message before forwarding it to c8y. 

Is there something implemented in thinedge that checks if the MQTT message size exceeds the max of 16184 bytes before forwarding it? Maybe the missing of that logic is a reason for that confusing error state tedge is getting into.

**Comment by makr11st** [comment]
Hi @simeonthefirst,

We have had run some tests and we found that there is a problem with tedge, it seems that the message over the threshold are being stuck in a broker, instead of being sent over HTTP as it used, we will mark it a bug and fix asap.

**Comment by rina23q** [comment]
Solve the bug which sends a message > 16KiB to Cumulocity. This causes unstable state of mosquitto, where the cumulocity never returns ack to mosquitto and the bridge config is QoS = 2. We have the size check of incoming message, however, we don't have the size check of output message. The size of output message should be checked.

Proposal 1)
Reject such a large request. The mapper rejects the message and gives an error. The mosquitto config `bridge_max_packet_size value` can be also helpful as a second level protection.

Proposal 2)
If the size is large, send the measurement via HTTP.

Proposal 3) 
If the output size > 16 KiB, mapper will split the measurements to smaller chunk. E.g. 

From
```
{"measurement_0": {"series_0": 5, "series_1": 5}, "measurement_1": {"series_0": 5, "series_1": 5},"time":<timestamp>}
```
To
```
{"measurement_0": {"series_0": 5, "series_1": 5},"time":<timestamp>}
{"measurement_1": {"series_0": 5, "series_1": 5},"time":<timestamp>}
```

If the measurements can't be split, the mapper refuse the measurement and report an error.

---

As a quick fix, first we will implement the proposal 1). Then, we will decide how to allow user to send such a large measurement to c8y.
