### ISSUE TITLE
Purging mosquitto removed tedge

### ISSUE THREAD

**Issue by initard** [thin-edge/thin-edge.io#1061]
**Describe the bug**

If we run `sudo tedge apt purge mosquitto` `tedge, tedge_mapper, tedge_agent, tedge_logfile_request` are also removed: 

**To Reproduce**

run `sudo apt purge mosquitto`
**Expected behavior**

This should not remove tedge. 

**Screenshots**

![image](https://user-images.githubusercontent.com/78221071/162186578-dd9e87f0-0e59-4c9c-b98d-5ca4d091a7e7.png)

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [e.g. 0.1.0]

**Additional context**

**Comment by rina23q** [comment]
Because `tedge` package has dependency on `mosquitto`. Without mosquitto, `tedge` won't work. For me, it's desired behaviour.

**Comment by makr11st** [comment]
Why would it be desired behaviour?

**Comment by rina23q** [comment]
I want to know why you will be happy if the removal of the dependency on mosquitto from `tedge` package.
From my point of view, the current dependency helps users
- Installing `tedge` invokes the installation of `mosquitto` automatically.
- As of now, `tedge connect/disconnect` doesn't work without `mosuqitto`.

**Comment by makr11st** [comment]
> However, tedge connect and disconnect still use mosquitto.

This is always assuming I'm using tedge cli, I needed to purge my mosquitto configuration because of the broken state, but because of that dependency also my entire tedge installation has been purged without a warning.

I would expect that on my device I can have things installed in any order I prefer and the most important by uninstalling a package for whatever reason another one is not being removed.

**Comment by rina23q** [comment]
Okay, it seems more troubles than benefits, so I'm now fine to remove the dependency.

Actually our [get-thin-edge_io.sh](https://github.com/thin-edge/thin-edge.io/blob/main/get-thin-edge_io.sh) script installs mosquitto explicitly. Also [our installation guide](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/howto-guides/002_installation.md) mentioned the step to install mosquitto as well. Also, the test workflow has the step to install mosquitto. 

So, we just remove the dependency without changing other script or docs.

**Comment by rina23q** [comment]
1. Investigate to find a solution to keep a soft dependency by debian package management
2. If we can't find a good solution, remove the dependency on mosquitto from tedge.
