### ISSUE TITLE
tedge --config-dir  connect c8y is not updating the /etc/tedge/moquitto.conf

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#1075]
**Describe the bug**
When `tedge --config-dir /path/to/config connect c8y` is used to connect to c8y cloud, the `/etc/mosquitto/mosquitto.conf` must use 
the config file from /path/to/config/moquitto-conf/tedge-mosquitto.conf` 

**To Reproduce**
Create all the configs using --config-dir
Connect to c8y using `tedge --config-dir /path/to/config c8y`

**Expected behavior**
The `/etc/mosquitto/mosquitto.conf`,
must include `/path/to/config/moquitto-conf/tedge-mosquitto.conf` 

**Screenshots**

**Environment (please complete the following information):**
 - OS: ubuntu
 - Hardware : x86
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version:0.6.1

**Additional context**

**Comment by rina23q** [comment]
The use-case of `--config-dir` is more for testing.

Solution:
- Add a new reference documentation to explain `--config-dir`, and prepare a section which mentions that user needs to add the config path to mosquitto.conf. Don't mention how to add the path to mosquitto.

Out of scope:
- Stop adding `include_dir /etc/tedge/mosquitto-conf` directly to `/etc/mosquitto/mosquitto.conf`, and place a new file to `/etc/mosquitto/conf.d/`. Changing a file not owned by us is a bad practice.
