### ISSUE TITLE
Cumulocity mapper fails to process messages when connected to a thick-edge VM

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#1082]
**Describe the bug**

When Cumulocity mapper starts, it tries to fetch the internal id of the connected device before it starts processing any incoming messages on `tedge/#` topics. This "internal id fetch" call is failing with the following error from the `reqwests` library client that we're using:

```
Apr 13 15:32:29 alsu-VirtualBox tedge_mapper[75187]: 2022-04-13T10:02:29.438508138Z  WARN init: rustls::check: Received a ServerHelloDone handshake message while expecting [CertificateRequest]
Apr 13 15:32:29 alsu-VirtualBox tedge_mapper[75187]: 2022-04-13T10:02:29.438552285Z  WARN init: rustls::conn: Sending fatal alert BadCertificate
Apr 13 15:32:29 alsu-VirtualBox tedge_mapper[75187]: 2022-04-13T10:02:29.438636561Z ERROR init: c8y_api::http_proxy: An error ocurred while retrieving internal Id, operation will retry in 60 seconds and mapper will reinitialise.
Apr 13 15:32:29 alsu-VirtualBox tedge_mapper[75187]:  Error: FromReqwest(reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("myown.iot.com")), port: None, path: "/identity/externalIds/c8y_Serial/albin", query: None, fragment: None }, source: hyper::Error(Connect, Custom { kind: Other, error: Custom { kind: InvalidData, error: InvalidCertificateData("invalid peer certificate: UnknownIssuer") } }) })
```

We're getting this `BadCertificate` error even though the thick-edge server's root certificate chain is added to `/etc/ssl/certs` directory on the thin-edge device. The `tedge cert upload c8y` command also fails for the same reason as follows:

```
$ sudo tedge cert upload c8y --user admin
Enter password: 
Error: failed to upload root certificate

Caused by:
    HTTP Connection Problem: invalid peer certificate: UnknownIssuer 
    Hint: Server certificate validation error.
```

The validity of this certificate setup could be confirmed with a direct secure MQTT connection from that thin-edge to that thick-edge VM, using the same certificates used by thin-edge, as follows: 

```
$ sudo mosquitto_sub -d -h myown.iot.com -p 8883 --capath /etc/ssl/certs/ --key /etc/tedge/device-certs/tedge-private-key.pem --cert /etc/tedge/device-certs/tedge-certificate.pem -i albin -t s/ds 
Client albin sending CONNECT 
Client albin received CONNACK (0) 
Client albin sending SUBSCRIBE (Mid: 1, Topic: s/ds, QoS: 0, Options: 0x00) 
Client albin received SUBACK 
Subscribed (mid: 1): 128 
```

From the above result, it's fairly obvious that the connectivity issue is limited to https calls from thin-edge. It looks like the `rusttls` library that's used by thin-edge is not picking up the certificates from `/etc/ssl/certs` directory. So, fixing this root-cause can fix both issues.

**To Reproduce**

Connect thin-edge to a thick-edge VM and check the `tedge cert upload c8y` command or the `tedge-mapper-c8y` service logs.

**Expected behavior**

* `tedge cert upload c8y` should succeed
* `tedge-mapper-c8y` should successfully fetch the internal id of the connected device and process messages `tedge/#` topics

**Comment by rina23q** [comment]
We need to find a bug, and fix so that our HTTP client can take the certificate `/etc/ssl/certs`. It worked a half year ago.

Reference:
https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/howto-guides/010_add_self_signed_trusted.md

**Comment by didier-wenzek** [comment]
@albinsuresh mentioned that `tedge cert upload` is not working with 0.4.3 release either.

**Comment by PradeepKiruvale** [comment]
I got the below error

sudo mosquitto_sub -d -h myown.iot.com -p 8883 --capath /etc/ssl/certs/ --key /etc/tedge/device-certs/tedge-private-key.pem --cert /etc/tedge/device-certs/tedge-certificate.pem -i thickedge -t s/ds

Client thickedge sending CONNECT
OpenSSL Error[0]: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Error: A TLS error occurred.

**Comment by PradeepKiruvale** [comment]
Now I could create the device in `Cumulocity` using the direct connection. But the `bridge` connection fails. with below error. Basically, the certification failed.

Connecting bridge (step 1) edge_to_c8y (myown.iot.com:8883)
1650682685: Connecting bridge (step 2) edge_to_c8y (myown.iot.com:8883)
`1650682685: OpenSSL Error[0]: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed`
1650682685: Client Cumulocity disconnected: Protocol error.

**Comment by PradeepKiruvale** [comment]
The `reqwest rusttls` does not consider a self-signed certificate as a valid TLS certificate  So, while building the `requestClientBuilder` one should use `danger_accept_invalid_certs()` (https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.danger_accept_invalid_certs) to disable certificate validation
After changing this the `tedge cert upload c8y` works fine.

**Comment by albinsuresh** [comment]
> The `reqwest rusttls` does not consider a self-signed certificate as a valid TLS certificate

Can't `rusttls` be configured to properly validate a self-signed certificate even when that certificate chain is installed in `/etc/ssl/certs` directory?

**Comment by PradeepKiruvale** [comment]
The `rustls` uses `webpki` underneath. So, the `self-signed` certs are not allowed in `webpki`. There is a pending PR to address this https://github.com/briansmith/webpki/pull/127. 

Here you can find the similar issue https://github.com/rustls/rustls/issues/143
