### ISSUE TITLE
Error message on invalid json is sometimes missing

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#1083]
**Describe the bug**

System test tedge_mapper_c8y_negative sometimes detects a missing error message

Also doublecheck with the new Rust test. 

**To Reproduce**

`pysys.py run tedge_mapper_c8y_negative `

**Expected behavior**

Error message:

`tedge/errors Invalid JSON: EOF while parsing an object at line 1 column 1: `{``

**Comment by didier-wenzek** [comment]
Is the test missing messages or the mapper that is actually not sending them?

**Comment by abelikt** [comment]
Hi, sorry, when this was not precise enough. My observation was that the error message is not appearing when subscribing to # (Either not sent or not received by mosquitto_sub).
Cannot retest as the tests now as were gone with merging #958.

**Comment by rina23q** [comment]
This test is removed from system test and ported to integration test by #1062. Therefore, I would close the issue.
