### ISSUE TITLE
Software list is missing on Rpis

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#1087]
**Describe the bug**

The software list is not appearing in C8y when uploaded from a Raspberry Pi.

To my opinion we should find a way of checking if the software list was not uploaded since this is an issue that we have repeatedly.

**To Reproduce**

    pysys.py run -XmyPlatform=container sm_apt_install_download_path

**Expected behavior**

Software list is appearing in C8y after it was uploaded.

**Screenshots**

![image](https://user-images.githubusercontent.com/75477722/163544410-a48c0842-9445-4417-8a76-6abf2118162a.png)

**Environment (please complete the following information):**

Thin-Edge.io 0.6.1; built on current HEAD
Works: amd64; Debian  Bullseye
Does not work: Rpi 3b+, Rpi at Mythic Beasts; Debian Buster

**Additional context**

context

**Comment by rina23q** [comment]
The test should subscribe the software list topic to check if the list has been sent by tedge-agent.

**Comment by abelikt** [comment]
Problem is reproducible on a hosted Rapberry Pi 3b.
(And not a local Rpi 3b+ and not on x86)

Log from Rpi 3b:
![image](https://user-images.githubusercontent.com/75477722/168593073-c23e5108-ebd7-40c8-845f-559df80d5c2e.png)

On a 3b+ we see the status "executing":
![image](https://user-images.githubusercontent.com/75477722/168593201-97ccd9ac-fdf7-4c96-820e-b5b5012f46b7.png)

**Comment by abelikt** [comment]
On a local Rpi 3b (no plus) I observe that we upload a software list when we delete a device and then connect. However, that does not seem to work out, when we use configure script (ci/configure_bridge.sh) there I observe that we do not send a software list.

**Comment by PradeepKiruvale** [comment]
From my investigation I found that the `tedge_agent --init` is not creating a session on mosquitto broker. This is the reason why the messages that were sent earlier to the `tedge_agent` are being missed.
To reproduce this issue.
`
### Initialize the tedge_agent
runuser -u tedge --  tedge_agent --init
### Send a software list request
tedge mqtt pub tedge/commands/req/software/list '{"id":"Vi_0XLZolo3qgIXaPmAac"}'
### Start the agent
runuser -u tedge --  tedge_agent
`

Now the `tedge_agent` should have received the requests that are sent in its absense and processed them, but its not receiving them.

**Comment by PradeepKiruvale** [comment]
Looks like similar issue reported here https://github.com/eclipse/mosquitto/issues/2519

**Comment by PradeepKiruvale** [comment]
With [this ](https://github.com/albinsuresh/thin-edge.io/tree/bug/1135/restart-operation-stuck-executing)fix it works, provided 
If we run the below commands before every `tedge connect`

```
tedge --init

tedge_mapper --init c8y

tedge_agent --init
```

**Comment by PradeepKiruvale** [comment]
Since this looks like the `mosquitto` issue with persistance sessions. As a work aorund to make it to work one has to `restart the tedge_mapper c8y` service after `tedge connect c8y` if the mapper fails to send the `software list` to the `c8y` cloud.
