### ISSUE TITLE
System test tedge_mapper_c8y_child_device_measurement is instable

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#1088]
**Describe the bug**

System Test tedge_mapper_c8y_child_device_measurement is instable, needs fixed and extensions that help to investigate.

On my PC the test sporadically fails. In CI, the test always fails but with a different reason.

**To Reproduce**

pysys.py run tedge_mapper_c8y_child_device_measurement

**Expected behavior**

works always

**Screenshots**

On my computer:

![image](https://user-images.githubusercontent.com/75477722/163951430-642dcf78-c8ef-4c72-8126-e740ec983e78.png)

Next invocation on my computer:

![image](https://user-images.githubusercontent.com/75477722/163951970-68536363-5bc4-471b-b665-2396fbfb5563.png)

On a hosted Rpi and  in CI:

![image](https://user-images.githubusercontent.com/75477722/163952071-ddffd4ea-a0ee-4e1f-8c9e-ab039aeae9b1.png)

**Comment by abelikt** [comment]
Update: Seems to pass in CI. Failure rate on my PC has widely decreased to approx 2%.

**Comment by rina23q** [comment]
The purpose of this test is to check the behaviour of our feature "measurements for child device". The test will be replaced by our new system test framework, therefore I would close the issue.
