### ISSUE TITLE
Delete uploaded certificates

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#1089]
**Is your feature request related to a problem? Please describe.**

Every once in a while we should delete uploaded certificates from C8y.

**Describe the solution you'd like**

Have a small script in the QA repo that does the job with the c8y_api. Unsure if we should just delete all certificates or avoid some that are in use.

**Describe alternatives you've considered**

It was mentioned that even millions of certificates shouldn't matter. So the alternative is to do nothing :)

**Additional context**

context

**Comment by rina23q** [comment]
* Prepare a script to remove all certificates from the eu-latest tenant in the QA repo.
* We run the script manually from time to time.

**Comment by rina23q** [comment]
This issue is still valid.
* We still run smoke tests to Cumulocity.
* The script [`configure_bridge.sh`](https://github.com/thin-edge/thin-edge.io/blob/main/ci/configure_bridge.sh#L34) creates a device certificate on every run and upload it to our Cumulocity tenant.

**Comment by reubenmiller** [comment]
If this is just for the CI/CD runner, then we could use my open source tool [go-c8y-cli](https://goc8ycli.netlify.app/)

After setting the required environment variables for the url, username, password etc, deleting all of the certificates can be done using:

```sh
c8y devicemanagement certificates list --includeAll  | c8y devicemanagement certificates delete
```

**Comment by rina23q** [comment]
> If this is just for the CI/CD runner, then we could use my open source tool [go-c8y-cli](https://goc8ycli.netlify.app/)
> 
> After setting the required environment variables for the url, username, password etc, deleting all of the certificates can be done using:
> 
> ```shell
> c8y devicemanagement certificates list --includeAll  | c8y devicemanagement certificates delete
> ```

After I saw your demo, I came back to this issue as I really think this is the solution :) It is just for the CI/CD runner.

**Comment by didier-wenzek** [comment]
Is this still relevant? I don't think so.

**Comment by reubenmiller** [comment]
The new integration test setup does an automatic cleanup of any uploaded device certificates to Cumulocity IoT.
