### ISSUE TITLE
Update from 0.5.1 to 0.6.2 failed

### ISSUE THREAD

**Issue by anonymosh** [thin-edge/thin-edge.io#1093]
**Describe the bug**
I loaded the Debian packages for 0.6.2 and tried to install tedge, tedge-agent and tedge-mapper via dpkg.
Running dpkg yields an error if I try to install the mapper:

> pi@raspberrypi:~/tedge/v062 $ sudo dpkg -i tedge_mapper_0.6.2_armhf.deb
> (Lese Datenbank ... 58881 Dateien und Verzeichnisse sind derzeit installiert.)
> Vorbereitung zum Entpacken von tedge_mapper_0.6.2_armhf.deb ...
> Entpacken von tedge_mapper (0.6.2) über (0.6.2) ...
> tedge_mapper (0.6.2) wird eingerichtet ...
> 2022-04-20T14:28:28.337018038Z  INFO flockfile::unix: Lockfile created "/run/lock/tedge-mapper-c8y.lock"
> 2022-04-20T14:28:28.337116371Z  INFO tedge_mapper::c8y::mapper: Initialize tedge mapper c8y
> Error: Creating the file failed: "/etc/tedge/operations/c8y/c8y_SoftwareUpdate".
> dpkg: Fehler beim Bearbeiten des Paketes tedge_mapper (--install):
>  »installiertes tedge_mapper-Skript des Paketes post-installation«-Unterprozess gab den Fehlerwert 1 zurück
> Fehler traten auf beim Bearbeiten von:
>  tedge_mapper

Looking at the post-install script I can see that tedge-mapper should be part of the tedge group, but it wasn't for me.

> pi@raspberrypi:~/tedge/v062 $ groups tedge-mapper
> tedge-mapper : tedge-mapper

After doing a 

> pi@raspberrypi:~/tedge/v062 $ sudo usermod -a -G tedge tedge-mapper

it still didn't work so I checked the operations directory and it looks like it belongs to tedge:

> pi@raspberrypi:~/tedge/v062 $ ls -la /etc/tedge/
> insgesamt 40
> drwxr-xr-x   9 tedge       tedge       4096 Feb  9 13:15 .
> drwxr-xr-x 102 root        root        4096 Apr 20 14:37 ..
> drwxr-xr--   2 tedge-agent tedge-agent 4096 Jan 28 17:13 .agent
> drwxr-xr-x   3 root        root        4096 Jan 28 16:31 contrib
> drwxr-xr-x   2 mosquitto   mosquitto   4096 Feb  9 09:31 device-certs
> drwxr-xr-x   2 tedge       tedge       4096 Feb 16 10:19 mosquitto-conf
> drwxr-xr-x   4 tedge       tedge       4096 Jan 28 16:31 operations
> drwxr-xr-x   2 tedge       tedge       4096 Jan 28 16:31 plugins
> drwxr-xr-x   2 root        root        4096 Jan 28 16:37 sm-plugins
> -rw-r--r--   1 tedge       tedge        248 Jan 28 17:13 tedge.toml

Changing the owner did resolve the problem for me:

> sudo chown -R tedge-mapper:tedge-mapper /etc/tedge/operations/

**To Reproduce**
I'm not entirely sure what caused this, but I suspect that the owner of the directory changed over the versions (or that the additional group membership was added later on). So installing an old version and then following the upgrade scenario described [here ](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/howto-guides/002_installation.md#upgrading-thin-edgeio) should yield the error.

**Expected behavior**
Thin-edge.io should be able to update (following the instructions) via dpkg without any problems

**Environment:**
- Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
- thin-edge.io version 0.6.2
- raspbian 10.11

**Comment by PradeepKiruvale** [comment]
@anonymosh The fix for this issue is in progress.
As a workaround, please change the ownership of the files present in `/etc/tedge/operations/c8y/` directory.
`sudo chown tedge-mapper:tedge-mapper /etc/tedge/operations/c8y/*`

Then try upgrading to 0.6.2.

**Comment by rina23q** [comment]
- [ ] The maintainer script of debian package should call [upgrade_tedge_0.6.sh](https://github.com/thin-edge/thin-edge.io/blob/main/configuration/contrib/tedge_upgrade/upgrade_tedge_0.6.sh) script in `preinst` if it's called for upgrading.
- [ ] Write about this script in the release note of 0.6.3 and 0.7.0.

**Comment by PradeepKiruvale** [comment]
@anonymosh We have fixed this issue. Could you please check the fix upgrading from 0.6.2 to 0.6.4?.

**Comment by rina23q** [comment]
Since we fixed the issue, and no new comment for more than two weeks, I would like to close this issue.
