### ISSUE TITLE
Finalize the configuration management plugin

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#1107]
The configuration management plugin can be improved by:

* Giving a type name to a config file as in `{ type='mosquitto', path="/etc/mosquitto/mosquitto.conf" }`
* Addressing the issue with the owner and mod of configuration files created on download. Consider here to add `owner` and `mod` to the config file record definition.
* Resending the list of configuration files when the plugin configuration file is updated.
* Using update notification topic specific for each configuration type.
* Updating the documentation accordingly

One can also consider adding a temporary target path, to open the opportunity for a component to check any freshly downloaded config before making this config effective.

**Comment by rina23q** [comment]
Is the `type` mandatory? If we use the type on the MQTT topic name to notify the change (`tedge/configuration_change/<type>`), it must be the mandatory filed. Otherwise, the `type` can be optional, if it's not specified, use the `path` as the type.

**Comment by rina23q** [comment]
Adding a "type" field
- [ ] The configuration file can accept `type` field.
- [ ] The `type` filed is optional. If it's missing, use the `path` as the `type`.
- [ ] The default type of the plugin configuration file is hard-coded as `c8y-configuration-plugin`.
- [ ] If there are duplicated types defined in the config file, consider the file is mal-formed. Report only `c8y-configuration-plugin` as a supported config type and record a warning in the log.

Addressing file permissions
- [ ] Add `owner` and `mod` in the config file definition.

Resending the supported config list after the plugin configuration updated
- [ ] Do it

Using update notification topic specific for each configuration type.
- [ ] Do it

Updating the documentation accordingly
- [ ] Do it
