### ISSUE TITLE
A dedicated instance of Cumulocity IoT Edge for thin-edge ci/cd 

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#1115]
**Is your feature request related to a problem? Please describe.**
The thin-edge provides the connectivity to Cumulocity IoT Edge. So, it's better to test this feature before the release of thin-edge version.

**Describe the solution you'd like**
A dedicated instance of Cumulocity IoT Edge, will be helpful for CI/CD of thin-edge.

**Describe alternatives you've considered**

**Additional context**
Has to be kept re-provisioned as and when the newer version of `Cumulocity IoT Edge` version is available.

**Comment by didier-wenzek** [comment]
Not a priority
