### ISSUE TITLE
Move the certificate management to a common place

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#1122]
**Is your feature request related to a problem? Please describe.**
Thin-edge uses the certificate to connect to the cloud. So, the certificate management code is duplicated in different places.
For certificate management thin-edge uses `rustls`. So, its better to move this duplicated code to one commonplace and reuse it across different places.

The other advantage is, if `rustls` version has to be changed/updated then it's easy to change at one place, instead of changing at multiple places.

**Describe the solution you'd like**
Move all the certificate management code to a separate crate.

**Describe alternatives you've considered**

**Additional context**

**Comment by didier-wenzek** [comment]
There is already the crate `crates/common/certificate` for that purpose.

**Comment by rina23q** [comment]
Currently, we have 3 places that directly use `rustls`.
1. tedge connect
2. tedge-mapper --init
3. tedge cert upload

**Comment by rina23q** [comment]
It is related to https://github.com/thin-edge/thin-edge.io/issues/1219

**Comment by gligorisaev** [comment]
My assuption is that if all functionalities concerning certificate management like:
tedge connect
tedge-mapper --init
tedge cert upload
are functioning after this improvement than no additional tests are needed to be created, this feature is tested by the other tests.

Tested and functioning
