### ISSUE TITLE
Possible issues with requesting logs

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#1123]
**Describe the bug**

All system-tests regarding log requests are failing.
The log request can be manually observed from C8y, but we receive no content in the system-test.

log_request_error_messages

![image](https://user-images.githubusercontent.com/75477722/166418103-70546da3-5c1e-4a30-86a6-1a095cc1340f.png)

log_request_num_lines

![image](https://user-images.githubusercontent.com/75477722/166418017-9cdb178c-01b8-452d-9c5b-c14d90255c06.png)

**To Reproduce**

source ~/env-pysys/bin/activate
pysys.py run -v DEBUG log_request_error_messages
pysys.py run -v DEBUG log_request_num_lines

**Expected behavior**

Works :)

**Screenshots**

See above

**Environment (please complete the following information):**
 - OS Debian 10,11
 - Rpi, X86

**Comment by rina23q** [comment]
- Does the dummy log file generation work properly? -> We don't know. So, we should add a check that confirms the dummy log file was properly created before uploading a logfile.
- We are working on the refactoring of the log file plugin. -> The system test should be applicable to the new plugin as well.
