### ISSUE TITLE
Broken links in docs (Introduction -> Grow your skills)

### ISSUE THREAD

**Issue by kpalf** [thin-edge/thin-edge.io#1130]
**Is your documentation request related to a problem? Please describe.**
Documentation as seen at 5 May 2022 has 4 broken links (404 result) on the following page:
https://thin-edge.github.io/thin-edge.io/html/001_overview.html
All 4 links in the bottom section, "Grow your skills".  Each of them references a different README, but none are resolved.

**Comment by kpalf** [comment]
Same README links also broken from https://thin-edge.github.io/thin-edge.io/html/SUMMARY.html

**Comment by didier-wenzek** [comment]
The point to have these files `README.md` and not `index.md` is to be able to browse the documentation directly on github without having to build it.

**Comment by rina23q** [comment]
I confirmed #1162 fixed the broken links. Therefore, I'd like to close this issue.
