### ISSUE TITLE
MQTT health endpoints for tedge plugin extensions

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#1172]
The following tedge daemons currently don't honour the tedge health check mechanism:

* `c8y-configuration-plugin`
* `c8y-log-plugin`
*  `tedge-watchdog`

These daemons must also implement the tedge health-check contract by exposing health endpoints via `tedge/health/<plugin-name>` topics.

**Comment by gligorisaev** [comment]
@PradeepKiruvale I really need to be able to see how is this issue Resolved, please add the Information

**Comment by gligorisaev** [comment]
GIVEN   thin-edge.io is installed on DUT
AND      Connected to Cumulocity (`sudo tedge connect c8y`)
AND      Log plugin service is started  (`sudo systemctl start c8y-log-plugin.service`)
AND      You have noted the PID of the c8y-log-plugin.service
WHEN   You start a mqtt subscriber
AND.      You send an empty message on

**Comment by rina23q** [comment]
Resolved by #1299
