### ISSUE TITLE
Upgrade the Azure IoT certificate for CI/CD devices

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#1177]
**Describe the bug**
Azure is replacing the `Baltimore cyber trust cert` with the `Digi cert root certificate`.
Once replaced the thin-edge device should connect to the `Azure IoT` without any issue.

**To Reproduce**
Try connecting to the "Azure cloud" using `tedge connect az`

**Expected behavior**
Should connect successfully and publish the measurements.

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [e.g. 0.1.0]

**Additional context**
More information can be found [here](https://techcommunity.microsoft.com/t5/internet-of-things-blog/azure-iot-tls-critical-changes-are-almost-here-and-why-you/ba-p/2393169)

**Comment by rina23q** [comment]
I don't think we need something specific action rather than the doc change.
https://thin-edge.github.io/thin-edge.io/html/tutorials/connect-azure.html#configure-the-device

**Comment by rina23q** [comment]
In addition, as of now, we just need to check all self-hosted runners have `DigiCert_Global_Root_G2.pem` certificate in `/etc/ssl/certs`.
