### ISSUE TITLE
c8y_configuration_plugin --init and c8y_log_plugin --init are overwriting exiting files

### ISSUE THREAD

**Issue by toewsar** [thin-edge/thin-edge.io#1189]
**Describe the bug**
The configuration files `c8y-configuration-plugin.toml` and `c8y-log-plugin.toml` will be overwritten on each thin-edge update. 
On each installation of `c8y-configuration-plugin` and `c8y-log-plugin` the `--init` method will be executed, which should create files and folders which not exists, or which are maleformed.
But the actual behavior is, that the files are recreated every time, even if they are modified.
That means if, someone has changed the `c8y-configuration-plugin.toml` or `c8y-log-plugin.toml` it will be overwritten by the `--init` method.

**To Reproduce**
Modifiy `c8y-configuration-plugin.toml` and `c8y-log-plugin.toml` and run `c8y_configuration_plugin --init` and `c8y_log_plugin --init`.

**Expected behavior**
Modified files (if they are still valid) shoud not be overwritten by `c8y_*_plugin --init`.

**Environment (please complete the following information):**
 - Raspbian OS
 - Raspberry PI 4
 - armhf
 - thin-edge.io version [0.7.0]

**Comment by rina23q** [comment]
`--init` is intended to be called only once, however, if user calls more than once, it should not break anything.

1) We should check all `--init` that creates new files and directories because the same problem occurs in other `--init`.
2) Extend the function where creates files and directories. If already exist, give warning to user that the file/dir already exists. (don't overwrite the existing ones)

**Comment by PradeepKiruvale** [comment]
1. Test `tedge_mapper --init c8y` 
GIVEN thin-edge installed on DUT
AND note down the creation time of the below files
`/etc/tedge/operations/c8y/c8y_Restart
/etc/tedge/operations/c8y/c8y_SoftwareUpdate`
WHEN I run the command
`sudo runuser -u tedge -- tedge_mapper --init c8y`
THEN the above-mentioned file's creation time must be the same as before.

2. Test `tedge_agent --init` 
GIVEN thin-edge installed on DUT
AND note down the creation time of the below directory
`/etc/tedge/.agent
WHEN I run the command
`sudo runuser -u tedge --  tedge_agent --init`
THEN the above-mentioned directory's creation time must be the same as before.

3. Test `c8y_configuration_plugin --init`
GIVEN thin-edge installed on DUT
AND note down the creation time of the below files
`/etc/tedge/c8y/c8y-configuration-plugin.toml
/etc/tedge/operations/c8y/c8y_UploadConfigFile
/etc/tedge/operations/c8y/c8y_DownloadConfigFile`
WHEN I run the command
`sudo c8y_configuration_plugin --init`
THEN the above-mentioned file's creation time must be the same as before.

4. Test `c8y_log_plugin --init`
GIVEN thin-edge installed on DUT
AND note down the creation time of the below files
`/etc/tedge/c8y/c8y-log-plugin.toml
/etc/tedge/operations/c8y/c8y_LogFileRequest
/etc/tedge/c8y/c8y-log-plugin.toml`
WHEN I run the command
`sudo c8y_log_plugin --init`
THEN the above-mentioned file's creation time must be the same as before.

**Comment by rina23q** [comment]
Hi @toewsar, we fixed the issue on 0.7.3 release. Can you check it? If you find it good, close the issue. Otherwise, give us a new comment.

**Comment by toewsar** [comment]
Hi @rina23q,
I fine with the result, thanks.
