### ISSUE TITLE
c8y-log-plugin is not working if tedge "reconnects"

### ISSUE THREAD

**Issue by toewsar** [thin-edge/thin-edge.io#1194]
**Describe the bug**
The c8y-log-plugin is not working anymore if tedge disconnects and connects again.
The c8y-log-plugin have to be restarted.

**To Reproduce**

1. `sudo tedge connect c8y`
2. `sudo systemctl start c8y-log-plugin.service`
3. `sudo tedge disconnect c8y`
4. `sudo tedge connect c8y`
5. log-plugin is not working

**Expected behavior**
`c8y-log-plugin` is working after `reconnect` of `tedge`.

**Environment (please complete the following information):**
 - Raspbian OS
 - RPI 4
 - armhf
 - thin-edge.io version [0.7.1]

**Comment by mbay-ODW** [comment]
Same is true for the configuration plugin. Will this also be fixed @didier-wenzek?

**Comment by didier-wenzek** [comment]
@mbay-ODW Yes the plan is to fix both log and config management.

**Comment by rina23q** [comment]
@toewsar 
@PradeepKiruvale fixed the issue by #1360, and the fix is available on 0.7.5 release. Could you check it? If no reply in one week, we will close this issue anyway.
