### ISSUE TITLE
Extend events API to support child devices

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#1197]
**Is your feature request related to a problem? Please describe.**

Provide APIs for child devices to raise events so that they are associated with their child device twins in Cumulocity.
The mapping logic for child devices is documented here: https://github.com/thin-edge/thin-edge.io/pull/1198

**AC:**

* An event for a child device can be published to `tedge/events/<event-type>/<child-device-id>` topic where the `child-device-id` is the unique device id for that child device
* The c8y-mapper on receipt of such messages should convert the Thin Edge JSON event payload to Cumulocity JSON format and publish it to `c8y/event/events/create` topic.
* If the `child-device-id` received with an incoming event does not already exist in the cloud, the mapper should first create a child device twin with that `child-device-id` as the "external ID" in Cumulocity before pushing that event payload itself. The mapper needs to cache these ids in-memory to avoid further recreation attempts.
* These child device ids need not be persisted over restarts. All known child device ids can be retrieved from the cloud during the startup by sending a [SmartREST 105](https://cumulocity.com/guides/10.11.0/reference/smartrest-two/#105) message. All child ids will be returned in a [SmartREST 106](https://cumulocity.com/guides/10.11.0/reference/smartrest-two/#106) message.
* Share this "child-device-id" caching logic with the child device handling logic of `tedge/measurements`

**Comment by rina23q** [comment]
Discussion: How to recreate the child device IDs cache on mapper restart? 

As of now, ignore the fourth bullet point. Use the same mechanism as the measurements.

> These child device ids need not be persisted over restarts. All known child device ids can be retrieved from the cloud during the startup by sending a [SmartREST 105](https://cumulocity.com/guides/10.11.0/reference/smartrest-two/#105) message. All child ids will be returned in a [SmartREST 106](https://cumulocity.com/guides/10.11.0/reference/smartrest-two/#106) message.

**Comment by PradeepKiruvale** [comment]
Is it required to cross-check the `child-device-id` and `ExternalId`?. If both are not the same then the messages will get lost without any response.

**Comment by didier-wenzek** [comment]
> Is it required to cross-check the `child-device-id` and `ExternalId`?. If both are not the same then the messages will get lost without any response.

As of now there is no need for such a check since the `child-device-id` given by the topic name is used as the `ExternalId` of the child devices. A check would make sense only if we decide to send events only for child devices that have been pre-registered on Cumulocity.

**Comment by PradeepKiruvale** [comment]
Resolved with #1243
