### ISSUE TITLE
Deprecate the user manager

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#1207]
## Motivations

A `UserManager` is used by the `tedge` command to control under which user is executed every steps of a thin-edge command.

In practice, the `tedge_user` crate causes more issues than benefits.
* This introduces [subtle access control issue](https://github.com/thin-edge/thin-edge.io/issues/885).
* The `tedge` command cannot run if there is no `tedge` user on the system. Having such a user is a good practice but should not be enforced from the inside.
* It's not convincing from a security perspective. As noted by @hansdaniels, changing the effective group id is not enough to run with just the requested access right.
* It introduces sophisticated rust issues notably to ensure there is a single instance of `UserManager`.

## Proposal

* Remove the five invocations of `become_user`.
   * 3 invocations are related to the certificate owned by mosquitto.
      * Use the recently added helpers in `tedge_utils` to create files with given user,group and mod.
   * The 2 others are easier to remove (becoming tedge on tedge start, restoring root to invoke systemd).
* Remove the `tedge_user` crate. 
  *  The only other usage was the `running_as` function that has been deprecated since there is no more regular user tedge config.

**Comment by albinsuresh** [comment]
So, from and end-user perspective, we're going to eliminate the `tedge` user and group completely and allow the creation of all the `tedge` files and processes with the executing user's access rights? Is it at least gonna be used as the "default user" in some cases?

**Comment by rina23q** [comment]
* Remove the lines like https://github.com/thin-edge/thin-edge.io/blob/main/crates/core/tedge/src/main.rs#L29
* Double-check if there is no change from user perspective.
* Will have a discussion again.
