### ISSUE TITLE
cargo outdated started faling

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#1219]
**Describe the bug**
See this workflow job. https://github.com/thin-edge/thin-edge.io/runs/7016861912?check_suite_focus=true

```
error: failed to select a version for `tokio`.
Error:     ... required by package `rumqttc v0.13.0`
    ... which satisfies dependency `rumqttc = "^0.[13](https://github.com/thin-edge/thin-edge.io/runs/7016861912?check_suite_focus=true#step:5:14).0"` of package `mqtt_channel v0.7.2 (/tmp/cargo-outdatedLvJuJl/crates/common/mqtt_channel)`
    ... which satisfies path dependency `mqtt_channel` (locked to 0.7.2) of package `c8y_api v0.7.2 (/tmp/cargo-outdatedLvJuJl/crates/core/c8y_api)`
    ... which satisfies path dependency `c8y_api` (locked to 0.7.2) of package `c8y_configuration_plugin v0.7.2 (/tmp/cargo-outdatedLvJuJl/plugins/c8y_configuration_plugin)`
versions that meet the requirements `=1.17.0` are: 1.17.0
all possible versions conflict with previously selected packages.
  previously selected package `tokio v1.[19](https://github.com/thin-edge/thin-edge.io/runs/7016861912?check_suite_focus=true#step:5:20).2`
    ... which satisfies dependency `tokio = "^1.19.2"` of package `batcher v0.7.2 (/tmp/cargo-outdatedLvJuJl/crates/common/batcher)`
    ... which satisfies path dependency `batcher` (locked to 0.7.2) of package `tedge_mapper v0.7.2 (/tmp/cargo-outdatedLvJuJl/crates/core/tedge_mapper)`
failed to select a version for `tokio` which could resolve this conflict
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 1
```

We need to work on it.

**Comment by didier-wenzek** [comment]
The fix is unfortunately not direct.

* `rumqttc` requires a fix version of `tokio`: `=1.17.0`.
* `tedge` doesn't compile with the latest version of `rumqttc`.

**Comment by matthiasbeyer** [comment]
I had a quick look.

So as of rumqttc 0.13.0, tokio is not required in a fixed version anymore. [This issue](https://github.com/bytebeamio/rumqtt/issues/409) documents that they rolled back to only set "1" as a required version, which is what we would need and expect of course. (implemented in [this PR](https://github.com/bytebeamio/rumqtt/pull/412))

But, we're still using 0.10.0 of rumqttc and there is no `CHANGELOG.md` in their repository that documents why things were (re)moved from 0.10.0 to 0.11.0. There is in fact a `CHANGELOG.md` file and some comments in the release tags, but the things that brake our build when updating from 0.10.0 to 0.11.0 are not documented. So updating rumqttc to 0.11.0 or further is non-trivial.

As the project heavily relies on MQTT, I think updating the library should be an important thing, as the update will also include latest improvements in the transitive dependencies, maybe even CVEs resolved in the underlying TLS implementation and so on (I didn't check), so IMO this may be even security-critical, right?

**Comment by matthiasbeyer** [comment]
I guess this could be closed, because (as far as I can see) `cargo-outdated` does not fail anymore :laughing:

**Comment by rina23q** [comment]
> I guess this could be closed, because (as far as I can see) `cargo-outdated` does not fail anymore laughing

On which version, `cargo-outdated` doesn't fail? On my local (version `1.59.0`), I still see the same error regarding Tokio.

By the way, how the [dependabot](https://github.com/thin-edge/thin-edge.io/blob/main/.github/dependabot.yml) replaces `cargo outdated` job? I thought, it will create a warning on the "Security" tab on GitHub, but there was nothing new created...

**Comment by matthiasbeyer** [comment]
> On which version, cargo-outdated doesn't fail?

I meant that it does not fail in the github-actions because it is not there anymore :laughing: 

> By the way, how the [dependabot](https://github.com/thin-edge/thin-edge.io/blob/main/.github/dependabot.yml) replaces cargo outdated job? I thought, it will create a warning on the "Security" tab on GitHub, but there was nothing new created...

It files PRs for updating dependencies, so there are no outdated dependencies on `main` anymore (except one right now, which we cannot easily update).

**Comment by rina23q** [comment]
> I meant that it does not fail in the github-actions because it is not there anymore laughing

Ah okay :sweat_smile: So, we still need to work on upgrading `rumqttc` version I guess.

**Comment by matthiasbeyer** [comment]
Yes, `rumqttc` is a ... <insert swearword here> ... I think @didier-wenzek mentioned somewhere that we should move away from the `rumqtt*` ecosystem, but for now we need to update the dependency.

I think, though, that this issue here can be closed, as it is resolved.

**Comment by rina23q** [comment]
Right, @didier-wenzek said that [here](https://github.com/thin-edge/thin-edge.io/pull/1291#issuecomment-1196464891).

**Comment by rina23q** [comment]
As @matthiasbeyer is suggested, the scope of this issue is done, as 
- we don't use `cargo outdated` anymore
- the PR to upgrade `rumqttc` is opened #1291, and well investigated the problems of upgrade by @matthiasbeyer. 

If we still need to upgrade the version of `rumqttc` to newer, we need another ticket. But it must be evaluated if it's worth spending time. @didier-wenzek also mentioned
> All these API changes, with no insight of their motivation nor workaround, remove my last hesitations: we must move away from rumqttc. The API is not so easy to use, there is no way to acknowledge messages, the tokio runtime is required, they are not reactive and now these breaking changes.
