### ISSUE TITLE
Plugins panic when payload is formatted incorrectly

### ISSUE THREAD

**Issue by initard** [thin-edge/thin-edge.io#1220]
**Describe the bug**

The log plugin exits if the format is specified incorrectly:

https://github.com/thin-edge/thin-edge.io/blob/2ab5aa4506979d350aba545882fad932fdec9b72/plugins/c8y_log_plugin/src/main.rs#L111-L118

**The same is true for the c8y configuration plugin.**

**To Reproduce**

Given mosquitto  2.0.11 installed on DUT
And thin-edge 0.6.3 installed on DUT
And c8y_log_plugin  0.7.0 installed on DUT
- `wget https://github.com/thin-edge/thin-edge.io/releases/download/0.7.0/c8y_log_plugin_0.7.0_arm64.deb`
- `sudo dpkg -i c8y_log_plugin_0.7.0_arm64.deb`

And mosquitto running
And c8y cloud connection 
And c8y_log_plugin is running:
- `sudo c8y_log_plugin --init`
- `sudo systemctl start c8y-log-plugin.service`

When sending a malformed payload to the c8y_log_plugin: 
- `tedge mqtt pub  'c8y/s/ds'  '522,'`
- `tedge mqtt pub 'c8y/s/ds' '522,[any-other-text-here]'`

Then the c8y_log_plugin panics and exits
- `sudo systemctl status c8y-log-plugin.service`

**Expected behavior**

Expect that the error  is handled and the application does not exit.

**Comment by rina23q** [comment]
From the viewpoint of regular users, the impact of fixing this issue is quite little honestly. I really don't expect that Cumulocity delivers mal-formed SmartREST messages to clients. However, better handling it than not addressing the cases at all.

It happens also on `c8y-configuration-plugin` if you send
```
mosquitto_pub -t 'c8y/s/ds' -m '526,'
```
or
```
mosquitto_pub -t 'c8y/s/ds' -m '524,'
```

Could you also fix them?

**Comment by gligorisaev** [comment]
to reproduce description is not complete, please define the "Given" state. 
example:

Precondition: thin-edge installed on DUT
                        DUT connected to C8Y and appearing in All Devices list....

Step 1. start c8y_log_plugin with 
`sudo ./target/debug/c8y_log_plugin `

Step 2. send the following with mosquitto_pub
`mosquitto_pub -t 'c8y/s/ds' -m '522,'`

etc. 

it is also maybe good to do it like:

GIVEN thin-edge installed on DUT
AND DUT is connected to C8Y and appearing in All Devices list
WHEN I run the command `sudo ./target/debug/c8y_log_plugin ` to start the c8y_log_plugin
AND I `run mosquitto_pub -t 'c8y/s/ds' -m '522,'`
THEN c8y_log_plugin panics and exits.

**Comment by initard** [comment]
> GIVEN thin-edge installed on DUT
> AND DUT is connected to C8Y and appearing in All Devices list
> WHEN I run the command `sudo ./target/debug/c8y_log_plugin ` to start the c8y_log_plugin
> AND I `run mosquitto_pub -t 'c8y/s/ds' -m '522,'`
> THEN c8y_log_plugin panics and exits.

Perfectly summarised. I would also add this is not just for: 
AND I `run mosquitto_pub -t 'c8y/s/ds' -m '522,'`
but also for '522,anything-else-here', like for example:
AND I `run mosquitto_pub -t 'c8y/s/ds' -m '522,sdfasdfasdf'`

**Comment by gligorisaev** [comment]
@initard, than please adjust the "Describe the bug" section accordingly
