### ISSUE TITLE
[tedge_apt] apt-utils is not installed

### ISSUE THREAD

**Issue by jji2019** [thin-edge/thin-edge.io#1227]
**Is your documentation request related to a problem? Please describe.**
Does `tedge apt` has a dependency of `apt-utils`? Would this be documented?

The installation process failed and there was a message `debconf: delaying package configuration, since apt-utils is not installed`.

Here is the log of Debian package installation process via `tedge apt`:
```
root@fa1dee079f24:/opt# sudo /etc/tedge/sm-plugins/apt install zementis-thinml-3732 --file /opt/zementis-thinml-3732_10.15.0.0.1-1_armhf.deb
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  zementis-thinml-3732
0 upgraded, 1 newly installed, 0 to remove and 65 not upgraded.
Need to get 0 B/12.7 MB of archives.
After this operation, 16.1 MB of additional disk space will be used.
Get:1 /opt/zementis-thinml-3732_10.15.0.0.1-1_armhf.deb zementis-thinml-3732 armhf 10.15.0.0.1-1 [12.7 MB]
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package zementis-thinml-3732.
(Reading database ... 22974 files and directories currently installed.)
Preparing to unpack .../zementis-thinml-3732_10.15.0.0.1-1_armhf.deb ...
Unpacking zementis-thinml-3732 (10.15.0.0.1-1) ...
Setting up zementis-thinml-3732 (10.15.0.0.1-1) ...
```

Then I did apt-utils installation manually:
```
root@fa1dee079f24:/opt# apt install apt-utils
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  apt-utils
0 upgraded, 1 newly installed, 0 to remove and 65 not upgraded.
Need to get 424 kB of archives.
After this operation, 1039 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bullseye/main armhf apt-utils armhf 2.2.4 [424 kB]
Fetched 424 kB in 2s (216 kB/s)    
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package apt-utils.
(Reading database ... 22987 files and directories currently installed.)
Preparing to unpack .../apt-utils_2.2.4_armhf.deb ...
Unpacking apt-utils (2.2.4) ...
Setting up apt-utils (2.2.4) ...
```

Here is the second log of Debian package installation via `tedge apt`:
```
root@fa1dee079f24:/opt# sudo /etc/tedge/sm-plugins/apt install zementis-thinml-3732 --file /opt/zementis-thinml-3732_10.15.0.0.1-1_armhf.deb
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  zementis-thinml-3732
0 upgraded, 1 newly installed, 0 to remove and 65 not upgraded.
After this operation, 16.1 MB of additional disk space will be used.
Get:1 /opt/zementis-thinml-3732_10.15.0.0.1-1_armhf.deb zementis-thinml-3732 armhf 10.15.0.0.1-1 [12.7 MB]
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
Selecting previously unselected package zementis-thinml-3732.
(Reading database ... 23057 files and directories currently installed.)
Preparing to unpack .../zementis-thinml-3732_10.15.0.0.1-1_armhf.deb ...
Unpacking zementis-thinml-3732 (10.15.0.0.1-1) ...
Setting up zementis-thinml-3732 (10.15.0.0.1-1) ...
W: Repository is broken: zementis-thinml-3732:armhf (= 10.15.0.0.1-1) has no Size information
```

**Describe the improvement you'd like**
The Debian package is able to be installed successfully via `dpkg -i zementis-thinml-3732_10.15.0.0.1-1_armhf.deb` but not sure why the Debian package is not able to be installed via `tedge-apt`

**Additional context**
The docker base image I am using for validating the Debian package installation process is:
- balenalib/raspberrypi3-python:3.7-build

The thin-edge.io version I am using: 
- RUN dpkg -I tedge-0.7.2.deb
- RUN dpkg -i tedge_mapper-0.7.2.deb
- RUN dpkg -i tedge_apt_plugin-0.7.2.deb
- RUN dpkg -i tedge_agent-0.7.2.deb

**Comment by rina23q** [comment]
The apt plugin calls `apt-get`. If a device doesn't have `apt-utils` installed, and calls `apt-get`, it gives the warning as you described. Actually, you can ignore this warnig.

From the second log of debian package, I suspect if your `zementis-thinml-3732_10.15.0.0.1-1_armhf.deb` requires user-interactive dialog when you install the package. Is my assumption correct?

This one helped me to diagnose your error messages. https://stackoverflow.com/questions/22466255/is-it-possible-to-answer-dialog-questions-when-installing-under-docker

**Comment by rina23q** [comment]
@jji2019 I found this thread hasn't moved since July, can I close the issue?

**Comment by jji2019** [comment]
Thanks for the reminder. I will close this issue. Some modules might be required but the warning message is showing reasonablely.
