### ISSUE TITLE
Certificate can't be uploaded 

### ISSUE THREAD

**Issue by Hadsch** [thin-edge/thin-edge.io#1228]
**Describe the bug**
I want to connect based on this tutorial: https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/tutorials/connect-c8y.md to a trial instance of cumulocity.

This fails with this error message:
```
Error: failed to upload root certificate

Caused by:
    0: I/O error
    1: No such file or directory (os error 2)
```

Info: 
* I read this bug https://github.com/thin-edge/thin-edge.io/issues/403 but my issues seem to be different.
* My user has the role 'Tenant Manager' (the user has all available roles) 

**To Reproduce**
* Login to Raspberry PI 3
* Follow the steps from the tutorial

```
$ sudo tedge config set c8y.url <teanant-id>.eu-latest.cumulocity.com
$ sudo tedge config set c8y.root.cert.path /etc/ssl/certs
$ sudo tedge cert create --device-id cloud-one
$ sudo tedge cert show
Device certificate: /etc/tedge/device-certs/tedge-certificate.pem
Subject: CN=cloud-one, O=Thin Edge, OU=Test Device
Issuer: CN=cloud-one, O=Thin Edge, OU=Test Device
Valid from: Tue, 05 Jul 2022 13:46:10 +0000
Valid up to: Wed, 05 Jul 2023 13:46:10 +0000
Thumbprint: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX (obfuscated)
```

The next step from the tutorial throws an error:
```
$  sudo tedge cert upload c8y --user <my-user-name>
Enter password:
Error: failed to upload root certificate

Caused by:
    0: I/O error
    1: No such file or directory (os error 2)
```

**Expected behavior**
Upload succeeds or a better error message

**Environment (please complete the following information):**

Raspi version info
```
 cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
console@cloud-one:~ $
```

```
$ uname -a
Linux cloud-one 5.15.32-v7+ #1538 SMP Thu Mar 31 19:38:48 BST 2022 armv7l GNU/Linux
````

```
$ tedge -V
tedge 0.7.2
```

**Additional context**

**Comment by Hadsch** [comment]
I ran the commands again and know it works ;) 
As far as I see in the command history, I exected the command ` sudo tedge config set c8y.root.cert.path ` again with a `wrong` path. 

Closing this ticket again!

**Comment by mstoffel-sag** [comment]
I ran into that to, would be good to change the example to the default path.
