### ISSUE TITLE
[tedge_apt] debian package installation was done partially

### ISSUE THREAD

**Issue by jji2019** [thin-edge/thin-edge.io#1229]
**Describe the bug**

A Debian package is validated by the command line:

`dpkg -i pkgName_10.15.0.0.1-1_armhf.deb`

The whole installation process is done completely. The whole functionalities are working as expected.

However, using below command line doesn't install the package like what `dpkg` can do:

`sudo /etc/tedge/sm-plugins/apt install pkgName --file /opt/pkgName_10.15.0.0.1-1_armhf.deb`

`apt` finished those install operations defined in `debian/pkgName.install` and showed successful but `apt` ignored other install operations defined in [`debian/pkgName.postinst`](https://www.debian.org/doc/manuals/debian-faq/pkg-basics.en.html#maintscripts).

**To Reproduce**
- generate a simple debian package
- use `debian/pkgName.install` for moving files around
- use `debian/pkgName.postinst` for executing script

**Expected behavior**
The debian package could be installed successfully and comprehensively via `apt` like what `dpkg` provided.

**Environment (please complete the following information):**
 - OS [balenalib/raspberrypi3-python:3.7-build]
 - Hardware [virtual machine]
 - System-Architecture [Linux 3312d1683465 5.10.104-linuxkit # 1 SMP Thu Mar 17 17:08:06 UTC 2022 armv7l GNU/Linux]
 - thin-edge.io version [0.7.2]

**Comment by rina23q** [comment]
Can you try the following command?
```
sudo apt-get install /opt/pkgName_10.15.0.0.1-1_armhf.deb

```

Why am I asking this command? Because executing debian maintainer scripts is a different layer's job from what the apt plugin does. The apt plugin is a wrapper of `apt-get`. And `apt-get` is a wrapper of `dpkg`.

**Comment by jji2019** [comment]
I tried to install `apt-utils` and followed the suggestion from StackOverflow [Is it possible to answer dialog questions when installing under docker?](https://stackoverflow.com/questions/22466255/is-it-possible-to-answer-dialog-questions-when-installing-under-docker); but it seems like that apt-get postinstall is not executed.
```sh
echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
export DEBIAN_FRONTEND=noninteractive
sudo apt-get install apt-utils
```

```sh
root@3b8fcc0fd0cc:/opt# sudo apt-get install -y /opt/<pkgName>_10.15.0.0.1-1_armhf.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting '<pkgName>' instead of '/opt/<pkgName>_10.15.0.0.1-1_armhf.deb'
The following NEW packages will be installed:
  <pkgName>
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/12.9 MB of archives.
After this operation, 16.3 MB of additional disk space will be used.
Get:1 /opt/<pkgName>_10.15.0.0.1-1_armhf.deb <pkgName> armhf 10.15.0.0.1-1 [12.9 MB]
Selecting previously unselected package <pkgName>.
(Reading database ... 23318 files and directories currently installed.)
Preparing to unpack .../<pkgName>_10.15.0.0.1-1_armhf.deb ...
Unpacking <pkgName> (10.15.0.0.1-1) ...
Setting up <pkgName> (10.15.0.0.1-1) ..
```

Different from `apt-get`, `postinst` was invoked using `dpkg`:
```
sudo dpkg --unpack <pkgName>_10.15.0.0.1-1_armhf.deb
sudo dpkg --configure <pkgName>
```

the `postinst` inside the debian package is not doing a lot but just to invoke python `pip`:
```bash
#!/bin/sh
set -e
if which pip3 >/dev/null 2>&1; then
	echo "[log] start install something via pip..."
        pip3 install ...
	done
fi
```

**Comment by jji2019** [comment]
Hi, what I found so far the issue was caused by the situation that apt-get subprocess doesn't have the same environment like what dpkg had; so `postinst ` cannot invoke `pip3` due to `pip3` is not available in the subprocess.

With additional environment setup for the subprocess, the full installation is done successfully.
