### ISSUE TITLE
Script to delete thin-edge.io from device

### ISSUE THREAD

**Issue by mbay-ODW** [thin-edge/thin-edge.io#1231]
**Describe the bug**
Currently I can install thin-edge.io via script. But I can not uninstall it and have to manually delete all parts.

**Expected behavior**
thin-edge.io provides a script that allows complete or binary (e.g. keep configs) uninstallation of thin-edge.io.

**Additional context**
Following steps might be needed within the script

1. Stop services
sudo systemctl stop tedge-mapper-collectd
sudo tedge disconnect c8y
sudo tedge disconnect az
sudo systemctl stop apama

2. purge apts
sudo apt --assume-yes purge tedge tedge_mapper tedge_agent tedge_watchdog tedge_apt_plugin tedge_apama_plugin c8y_log_plugin c8y_configuration_plugin
 sudo DEBIAN_FRONTEND=noninteractive apt --assume-yes purge mosquitto-clients mosquitto libmosquitto1 collectd-core collectd

3. delete /etc/tedge
rm -r /etc/tedge

**Comment by rina23q** [comment]
AC:
* Create a simple script to `purge`/`remove` thin-edge.io packages.
* Add the description how to uninstall on https://thin-edge.github.io/thin-edge.io/html/howto-guides/002_installation.html

**Comment by PradeepKiruvale** [comment]
Resolved #1320 #1331

**Comment by rina23q** [comment]
Hi @mbay-ODW, now we have the description [how to uninstall](https://thin-edge.github.io/thin-edge.io/html/howto-guides/002_installation.html#uninstall-thin-edgeio), and the [script](https://github.com/thin-edge/thin-edge.io/blob/main/uninstall-thin-edge_io.sh).

If you are happy with them, can you close the issue? If no comment after 1 week, we will close the issue as it's done in our point of view. Thanks in advance!

**Comment by mbay-ODW** [comment]
looks good, will close
