### ISSUE TITLE
Script to update thin-edge.io from device 

### ISSUE THREAD

**Issue by mbay-ODW** [thin-edge/thin-edge.io#1232]
Describe the bug
Currently I can install thin-edge.io via script. But I can not update it.

Expected behavior
thin-edge.io provides a script that allows update of thin-edge.io via anprovided upgrade path.

**Comment by rina23q** [comment]
I use the same script to upgrade thin-edge as the installation script, introduced [here](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/howto-guides/002_installation.md).

So we can consume the same script to upgrade/downgrade. However, we don't really document how to do it. I think this is what we should do.

**Comment by mbay-ODW** [comment]
Using the installation script as "upgrade" script only works partially in our experience. It strongly depended on from which version I jump to which version. This should be handled by the script via an upgrade path.

**Comment by rina23q** [comment]
Upgrading feature is already available, but not well-known. We will work to improve our current documentation. Focus on this page https://thin-edge.github.io/thin-edge.io/html/howto-guides/002_installation.html.

**Comment by didier-wenzek** [comment]
> Using the installation script as "upgrade" script only works partially in our experience. It strongly depended on from which version I jump to which version. This should be handled by the script via an upgrade path.

The upgrade script should work for upgrades or to install a specific version - so if you experience some issue using it, please create an issue.

**Comment by rina23q** [comment]
Resolved with #1309
