### ISSUE TITLE
All PR check workflows should be run when one of workflows has been changed

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#1233]
Currently, when any workflow files are changed, we run only `block-fix-up` job. All other jobs are skipped by the filter, coded [here](https://github.com/thin-edge/thin-edge.io/blob/main/.github/workflows/pull-request-checks.yml#L24). For example, in this PR https://github.com/thin-edge/thin-edge.io/pull/1224, workflows got changed, but you can see only `block-fix-up` job ran.

---

It would be good to run *all* the workflows when one of the workflows has been changed. The current optimization (run rust/doc related workflow only when rust/doc files are updated) is neat, but workflow update should be an exception.

_Originally posted by @didier-wenzek in https://github.com/thin-edge/thin-edge.io/pull/1224#pullrequestreview-1036915308_

---

AC:
* All other workflows defined in pull-request-checks will be triggered when one of the workflow has been changed.

**Comment by gligorisaev** [comment]
I have problem to understand how this ticket is resolved

**Comment by rina23q** [comment]
Resolved with #1224
