### ISSUE TITLE
Get rid of system tests from after-merge workflow

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#1234]
**Is your feature request related to a problem? Please describe.**
We have `ci_pipeline.yml`, which is triggered every after merge.
However, this result is always "red", because we have unstable system tests. Now we don't check or fix the failure. For me, it makes no sense to keep such tests.

**Describe the solution you'd like**
My proposal is to disable the jobs below from `ci_pipeline.yml`.
- system-test-offsite-matrix
- system-test-postprocessing

**Describe alternatives you've considered**
How to disable the jobs? => Either comment them out or completely remove these lines. I'd prefer commenting them out as we can keep some information how to use GitHub Secrets...

**Additional context**
I would like to remark, other jobs in [`ci_pipeline.yml`](https://github.com/thin-edge/thin-edge.io/blob/main/.github/workflows/ci_pipeline.yml) works as expected.

**Comment by rina23q** [comment]
Once we decide to deprecate our pysys tests, we can close the following issues.

- https://github.com/thin-edge/thin-edge.io/issues/1089
- https://github.com/thin-edge/thin-edge.io/issues/1088
- https://github.com/thin-edge/thin-edge.io/issues/1083
- https://github.com/thin-edge/thin-edge.io/issues/1081
- https://github.com/thin-edge/thin-edge.io/issues/1012
- https://github.com/thin-edge/thin-edge.io/issues/804
- https://github.com/thin-edge/thin-edge.io/issues/788
- https://github.com/thin-edge/thin-edge.io/issues/752

**Comment by rina23q** [comment]
Our pysys tests won't be removed by this task. Pysys tests will be replaced by the framework proposed by https://github.com/thin-edge/thin-edge.io/issues/808.

**Comment by matthiasbeyer** [comment]
> How to disable the jobs? => Either comment them out or completely remove these lines. I'd prefer commenting them out as we can keep some information how to use GitHub Secrets...

Hi! Why not removing them? They are still in the git history and the "Remove xyz test" patches can easily be `git-revert`ed! Outcommented code is just dept.

**Comment by rina23q** [comment]
> > How to disable the jobs? => Either comment them out or completely remove these lines. I'd prefer commenting them out as we can keep some information how to use GitHub Secrets...
> 
> Hi! Why not removing them? They are still in the git history and the "Remove xyz test" patches can easily be `git-revert`ed! Outcommented code is just dept.

Going to remove :D Don't worry.

**Comment by rina23q** [comment]
We can't close these two issues.
- https://github.com/thin-edge/thin-edge.io/issues/1089
We still run smoke test to c8y from the after-merge workflow. The test uploads the certificate to Cumulocity.
- https://github.com/thin-edge/thin-edge.io/issues/792
It looks we have some issue in batching. Need further investigation.

**Comment by rina23q** [comment]
Two jobs below from ci_pipeline.yml is already disabled by #1300. 
- system-test-offsite-matrix
- system-test-postprocessing

Also, close some issues no longer applicable. So, I would close the issue.
