### ISSUE TITLE
Refactor `tedge_mapper` crate

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#1235]
**Is your feature request related to a problem? Please describe.**
`tedge_mapper` is consists of a generic mapper component and cloud specific components.

The `Mapper` struct is the cloud agnostic representation.
```rust
pub struct Mapper {
    input: UnboundedReceiver<Message>,
    output: UnboundedSender<Message>,
    converter: Box<dyn Converter<Error = ConversionError>>,
    health_check_topics: TopicFilter,
    health_status_topic: Topic,
}
```

And all cloud specific part (how to convert Thin Edge JSON <-> Cloud specific message format) is representative as `Converter`. This separation of roles is based on our initial design.

1. The main principle of mapper is cloud-agnostic. Receiving a message, and translating the input message to one or more messages.
2. The convert part is cloud-specific. For Cumulocity, there is a possibility of the various combination of input and output.
input: SmartREST2.0, output: Thin Edge JSON (e.g. all operations)
input: Thin Edge JSON, output: SmartREST2.0 (e.g. alarms)
input: Thin Edge JSON, output: Cumulocity JSON via MQTT (e.g. measurements)
input: Thin Edge JSON, output: Cumulocity JSON via HTTP (e.g. software list)
input: Thin Edge JSON, output: Cumulocity JSON via HTTP and SmartREST2.0 (e.g. child device for events)

To address the complexity of Cumulocity message conversion, now we are a kind of "abusing" converter. Converter was intended to translate the message only, however, now I can see converter is sending HTTP requests. You can find [here](https://github.com/thin-edge/thin-edge.io/blob/main/crates/core/tedge_mapper/src/c8y/converter.rs#L249) and [here](https://github.com/thin-edge/thin-edge.io/blob/main/crates/core/tedge_mapper/src/c8y/converter.rs#L640).

**Describe the solution you'd like**
My proposal is to refactor the mapper.
1. The input of mapper is always a single MQTT message.
2. The output of mapper is one or more messages with any protocol (MQTT, HTTP as of now). (Call it queue of "any protocol messages").
3. The converter dedicates on translation messages. Sending out no messages.
4. The mapper sending out the order of "any protocol messages" queue with the appropriate protocol.

**Describe alternatives you've considered**

**Additional context**
We should consider the business value by the refactoring. This refactoring helps the child device creation with a large size payload message (related to #1197). However, if we go to refactor whole existing mapper by actor model, probably this proposal will no longer make sense.

**Comment by didier-wenzek** [comment]
No longer applicable. However, the goal has been reached thanks to the actor refactoring.
