### ISSUE TITLE
Apply the `fs_inotify` crate to `c8y_configuration_plugin`

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#1248]
After https://github.com/thin-edge/thin-edge.io/issues/1173 is done, we need to apply the crate to `c8y_configuration_plugin` to detect the changes on the configuration file of the plugin.

AC:
- `c8y_configuration_plugin` consumes the fs_inotify crate
- Tested

**Comment by initard** [comment]
# How to Tes

```gherkin
Feature: changes to configuration plugin are automatically updated in the cloud

    @important @essential
    Scenario Outline: changing configuration file 
      Given DUT has c8y-configuration-plugin installed
      And DUT is connected to c8y
      When I change the configuration file
      Then I should see the configuration update in the cloud

      Examples:
        | start | eat | left |
        |    12 |   5 |    7 |
        |    20 |   5 |   15 |
```

**Comment by didier-wenzek** [comment]
We also decided to simple the command line arguments removing the `--config-file` option in favor of the `--config-dir` option.

**Comment by initard** [comment]
> We also decided to simple the command line arguments removing the `--config-file` option in favor of the `--config-dir` option.

@didier-wenzek, @rina23q does this need a system test?

**Comment by rina23q** [comment]
Automated tests will come later.
