### ISSUE TITLE
Transfer `tests/PySys/tedge` tests to new test framework

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#1255]
**Is your feature request related to a problem? Please describe.**
Refactor the existing test cases under `tests/PySys/tedge` to robot framework.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gligorisaev** [comment]
This issue was covered with the PR #1319

**Comment by rina23q** [comment]
Covered by #1256
