### ISSUE TITLE
Transfer `tests/PySys/tedge_connect` tests to new test framework

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#1256]
**Is your feature request related to a problem? Please describe.**
Refactor the existing test cases under tests/PySys/tedge_connect to robot framework.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gligorisaev** [comment]
Test Cases transfered to Robot Framework

**Comment by matthiasbeyer** [comment]
Can someone point me to the rationale why we would want to use something like the robot framework?

I cannot think of a usecase for it right now... maybe I missed some discussion?

**Comment by rina23q** [comment]
We used PySys framework for system tests and end-to-end tests. However, the tests went unstable as discussed [here](https://github.com/thin-edge/thin-edge.io/issues/808#issuecomment-1185390828).

We keep unit tests and integration tests in Rust. On the other hand, we also need black box tests written not by developers, and end-to-end tests (thin-edge device <=> cloud). For this case, using Robot Framework is good instead of Pysys.

**Comment by rina23q** [comment]
Resolved by #1255
