### ISSUE TITLE
Specify child-device model and behaviour

### ISSUE THREAD

**Issue by cstoidner** [thin-edge/thin-edge.io#1260]
Create a user-faced specification that describes static and dynamic behaviour of child-devices from thin-egde POV. That specification shall focus on general details about child-device, decoupled from specific feature as measurement, events, alarms, configuration management, ...

Scope:
* specification of a "child-device model", i.E. the static behaviour (what exactly is a child-device?)
   * definition of relationships, deployment, artifacts
   * definition of unique terminology for that scope
* specification of dynamic behaviour
   * definition of initialization-behaviour of a child-device
         * who creates when the child-device twin in the cloud?
         * who declares when capabilities on the twin in the cloud?
         * what need to be considered on the thin-edge device / who takes care, and when? 

**AC:**

* User-facing specification is available on https://github.com/thin-edge/thin-edge.io/tree/main/docs

**Comment by didier-wenzek** [comment]
> decoupled from specific feature as measurement, events, alarms, configuration management, ...

I think the concept of child-device cannot be decouple from measurement, events, alarms, configurations ...
* A child device is a source of measurements and any source of measurements can be seen as a child device.
* The behavior of a child-device is defined by a set of configuration files that can be managed from the cloud.
* ...

**Comment by rina23q** [comment]
The PR is here: https://github.com/thin-edge/thin-edge.io/pull/1236

**Comment by cstoidner** [comment]
@rina23q 
As decided in sprint planning on 2022-09-14, scope of that issue has changed,

from: specification of a "child-device model"

to: specification of (1) a "thin-edge domain model" and (2) a "thin-edge data model", where child-devices are a subset.

**Comment by cstoidner** [comment]
@rina23q 
As stated in sprint planning on 2022-09-14, rest effort for upcoming spring # 47:

3 SP, sum of 1.5 for "domain model" and 1.5 for "data model".

**Comment by cstoidner** [comment]
> The PR is here: #1195

PR #1195 went to too vague / wide.

All domain-model content was now moved to a new PR, that exclusively focuses on the domain-model. 
See #1554

**Comment by didier-wenzek** [comment]
Closing as addressed by the new MQTT topic scheme
