### ISSUE TITLE
Specify child-device support for C8Y configuration management plugin

### ISSUE THREAD

**Issue by cstoidner** [thin-edge/thin-edge.io#1261]
As a user I want to manage a child-device's configuration files using C8Y configuration management plugin.

Create a user-faced specification how to handle child-devices in the C8Y configuration management plugin.

Scope:
* configuration files shall be consumed/provided from/to an external device via network
* configuration files shall appear in the cloud underneath coresponding child-devices
* child-devices shall not be created by the C8Y configuration management plugin, but created upfront
  (e.g. user creates them directly in the cloud, or user send sends once an event with thin-edge to the child device). Consolidation on that behaviour with other features (as measurements, events, alarms) will follow when the child-device model and initialization behaviour was confirmed (see https://github.com/thin-edge/thin-edge.io/issues/1260).

**AC:**

* Existing C8Y configuration plugin documentation (https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/references/c8y-configuration-management.md) is extended with details about child-device management.

**Comment by rina23q** [comment]
> child-devices shall not be created by the C8Y configuration management plugin, but created upfront
(e.g. user creates them directly in the cloud, or user send sends once an event with thin-edge to the child device).

This sounds a solution. I think the scope should be
* Specify who will create a child device object in Cumulocity.

**Comment by rina23q** [comment]
The PR is here: https://github.com/thin-edge/thin-edge.io/pull/1236

**Comment by rina23q** [comment]
QA check passed, therefore close this issue.
