### ISSUE TITLE
Test thin-edge health-check feature

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#1302]
**Is your feature request related to a problem? Please describe.**

Thin-edge provides `health-check` feature for checking the health of the `thin-edge` services.
Basically, these services expose `MQTT` topics to check the health of the services.

As a reference implementation thin-edge implements the `systemd` based health-check mechanism.
This feature has to be tested. 

**Describe the solution you'd like**
Test steps
For example for `tedge-mapper-c8y`
1. `tedge connect`, this will start the `tedge-mapper-c8y` service
2. Stop `tedge-mapper-c8y` service using `systemctl stop tedge-mapper-c8y.service`
3. Update the `/lib/systemd/system/tedge-mapper-c8y.service` file with `WatchdogSec=30` in the services section
4. Reload the systemd files `systemctl daemon-reload`
5. Now start `tedge-mapper-c8y` as `systemctl start tedge-mapper-c8y.service`
6. Start the watchdog service `systemctl start tedge-watchdog.service`. The watchdog then starts monitoring the `tedge-mapper` process for liveness.
7. Kill the `tedge-mapper c8y` process that was spawned by starting `tedge-mapper-c8y.service`
9. Systemd watchdog should have detected that this `tedge-mapper` process is dead after the watchdog timeout of 30 seconds and respawn a new one. Verify that a new `tedge-mapper` process is spawned automatically after this timeout interval.

This process has to be followed for all the services
`tedge-agent`
`tedge-mapper-az`
`tedge-mapper-collectd`
`c8y-log-plugin`
`c8y-configuration-plugin`

**Describe alternatives you've considered**

**Additional context**
One can see more information here

https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/howto-guides/020_monitor_tedge_health.md
https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/howto-guides/021_enable_tedge_watchdog_using_systemd.md

**Comment by gligorisaev** [comment]
Test Cases Automated:

* `health_c8y-configuration-plugin.robot`
* `health_c8y-log-plugin.robot`
* `health_tedge_mapper.robot`
* `health_tedge-agent.robot`
* `health-mapper-az.robot`
* `health_tedge-mapper-collectd.robot`

Steps: (Same steps implemented for all relevant services mentioned above)

1. Stop the service `sudo systemctl stop c8y-configuration-plugin.service`
2. Update the service file adding `WatchdogSec=30`
3. Reload systemd files `sudo systemctl daemon-reload`
4. Start c8y-configuration-plugin `sudo systemctl start c8y-configuration-plugin.service`
5. Start watchdog service `sudo systemctl start tedge-watchdog.service`
6. Check PID of c8y-configuration-plugin `pgrep -f 'c8y_configuration_plugin`'
7. Restart c8y-configuration-plugin `sudo systemctl restart c8y-configuration-plugin.service`
8. Recheck PID of c8y-configuration-plugin `pgrep -f 'c8y_configuration_plugin`'
9. Compare PID change `Should Not Be Equal`
10. Stop watchdog service `sudo systemctl stop tedge-watchdog.service`
11. Remove entry from service file `sudo sed -i '9d' /lib/systemd/system/c8y-configuration-plugin.service`

**Comment by PradeepKiruvale** [comment]
Does `health_tedge_mapper.robot` include the `c8y` and `az` mappers?

**Comment by PradeepKiruvale** [comment]
Step 7. should be `sudo kill -9 c8y_configuration_plugin`, once it gets killed then the systemd will automatically restart the `c8y-configuration-plugin`

**Comment by gligorisaev** [comment]
@PradeepKiruvale 
1. `health_tedge_mapper.robot` renamed to `health_tedge_mapper_c8y.robot`
2. `sudo kill -9 c8y_configuration_plugin` results in:
```
pi@raspberrypi:~ $ sudo kill -9 c8y_configuration_plugin
kill: failed to parse argument: 'c8y_configuration_plugin'
```

have you tried the "kill"?, are you sure this is the correct command?

**Comment by PradeepKiruvale** [comment]
Sorry I meant the PID of the `c8y_plugin`

`sudo kill -9 pid_of_c8y_configuration_plugin`
