### ISSUE TITLE
Explore local thin-edge file transfer with a prototype

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#1307]
A thin-edge device and its child devices have to exchange files for various purposes:

* pushing to a child-device a new configuration file or a software package,
* pulling from a child-device a configuration file or a log file.

This is more than just files upload and download.

* The thin-edge device must *notify availability* of a file for a child device.
  * It can be a new configuration files or a package to install.
  * So the child devices can download (HTTP GET) and apply those.
* The thin-edge device must be able to *request* a file from a child device.
   * It can be the latest version of a log file or the current version of a configuration file.
   * So the child device can upload (HTTP PUT) the requested file.
* The child devices must *notify progress* of an upload/download operation
  *  So, the thin-edge device can proceed .e.g forward the progress status to the cloud or remove any temporary file.
  * A child devices must be able notify success as well as errors.

I imagine:
* A main transfer service implemented by the agent and used by other thin-edge features (configuration management, log management, software update, firmware update ...).
* A combination of HTTP (for the actual file transfer) and MQTT (for progress notification).
   * The child devices act only as clients.
   * The thin-edge device serves over HTTP a bench of files which content is directly accessed by the plugins running on the main thin-edge devices.
   * MQTT is used to notify availability of new file versions and progress of transfers.

## Prototype

What is not clear, and needs to be explore with a prototype, is __how the responsibilities are distributed between the transfer service, the plugins and the child devices__
  * The agent can act as a regular HTTP server, simply serving files under some directory root content.
     * The operation plugins will have then to
        * move the files around, making them available for download or consuming them once uploaded,
        * send/expect operation specific MQTT messages to/from the child devices.
  * The agent can combine HTTP with MQTT to notify changes under the root content.
     * The notification messages sent over MQTT are in this case generic (Creation/Update/Removal).
     * The protocol of the operation plugins leverage the these generic notification. For instance, updating a file (representing the desired configuration of a plugin) generates a generic Update notification the child has to react upon. Similarly, the child device uploading its current configuration triggers a generic Update notification interpreted by the thin-edge as a successful re-configuration.
  * NOTE: writing this, I'm now convinced that the second option is fragile and cumbersome. Even if this was my former idea, I do think now that the first solution with operation specific messages will be more flexible and robust.

One also have to explore alternative workflows for the main operations:
* Configuration management
  * Are the configuration files currently used by the child devices uploaded to the main device on thin-edge request or child init?  
* Log management
   * Do we need to be able to request partial upload? 
* Software update
   * Once successfully installed on the child devices, the packages can be deleted the main device.
* Firmware update
   *  It would be good to entirely avoid to store the image on the gateway device. 

I expect a running prototype that demonstrates the interactions between thin-edge and the child device of the main operations.
* This is a prototype.
   * It can be implemented independently of the tedge agent and the operation plugins.
* The focus is not on code quality but on:
      * HTTP and MQTT interactions
      * MQTT message topics and payloads
      * File movements (making a file available for download, removing temporary files)
      * Workflow / protocol to achieve the main operations.
      * How errors are handled
* I expect 3 daemons to demonstrate the interactions
  * A transfer service that serves HTTP requests. It can be an off the shelf HTTP server. 
  * A daemon that simulates the operation plugins for configuration and log, possibly software update. There is no point to address the protocol with the cloud.
  * A daemon that simulates a child device. There is no point to do more than persisting the received files and notifying results. Simulating not only success but also errors is important.

## Open questions
* Is there use cases, where it would be useful for a child device to take the initiative of a transfer?
  * For instance, one can imagine that a child device upload on start its configuration files to the main device.
* How to avoid unnecessary copies?
   * When thin-edge downloads a file from the cloud before making it available for child devices. 

### Additional context

* Such a transfer feature raises security concerns, but I would ignore them for now, addressing authentication and authorization later.

**Comment by albinsuresh** [comment]
Also validate if custom operations can take advantage of this file transfer service for any binary transfer associated with those.

**Comment by albinsuresh** [comment]
Addressed in https://github.com/thin-edge/thin-edge.io_spikes/pull/4
