### ISSUE TITLE
Porting rust "integration" tests to Robot Framework 

### ISSUE THREAD

**Issue by 6367f766** [thin-edge/thin-edge.io#1308]
To close https://github.com/thin-edge/thin-edge.io/discussions/1274, we have to port the apt plugin tests to robot framework as system test.

This is a follow-up PR from #1304 where we disabled the rust "integration" tests. 

The final step is to port the tests to robot framework as system tests.

Since we moved on from integration tests in rust, and @gligorisaev will take care of tests as such, I propose to port these tests to robot framework.  

The test is found here: https://github.com/thin-edge/thin-edge.io/blob/2e98c65e610bfa23dd74433ac75e1b1674dc7fa7/plugins/tedge_apt_plugin/tests/main.rs

For more information on the tedge apt plugin feature see here: https://thin-edge.github.io/thin-edge.io/html/tutorials/software-management.html

## Todo

```gherkin
Feature: tedge apt plugin can install a package from Cumulocity

    Scenario: user provides an empty space in the file path to a package and installs this from Cumulocity 
      Given DUT has tedge_apt_plugin, tedge, tedge_agent and tedge_mapper installed
      And DUT is connected to c8y
      And a space is entered on the cloud-side (Cumulocity UI)
      When an install of the package is triggered on the cloud-side
      Then this package appears on the software list on Cumulocity

    Scenario: user provides a file path to a package and installs this from Cumulocity 
      Given DUT has tedge_apt_plugin, tedge, tedge_agent and tedge_mapper installed
      And DUT is connected to c8y
      And a package url is entered on the cloud-side (Cumulocity UI)
      When an install of the package is triggered on the cloud-side
      Then this package appears on the software list on Cumulocity    

    Scenario: user uploads a binary and installs a package from Cumulocity
      Given DUT has tedge_apt_plugin, tedge, tedge_agent and tedge_mapper installed
      And DUT is connected to c8y
      And a package binary is uploaded to c8y on the cloud-side (Cumulocity UI)
      When an install of the package is triggered on the cloud-side
      Then this package appears on the software list on Cumulocity
      
```

**Comment by reubenmiller** [comment]
Looking at the code base, there does not seem to be any current references to the `integration-tests` in rust code. The functionality mentioned here has already been ported to `PySys`, and will be ported to `RobotFramework`.
