### ISSUE TITLE
"cargo-udeps" job is not run

### ISSUE THREAD

**Issue by matthiasbeyer** [thin-edge/thin-edge.io#1312]
In #1311 I changed rust code, but [the "udeps" job](https://github.com/thin-edge/thin-edge.io/runs/7626868894?check_suite_focus=true) is not run although [the workflow file looks like](https://github.com/thin-edge/thin-edge.io/blob/main/.github/workflows/pull-request-checks.yml#L51) it should have been run.

**Comment by rina23q** [comment]
Filter "rust" is set to `true` as you can see from here: https://github.com/thin-edge/thin-edge.io/runs/7626869067?check_suite_focus=true
Also, other jobs which are supposed to be triggered by the `needs.changes.outputs.rust == 'true'` ran. I will check the behaviour on my fork repo.

**Comment by rina23q** [comment]
Ah! I understand. "Check unused dependencies" job must be run after the "Filter changes" job! I will create a quick PR.
![Screenshot from 2022-08-02 14-28-43](https://user-images.githubusercontent.com/18257209/182374750-cad9b956-0a15-4515-a8c6-455ab1258ef0.png)

**Comment by matthiasbeyer** [comment]
Hah! Nice! I didn't notice that it was missing the `needs` line! :tada: awesome job!

**Comment by rina23q** [comment]
It is done by #1313. Now the "cargo-udeps" runs upon the rust changes. Look at [this run](https://github.com/thin-edge/thin-edge.io/actions/runs/2784310169).
The failure of "cargo-udeps" should be addressed in another issue.
