### ISSUE TITLE
Allow upload of files to the c8y binary storage via tedge cli

### ISSUE THREAD

**Issue by mbay-ODW** [thin-edge/thin-edge.io#1315]
**Is your feature improvement request related to a problem? Please describe.**
The configuration/log plugin has implemented a logic to upload files to the binary storage of Cumulocity,
However if I develop an own plugin and need to upload files to the binary storage of c8y, I currently can not do so without implementing own Rest API logic into my plugin, using the jet token etc. .

**Describe the solution you'd like**
Since file upload logic is already available somehow in the code I would basically wish something on the cli such as:

```bash
tedge file upload c8y --file /test/filename.txt
```

For the cli I used the structure  of the cert upload. I would basically expect to get back the binaryID of the uploaded file.

**Comment by didier-wenzek** [comment]
A more generic option would be to have a [local HTTP proxy](https://github.com/thin-edge/thin-edge.io/discussions/915) to the cloud endpoint, so the full REST API of Cumulocity would be available locally.

**Comment by mbay-ODW** [comment]
Any feedback on this here? Got the same request here now:

https://tech.forums.softwareag.com/t/upload-a-base64-picture-string-via-event-message-thinedge-to-cumulocity/265434/7

**Comment by didier-wenzek** [comment]
With the new local c8y auth proxy, we are now in good position to ease file upload to c8y.

@reubenmiller can you take some time to define a solution?

**Comment by didier-wenzek** [comment]
The proposal is to extend the `tedge` cli with a `tedge c8y upload` command,
the plan being to add new Cumulocity-specific commands overtime.

```sh
$ tedge c8y upload --help

Upload a file to Cumulocity

The command create a new event for the device and attach the given file content to this new event.

Usage: tedge c8y upload

Options:
      --text <STRING>
          Text description of the event. Defaults to the event type.

      --time <DATE>
          Time of the event. Defaults to current timestamp.

      --type <STRING>
          Type of the event.
                  
      --json <JSON>
          JSON content attached to the event. Optional.
            
      --file <PATH>
          Path to the uploaded file.

      --mime-type <STRING>
          MIME type of the file content. Defaults to `application/octet-stream`
```


Note: The initial proposal was to add support for a `tedge file upload c8y` command.
However, the need is more to simplify the interactions with the [Cumulocity event API](https://cumulocity.com/api/core/#tag/Attachments)
rather than to upload files to various targets. Hence, the decision to shift the focus toward a `tedge c8y upload` command.

**Comment by reubenmiller** [comment]
@mbay-ODW Great news, this feature has been merged into the main branch and will be part of the 1.4.0 release (due this week).
