### ISSUE TITLE
Connect child devices to Cumulocity with configuration management enabled for them

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#1336]
**Is your feature request related to a problem? Please describe.**

Provide a mechanism for child devices to connect to thin-edge and report their supported configuration types so that its child device twin is created in Cumulocity with `c8y_ConfigurationUpload` and `c8y_ConfigurationDownload` capabilities enabled for the config types reported by the device.

**Describe the solution you'd like**

Implement the device provisioning mechanism as documented in https://github.com/thin-edge/thin-edge.io/pull/1236

* The `c8y-mapper` to handle the creation of child device twin using the `device-name` and `device-type` fields in the `tedge/meta` message.
* The `c8y-configuration-plugin` parses the `configuration` key in the `tedge/meta` message to extract the supported config types and create `c8y-configuration-plugin.toml` file for the child device.

**Comment by rina23q** [comment]
It's outdated and the topic is covered by the work of https://github.com/thin-edge/thin-edge.io/issues/2098. Therefore, I'd close the ticket.

**Comment by rina23q** [comment]
as above
