### ISSUE TITLE
Extend c8y-configuration-plugin to support config management in child devices

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#1337]
**Is your feature request related to a problem? Please describe.**

Support the following config management operations on child devices:
1. Fetch config snapshots from child devices to Cumulocity cloud
2. Push config updates from Cumulocity to child devices

**Describe the solution you'd like**

Implement the config management solution for child devices described in: https://github.com/thin-edge/thin-edge.io/pull/1236

* The `c8y-configuration-plugin` to map `c8y_ConfigUpload` requests (SmartREST 526) to `tedge/<child-id>/commands/req/config_snapshot` requests and deliver it to the appropriate child device
* Similarly, map `c8y_ConfigDownload` requests (SmartREST 524) to `tedge/<child-id>/commands/req/config_update` requests and deliver it to the appropriate child device
* The plugin uses tedge file repository to store the binary files downloaded from Cumulocity before they shared with child devices
* The plugin maps operation status updates that it receives updates from the external device to Cumulocity after mapping them to their SmartREST equivalents.
* The plugin is responsible for deleting any binary files stored in the tedge file repository after an operation completes. That applies to both the files uploaded by the plugin itself (for `config_update` operation) as well as the file uploaded by the child devices for `config_snapshot` operation.
* The c8y-configuration-plugin loads the provided config file list for a child-device from a child-devices individual TOML file
* A dummy child device process implemented in any language can be used for testing this feature. Even the mock chil device in https://github.com/thin-edge/thin-edge.io_spikes/pull/4

**Out of scope**

* Handling of operations that takes too long (failing them with timeouts)

**Comment by cstoidner** [comment]
I see things we should add to the scope:

* The `c8y-configuration-plugin` loads the provided config file list for a child-device from a child-devices individual TOML file
* Whenever the `c8y-configuration-plugin` loads the TOML file, the `c8y-configuration-plugin` creates the folder `/etc/tedge/operations/c8y/<child-id>` and creates the supported operations files `c8y_UploadConfigFile` and `c8y_DownloadConfigFile` in that folder
* The _supported operations API_ accepts supported operations in a subfolder and delcares corresponding supported operation to the clouds child-device twin, using the subfolder name as `child-id`
* Whenever the `c8y-configuration-plugin` loads the TOML file, the `c8y-configuration-plugin` sends the provided _configuration types_ defined in the child-devices TOML file to the clouds child-device twin.

Also things to add to "out of scope":
* Providing a child-device can annouce itself with its supported config-types to the plugin

**Comment by albinsuresh** [comment]
> I see things we should add to the scope:
> 
> * The `c8y-configuration-plugin` loads the provided config file list for a child-device from a child-devices individual TOML file
> * Whenever the `c8y-configuration-plugin` loads the TOML file, the `c8y-configuration-plugin` creates the folder `/etc/tedge/operations/c8y/<child-id>` and creates the supported operations files `c8y_UploadConfigFile` and `c8y_DownloadConfigFile` in that folder
> * The _supported operations API_ accepts supported operations in a subfolder and delcares corresponding supported operation to the clouds child-device twin, using the subfolder name as `child-id`
> * Whenever the `c8y-configuration-plugin` loads the TOML file, the `c8y-configuration-plugin` sends the provided _configuration types_ defined in the child-devices TOML file to the clouds child-device twin.
> 
> Also things to add to "out of scope":
> 
> * Announcing list of supported configuration files by the child-device itself (to the plugin via MQTT)

The first item has been pulled into the scope of this story. The rest of the items are more about child device provisioning and hence, would be addressed in #1336.

**Comment by initard** [comment]
**This test requires a child device.**

The child device should have a configuration file like this:

```toml
files = [
    { path = '/home/user/Desktop/file_a', type = 'file_a' },
]
```

The child device also requires a script that communicates with the parent device via MQTT and HTTP.
An example script can be found in [thin-edge.io_spikes](https://github.com/thin-edge/thin-edge.io_spikes/blob/main/file-transfer-service/child_device.py). 

Tests should cover:

# child device bootstrapping

On the child device:
1. Make a PUT request with the contents of the c8y-configuration-toml to: http://<ADDRESS>:80/tedge/file-transfer/<CHILD-ID>/c8y-configuration-plugin
2. Notify the parent device this was done by sending an MQTT message with the following topic and payload:

```text
Topic: tedge/<CHILD-ID>/commands/res/config_snapshot
Payload (json string): { "status": None,  "path": "", "type":c8y-configuration-plugin, "reason": None} 
```

3. Restart the tedge-mapper c8y

On the cloud you should see a new device created, with configuration management enabled.

# child device config snapshot
> **this assumes the child device has already been bootstrapped**. 
1. From the cloud trigger a configuration snapshot for "file_a"
2. On receiving the following mqtt message from the parent device: 

```text
Topic: [tedge/<child-id>/commands/req/config_snapshot] 
Payload: {"url":"http://127.0.0.1:80/tedge/file-transfer/<child-id>/config_snapshot/<file-type>","path":"/path/to/file","type":"<file-type>"}
```

The child device should send an executing back:
```text
Topic: [tedge/<child-id>/commands/res/config_snapshot]
Payload: {"status": "executing", "path": "/path/to/file", "type": "<file-type>", "reason": null}
```
3. Next the child device should use the URL above (from the config snapshot request payload) to PUT the file in the file transfer repository (http://ADDRESS:80/tedge/file-transfer/<child-id>/config_snapshot/<file-type>)
4. After that the child device should send successful:
```text
Topic: [tedge/<child-id>/commands/res/config_snapshot]
Payload: {"status": "successful", "path": "/path/to/file", "type": "<file-type>", "reason": null}
```
5.  The configuration should be visible in the cloud, on the child-device overview, in the configuration management tab.

# child device config update
> **this assumes the child device has already been bootstrapped**.

1. From the cloud trigger a configuration update for "file_a"
2. On receiving the following mqtt message from the parent device: 

```text
Topic: [tedge/<child-id>/commands/req/config_update] 
Payload: {"url":"http://ADDRESS:80/tedge/file-transfer/<child-id>/config_snapshot/<file-type>","path":"/path/to/file","type":"<file-type>"}
```

The child device should send an executing back:
```text
Topic: [tedge/<child-id>/commands/res/config_update]
Payload: {"status": "executing", "path": "/path/to/file", "type": "<file-type>", "reason": null}
```
3. Next the child device should use the URL above (from the config snapshot request payload) to GET the file in the file transfer repository (http://ADDRESS:80/tedge/file-transfer/<child-id>/config_snapshot/<file-type>) 
4. The child device should move the downloaded file to the "path" provided in step 2. 
5. After that the child device should send successful:
```text
Topic: [tedge/<child-id>/commands/res/config_snapshot]
Payload: {"status": "successful", "path": "/path/to/file", "type": "<file-type>", "reason": null}
```
6.  The new configuration should be updated in the path on the child device.

**Comment by rina23q** [comment]
QA check passed, therefore close this issue.
