### ISSUE TITLE
Restart of tedge-mapper-c8y is recreating deleted child devices

### ISSUE THREAD

**Issue by gligorisaev** [thin-edge/thin-edge.io#1340]
**Describe the bug**

- Sending MQTT alarm message to not existing child device, will create the child device in cloud
- Stopping tedge-mapper and sending same alarm, alarm will be sent as soon tedge-mapper gets restarted
- At same time all previously deleted child devices will be recreated

**To Reproduce**

1. DUT is connected to c8y, no child devices are existing
2. Execute: 
`sudo tedge mqtt pub 'tedge/alarms/critical/temperature_high/testing' '{ "message": "Temperature is very high", "time": "2021-01-03T05:30:45+00:00" }' -q 2 -r`
- Child device "testing" will be created and alarm will be shown in alarms section
3. Delete the Child device on c8y
4. Execute:
`sudo systemctl stop tedge-mapper-c8y.service`
5. Execute:
`sudo tedge mqtt pub 'tedge/alarms/critical/temperature_high/testing_again' '{ "message": "Temperature is very high", "time": "2021-01-03T05:30:45+00:00" }' -q 2 -r`
6. Execute:
`sudo systemctl start tedge-mapper-c8y.service`
7. Go to Child device section and observe 2 created devices, the deleted "testing" and the "testing_again"

**Expected behavior**

Deleted child device should remain deleted untill it will be recreated intentially

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [e.g. 0.1.0]

**Additional context**

**Comment by PradeepKiruvale** [comment]
Resolved with #1344

**Comment by gligorisaev** [comment]
#1344 = Build 818
