### ISSUE TITLE
thin-edge.io images on docker hub 

### ISSUE THREAD

**Issue by mbay-ODW** [thin-edge/thin-edge.io#1358]
**Is your feature request related to a problem? Please describe.**
Currently there is no docker hub image that can be used. However it would be perfect to be able to have docker image on docker hub with various tags such as armv7 armv8, musl, etc.

**Describe the solution you'd like**
See example from alpine

![image](https://user-images.githubusercontent.com/58465677/186080047-56724228-58b6-4544-a079-af8b232a42fb.png)

Currently the image has to be build manually from .deb or compiled.

**Comment by reubenmiller** [comment]
Thanks @mbay-ODW for the suggestion. Yes there has been some discussion regarding containerisation and I am trying to collect the exact requirements.

Would you be able to answer some of these questions so I get a better idea on the what you are looking for?
1. Is there a desired base image and why? Examples: alpine, debian, ubuntu etc.
2. I assume having the images in dockerhub is not a must and we could host it in [github](https://github.com/features/packages) instead?
3. Which CPU architectures are you looking to run this on? armel, armhf, arm64, amd64?

**Comment by reubenmiller** [comment]
A single process container is now published directly to ghcr.io (Github Container Registry), though we're still working on updating the documentation.

However the following multi-platform images will be created:

* [tedge-main (available now)](https://github.com/thin-edge/thin-edge.io/pkgs/container/tedge-main) - latest version built when merging into the main branch
* [tedge (avilable on next official release)](https://github.com/thin-edge/thin-edge.io/pkgs/container/tedge) - built on official releases

The following Container OS/Arch are supported (in the single multi-platform image):
* linux/amd64
* linux/arm/v6
* linux/arm/v7
* linux/amd64

The tedge-demo-container examples are also being updated to use the new container images in new single process container examples (e.g. one process per container).

**Comment by reubenmiller** [comment]
Documentation will be added as part of another ticket: https://github.com/thin-edge/thin-edge.io/issues/1949
