### ISSUE TITLE
Durring installation of thin-edge.io /var/log/tedge/agent/tedge and /var/log/tedge/agent/tedge/agent are created

### ISSUE THREAD

**Issue by gligorisaev** [thin-edge/thin-edge.io#1367]
**Describe the bug**
Durring installation of thin-edge.io 
`/var/log/tedge/agent/tedge `
and 
`/var/log/tedge/agent/tedge/agent `
are created

**To Reproduce**
Browse to `/var/log/tedge/agent/` and observe the content

**Expected behavior**
`/var/log/tedge/agent/tedge `
and 
`/var/log/tedge/agent/tedge/agent `
should not be created

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [e.g. 0.1.0]

**Additional context**

**Comment by rina23q** [comment]
Is this the same as https://github.com/thin-edge/thin-edge.io/issues/1387?
