### ISSUE TITLE
Install Shell Script broken (again)

### ISSUE THREAD

**Issue by crismancich** [thin-edge/thin-edge.io#1374]
**Description**
If you are using the install script as in the documentation, the install fails with a 404 error.
The reason is, that in the install script, the newer version (in this case 0.7.4) has already been updated. But in the same time, 0.7.4 is not already available in the downloads, so the download fails and ends in a 404.

Affected: Line 79 in 'https://raw.githubusercontent.com/thin-edge/thin-edge.io/main/get-thin-edge_io.sh'

**Reproduce**
`curl -fsSL https://raw.githubusercontent.com/thin-edge/thin-edge.io/main/get-thin-edge_io.sh | sudo sh -s`

**Expected behavior**
The install script should always run. It is the touchpoint that most people use and if its broken, it gives thin-edge a bad reputation.
As this happens not the first time, I think there should be an integration test or something, that makes sure the script does not end up in 404 errors with the default version.

**Screenshots**
![404 in install-sh](https://user-images.githubusercontent.com/7170343/187387415-0dbe81bf-3d3d-4562-ac84-b2cc3988e611.png)

**Comment by rina23q** [comment]
Today we created the new release 0.7.4. The script should work now.

**Comment by rina23q** [comment]
As it's fixed apparently, I would close the issue.
