### ISSUE TITLE
tedge unset mqtt port not functioning

### ISSUE THREAD

**Issue by gligorisaev** [thin-edge/thin-edge.io#1382]
**Describe the bug**
tedge unset mqtt port not functioning

**To Reproduce**

*Preconditions*

* thin-edge is installed on DUT
* DUT is connected to c8y
* The MQTT bind port has an custom IP address

*Steps to reproduce*

1. Use the tedge command to set the default bind address `sudo tedge config unset mqtt.port`
2. Disconnect from cloud `tedge disconnect c8y`
3. Connect to cloud `tedge connect c8y`
4. Check the bind address setting `tedge config list`

Observe that nothing has been changed, custom IP address is still set

**Expected behavior**
Unsetting the IP address of the MQTT bind address to be able to set to default

**Screenshots**

**Environment (please complete the following information):**

 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture: Linux raspberrypi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
 - thin-edge.io version 0.7.4

**Additional context**

**Comment by rina23q** [comment]
@gligorisaev Are you talking about address or port? 

> sudo tedge config unset mqtt.port
This is the port number, e.g. 1883 (default), 8883.

But on the other hand, you are saying about mqtt.bind_address
> Observe that nothing has been changed, custom IP address is still set

**Comment by gligorisaev** [comment]
Ups, used wrong copy/paste sequence, closing this issue
