### ISSUE TITLE
Creating custom log directory path is creating sub folders to the created custom folders

### ISSUE THREAD

**Issue by gligorisaev** [thin-edge/thin-edge.io#1387]
**Describe the bug**

Creating custom log directory path is creating sub folders to the created customised folders

**To Reproduce**

*Preconditions*

* thin-edge is installed on DUT
* Check if device is connected to c8y, should be ***DISCONNECTED***

*Steps*

1. Change the log path `sudo tedge config set logs.path /test`
2. Initialize the tedge_agent `sudo -u tedge tedge_agent --init`

Observe the tree of the created folder

`pi@raspberrypi:~ $ tree /test`

`/test/tedge/agent/tedge/agent`

`4 directories, 0 files`

**Expected behavior**
The folder tree should look like:

`test/tedge/agent`

Folder agent should not have subfolder `/tedge/agent`

**Screenshots**

**Environment (please complete the following information):**

 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture: Linux raspberrypi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
 - thin-edge.io version 0.7.4

**Additional context**

**Comment by gligorisaev** [comment]
The Bug still exists, pushing issue back

**Comment by rina23q** [comment]
> The Bug still exists, pushing issue back

We confirmed the bug is fixed by #1398. Therefore, close the issue.
