### ISSUE TITLE
Review current github project membership

### ISSUE THREAD

**Issue by matthiasbeyer** [thin-edge/thin-edge.io#1388]
Part of #1385 

---

With the implementation of the new governance model, the team structure now presents who is responsible for which implementation part of thin-edge.io.

There are people part of the current team structure that, to my best knowledge, are not maintainers. So I propose to review membership and remove everyone who isn't a thin-edge.io maintainer.

A list of accounts/people that are associated with the organization/project but might not be maintainers:

* Lukasz Woznicki
* Michael Abel
* Andrej Schreiner
* gligorisaev
* Hans Boef
* Christoph Rohland
* Roshan Kumar
* louiseam-sag
* mbay-ODW
* Marco Stoffel
* Philip Hooker
* sagIoTPower
* Stefan Witschel
* Tobias Sommer
* Stefan Vaillant

**Comment by TheNeikos** [comment]
I consider this to be a subset of what needs to be done in #1390

**Comment by matthiasbeyer** [comment]
Nope, sorry! This issue is about membership in the organization, not in the teams! Please re-open!

**Comment by TheNeikos** [comment]
But what membership if not of the teams?

**Comment by matthiasbeyer** [comment]
Of the organization.

**Comment by TheNeikos** [comment]
Then that would be #1389?

**Comment by matthiasbeyer** [comment]
No, that's a whole seperate issue?

**Comment by matthiasbeyer** [comment]
So it might be that resolving #1389 will automatically remove accounts that are not relevant here, but TBH I do not see any indication for that.
The main concern is that all the above accounts have writable access to this repository whereas only the maintainers should have.

**Comment by TheNeikos** [comment]
You are right, I confused _repo_ membership and _project_ membership. Of course, no-one should be in the repo except the maintainers.

**Comment by didier-wenzek** [comment]
Members that are no more contributing have been removed.
