### ISSUE TITLE
Review offsite CI jobs

### ISSUE THREAD

**Issue by matthiasbeyer** [thin-edge/thin-edge.io#1395]
Part of #1385 

---

We should review our dependency on offsite github-action runners.

Tests should generally be able to run on github-actions alone so we do not depend on network connectivity or that the external resource is reachable and up.

For that we have to carefully review our offsite-CI setup and which jobs are actually needed and which not.

**Comment by didier-wenzek** [comment]
Offsite test runners have been deprecated by https://github.com/thin-edge/thin-edge.io/pull/1714
