### ISSUE TITLE
Consolidate main and PR CI workflow

### ISSUE THREAD

**Issue by matthiasbeyer** [thin-edge/thin-edge.io#1396]
Part of #1385 

---

Right now, the workflow for building thin-edge.io on "main" is completely different than the workflow for building PRs.

This leads to working PR CI and failing "main" branch CI.

We need to consolidate and reimplement the CI pipeline to only consist of _one_ workflow for building.

**Comment by didier-wenzek** [comment]
Main and PR CI checks have been made consistent by https://github.com/thin-edge/thin-edge.io/pull/1714
