### ISSUE TITLE
"Squash and merge" is allowed or forbidden?

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#1397]
Recently, [CONTRIBUTING.md](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) is updated. I found two contradicting descriptions regarding "Squash and merge".

One hand:
>If the PR consists of more than one commit because the author added commits to address feedback, the commits should be squashed into a single commit (or more than one logical commit, if it is a big feature that needs more commits). This can be achieved by the “Squash and merge” option. If they do this, the merger is responsible for cleaning up the commit message according to the previously stated commit message guidance.

On the other hand:
> The following actions are not allowed:
...
Squash-Merging of pull requests (which is equivalent to committing to master/main directly). The github repository is configured to not allow squash merges.

What are intended here?

**Comment by didier-wenzek** [comment]
This needs to be addressed here: https://github.com/thin-edge/thin-edge.io/pull/1384

**Comment by matthiasbeyer** [comment]
In #1379 we moved the "contributing" related stuff from the `GOVERNANCE.md` file to the `CONTRIBUTING.md` file, but concluded that cleanup of the contents should happen in a seperate PR. This is what #1384 targets (as @didier-wenzek pointed out).

I'd consider this issue resolved once #1384 is merged.

**Comment by rina23q** [comment]
From #1384, I could read that we will ban "Squash and merge". It's okay. You can close the issue after the PR is merged.

**Comment by matthiasbeyer** [comment]
#1384 is merged, so I'll close this.

**Comment by matthiasbeyer** [comment]
@rina23q did you alter the setting already? Because I still see squash merges.
