### ISSUE TITLE
Complete test & doc coverage of the user-facing API

### ISSUE THREAD

**Issue by TheNeikos** [thin-edge/thin-edge.io#1404]
This is a preparation to refactoring: https://github.com/thin-edge/thin-edge.io/issues/1401. Before jumping into refactoring, we need a list of features we want to keep and be sure every thing is documented and tested:

* telemetry: measurements/alarms/events
* child devices
* health checks
* software updates
* configuration management
* log management
* device restart
* operation plugins
* software management plugins
* certificate management
* MQTT bridge creation
* tedge command.
* tedge_mapper daemon
* tedge_agent daemon
* tedge configuration

What we need here are links to doc sessions and tests we already have. If some piece is really missing then we will add tasks to fix these gaps.

**Comment by matthiasbeyer** [comment]
All the above points could be converted to actionable tasks (each point could be converted to an issue and be assigned), right?

**Comment by didier-wenzek** [comment]
> All the above points could be converted to actionable tasks (each point could be converted to an issue and be assigned), right?

What we need here are links to doc sessions and tests we already have. If some piece is really missing then we will add task to fix these gaps.

**Comment by albinsuresh** [comment]
| Topic  | User Doc | Implementation spec | Test |
| ------------- | ------------- | --- | --- |
|  |  |  |
| **Tedge Commands**  | 
| `tedge` command  | https://thin-edge.github.io/thin-edge.io/html/references/tedge.html |   |
| `tedge config` command | https://thin-edge.github.io/thin-edge.io/html/references/tedge.html | 
| `tedge cert` command | https://thin-edge.github.io/thin-edge.io/html/references/tedge.html | 
| `tedge connect` command | https://thin-edge.github.io/thin-edge.io/html/references/tedge.html | 
| `tedge disconnect` command | https://thin-edge.github.io/thin-edge.io/html/references/tedge.html | 
| `tedge mqtt` command | https://thin-edge.github.io/thin-edge.io/html/references/tedge.html | 
| **Tedge Configuration**  | 
| `tedge config` command | https://thin-edge.github.io/thin-edge.io/html/references/tedge.html | 
| `tedge.toml` config file | | NA |
| `system.toml` config file | https://thin-edge.github.io/thin-edge.io/html/howto-guides/019_how_to_use_preferred_init_system.html | NA |
| **Cloud Connectivity**  | 
| Cumulocity | https://thin-edge.github.io/thin-edge.io/html/tutorials/connect-c8y.html <br> https://thin-edge.github.io/thin-edge.io/html/howto-guides/004_connect.html |  |
| Azure | https://thin-edge.github.io/thin-edge.io/html/tutorials/connect-azure.html |
| **Telemetry**  | 
| Measurements | https://thin-edge.github.io/thin-edge.io/html/tutorials/send-thin-edge-data.html |  |
| Alarms | https://thin-edge.github.io/thin-edge.io/html/tutorials/raise-alarm.html |  |
| Events | https://thin-edge.github.io/thin-edge.io/html/tutorials/send-events.html |  |
| **Operation Management** | https://thin-edge.github.io/thin-edge.io/html/tutorials/supported_operations.html |
| Software Management | https://thin-edge.github.io/thin-edge.io/html/howto-guides/012_install_and_enable_software_management.html |  |
| Software Plugin API | https://thin-edge.github.io/thin-edge.io/html/tutorials/write-my-software-management-plugin.html | https://thin-edge.github.io/thin-edge.io/html/references/plugin-api.html |
| Apt Plugin | | | 
| Apama Plugin | https://thin-edge.github.io/thin-edge.io/html/howto-guides/017_apama_software_management_plugin.html |
| Configuration Management | https://thin-edge.github.io/thin-edge.io/html/howto-guides/025_config_management_plugin.html | https://thin-edge.github.io/thin-edge.io/html/references/c8y-configuration-management.html |
| Log Management | https://thin-edge.github.io/thin-edge.io/html/howto-guides/023_c8y_log_plugin.html | |
| **Device Monitoring** | https://thin-edge.github.io/thin-edge.io/html/tutorials/device-monitoring.html |
| **Health Monitoring** |
| Health Endpoints |  https://thin-edge.github.io/thin-edge.io/html/howto-guides/020_monitor_tedge_health.html |
| Watchdog Monitoring |  https://thin-edge.github.io/thin-edge.io/html/howto-guides/020_monitor_tedge_health.html |
| `tedge-watchdog` daemon | |
| **Mosquitto** |
| MQTT Bridge Topics | | https://thin-edge.github.io/thin-edge.io/html/references/bridged-topics.html |
| MQTT BridgeConfiguration | |
| **Mappers** |
| Cumulocity Mapper | | https://thin-edge.github.io/thin-edge.io/html/architecture/mapper.html#cumulocity-mapper |
| Azure Mapper | | https://thin-edge.github.io/thin-edge.io/html/architecture/mapper.html#azure-iot-hub-mapper |
| Collectd Mapper | https://thin-edge.github.io/thin-edge.io/html/tutorials/device-monitoring.html#configure-collectd | 
| **Thin Edge Agent** | 
| `tedge-agent` daemon| |
| `tedge-agent` MQTT APIs | |
| `tedge-agent` HTTP APIs | |

**Comment by gligorisaev** [comment]
**This table is a WIP. This WIP Label will be removed once it's complete**

| Topic  | User Doc | Implementation spec | Test |
| ------------- | ------------- | --- | --- |
|  |  |  |
| **Tedge Commands**  | 
| `tedge` command  | https://thin-edge.github.io/thin-edge.io/html/references/tedge.html | | https://github.com/thin-edge/thin-edge.io/blob/main/tests/RobotFramework/tedge/call_tedge.robot |
| `tedge config` command | https://thin-edge.github.io/thin-edge.io/html/references/tedge.html | |https://github.com/thin-edge/thin-edge.io/blob/main/tests/RobotFramework/tedge/call_tedge_config_list.robot
| `tedge cert` command | https://thin-edge.github.io/thin-edge.io/html/references/tedge.html | |https://github.com/thin-edge/thin-edge.io/blob/main/tests/RobotFramework/tedge/call_tedge_config_list.robot
| `tedge connect` command | https://thin-edge.github.io/thin-edge.io/html/references/tedge.html | |https://github.com/thin-edge/thin-edge.io/blob/main/tests/RobotFramework/tedge/call_tedge_config_list.robot
| `tedge disconnect` command | https://thin-edge.github.io/thin-edge.io/html/references/tedge.html | |https://github.com/thin-edge/thin-edge.io/blob/main/tests/RobotFramework/tedge/call_tedge_config_list.robot
| `tedge mqtt` command | https://thin-edge.github.io/thin-edge.io/html/references/tedge.html | |https://github.com/thin-edge/thin-edge.io/blob/main/tests/RobotFramework/tedge/call_tedge_config_list.robot
| **Tedge Configuration**  | 
| `tedge config` command | https://thin-edge.github.io/thin-edge.io/html/references/tedge-config.html | |https://github.com/thin-edge/thin-edge.io/blob/main/tests/RobotFramework/tedge/call_tedge_config_list.robot
| `tedge.toml` config file | | NA |
| `system.toml` config file | https://thin-edge.github.io/thin-edge.io/html/howto-guides/019_how_to_use_preferred_init_system.html | NA |no robot test yet
| **Cloud Connectivity**  | 
| Cumulocity | https://thin-edge.github.io/thin-edge.io/html/tutorials/connect-c8y.html <br> https://thin-edge.github.io/thin-edge.io/html/howto-guides/004_connect.html | |yes, not merged yet <br> yes, not merged yet|
| Azure | https://thin-edge.github.io/thin-edge.io/html/tutorials/connect-azure.html ||yes, not merged yet
| **Telemetry**  | 
| Measurements | https://thin-edge.github.io/thin-edge.io/html/tutorials/send-thin-edge-data.html |  |yes, not merged yet
| Alarms | https://thin-edge.github.io/thin-edge.io/html/tutorials/raise-alarm.html |  |yes, not merged yet
| Events | https://thin-edge.github.io/thin-edge.io/html/tutorials/send-events.html |  |yes, not merged yet
| **Operation Management** | https://thin-edge.github.io/thin-edge.io/html/tutorials/supported_operations.html |
| Software Management | https://thin-edge.github.io/thin-edge.io/html/howto-guides/012_install_and_enable_software_management.html |  |yes, not merged yet
| Software Plugin API | https://thin-edge.github.io/thin-edge.io/html/tutorials/write-my-software-management-plugin.html | https://thin-edge.github.io/thin-edge.io/html/references/plugin-api.html |no robot test yet
| Apt Plugin | | |no robot test yet| 
| Apama Plugin | https://thin-edge.github.io/thin-edge.io/html/howto-guides/017_apama_software_management_plugin.html ||no robot test yet
| Configuration Management | [https://thin-edge.github.io/thin-edge.io/html/howto-guides/025_config_management_plugin.html](https://thin-edge.github.io/thin-edge.io/html/howto-guides/025_config_management_plugin.html) | https://thin-edge.github.io/thin-edge.io/html/references/c8y-configuration-management.html |yes, not merged yet
| Log Management | https://thin-edge.github.io/thin-edge.io/html/howto-guides/023_c8y_log_plugin.html ||no robot test yet |
| **Device Monitoring** | https://thin-edge.github.io/thin-edge.io/html/tutorials/device-monitoring.html ||no robot test yet
| **Health Monitoring** |
| Health Endpoints |  https://thin-edge.github.io/thin-edge.io/html/howto-guides/020_monitor_tedge_health.html ||https://github.com/thin-edge/thin-edge.io/blob/main/tests/RobotFramework/MQTT_health_check/MQTT_health_endpoints.robot
| Watchdog Monitoring |  https://thin-edge.github.io/thin-edge.io/html/howto-guides/020_monitor_tedge_health.html ||yes, not merged yet
| `tedge-watchdog` daemon | ||yes, not merged yet
| **Mosquitto** |
| MQTT Bridge Topics | | https://thin-edge.github.io/thin-edge.io/html/references/bridged-topics.html |no robot test
| MQTT BridgeConfiguration | ||no robot test yet
| **Mappers** |
| Cumulocity Mapper | | https://thin-edge.github.io/thin-edge.io/html/architecture/mapper.html#cumulocity-mapper |yes, not merged yet
| Azure Mapper | | https://thin-edge.github.io/thin-edge.io/html/architecture/mapper.html#azure-iot-hub-mapper |no robot test
| Collectd Mapper | https://thin-edge.github.io/thin-edge.io/html/tutorials/device-monitoring.html#configure-collectd | |yes, not merged yet

| **Thin Edge Agent** | 
| `tedge-agent` daemon| |
| `tedge-agent` MQTT APIs | |
| `tedge-agent` HTTP APIs | |

**Comment by rina23q** [comment]
The table is completed. Therefore, close this issue.
