### ISSUE TITLE
Gather the pain points on implementing IIoT components and composing them

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#1406]
This is a preparation to refactoring: https://github.com/thin-edge/thin-edge.io/issues/1401.

What are the main pain points using thin-edge as a developer? When implementing an extension, adding a feature or simply fixing an issue.

**Comment by didier-wenzek** [comment]
# Pain-points of the current design

## Too many daemons and not enough flexibility

The version 0.8 of thin-edge comes with several executables:

* the `tedge` cli,
* the `tedge_mapper` daemon that provides connections to different clouds but also to `collectd`,
* the `tedge_agent` daemon that features software-management but also device restart and a file-transfer service,
* a `tedge_watchdog` daemon for `systemd`,
* two software-management plugins, `tedge_apama_plugin` and `tedge_apama_plugin`,
* two Cumulocity operation plugins, `c8y_configuration_plugin` and `c8y_log_plugin`.

These causes several issues:
* This unnecessary increases disk and memory usage, even [exceeding available resources](https://github.com/thin-edge/thin-edge.io/issues/1459).
* This introduces robustness issues - all the daemons expecting the others to be up.
* This makes packaging and deployment unnecessary complex - while the reference use-case would be to install all these features.
* This even introduces security issues - critical messages flowing over the MQTT bus.

However, reducing the number of executables is not an easy task today.
* There are small but numerous differences between each and moving code around is not so easy.
* For a user, it's convenient to have independent executables since he can launch one but not the other
  and even replace a plugin by its own implementation.

Without removing the possibility to extend thin-edge with MQTT based components,
one needs a way to extend thin-edge with components written in Rust
that follow some thin-edge contract but share no code with each others.

## No clear contract for a mapper

It's not an easy task to add support for a new cloud,
as this has been proposed [here](https://github.com/thin-edge/thin-edge.io/pull/1460)
and [here](https://github.com/thin-edge/thin-edge.io/pull/1347).
Or more precisely, this is
* tedious: One has to go through all the code base and add duplicated code with tiny variations,
* unclear: What has to be done, beyond replacing code that is obviously specific to some cloud?
* undocumented: What is the contract of a mapper? What must be done? What can be done?

It would be good to have:
* A documented cloud mapper contract materialized by a `trait`.
* This `trait` would cover all the aspects, possibly optional, of a mapper:
  connection, MQTT bridge, telemetry messages, operations, child devices
  (independently or where and when these features are used by `tedge` command of the `tedge_mapper` daemon).
* Adding a new cloud should be focused on the implementation of this `trait`, 
  and the registration of this implementation under some well-known name
  in the `tedge` command of the `tedge_mapper` daemon.

## Mix of MQTT and HTTP

The Cumulocity mapper uses a mix of MQTT and HTTP.
Nothing bad about that, even if a bit cumbersome because the HTTP requests need a JWT token retrieved form MQTT.
The issue is that this breaks the former design of the mapper event loop.
This loop uses a converter grouping all cloud specific behavior and which was originally effect-less:
returning the list of MQTT messages to be sent as a reaction to some received MQTT message.

```rust
pub trait Converter {
  fn try_convert(&mut self, input: &MQTT::Message) -> Result<Vec<MQTT::Message>, Self::Error>;
}
```

When the reaction to a message if effect-full - as sending an HTTP request and waiting for a response;
not only the converter must be `async` but the trait becomes somehow pointless,
since effects are then handled both by the converter and the mapper using the converter.
Testing the converter is also more complex. Having a mock HTTP server is not enough,
since we also have to publish fake JWT tokens over MQTT.
In practice, we experienced [hard to fix bugs](https://github.com/thin-edge/thin-edge.io/pull/1094).

An approach could be to let the converter returns not only `MQTT::Message`s but also `HTTP::Request`.
Something along the lines:

```rust
pub trait Converter {
  fn try_convert(&mut self, input: &Either<MQTT::Message,HTTP:Response>) 
    -> Result<Vec<Either<MQTT::Message,HTTP::Request>>, Self::Error>;
}
```

The responsibility of handling effects is then moved to one place, in the mapper main loop.
However, the converter needs to be stateful to handle an HTTP response in the context of the HTTP request.
Somehow we are loosing one of the benefits of the `async`/`await` model
where such a state machine is managed by the runtime.
This also introduces other issues related to concurrency,
as handling new MQTT messages while the previous ones have not been fully processed yet.

Another alternative, is to embrace side effects and `async`/`await`,
and let the converter invoke an external service waiting for the response.
And we do currently but using a trait that can be easily mocked.

This issue needs to be specifically addressed by the
[design for a new architecture](https://github.com/thin-edge/thin-edge.io/pull/1549),
with a proposal for a mix of the two communication patterns (pub/sub vs request/response).
 
## Difficulties to debug

It's not easy to trace what causes an issue or even to detect that there is a issue.
Observing the messages sent over MQTT helps a lot but is not enough.
* Some errors are logged into log files but not over MQTT.
* There are too many log files.
* Many requests are not sent over MQTT but via HTTP or executed as a command.
* Some MQTT events can not be observed over MQTT:
  connection/disconnection, session names, subscriptions.

The should be given a way to observe all the events of a running thin-edge device:
* service start / stop / crash,
* messages / requests / responses / errors,
* sent to / received from the cloud,
* sent to / received from child devices,
* exchanged between internal components.

This should be addressed globally by the core design
and not in adhoc manner by each component.

**Comment by albinsuresh** [comment]
Here are a few more:

1. **Having a centralized tedge config with core tedge configurations as well as mapper configurations in a single file**: This unified file based configuration makes it difficult to have different tedge components running as independent containers as they all need to read the config file from the same file system. So, there should be some config mechanism/service that is exposed over the network so that various components can query these configs irrespective of their location.
2. **Software plugins not accessible over-the-network**: Since software management plugins **must be** installed on the same file system as of the `tedge-agent`, this limits their deployment flexibility, especially when `tedge-agent` is deployed inside a container.

**Comment by didier-wenzek** [comment]
This [unsolved issue](https://github.com/thin-edge/thin-edge.io/issues/958) is related to the complex interactions between MQTT / HTTP and JWT over MQTT.

**Comment by didier-wenzek** [comment]
`tedge_config` is too complex for the task at hand.

See:
* https://github.com/thin-edge/thin-edge.io/issues/1783
* https://github.com/thin-edge/thin-edge.io/pull/1798
* https://github.com/thin-edge/thin-edge.io/pull/1789

**Comment by didier-wenzek** [comment]
Now that several paint points have been addressed by refactoring tasks, it's time to assess

- where we are,
- what progress have been actually made,
- what still need to be addressed.

**Comment by didier-wenzek** [comment]
### Too many daemons and not enough flexibility

This is still the case, but now we are in position to move. All the plugins are implemented as actors and can possibly be launched inside a single executable. We are postponing this move for usage-related reasons. For the user it's better to have a single large executable re-org rather than a sequence of small ones. To group all the plugins in one executable the best candidate is tedge-agent. But this implies we need first to replace the [c8y plugins with tedge plugins](https://github.com/thin-edge/thin-edge.io/issues/2048) 

### No clear contract for a mapper

The new [MQTT topic scheme](https://github.com/thin-edge/thin-edge.io/pull/2030), the [tedge plugins](https://github.com/thin-edge/thin-edge.io/pull/2069), the [digital twin representation](https://github.com/thin-edge/thin-edge.io/issues/2081) mark progress in that direction.

### Difficulties to debug

The actors refactoring has improved a log debuggability. However, things can still be improved here, as demonstrated by the lack of information we have on the CI with sporadic MQTT connection issues.

### Having a centralized tedge config with core tedge configurations as well as mapper configurations in a single file

There is still a centralized tedge-config but it's now easier for other components to add their own settings there.

### Software plugins not accessible over-the-network

The plan here is to [run tedge-agent on child-devices](https://github.com/thin-edge/thin-edge.io/issues/2018)
