### ISSUE TITLE
Meta-Issue for Documentation Improvement

### ISSUE THREAD

**Issue by switschel** [thin-edge/thin-edge.io#1412]
We need a new documentation structure with new documentation content like proposed here 
https://github.com/thin-edge/thin-edge.io/pull/1411/files and discussed here #1238 

For the new proposed structure the following task are necessary.

# Tasks

- [ ] Create new documentation folder structure
## Concepts
- [x] #1416
- [ ] #1418
- [ ] #1419
- [ ] #1420
- [ ] #1421
- [ ] #1422
- [ ] #1423
- [ ] #1424

### Device Management Concepts
- [ ] #1426
- [ ] #1427
- [ ] #1428
- [ ] #1429

## Getting Started Guide
- [ ] #1430
- [ ] #1431
- [ ] #1432
- [ ] #1433
- [ ] #1434

## How To Guides
- [ ] #1435
- [ ] #1436

## Tutorials
- [ ] #1437
- [ ] #1438
- [ ] #1439

## Reference Guide
- [ ] #1440
- [ ] #1441
- [ ] #1442
- [ ] #1443

## API Description
- [ ] #1444

## Additional Resources
- [ ] #1445
- [ ] #1446
- [ ] #1447

**Comment by reubenmiller** [comment]
The main points mentioned in this ticket has been resolved.
