### ISSUE TITLE
ansi_term is Unmaintained

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#1454]
Raised by dependabot

> The maintainer has adviced this crate is deprecated and will not
receive any maintenance.
The crate does not seem to have much dependencies and may or may not be ok to use as-is.
Last release seems to have been three years ago.

* `ansi_term` is used only indirectly by `tedge_utils`, via the `tracing-subscriber` crate.
* One can wait for https://github.com/tokio-rs/tracing/issues/2282 to be resolved.

**Comment by rina23q** [comment]
Let's wait for the fix as of now. We will recheck in two weeks.

**Comment by didier-wenzek** [comment]
Resolved by https://github.com/thin-edge/thin-edge.io/pull/1492
