### ISSUE TITLE
Reduce binary size

### ISSUE THREAD

**Issue by toewsar** [thin-edge/thin-edge.io#1459]
**Is your feature request related to a problem? Please describe.**
We are using very diskspace constrained devices, but would like to add thin-edge to them.
When mosquitto is already installed and only the tedge-binaries are missing there are ~3MB left.

**Describe the solution you'd like**
I read [here](https://github.com/johnthagen/min-sized-rust) that rust binaries can be minimized.
Some of the steps are already done in thin-edge and adding `strip` is not a big deal.
Interessting are the steps [Optimize libstd with build-std](https://github.com/johnthagen/min-sized-rust#optimize-libstd-with-build-std) and [Removing libstd with #![no_std]](https://github.com/johnthagen/min-sized-rust#removing-libstd-with-no_std), but i don't know rust so well that i could do it myself.

**Comment by didier-wenzek** [comment]
[Optimizing libstd with build-std](https://github.com/johnthagen/min-sized-rust#optimize-libstd-with-build-std) is indeed an idea to explore.

I did a quick experiment. The size is reduced by 15% 

```
$ cargo build --release
$ ls -lh target/release/tedge*
-rwxrwxrwx 2 didier didier 3.6M Sep 23 14:55 target/release/tedge
-rwxrwxrwx 2 didier didier 4.3M Sep 23 14:55 target/release/tedge_agent
-rwxrwxrwx 2 didier didier 4.7M Sep 23 14:55 target/release/tedge_mapper

$  cargo +nightly build -Z build-std=std,panic_abort --target  x86_64-unknown-linux-gnu --release
$ ls -lh target/x86_64-unknown-linux-gnu/release/tedge*
-rwxrwxrwx 2 didier didier 3.0M Sep 23 15:08 target/x86_64-unknown-linux-gnu/release/tedge
-rwxrwxrwx 2 didier didier 3.6M Sep 23 15:09 target/x86_64-unknown-linux-gnu/release/tedge_agent
-rwxrwxrwx 2 didier didier 3.9M Sep 23 15:09 target/x86_64-unknown-linux-gnu/release/tedge_mapper
```

[Removing libstd with #![no_std]](https://github.com/johnthagen/min-sized-rust#removing-libstd-with-no_std) is a complete different story that would imply a lot of code updates. I don't even think this is doable at this stage of the project.

That said this issue needs to be addressed.
* Reducing the number of executables is likely the most promising approach.
* Reducing the number of dependencies must be explored too.

**Comment by reubenmiller** [comment]
@toewsar  thin-edge.io now uses a multi-call binary approach. This reduces the overall binary size from ~40MB to ~8MB (uncompressed).

**Comment by reubenmiller** [comment]
Additional packers such as [upx](https://upx.github.io/) can be used to further decrease the binary sizes if further reduction is required (and the performance tradeoffs are ok).
