### ISSUE TITLE
Configurable address and port settings for HTTP file-transfer service

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#1479]
**Is your feature improvement request related to a problem? Please describe.**

The HTTP port on which the file-transfer service is hosted is currently hard-coded to port 80. Change it to another non-standard default like 8080 and make it configurable.

Also deprecate the `mqtt.bind_address` and `mqtt.external.bind_address` config values and replace them with a common `tedge.bind_address` and `tedge.external.bind_address` which will be used to bind both the HTTP and MQTT endpoints.

**Comment by reubenmiller** [comment]
It might be more useful to decouple the `mqtt` and `http` settings so that they be configured individually, e.g. if you want to use an internal mqtt broker, but still expose the http server for other devices to connect to.

In addition, it might make sense to reduce the number of configuration items by replacing the `bind_address` and `external.bind_address` just with one entry `bind_address` to simplify the configuration effort.

Below are the proposed configuration keys:

|Key|Description|Example values|
|---|---|---|
|`mqtt.bind_address`|MQTT bind address (could be local or external)|`127.0.0.1` or `0.0.0.0` or `192.168.1.2`|
|`mqtt.port`|MQTT port|`1883`|
|`http.bind_address`|HTTP server bind address (could be local or external)|`127.0.0.1` or `0.0.0.0` or `192.168.1.2`|
|`http.port`|HTTP server port|`8000`|

@albinsuresh What do you think?

**Comment by reubenmiller** [comment]
Though there is nothing stopping us from providing additional TLS settings which are only read if they are set.

I see the following disadvantages of having both the internal and external binding address settings for a single protocol (e.g. http)

**Disadvantages**
* Adds configuration confusion (two settings to do the same thing from a user's point of view, and the settings are mutually exclusive)
* More configuration options to maintain
* Does not follow convention used by other tools ([mosquitto](https://mosquitto.org/man/mosquitto-conf-5.html), [grafana](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#server), [nodejs http servers](https://nodejs.org/api/net.html#serverlistenoptions-callback))
* Confusion about usage of `0.0.0.0` address which is technically both internal and external

**Comment by albinsuresh** [comment]
> It might be more useful to decouple the mqtt and http settings so that they be configured individually

I agree that individual configurability of mqtt and http would be useful to a few, but the vast majority, is most likely just gonna need one. So, I agree with you that merging them into a single setting probably will take away that configurability, but at the same time I also feel that there should be another **unified config** that lets user configure both at the same time. So, may be we can keep separate `mqtt.bind_address` and `http.bind_address` but have them default to a unified `tedge.bind_address`, if they are not set individually.

> These are not used the same way. bind_address is used to tell thin-edge where mosquitto is running (but configure nothing on mosquitto). external.bind_address is used to configure a new mosquitto listerner.

The answer to that confusion is to have just one bind address setting, right? Is there is a bind address, mosquitto should be listening on that address and all thin-edge components should also be using that to connect to mosquitto. I still don't get the extra benefit in having both separately.

> I would really avoid to give 0.0.0.0 as a possible bind address as of now, since this makes mosquiito listen to all the network interfaces while there is no auth nor encryption.

I also agree that we shouldn't default to this value. But, we shouldn't prevent a user from using that value either.

**Comment by reubenmiller** [comment]
This ticket is opening up some much larger topics which is detracting from the original goal. I would recommend that we revise the scope of the ticket to the following:

* Make http server port configurable

**Comment by initard** [comment]
# how to test

This PR adds two new keys to `tedge config list` 

-  `http.port` can be set or unset 
- `http.address` is read-only and is equal to mqtt.bind_address or mqtt.external.bind_address (depending on which is set).

---

For http.port check that:
- - [ ] port value can be set
- - [ ] port value can be unset
- - [ ] port value can be get

--- 
For `http.address` check that: 
- - [ ] address value can be get AND is equal to `mqtt.bind_address` WHEN no `mqtt.external.bind_address` is set
- - [ ] address value can be get AND is equal to `mqtt.external.bind_address` WHEN `mqtt.external.bind_address` is set
