### ISSUE TITLE
Automatically update supported config list of child devices when their c8y-config-plugin.toml is updated

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#1481]
**Is your feature improvement request related to a problem? Please describe.**

Thin Edge preserves a copy of the `c8y-configuration-plugin.toml` for each child device at `/etc/tedge/c8y/<child-id>` directory. Whenever this file is updated, either locally, or as a result of a config snapshot/update requests, the supported config list on the cloud must be updated automatically by sending the SmartREST 119 message with the config types derived from this config file. This must be done using the same file-watcher mechanism used to dynamically update the supported operations of child devices.

When this file is updated with config update requests from the cloud, the config file at `/etc/tedge/c8y/<child-id>` must be updated only after the child device sends the successful response.

**Comment by rina23q** [comment]
It's outdated and it's covered by the work of https://github.com/thin-edge/thin-edge.io/issues/2098. Therefore, I'd close the ticket.
