### ISSUE TITLE
Refactor the `fs_crate` using `notify` and no more `inotify`

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#1484]
The `fs_crate`:
* fails to signal properly a directory is created under a watched directory,
* provides no way to watch recursively a directory,
* is a bit complex for the task notably because using inappropriate data structures,
* exposes a `stream` of events while a `channel` would be more convenient.

The first two points are required to detect that a new child device has been added.
Unfortunately, the [crate we use to wrap `inotify`](https://lib.rs/crates/inotify) provides no easy way to dynamically add watchers.
Hence, the proposal to use instead the [`notify` crate](https://lib.rs/crates/notify) that address our needs,
notably the most critical one a recursive mode.

AC:
* Keep the current API unchanged to avoid changes in the mapper and plugins.
* Extend this API with a support for a recursive mode.
   * Use this recursive mode to fix the mapper: it must detect and watch a new child when is added the associated directory.
* Consider a new API exposing a channel rather than a stream.
   * What would be the benefits for the mapper and plugins?

**Comment by rina23q** [comment]
Delivered in 0.8.0.
