### ISSUE TITLE
Implicit package dependencies not provided by install script

### ISSUE THREAD

**Issue by mjj29** [thin-edge/thin-edge.io#1487]
Hi there, I was starting from a very minimal debian docker container and trying to install thin-edge.io using the script. There were several missing packages which were assumed by tedge which weren't dependencies of the package and weren't installed by the script.

Specifically, you're assuming the existence of wget and sudo. Sudo should be added as a dependency of the tedge package (it tries to create a file /etc/sudoers.d/tedge, but the directory doesn't exist) - or the preinst should be rewritten to cope with that directory not existing. The script itself uses wget, but only curl is installed in my minimal install. It does nothing to ensure that wget is installed first.

I also had a following error on tedge_mapper's install:

Preparing to unpack .../tedge_mapper_0.7.5_amd64.deb ...
Unpacking tedge_mapper (0.7.5) over (0.7.5) ...
Setting up tedge_mapper (0.7.5) ...
2022-10-13T17:03:14.6537354Z  INFO flockfile::unix: Lockfile created "/run/lock/tedge-mapper-c8y.lock"
2022-10-13T17:03:14.653784801Z  INFO tedge_mapper::c8y::mapper: Initialize tedge mapper c8y
Error: Creating the directory failed: "/etc/tedge/device".
dpkg: error processing package tedge_mapper (--install):
 installed tedge_mapper package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 tedge_mapper

I don't know what's causing this though. There's a similar error with tedge_agent once I work around the mapper error:

Setting up tedge_agent (0.7.5) ...
2022-10-13T17:06:03.715879249Z  INFO flockfile::unix: Lockfile created "/run/lock/tedge_agent.lock"
2022-10-13T17:06:03.715910633Z  INFO tedge_agent::agent: tedge_agent starting
Error: Creating the directory failed: "/etc/tedge/.agent".
dpkg: error processing package tedge_agent (--install):
 installed tedge_agent package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 tedge_agent

**Comment by rina23q** [comment]
> Sudo should be added as a dependency of the tedge package (it tries to create a file /etc/sudoers.d/tedge, but the directory doesn't exist)

It's a good point. `sudo` is indeed used in postinst script, so if your device doesn't have sudo, the package installation will end up with an error. It should be a dependency on the package.

> The script itself uses wget, but only curl is installed in my minimal install. It does nothing to ensure that wget is installed first.

`wget` is used by [`get-thin-edge_io.sh`](https://github.com/thin-edge/thin-edge.io/blob/main/get-thin-edge_io.sh), however, it's not used in the package. So it should not be a dependency of any package. However, it would be better if we mention inside the [installation guide](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/howto-guides/002_installation.md).

**Comment by rina23q** [comment]
For the errors, I have questions to you @mjj29.

1) `tedge` package installation was successful before `tedge_mapper` or `tedge_agent` installation?
2) Did you install `sudo` before the installation?

**Comment by reubenmiller** [comment]
@rina23q maybe we can remove the usage of `sudo` in all debian maintainer scripts (postinst, postrm) of all packages. Maintainer scripts are run under root as `dpkg -i` requires root rights anyway. And if ownership of a file or folder needs to be modified, then you can always use `chown tedge:tedge -R ...` afterwards.

**Comment by mjj29** [comment]
1. Yes
2. No

And wget might not need to be a dependency of a package, but the get script installs other packages when it starts, but not wget. It should probably also install wget

**Comment by rina23q** [comment]
> @rina23q maybe we can remove the usage of `sudo` in all debian maintainer scripts (postinst, postrm) of all packages. Maintainer scripts are run under root as `dpkg -i` requires root rights anyway. And if ownership of a file or folder needs to be modified, then you can always use `chown tedge:tedge -R ...` afterwards.
> 
> #1557 already removed one usage of `sudo` but I think there are still some other usages out there, e.g.
> 
> * https://github.com/thin-edge/thin-edge.io/blob/0d7dd882829c69523066269ef2d6a7f9451a36ac/configuration/debian/tedge/preinst
> * https://github.com/thin-edge/thin-edge.io/blob/4ada8ea69342bd4fc5a0b1de51616d553211b7c3/configuration/debian/tedge_mapper/postinst

@reubenmiller 
Using `sudo` with `chown` is really useless, so definitely we can remove them immediately. 

But I have a mixed feeling for the case
```
sudo -u tedge -- tedge_mapper --init c8y
```
We need to run `tedge_mapper` as `tedge` user. We can use `runuser` instead, but still need to add the dependency on `runuser`. Actually, a guy changed `runuser` to `sudo` by this commit https://github.com/thin-edge/thin-edge.io/commit/1c627374f60b202dd766067404f948f1b936a2e6.

Also, we create a file under `/etc/sudoers.d/`. https://github.com/thin-edge/thin-edge.io/blob/main/configuration/debian/tedge/preinst#L16. So, I think we have anyway dependency on `sudo`.

**Comment by didier-wenzek** [comment]
> But I have a mixed feeling for the case
> ```sudo -u tedge -- tedge_mapper --init c8y```
> We need to run tedge_mapper as tedge user. We can use runuser instead, but still need to add the dependency on runuser. Actually, a guy changed runuser to sudo by this commit https://github.com/thin-edge/thin-edge.io/commit/1c627374f60b202dd766067404f948f1b936a2e6.

This changes from `runuser` to `sudo` has been made by Krzysztof in the context of yocto.

**Comment by reubenmiller** [comment]
What about switching to using `su`? This seems to be installed by default (at least in the alpine and debian docker images I tried out).

And since these commands are generally running under root to start with (in the maintainer scripts), then there is not too much of a downside imho).

You can run a command under `tedge` using:

```sh
su -c 'mkdir -p /tmp/my-tedge' -s /bin/bash tedge
```

Below shows an example usage of `su` in alpine and debian docker images and in both cases `su` was already installed.

### Example using debian:11-slim

```sh
docker run -it debian:11-slim sh
useradd tedge
su -c 'mkdir -p /tmp/my-tedge' -s /bin/bash tedge
ls -ltr /tmp
```

**Output**
```
total 4
drwxr-xr-x 2 tedge tedge 4096 Dec  2 10:47 my-tedge
```

### Example using alpine:3.14

```sh
docker run -it alpine:3.14 sh
adduser tedge --disabled-password
su -c 'mkdir -p /tmp/my-tedge' -s /bin/bash tedge
ls -ltr /tmp
```

**Output**
```
total 4
drwxr-xr-x    2 tedge    tedge         4096 Dec  2 10:50 my-tedge
```

**Comment by didier-wenzek** [comment]
@jarhodes314 experimented a similar issue, on a machine where `sudo` is installed but not configured to be used by `root`. 

> What about switching to using `su`? 

This is the way to go. One has to replace `sudo` by `su` in `configuration/debian/tedge/preinst`.

**Comment by reubenmiller** [comment]
The situation has improved dramatically recently by extending the package types provided by thin-edge.io (e.g. apk, rpm, deb and tarballs) as well as a new install script which will detect which package type you need for your system.

For example the following Dockerfile snippet can be used to install thin-edge.io in a container. It does not require sudo (as you can run it using root during build).

```dockerfile
RUN wget -O - thin-edge.io/install.sh | sh -s

# or using curl
RUN curl -fsSL https://thin-edge.io/install.sh | sh -s
```

Though if you're running thin-edge.io in a container, you will have to think about which init system to use. There are several options, but I would personally recommend using s6-overlay. There is an additional `install-service.sh` script which can also install community packages which provide the services definitions for various init systems. There is an example of running thin-edge.io under s6-overlay can be found [here](https://github.com/thin-edge/tedge-demo-container/blob/main/images/alpine-s6/alpine-s6.dockerfile)


Documentation links are here:

* [install-guide](https://thin-edge.github.io/thin-edge.io/next/install/)
* [init_systems](https://thin-edge.github.io/thin-edge.io/next/operate/installation/init_systems/)

**Comment by reubenmiller** [comment]
> @jarhodes314 experimented a similar issue, on a machine where `sudo` is installed but not configured to be used by `root`.
> 
> > What about switching to using `su`?
> 
> This is the way to go. One has to replace `sudo` by `su` in `configuration/debian/tedge/preinst`.

Any usage of sudo with maintainer scripts has been removed. Any no assumptions are made about the sudoer.d file, so the installation scripts will only add the sudoers.d config if sudo is installed.
