### ISSUE TITLE
Collectd not in 22.04 included

### ISSUE THREAD

**Issue by mbay-ODW** [thin-edge/thin-edge.io#1494]
**Describe the bug**
Currently there is no candidate via apt package manager for collectd. 
There was a critical bug, that's why it has been removed in 22.04: https://bugs.launchpad.net/ubuntu/+source/collectd/+bug/1971093

**Environment (please complete the following information):**
 - OS Ubuntu 22.04 Server (aka Jammy)
 - thin-edge.io version 0.7.5

**Additional context**
Collectd can be installed manually via:

```bash
sudo wget https://launchpad.net/ubuntu/+source/collectd/5.12.0-9/+build/23189375/+files/collectd-core_5.12.0-9_amd64.deb
sudo wget https://launchpad.net/ubuntu/+source/collectd/5.12.0-9/+build/23189375/+files/collectd_5.12.0-9_amd64.deb
sudo apt install ./collectd-core_5.12.0-9_amd64.deb
sudo apt install ./collectd_5.12.0-9_amd64.deb
```

**Comment by reubenmiller** [comment]
@mbay-ODW Thanks for posting the workaround

I'm not sure if I would classify this as a bug as it is an external package which we don't have control over it.

It looks like that the package will be eventually added back into the Ubuntu `22.04` (jammy). The package is already available in other past and future Ubuntu versions ([bionic](https://packages.ubuntu.com/search?suite=bionic&arch=any&searchon=names&keywords=collectd), [focal](https://packages.ubuntu.com/search?suite=focal&arch=any&searchon=names&keywords=collectd), [kinetic](https://packages.ubuntu.com/search?suite=kinetic&arch=any&searchon=names&keywords=collectd))

And remember if you can't ever install a package via the public repositories you can usually build it yourself by following the [collectd instructions](https://collectd.org/download.shtml)
