### ISSUE TITLE
Health status messages on startup and shutdown of tedge daemons

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#1503]
**Is your feature improvement request related to a problem? Please describe.**

This is a follow-up task of #769 which introduced health endpoints for all tedge daemons, on explicit request. It would be better if the daemons sent their health status on their own after their initialization, without an external request. These initial health messages can be used to detect the readiness of these daemons once they are started.

AC:
* The daemon to publish a retained message: `{"status": "up", "pid": <pid>, "time": <timestamp> }` to `tedge/health/{daemon}` topic on its startup, after its initialisation phase, when it's fully ready, 
* The daemon to register a retained last will message:  `{"status": "down"}` with the broker to be published on `tedge/health/{daemon}` topic, when the broker detects that this daemon is disconnected and gone.

**Comment by reubenmiller** [comment]
Yes this sounds useful, though the last will message should also contain the timestamp to make it more visible when the message was sent, e.g. `{"status": "down", "time": <timestamp> }`

Though we need to clearly document that the last will is only sent by the individual daemons so it is not 100% reliable when there are abrupt shutdowns such as power outages, however the status `up` message includes the timestamp, so observers could determine if it is a stale message.

**Comment by reubenmiller** [comment]
> Yes this sounds useful, though the last will message should also contain the timestamp to make it more visible when the message was sent, e.g. `{"status": "down", "time": <timestamp> }`
> 
> Though we need to clearly document that the last will is only sent by the individual daemons so it is not 100% reliable when there are abrupt shutdowns such as power outages, however the status `up` message includes the timestamp, so observers could determine if it is a stale message.

@didier-wenzek just reminded me that a timestamp can't be added to the last will as it must be a static message as it is registered to the server when the mqtt client connection is established.

**Comment by PradeepKiruvale** [comment]
Testing the feature

1. Install the `thin-edge.io` from the below link https://github.com/thin-edge/thin-edge.io/actions/runs/3846114903

2. Start an MQTT subscriber as below to observe the status message from each tedge daemon

`sudo tedge mqtt sub '#'`


3. verify the `tedge-mapper` status message
   `sudo systemctl stop tedge-mapper-c8y.service`   
    verify `[tedge/health/tedge-mapper-c8y] {"pid":8071,"status":"down"}` in the subscriber

    `sudo systemctl start tedge-mapper-c8y.service`
    verify `[tedge/health/tedge-mapper-c8y] {"pid":10049,"status":"up","time":1672975231}` in the subscriber

    Note: Here `pid` will be different, the status must be `up` when starts and `down` when stops.



4. verify the `tedge-agent` status message
   `sudo systemctl stop tedge-agent.service`   
    verify `[tedge/health/tedge-agent] {"pid":8758,"status":"down"}` in the subscriber

    `sudo systemctl start tedge-agent.service`
    verify `[tedge/health/tedge-agent] {"pid":10049,"status":"up","time":1672975231}` in the subscriber

    Note: Here `pid` will be different, the status must be `up` when starts and `down` when stops.


5. verify the `c8y-log-plugin` status message
   `sudo systemctl stop c8y-log-plugin.service`   
    verify `[tedge/health/c8y-log-plugin] {"pid":8071,"status":"down"}` in the subscriber

    `sudo systemctl start  c8y-log-plugin.service`
    verify `[tedge/health/c8y-log-plugin] {"pid":10463,"status":"up","time":1672975587}` in the subscriber

    Note: Here `pid` will be different, the status must be `up` when starts and `down` when stops.

5. verify the `c8y-configuration-plugin` status message
   `sudo systemctl stop c8y-configuration-plugin.service`   
    verify `[tedge/health/c8y-configuration-plugin] {"pid":8071,"status":"down"}` in the subscriber

    `sudo systemctl start  c8y-configuration-plugin.service`
    verify `[tedge/health/c8y-configuration-plugin] {"pid":10463,"status":"up","time":1672975587}` in the subscriber

    Note: Here `pid` will be different, the status must be `up` when starts and `down` when stops.


6.  verify the `tedge-watchdog` status message
     Enable watchdog for `tedge-mapper-c8y` service as below
     in file  `/usr/lib/systemd/system/tedge-mapper-c8y.service` add `WatchdogSec=10` under `[Service]` section
        
   `sudo systemctl start tedge-watchdog.service`   
    verify `[tedge/health/tedge-watchdog] {"pid":8071,"status":"up","time":1672975231}` in the subscriber

    `sudo systemctl stop tedge-watchdog.service`
    verify `[tedge/health/tedge-watchdog] {"pid":10049,"status":"down"}` in the subscriber

    Note: Here `pid` will be different, the status must be `up` when starts and `down` when stops.
