### ISSUE TITLE
Configuration Options

### ISSUE THREAD

**Issue by mstoffel-sag** [thin-edge/thin-edge.io#1504]
**Is your feature request related to a problem? Please describe.**
It is frustration that I have to use the tedge cli for configuration. It is very limiting. We also need other option to get the executable configured.

**Describe the solution you'd like**
Make configuration possible in the following ways:

- Config File
Have a default configuration file including docs in comments for all viable options (like most linux programs have). The config file location can be configured via a command line argument for the executable.
- Command line parameters
Each config parameter can be provided via a command line argument
- Environment variables
Each config parameter can be provided via an Environment variable

**Additional context**
This would be very helpful for running thinedge outside systemd envs. Also would enable containerisation.

**Comment by didier-wenzek** [comment]
> Have a default configuration file including docs in comments for all viable options

This is an option we can indeed consider.

> This would be very helpful for running thinedge outside systemd envs. Also would enable containerisation.

[thin-edge can be configured to use another init system](https://thin-edge.github.io/thin-edge.io/html/howto-guides/019_how_to_use_preferred_init_system.html)

**Comment by reubenmiller** [comment]
Good news this is covered as part of #1783. It will be included in 0.10.0. It has been merged into main already, however it is still under official verification.
