### ISSUE TITLE
Use CA signed certificates

### ISSUE THREAD

**Issue by mstoffel-sag** [thin-edge/thin-edge.io#1505]
**Is your feature improvement request related to a problem? Please describe.**
Right now the we rely heavily on self signed certificates which are generated and als oploaded via tedge cli. This is no production scenario. 

**Describe the solution you'd like**
We should describe how to use real ca signed certificates. How to configure thinEdge to use the device cert and how to upload the ca to c8y 

**Additional context**
We should put pressure on c8y core RND to implement a Certificate Revocation List to make that whole scenario production ready.

**Comment by didier-wenzek** [comment]
The documentation to use a CA signed certificate is indeed missing.

**Comment by reubenmiller** [comment]
Though I am afraid this is really a much larger topic for a PKI in general. The whole certificate lifecycle needs to be addressed (e.g. root cert creation, CSR (device cert creation via Certificate Signing Request), renewal, revocation etc.)

**Comment by mstoffel-sag** [comment]
Actually I think we could start where to put/configure the client cert on thinEdge. And where to upload the CA to cumulocity.....

**Comment by didier-wenzek** [comment]
Certificate related docs have been updated with https://github.com/thin-edge/thin-edge.io/pull/2585

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the function and it's functioning according description.
