### ISSUE TITLE
Document configuration management contract for child device agents

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#1513]
Write a user-facing document on how to write a child device agent to work with `c8y-configuration-plugin` explaining the following contracts:

* Child device bootstrap contract
* How to handle `config_snapshot` requests?
* How to handle `config_update` request?
* How to use the file-transfer repository for config file exchanges?
 
Our [child device agent](https://github.com/thin-edge/thin-edge.io_spikes/blob/main/file-transfer-service/child_device.py) sample written in Python can be linked for reference.

**Comment by albinsuresh** [comment]
Documentation available at https://thin-edge.github.io/thin-edge.io/html/howto-guides/child_device_config_management_agent.html

**Comment by gligorisaev** [comment]
This document can be created according the new structure implemented by Hans. I will send to Albin my proposal document
