### ISSUE TITLE
`notify` crate: separate file created from directory created; and file deleted from directory deleted  

### ISSUE THREAD

**Issue by initard** [thin-edge/thin-edge.io#1520]
**Is your feature improvement request related to a problem? Please describe.**

With the new `notify` crate: https://docs.rs/notify/latest/notify/ we have the ability to segregate file creation from directory creation, file deletion from directory deletion: https://docs.rs/notify/latest/notify/event/enum.CreateKind.html. It would be nice to allow this flexibility in our ```pub enum FileEvent```, which currently only deals with Created, Deleted, Modified events. 

**Describe the solution you'd like**

- [x] Rename `FileEvent` to `FsEvent` and extend with the following variants:
```rust
FsEvent {
     FileCreated,
     FileDeleted,
     DirCreated,
     DirDeleted
}
```

- [x] Map CreateKind::Dir to FsEvent::DirCreated, CreateKind::File to FsEvent::FileCreated.
- [x] Map RemoveKind::Dir to FsEvent::DirDeleted, RemoveKind::File to FsEvent::FileDeleted. 
- [x] In the code-base when watching for a directory created, change to watch for `DirCreated`. 
- [x] In the code-base when watching for a file crated, change to watch for `FileCreated`.
etc..

- [x] Fix, all the tests include the crate tests to make use of the new enum variants.

**Describe alternatives you've considered**

**Additional context**

**Comment by rina23q** [comment]
Deliver in 0.8.1.
