### ISSUE TITLE
Empty directory for a child ops not creating the child device in c8y

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#1526]
**Describe the bug**
When a directory created in `/etc/tedge/operations/c8y/child_test`, its not creating the child device `child_test` in c8y.

Creates the child device in c8y only when at least one operation is inside the `child operation` directory.

**To Reproduce**
`sudo tedge connect c8y`
`sudo mkdir /etc/tedge/operations/c8y/child_test`

**Expected behavior**
Expect a child device to appear in c8y cloud under the `tedge` device.

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [e.g. 0.1.0]

**Additional context**
Maybe we need to handle this error 
[tedge/errors] Is a directory (os error 21)

**Comment by rina23q** [comment]
Deliver in 0.8.1.
