### ISSUE TITLE
c8y-log-plugin not working properly: "Is your path key correct?"

### ISSUE THREAD

**Issue by mbay-ODW** [thin-edge/thin-edge.io#1532]
**Describe the bug**
Currently the log-plugin is not working properly anymore. Requesting a log file results in:

"Handling of operation failed with No logs available for log type: software-management. Hint: is your `path` key correct?"

However if you rewrite the c8y-log-plugin.toml via the Cumulocity IoT device management it works.

**To Reproduce**
1. Get snapshot:

<img width="993" alt="image" src="https://user-images.githubusercontent.com/58465677/198244105-9c226c58-bf32-4a33-abb5-c43027f56bd4.png">

2. Save to repo:
<img width="447" alt="image" src="https://user-images.githubusercontent.com/58465677/198244169-8d5a2c7d-74d9-4d55-947b-165d0ee8f3ce.png">

3. Write back to device:
<img width="999" alt="image" src="https://user-images.githubusercontent.com/58465677/198244220-c25486ca-5024-45ba-b165-b375e0514a3e.png">

The content itself was not changed with that process but now the log request works:

<img width="356" alt="image" src="https://user-images.githubusercontent.com/58465677/198244327-2f43d8b4-82e7-43ef-bda2-f610bc16a5d1.png">

**Environment (please complete the following information):**
 - OS: latest Debian on raspberry pi
 - thin-edge.io version: 0.7.5

**Comment by rina23q** [comment]
Thanks @mbay-ODW. 

The log plugin didn't load the `c8y-log-plugin.toml` at the start-up of the process. Your workaround by applying the same configuration file worked because it triggers inotify, which loads the `.toml` configuration again.

0.8.0 will contain the fix.

Note: There are two PRs having the same changes.
#1533 for `release-0.8.0` branch. #1534 for `main` branch.

**Comment by rina23q** [comment]
Delivered in 0.8.0. @mbay-ODW  Can we close it?

**Comment by mbay-ODW** [comment]
Perfect, thanks for fast delivery.
