### ISSUE TITLE
Minus sign instead of hyphen used in command line code example

### ISSUE THREAD

**Issue by rus-sag** [thin-edge/thin-edge.io#1541]
[thin-edge.io connectivity instructions](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/howto-guides/004_connect.md)

The first "hyphen" in user flag is a minus. This cause much grief if you cut and paste to the cmd line.

sudo tedge cert upload c8y –-user <username>

**Comment by rina23q** [comment]
Very good catch @rus-sag. I created a pull request to change it. Once it gets merged, I will close this issue. I checked all other docs, and only the command that you mentioned has "minus" instead of hyphen.
