### ISSUE TITLE
Certificate in in /etc/ssl/certs not being authenticated when software package specified via URL

### ISSUE THREAD

**Issue by rus-sag** [thin-edge/thin-edge.io#1550]
**Describe the bug**
Note that I can curl and wget the internal package URL on the device fine (I’ve added the SAG certificate to the device), but thin-edge’s sm plugins can’t get it. This is the signing certificate of the that server, yes. It’s in /etc/ssl/certs as a result of running update-ca-certificates, and wget and curl can both authenticate using that certificate.
 

**To Reproduce**
1. Install thin edge
2. Use the C8Y UI. device mangement/software repository/ add software. 
3. Name: apama-repo-internal, software type: apt, version: 20222::apt. 
4. Select provide a file path and point it at https://svndae.apama.com/apama_installers/Apama/debian-apt/apama-repo-internal_2022_all.deb
5. Click install.
6. Deploy to thin-edge: Go to all devices, select thin-edge device, then software, click on install software
7. Select apama-repo-internal from the list, and select 2022::apt from the drop down, then click install.
8. Click apply changes.
9. It should work, but this is where we see the error below.

**Expected behavior**
It should allow the .deb package to be installed on thin-edge.

**Screenshots**
Oct 31 14:55:08 trifle tedge_agent[13358]: #033[2m2022-10-31T14:55:08.927804075Z#033[0m #033[32m INFO#033[0m #033[1msm-agent#033[0m#033[2m:#033[0m #033[2mplugin_sm::plugin_manager#033[0m#033[2m:#033[0m Plugin activated: /etc/tedge/sm-plugins/apt
Oct 31 14:55:16 trifle tedge_agent[13358]: #033[2m2022-10-31T14:55:16.140618196Z#033[0m #033[33m WARN#033[0m #033[1msm-agent#033[0m#033[2m:#033[0m #033[2mrustls::conn#033[0m#033[2m:#033[0m Sending fatal alert BadCertificate
Oct 31 14:55:16 trifle tedge_agent[13358]: #033[2m2022-10-31T14:55:16.141220119Z#033[0m #033[31mERROR#033[0m #033[1msm-agent#033[0m#033[2m:#033[0m #033[2mplugin_sm::plugin#033[0m#033[2m:#033[0m Download error: DownloadError error: "JSON parse error: \"error sending request for url ([https://svndae.apama.com/apama_installers/Apama/debian-apt/apama-repo-internal_2022_all.deb):](https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsvndae.apama.com%2Fapama_installers%2FApama%2Fdebian-apt%2Fapama-repo-internal_2022_all.deb)%3A&data=05%7C01%7CRupert.Summerton%40softwareag.com%7C9e1cd2ca8f504302b89b08dabb58e6e9%7Cd9662eb9ad984e74a8a204ed5d544db6%7C1%7C0%7C638028287743585488%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XCTJzU%2BbLT3X9hj6xVqaB6RS8HnOb45vegeAeioQKF8%3D&reserved=0) error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer\"" for "[https://svndae.apama.com/apama_installers/Apama/debian-apt/apama-repo-internal_2022_all.deb"](https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsvndae.apama.com%2Fapama_installers%2FApama%2Fdebian-apt%2Fapama-repo-internal_2022_all.deb%2522&data=05%7C01%7CRupert.Summerton%40softwareag.com%7C9e1cd2ca8f504302b89b08dabb58e6e9%7Cd9662eb9ad984e74a8a204ed5d544db6%7C1%7C0%7C638028287743585488%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O1mBDwiEyV8D6k%2BNM93d6w0Ge73hwuFZDoKKBmrc8Cs%3D&reserved=0)

**Environment (please complete the following information):**
 - OS: armv7-debian10
 - Hardware raspberry pi 4 8GB, 4 cores
 - System-Architecture: Linux trifle.apama.com 5.10.52-v7l+ #1441 SMP Tue Aug 3 18:11:56 BST 2021 armv7l GNU/Linux
 - thin-edge.io version: 0.8.0

**Additional context**

**Comment by didier-wenzek** [comment]
Edited screenshot, highlighting the error "invalid peer certificate: UnknownIssuer":

```
Oct 31 14:55:08 trifle tedge_agent[13358]: 2022-10-31T14:55:08.927804075Z INFO sm-agent plugin_sm::plugin_managerm Plugin activated: /etc/tedge/sm-plugins/apt
Oct 31 14:55:16 trifle tedge_agent[13358]: 2022-10-31T14:55:16.140618196Z WARN sm-agent rustls::conn: Sending fatal alert BadCertificate
Oct 31 14:55:16 trifle tedge_agent[13358]: 2022-10-31T14:55:16.141220119Z ERROR sm-agent plugin_sm::plugin: Download error: DownloadError error:
    "JSON parse error: 
        \"error sending request for url ([https://svndae.apama.com/apama_installers/Apama/debian-apt/apama-repo-internal_2022_all.deb):](https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsvndae.apama.com%2Fapama_installers%2FApama%2Fdebian-apt%2Fapama-repo-internal_2022_all.deb)%3A&data=05%7C01%7CRupert.Summerton%40softwareag.com%7C9e1cd2ca8f504302b89b08dabb58e6e9%7Cd9662eb9ad984e74a8a204ed5d544db6%7C1%7C0%7C638028287743585488%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XCTJzU%2BbLT3X9hj6xVqaB6RS8HnOb45vegeAeioQKF8%3D&reserved=0)
        error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer\"" 
        for "[https://svndae.apama.com/apama_installers/Apama/debian-apt/apama-repo-internal_2022_all.deb"](https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsvndae.apama.com%2Fapama_installers%2FApama%2Fdebian-apt%2Fapama-repo-internal_2022_all.deb%2522&data=05%7C01%7CRupert.Summerton%40softwareag.com%7C9e1cd2ca8f504302b89b08dabb58e6e9%7Cd9662eb9ad984e74a8a204ed5d544db6%7C1%7C0%7C638028287743585488%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O1mBDwiEyV8D6k%2BNM93d6w0Ge73hwuFZDoKKBmrc8Cs%3D&reserved=0)

```

**Comment by reubenmiller** [comment]
@rus-sag is this still an issue?

**Comment by reubenmiller** [comment]
> 

Thanks for the details. We'll investigate how/when the ca certs are read from the OS and get back to you.

**Comment by didier-wenzek** [comment]
The root issue is likely the same as for https://github.com/thin-edge/thin-edge.io/issues/1678

**Comment by reubenmiller** [comment]
Good news @rus-sag, the thin-edge.io components now use the operating system CA store by default. We're hoping this makes the behaviour more predictable for users.

So for example as long as the server's certificates have been added to OS's CA store then you should be good to go.

Below is an example of adding the common Let's Encrypt root and intermediate certificates into the cert store (via update-ca-certificates in Debian)

```sh
# Download certs
curl https://letsencrypt.org/certs/isrgrootx1.pem | sudo tee /usr/local/share/ca-certificates/ISRGRootX1.crt
curl https://letsencrypt.org/certs/lets-encrypt-r3.pem | sudo tee /usr/local/share/ca-certificates/lets-encrypt-r3.crt

# Regenerate cert store (e.g. /etc/ssl/certs/ca-certificates.crt)
sudo update-ca-certificates
```

Afterwards you can verify if a server's certificate is trusted or not via a simple curl request (assuming your server supports https), as curl will also use the OS's CA store by default.

```sh
curl https://myserver.example.com
```

### How can I try it out?

You can install the latest thin-edge.io pre-release version from our public Debian repository. Instructions can be found [here](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/developer/DEBIAN_PACKAGE_HOSTING.md).

**Comment by reubenmiller** [comment]
Closing as it should be fixed now in the pre-release version or in the upcoming 0.11.0 release. Please open the ticket again if you are experience the same error after updating.
