### ISSUE TITLE
Update after stopping tedge_agent not functioning until key file is manually deleted

### ISSUE THREAD

**Issue by gligorisaev** [thin-edge/thin-edge.io#1551]
**Describe the bug**
According the How to documentation in order to make tedge update user can use the same script as the fresh installation, but tedge components need to be stopped. 

**To Reproduce**
Following the documentation:
To successfully upgrade thin-edge.io all thin-edge.io components **must be stopped**

1. `sudo systemctl stop tedge-mapper-c8y`
2. `sudo systemctl stop tedge-mapper-collectd`
3. `sudo systemctl stop tedge-agent`
4. `sudo systemctl stop c8y-log-plugin`
5. `sudo systemctl stop c8y-configuration-plugin`
6. `curl -fsSL https://raw.githubusercontent.com/thin-edge/thin-edge.io/main/get-thin-edge_io.sh | sudo sh -s`

Error message will be noticed that Another instance of tedge_agent is running
`ERROR flockfile::unix: Another instance of tedge_agent is running.`

Error will not appear only if the file:
`/run/lock/tedge_agent.lock`
will be manually removed

**Expected behavior**
the existeance of tedge_agent.lock should not be registered as another tedge_agent instance is running, having in mind that at the mentioned location 
`tedge-mapper-az.lock`  
`tedge-mapper-c8y.lock`  
`tedge-mapper-collectd.lock`
`tedge_agent.lock`
are also existing

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [e.g. 0.1.0]

**Additional context**

**Comment by rina23q** [comment]
I can guess why it happened.

1. A device has already `tedge_agent.lock` owned by `tedge` user as `tedge_agent` is supposed to run by `tedge` user.
2. However, `tedge_agent --init` is now run as `root` user. This was changed by https://github.com/thin-edge/thin-edge.io/commit/fe705ffdf2b18e09492df0ab613a69f8b5bca72f.

**Comment by rina23q** [comment]
A workaround to fix is to delete the `/run/lock/tedge_agent.lock` file. Like
```
sudo rm /run/lock/tedge_agent.lock
```

**Comment by rina23q** [comment]
Resolved by #1557. The build is [#918](https://github.com/thin-edge/thin-edge.io/actions/runs/3394522527)

**Comment by gligorisaev** [comment]
Tested: Issue cannot be reproduced

**Comment by rina23q** [comment]
Will deliver in 0.8.1
