### ISSUE TITLE
Out of the box configuration management plugin for child devices

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#1553]
**Is your feature request related to a problem? Please describe.**

Currently, a child device needing configuration management needs to develop a child device configuration management agent as per the specification [here](https://thin-edge.github.io/thin-edge.io/html/howto-guides/child_device_config_management_agent.html). It would have been better of an out-of-the-box agent was available that the user could just install on his device.

**Describe the solution you'd like**

An out-of-the-box lightweight `tedge-configuration-plugin` for Linux based devices, which can be repurposed from the existing `c8y-configuration-plugin` by making it respond to tedge `config_snapshot` and `config_update` commands instead of the `c8y_UploadConfigFile` and `c8y_DownloadConfigFile` operations from Cumulocity directly. Rest of its functionality like the usage of `c8y-configuration-plugin.toml` file for the supported config list management etc can stay the same way.

One additional functionality that this new plugin would need, which is absent in the `c8y-configuration-plugin`, is the ability to invoke a third-party logic/script on a `config_snapshot` and `config_update` request, which typically will contain the logic to perform the actual configuration read/update from/to the external physical child device over some proprietary protocol.

**Comment by reubenmiller** [comment]
Similar topic to
* #2018 
* #2017

**Comment by rina23q** [comment]
It's outdated and the topic is covered by the work of https://github.com/thin-edge/thin-edge.io/issues/2098. Therefore, I'd close the ticket.
