### ISSUE TITLE
Release thin-edge.io Debian packages on Debian repository

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#1560]
**Is your feature request related to a problem? Please describe.**
As of now, the newer version of `thin-edge.io` packages are released as `Debian` packages on Github.
The `get-thin-edge_io.sh` script will download these Debian packages and installs them onto the device.
The verification of the architecture of the device and the download of the packages for that particular architecture is done by this installation script. This is the overhead for the script and can be delegated to the package manager.

Also, this is not secure to download and install some packages on the device from insecure sources.
Customers might need some sort of secure Debian repository from where they can download the packages.

**Describe the solution you'd like**
So, release the `thin-edge.io` packages on some secure Debian package repositories like `Jfrog` or `packagecloud.io`.
When someone has to download the packages they can add a repository path to the `apt` source list and then install the packages.
Now the `apt` package manager will take care of verifying the platform type and downloading that compatible packages.
This will simplify the `thin-edge.io` `installation` script as well.

**Describe alternatives you've considered**

**Additional context**

**Comment by reubenmiller** [comment]
We have some exciting news :) 

From 0.9.0 onwards, we have published the debian packages to a publicly available debian (apt) repository. We don't have official documentation on the website just yet, however the repositories are there, so we are going for a soft release, to get some user feedback. The documentation also explains which repositories are used for which purposes.

* [How to setup and use the tedge APT repositories](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/developer/DEBIAN_PACKAGE_HOSTING.md)

We are still investigating changing the thin-edge.io installation script to make the setup even more convenient.

**Notes**
The hosting is provided for free by [cloudsmith.io](https://cloudsmith.io/~thinedge/repos/).
[![Hosted By: Cloudsmith](https://img.shields.io/badge/OSS%20hosting%20by-cloudsmith-blue?logo=cloudsmith&style=flat-square)](https://cloudsmith.com)
