### ISSUE TITLE
c8y_log_plugin connection closed before message completed

### ISSUE THREAD

**Issue by bjoernsauer** [thin-edge/thin-edge.io#1561]
**Describe the bug**

Requesting a log file from cumulocity leads to an error: connection closed before message completed. The log file request fails. The log output of the c8y_log_plugin includes following lines:

```
2022-11-07T06:41:27.43706957Z  INFO c8y_log_plugin: Log request received: 522,axcf3152-test1,mosquitto,2022-11-06T07:41:15+0100,2022-11-07T07:41:15+0100,,1000
2022-11-07T06:41:37.831719078Z ERROR c8y_log_plugin: Handling of operation: '522,axcf3152-test1,mosquitto,2022-11-06T07:41:15+0100,2022-11-07T07:41:15+0100,,1000' failed with error sending request for url (https://certification-phoenixcontact.eu-latest.cumulocity.com/event/events/34323/binaries): connection closed before message completed
```

However if I only request 1 line of the log file the request does succeed.

**To Reproduce**

Request a log file from cumulocity.

**Expected behavior:**

The log life request should complete successful.

**Environment:**

 - OS: Custom yocto build, glibc 2.35, gcc 11.2
 - Phoenix Contact AXC F 3152, Custom embedded hardware x86_64 Intel(R) Atom(TM) Processor E3930
 - System-Architecture: Linux axcf3152 5.4.161-rt66-pxc # 1 SMP PREEMPT_RT Tue Jul 19 13:05:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 - thin-edge.io version 0.8.0

**Comment by bjoernsauer** [comment]
Here is the corresponding configuration file `c8y-log-plugin.toml`:

```
files = [
    { path = '/var/log/tedge/agent/software-*', type = 'software-management' },
    { path = '/opt/plcnext/logs/Output.log', type = 'plcnext-output' },
    { path = '/opt/plcnext/logs/plcnextapp.log', type = 'plcnext-plcnextapp' },
    { path = '/var/log/syslog', type = 'syslog' },
    { path = '/var/log/mosquitto/mosquitto.log', type = 'mosquitto' }
]
```

**Comment by reubenmiller** [comment]
@bjoernsauer thanks for the details. Just a few more questions to clarify a few points so we can effectively investigate it:
* Do you know roughly are large the log file is that you are trying to transfer?
* Is the device network connection stable?

**Comment by bjoernsauer** [comment]
The log file mosquitto.log has approximately 32 Kb.
The device is connected over LAN cable.

**Comment by reubenmiller** [comment]
Thanks for extra details. We will try to reproduce it, otherwise we will reach out for more details.

**Comment by bjoernsauer** [comment]
I have tackled down the issue. We have a restricted MTU size in our internal test network. I had to reduce the MTU size of the network interface on the device, now it's working.
So the issue was a miss configured network interface on my side. You may close the issue, thank you for your patience.

**Comment by rina23q** [comment]
It seems that we can close this issue without a problem. If you face to the same issue, feel free to reopen it.
