### ISSUE TITLE
Cannot reconnect device once it has been deleted in the tenant

### ISSUE THREAD

**Issue by rus-sag** [thin-edge/thin-edge.io#1572]
**Describe the bug**
Deleted the thin-edge device shown in Device Management/All devices. Then tried to follow instructions in thin-edge docs on how to connect your device to C8Y, but I get various errors. In particular, When I try to connect, it says certificate unknown, but when I tried to upload the cert, it says it already exists. (BTW, the reason I deleted the device in the first place was that I couldn't figure out how to recover from bug 1565.)

Confession: I am very much a newbie in C8Y so this should be treated as much as a request for help as a bug, however it was suggested to me by colleagues in Apama that filing a defect was best way to proceed.

**To Reproduce**
I ran:
```
-bash-5.0$ sudo tedge config set c8y.url apamarus.latest.stage.c8y.io
-bash-5.0$ sudo tedge config set c8y.root.cert.path /etc/ssl/certs
-bash-5.0$ sudo tedge cert create --device-id rus_tedge_device
Error: failed to create a test certificate for the device rus_tedge_device.

Caused by:
    A certificate already exists and would be overwritten.
            Existing file: "/etc/tedge/device-certs/tedge-certificate.pem"
            Run `tedge cert remove` first to generate a new certificate.

-bash-5.0$ sudo tedge config set c8y.url apamarus.latest.stage.c8y.io
-bash-5.0$ sudo tedge config set c8y.root.cert.path /etc/ssl/certs
-bash-5.0$ sudo tedge connect c8y
The system config file '/etc/tedge/system.toml' doesn't exist. Use '/bin/systemctl' as a service manager.

Checking if systemd is available.

Checking if configuration for requested bridge already exists.

Error: failed to connect Cumulocity cloud.

Caused by:
    Connection is already established. To remove existing connection use 'tedge disconnect c8y' and try again.
-bash-5.0$ sudo tedge disconnect c8y
The system config file '/etc/tedge/system.toml' doesn't exist. Use '/bin/systemctl' as a service manager.

Removing Cumulocity bridge.

Applying changes to mosquitto.

Cumulocity Bridge successfully disconnected!

Stopping tedge-mapper-c8y service.

Disabling tedge-mapper-c8y service.

tedge-mapper-c8y service successfully stopped and disabled!

Stopping tedge-agent service.

Disabling tedge-agent service.

tedge-agent service successfully stopped and disabled!

-bash-5.0$ sudo tedge connect c8y
The system config file '/etc/tedge/system.toml' doesn't exist. Use '/bin/systemctl' as a service manager.

Checking if systemd is available.

Checking if configuration for requested bridge already exists.

Validating the bridge certificates.

Creating the device in Cumulocity cloud.

ERROR: Io(Custom { kind: InvalidData, error: AlertReceived(CertificateUnknown) })
Error: failed to connect Cumulocity cloud.

Caused by:
    Connection check failed
-bash-5.0$ sudo tedge cert upload c8y --user apamabld
Enter password:
Certificate already exists in the cloud.
```

**Expected behavior**
An easy way to reconnect a deleted device.

**Screenshots**

**Environment (please complete the following information):**
 OS: armv7-debian10
Hardware raspberry pi 4 8GB, 4 cores
System-Architecture: Linux trifle.apama.com 5.10.52-v7l+ https://github.com/thin-edge/thin-edge.io/issues/1441 SMP Tue Aug 3 18:11:56 BST 2021 armv7l GNU/Linux
thin-edge.io version: 0.8.0

**Additional context**

**Comment by reubenmiller** [comment]
thanks @rus-sag for the details. Your message is a little bit difficult to see which is a command which is the command output. Could you please reformat it to make use of code blocks?

You can use triple back-ticks in the markdown to denote a code block. Below is the markdown, and after than is how an example could look like (when rendered)

````markdown
```
Using 3 back-ticks will render the lines as a full code block
```
````

Example showing a more readable command and output

1. I ran a command to collect the logs
   ```
    sudo journalctl -u tedge-agent -n 10
   ```

    **Output**
    ```
    Nov 09 07:37:39 lima-ubuntu sudo[25770]: pam_unix(sudo:session): session closed for user root
    Nov 09 07:37:39 lima-ubuntu tedge_agent[25740]: 2022-11-09T07:37:39.054484862Z ERROR sm-agent: plugin_sm::plugin_manager: File /etc/tedge/sm-plugins/apama in plugin directory does not support list operation and may not be a valid plugin, skipping.
    Nov 09 07:37:39 lima-ubuntu sudo[25775]:    tedge : PWD=/ ; USER=root ; COMMAND=/etc/tedge/sm-plugins/apt list
    Nov 09 07:37:39 lima-ubuntu sudo[25775]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=998)
    Nov 09 07:37:39 lima-ubuntu sudo[25775]: pam_unix(sudo:session): session closed for user root
    Nov 09 07:37:39 lima-ubuntu tedge_agent[25740]: 2022-11-09T07:37:39.239769286Z  INFO sm-agent: plugin_sm::plugin_manager: Plugin activated: /etc/tedge/sm-plugins/apt
    Nov 09 07:37:39 lima-ubuntu tedge_agent[25740]: 2022-11-09T07:37:39.239802992Z  INFO sm-agent: plugin_sm::plugin_manager: Default plugin type: Not configured
    Nov 09 07:37:39 lima-ubuntu sudo[25782]:    tedge : PWD=/tmp ; USER=root ; COMMAND=/etc/tedge/sm-plugins/apt list
    Nov 09 07:37:39 lima-ubuntu sudo[25782]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=998)
    Nov 09 07:37:39 lima-ubuntu sudo[25782]: pam_unix(sudo:session): session closed for user root
    ```

Since writing long markdown in GitHub directly is annoying (e.g. you can't easily indent multiple lines), I write it in a text editor first, then just paste the text afterwards. There are many text editors which also provide a markdown viewer from within the editor (e.g. VSCode)

**Comment by reubenmiller** [comment]
I tried to reproduce this issue by running the following sequence and did not have a problem.

1. Generate a device certificate
2. Upload the device certificate
3. Connect to c8y
4. Verify the device exists in Cumulocity
5. Delete the device
6. Disconnect tedge
7. Connect tedge
8. Verify that a new device has been created in Cumulocity

Are you sure your certificate was not uploaded to a different tenant at some point in time?

The same device certificate can only be uploaded to one tenant, for example the certificate fingerprint must be unique on the whole Cumulocity Instance (not just inside the tenant).

**Comment by rus-sag** [comment]
Hi Reuben,

sorry I haven't replied sooner, but I don't work Wednesdays. I've tried to format the output to make it easier to read. I have just retried reconnecting thin-edge device, but I see the same error:

```
-bash-5.0$ sudo tedge connect c8y
The system config file '/etc/tedge/system.toml' doesn't exist. Use '/bin/systemctl' as a service manager.

Checking if systemd is available.

Checking if configuration for requested bridge already exists.

Validating the bridge certificates.

Creating the device in Cumulocity cloud.

ERROR: Io(Custom { kind: InvalidData, error: AlertReceived(CertificateUnknown) })
Error: failed to connect Cumulocity cloud.

Caused by:
    Connection check failed
```

I also checked in the logs. The problem occurred Nov 8th, so these are the last lines in the log which seem to refer to that time:

```
Nov 01 13:02:01 trifle.apama.com sudo[3369]: pam_unix(sudo:session): session opened for user root by (uid=0)
Nov 01 13:02:01 trifle.apama.com sudo[3369]: pam_unix(sudo:session): session closed for user root
Nov 08 15:55:44 trifle.apama.com tedge_agent[13358]: 2022-11-08T15:55:44.301179745Z ERROR tedge_agent::agent: MQTT connection error: Mqtt state: Io error: Custom { kind: ConnectionAborted, error: "connection closed by peer" }
Nov 08 15:55:45 trifle.apama.com systemd[1]: Stopping tedge-agent is a thin-edge.io component to support operations....
Nov 08 15:55:45 trifle.apama.com systemd[1]: tedge-agent.service: Main process exited, code=killed, status=15/TERM
Nov 08 15:55:45 trifle.apama.com systemd[1]: tedge-agent.service: Succeeded.
Nov 08 15:55:45 trifle.apama.com systemd[1]: Stopped tedge-agent is a thin-edge.io component to support operations..
```

I don't think the certificate was uploaded to a different tenant, I only use my own one:  apamarus.latest.stage.c8y.io

**Comment by reubenmiller** [comment]
Could you backup the device certificates (on the device) and then recreate them? This would at least be helpful to narrow down the issue (and I suspect you can also proceed with using your device).

But backing up of the certificates will be useful for tracking down the root cause afterwards.

**Comment by reubenmiller** [comment]
Interesting enough I think I just ran into the same issue on one of my devices.

I don't exactly know what the lead up to this scenario was but the following were the steps I took, and how to fix it. (I think is more of a problem related to Cumulocity rather than thin-edge...maybe the certificate is not propogated to all cores so some cores are not aware that the certificate is actually trusted)

1. Tried to connect the mapper but it fails with `AlertReceived(CertificateUnknown)` error

    ```sh
    $ sudo tedge connect c8y
    The system config file '/etc/tedge/system.toml' doesn't exist. Use '/bin/systemctl' as a service manager.

    Checking if systemd is available.

    Checking if configuration for requested bridge already exists.

    Validating the bridge certificates.

    Creating the device in Cumulocity cloud.

    ERROR: Io(Custom { kind: InvalidData, error: AlertReceived(CertificateUnknown) })
    Error: failed to connect Cumulocity cloud.

    Caused by:
        Connection check failed
    ```

2. Tried to upload the certificate again but it fails with `Certificate already exists in the cloud`

    ```sh
    sudo tedge cert upload c8y --user myusername
    Enter password:
    Certificate already exists in the cloud.
    ```

3. In Cumulocity disable then enable the device certificate related to your device

4. `tedge connect c8y` works again

    ```sh
    $ sudo tedge connect c8y
    The system config file '/etc/tedge/system.toml' doesn't exist. Use '/bin/systemctl' as a service manager.

    Checking if systemd is available.

    Checking if configuration for requested bridge already exists.

    Validating the bridge certificates.

    Creating the device in Cumulocity cloud.

    Saving configuration for requested bridge.

    Restarting mosquitto service.

    Awaiting mosquitto to start. This may take up to 5 seconds.

    Enabling mosquitto service on reboots.

    Successfully created bridge connection!

    Sending packets to check connection. This may take up to 2 seconds.

    Connection check is successful.

    Checking if tedge-mapper is installed.

    Starting tedge-mapper-c8y service.

    Persisting tedge-mapper-c8y on reboot.

    tedge-mapper-c8y service successfully started and enabled!

    Enabling software management.

    Checking if tedge-agent is installed.

    Starting tedge-agent service.

    Persisting tedge-agent on reboot.

    tedge-agent service successfully started and enabled!
    ```

### How to disable/enable your device certificate in Cumulocity

1. On you device get your certificate thumbprint/fingerprint using `tedge cert show`

    ```sh
    $ tedge cert show
    Device certificate: /etc/tedge/device-certs/tedge-certificate.pem
    Subject: CN=rmiller-thin-edge.io, O=Thin Edge, OU=Test Device
    Issuer: CN=rmiller-thin-edge.io, O=Thin Edge, OU=Test Device
    Valid from: Mon, 07 Nov 2022 18:04:04 +0000
    Valid up to: Tue, 07 Nov 2023 18:04:04 +0000
    Thumbprint: 797E66D0CCE98FD7958C8AFEC0B6D26C3B7B0CCC
    ```

2. Disable then enable the device certificate via Cumulocity REST API

    **Option 1: Using REST API**

    ```sh
    PUT /tenant/tenants/{tenant}/trusted-certificates/{fingerprint}
    BODY:
        {"status": "DISABLED"}

    PUT /tenant/tenants/{tenant}/trusted-certificates/{fingerprint}
    BODY:
        {"status": "ENABLED"}
    ```

    **Option 2: Using go-c8y-cli**

    ```sh
    c8y devicemanagement certificates update --id 797E66D0CCE98FD7958C8AFEC0B6D26C3B7B0CCC --status DISABLED \
    | c8y devicemanagement certificates update --status ENABLED
    ```

    **Notes**

    * Enabling/disabling a device certificate via the UI might be easier if you can easily spot your certificate. If you have hundreds of certificates like my setup, then API calls are much easier.

**Comment by reubenmiller** [comment]
Seems like this issue might be related to a server side problem. Please reopen if necessary
