### ISSUE TITLE
The links under 002_installation.md to register and connect are broken

### ISSUE THREAD

**Issue by mstoffel-sag** [thin-edge/thin-edge.io#160]
**Is your documentation request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

**Describe the improvement you'd like**

**Additional context**
Add any other context or screenshots about the documenatation request here.

**Comment by itsyitsy** [comment]
Thank you for reporting that @mstoffel-sag, we will fix that.

**Comment by mstoffel-sag** [comment]
Could not be reproduced
