### ISSUE TITLE
Remove prompt sign from shell statement.

### ISSUE THREAD

**Issue by mstoffel-sag** [thin-edge/thin-edge.io#1616]
**Is your documentation request related to a problem? Please describe.**
In the installation manual there are several command line statements to execute. It is good to have a copy link at the end of each. It is not good the copy includes the shell prompt ($) like

`$ sudo tedge config set c8y.root.cert.path /etc/ssl/certs`

In that way the command is not executable.

**Describe the improvement you'd like**
Please remove the prompt sign from the line.

**Comment by didier-wenzek** [comment]
I agree that the prompt is annoying when the point is to give the precise command for a specific step as in:

```
$ sudo tedge config set c8y.root.cert.path /etc/ssl/certs
```

However, the point of prefixing commands with an explicit prompt is not to save some typing but to convey many details in a single *snapshot* as below:

```
$ cat /etc/tedge/c8y/c8y-configuration-plugin.toml
files = [
    { path = '/etc/tedge/tedge.toml', type = 'tedge.toml' },
    { path = '/etc/tedge/mosquitto-conf/c8y-bridge.conf' },
    { path = '/etc/tedge/mosquitto-conf/tedge-mosquitto.conf' },
    { path = '/etc/mosquitto/mosquitto.conf', type = 'mosquitto', user = 'mosquitto', group = 'mosquitto', mode = 0o644 }
  ]
```

So, I'm okay to remove some prompts from the documentation but on a case-by-case basis.

That said, I also think a user must be cautious copy-pasting `sudo` command from a website!

**Comment by mstoffel-sag** [comment]
> 



> Thanks @mstoffel-sag, yes that makes sense. Though we are always happen to accept doc PRs (it is sometimes faster than creating a ticket). I can run you through the process if you would like.

sure will do in the future.

**Comment by reubenmiller** [comment]
@mstoffel-sag @didier-wenzek 
I think we can tweak the formatting to separate the commands from the output to make it easier to copy for users, and separate the command from the output.

The following is an example where it splits the command and output into two code blocks. And when we split up the code blocks it enables the possibility to improve the layout even further in the future (via using other static website generators such as docusaurus). (I'm not saying that we should be switching to docusaurus, but saying that splitting is more flexible for the future.)


----

### Code block example

You can then check the content of that certificate.

```shell
sudo tedge cert show
```

```
Device certificate: /etc/tedge/device-certs/tedge-certificate.pem
Subject: CN=my-device, O=Thin Edge, OU=Test Device
Issuer: CN=my-device, O=Thin Edge, OU=Test Device
Valid from: Tue, 09 Feb 2021 17:16:52 +0000
Valid up to: Tue, 11 May 2021 17:16:52 +0000
Thumbprint: CDBF4EC17AA02829CAC4E4C86ABB82B0FE423D3E
```

### Code block with title (using docusaurus static website generator)

<img width="982" alt="image" src="https://user-images.githubusercontent.com/3029781/205168658-f012b06a-12e5-44a6-8157-e5e4222e36f6.png">

**Comment by mstoffel-sag** [comment]
Another suggestion here.

We have to assume that users are very very lazy (as I am too :-)
Keeping that in mind we should provide one code block or script with the happy path and put all the exceptions at the end. I also stumbled into executing 
![image](https://user-images.githubusercontent.com/29426188/205244716-888c173e-7092-4a31-8515-aaa388af6768.jpeg)
by accident...

**Comment by reubenmiller** [comment]
> Another suggestion here.
> 
> We have to assume that users are very very lazy (as I am too :-) Keeping that in mind we should provide one code block or script with the happy path and put all the exceptions at the end. I also stumbled into executing ![image](https://user-images.githubusercontent.com/29426188/205244716-888c173e-7092-4a31-8515-aaa388af6768.jpeg) by accident...

I don't think we can prevent level of "laziness" ;)

**Comment by didier-wenzek** [comment]
> Code block example

It's a nice compromise to separate the command line from its output.

**Comment by reubenmiller** [comment]
The `$` prefixes have now been removed, below is an example how it looks on the online docs
![image](https://user-images.githubusercontent.com/3029781/207082026-4227788a-6c67-4ff4-a936-8051b49dc732.png)

[Link](https://thin-edge.github.io/thin-edge.io/html/tutorials/connect-c8y.html#configure-the-device)
