### ISSUE TITLE
tedge-agent cannot start

### ISSUE THREAD

**Issue by mstoffel-sag** [thin-edge/thin-edge.io#1617]
**Describe the bug**
After installation the tedge-agent cannot start. 

sudo systemctl status tedge-agent
● tedge-agent.service - tedge-agent is a thin-edge.io component to support operations.
     Loaded: loaded (/lib/systemd/system/tedge-agent.service; enabled; vendor preset: enabled)
     Active: failed (Result: core-dump) since Tue 2022-11-29 11:08:07 UTC; 5min ago
    Process: 78767 ExecStart=/usr/bin/tedge_agent (code=dumped, signal=ABRT)
   Main PID: 78767 (code=dumped, signal=ABRT)

Nov 29 11:08:07 UbuntuTest systemd[1]: tedge-agent.service: Scheduled restart job, restart counter is at 6.
Nov 29 11:08:07 UbuntuTest systemd[1]: Stopped tedge-agent is a thin-edge.io component to support operations..
Nov 29 11:08:07 UbuntuTest systemd[1]: tedge-agent.service: Start request repeated too quickly.
Nov 29 11:08:07 UbuntuTest systemd[1]: tedge-agent.service: Failed with result 'core-dump'.
Nov 29 11:08:07 UbuntuTest systemd[1]: Failed to start tedge-agent is a thin-edge.io component to support operations..

No logfile is created

**To Reproduce**
Install via script

**Expected behavior**
working

**Screenshots**

**Environment (please complete the following information):**
 - OS ubuntu 20.04 LTS
 - Hardware AMD64
 - System-Architecture AMD64
 - thin-edge.io version 0.8.1

**Additional context**

**Comment by mstoffel-sag** [comment]
Tried to run it from the shell directly:

sudo -u tedge tedge_agent --debug
2022-11-29T11:16:39.388385494Z  INFO flockfile::unix: Lockfile created "/run/lock/tedge_agent.lock"
2022-11-29T11:16:39.388400318Z  INFO tedge_agent::agent: tedge_agent starting
2022-11-29T11:16:39.388435588Z  INFO sm-agent: tedge_agent::agent: Starting tedge agent
2022-11-29T11:16:39.388632809Z TRACE sm-agent: mio::poll: registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
2022-11-29T11:16:39.388748894Z DEBUG sm-agent: rumqttc::state: Subscribe. Topics = [Filter = tedge/commands/req/software/#, Qos = AtLeastOnce, Filter = tedge/commands/req/control/#, Qos = AtLeastOnce, Filter = tedge/health-check, Qos = AtLeastOnce, Filter = tedge/health-check/tedge-agent, Qos = AtLeastOnce], Pkid = 1
thread 'main' panicked at 'error binding to 127.0.0.1:8000: error creating server listener: Address already in use (os error 98)', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.20/src/server/server.rs:77:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted

Looks like the port is already used on the machine.

**Comment by mstoffel-sag** [comment]
It is working now. Would be good to indicate that in the systemctl status message

**Comment by didier-wenzek** [comment]
Oops, [hyper panics on bind](https://github.com/thin-edge/thin-edge.io/blob/main/crates/core/tedge_agent/src/http_rest.rs#L221).

One must use [try_bind](https://docs.rs/hyper/latest/hyper/server/struct.Server.html#method.try_bind) and not [bind](https://docs.rs/hyper/latest/hyper/server/struct.Server.html#method.bind).

**Comment by initard** [comment]
@didier-wenzek is there a need for a system test here? 

I already added a rust test for it and I feel that the effort is not worth the benefit.

**Comment by didier-wenzek** [comment]
> @didier-wenzek is there a need for a system test here?
> 
> I already added a rust test for it and I feel that the effort is not worth the benefit.

Having a system test is not necessary.
