### ISSUE TITLE
Typo in tedge command line hint

### ISSUE THREAD

**Issue by mstoffel-sag** [thin-edge/thin-edge.io#162]
When I do:

sudo tedge cert create --device-id tedge
Error: failed to create a test certificate for the device tedge.

Caused by:
    A certificate already exists and would be overwritten.
            Existing file: "/etc/tedge/device-certs/thinedge.pem"
            Run `tegde cert remove` first to generate a new certificate.

typo teged should be tedge

**Comment by itsyitsy** [comment]
Thank you for reporting, we will fix that misspelling

**Comment by PradeepKiruvale** [comment]
Fixed!
