### ISSUE TITLE
Mapping error: trailing characters on tedge-mapper-c8y startup

### ISSUE THREAD

**Issue by bjoernsauer** [thin-edge/thin-edge.io#1627]
**Describe the bug**

Starting the tedge-mapper c8y service I get the following error meassage in the tedge-mapper-c8y.log file:

```
2022-12-02T06:32:24.6277056Z  INFO flockfile::unix: Lockfile created "/run/lock/tedge-mapper-c8y.lock"
2022-12-02T06:32:24.76629353Z  INFO init: c8y_api::http_proxy: Initialisation
2022-12-02T06:32:25.18990321Z  INFO init: c8y_api::http_proxy: Initialisation done.
2022-12-02T06:32:25.19150392Z  INFO tedge_mapper::core::mapper: tedge-mapper-c8y starting
2022-12-02T06:32:25.19633927Z  INFO tedge-mapper-c8y: tedge_mapper::core::mapper: Running
2022-12-02T06:32:28.36366462Z ERROR tedge-mapper-c8y:messages{ops_dir=Some("/etc/tedge/operations/c8y")}: tedge_mapper::core::converter: Mapping error: trailing characters at line 1 column 81
```

**To Reproduce**

This error occurs every time the tedge-mapper c8y service starts.

**Expected behavior**

Normal startup without an error.

**Environment:**

- OS: Custom yocto build
- Phoenix Contact AXC F 2152, Custom embedded hardware ARMv7
- System-Architecture: Linux axcf2152 5.4.47-rt28-pxc # 1 SMP PREEMPT_RT Wed Dec 15 20:26:30 UTC 2021 armv7l armv7l armv7l GNU/Linux
- thin-edge.io version 0.8.1

**Additional context:**

I use custom software management plugin. Checked it already if it outputs trailing whitespace characters on the list command, but it looks ok to me.

**Comment by reubenmiller** [comment]
Thanks @bjoernsauer for providing the details.

Are you able to provide the custom sm plugin?

**Comment by bjoernsauer** [comment]
Hi Reuben, I'm sorry that is not possible.

**Comment by reubenmiller** [comment]
> From the logs below , it looks like there was a malformed alarm message, the mapper failed to parse the message.
> 
> ```
> [c8y/s/us] 302,temperature_alarm,"The temperature is over 99 grad celcius",2022-12-09T06:31:24Z
> [c8y-internal/alarms/major/temperature_alarm] {"time":"2022-12-09T06:31:24Z","text":"The temperature is over 99 grad celcius"}
> [tedge/errors] trailing characters at line 1 column 81
> ```
> 
> The workaround we did is clearing all the retained `alarm` messages and restarting the `mapper`. Now sending the alarm/measurement messages will not fail anymore. The mapper is working as expected.
> 
> So, the mapper should log verbose `error` messages.
> 
> The error can be reproduced by sending the below alarm message.
> 
> ```
> sudo tedge mq
> tt pub 'tedge/alarms/critical/temperature_high'  '{
>     "message": "Temperature is very high",
>     "time": "2021-01-01T05:30:45+00:00"
> }'‎  -q 2 -r
> ```
@PradeepKiruvale What was the malformation with the body (it is not so obvious, due to multiple lines, or timestamp format)?

**Comment by PradeepKiruvale** [comment]
@reubenmiller At the end of the json message, there is an `invisible non-space` character. That is what is causing the parsing error.

**Comment by PradeepKiruvale** [comment]
Steps to test 

Install the thin-edge from below link.
https://github.com/thin-edge/thin-edge.io/actions/runs/3710046820

`sudo tedge connect c8y`

publish an alarm as below

`sudo tedge mq
tt pub 'tedge/alarms/critical/temperature_high'  '{
    "message": "Temperature is very high",
    "time": "2021-01-01T05:30:45+00:00"
}'‎  -q 2 -r`

Get the log error message as below
`journalctl -u tedge-mapper-c8y.service -n 100 --no-pager | grep ERROR`

Observe an error message as below

`ERROR tedge-mapper-c8y:messages{ops_dir=Some("/etc/tedge/operations/c8y")}: tedge_mapper::core::converter: Mapping error: Parsing of alarm message received on topic: tedge/alarms/critical/temperature_high failed due to error: trailing characters at line 4 column 2. Snipped payload: {
    "message": "Temperature is very high",`

**Comment by gligorisaev** [comment]
Checked and not reproducable, needs to be verified on Yocto still

**Comment by reubenmiller** [comment]
I will close the ticket (in preparation for a release). If it fails on yocto (though that would be very surprising), then we can open up a new ticket.
