### ISSUE TITLE
Support non-interactive mode for tedge cert upload

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#1636]
**Is your feature request related to a problem? Please describe.**

Support non-interactive uploading of the device certificate via `tedge cert upload`.

Use-case

I want to be able to upload the device certificate in a non-interactive environment, eg. like when defining it in CI/CD environment or when building a custom container.

**Describe the solution you'd like**

I would suggest to add a new flag which allows the user to provide the password, `--password <string>`.

Example

```sh
# example 1: interactive (user is prompted for the password)
tedge cert upload c8y --user myuser

# example 2: non-interactive (user is NOT prompted for the password
tedge cert upload c8y --user myuser --password "mypassword"
```

**Describe alternatives you've considered**

Taking a similar approach to [docker login](https://docs.docker.com/engine/reference/commandline/login/) where there is an option that accepts reading the password from standard input.

```sh
echo "$MY_PASSWORD" | tedge cert upload c8y --user myuser --password-stdin
```

**Comment by didier-wenzek** [comment]
There is already a mechanism for that using `C8YPASS` environment variable.

```shell
C8YPASS=my-password tedge cert upload c8y --user my-user
```

**Comment by reubenmiller** [comment]
My apologies I didn't see it some how in the help, but the non-attended functionality is already there.

```sh
tedge cert upload c8y --help
tedge-cert-upload-c8y 
Upload root certificate to Cumulocity

The command will upload root certificate to Cumulocity.

USAGE:
    tedge cert upload c8y --user <USERNAME>

OPTIONS:
    -h, --help
            Print help information

        --user <USERNAME>
            Provided username should be a Cumulocity user with tenant management permissions. The
            password is requested on /dev/tty, unless the $C8YPASS env var is set to the user
            password
```
