### ISSUE TITLE
Add new tedge reconnect command

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#1638]
**Is your feature improvement request related to a problem? Please describe.**

When there are problems with the thin-edge connection to the cloud, I am often running `tedge disconnect xxxx` then `tedge connect xxxx` to refresh the connection to eliminate any problems with the mqtt bridge connection.

Running two commands just to reconnect the mqtt bridge (amongst other things) requires too much typing.

**Describe the solution you'd like**

Add support for a new `tedge reconnect` command

The reconnect command should
1. disconnect tedge (if it was previously connect, if not then only print out an INFO message saying that it was not previously connected)
2. connect tedge

Example usage:

```sh
tedge reconnect c8y
```

**Describe alternatives you've considered**

Adding a shell alias on my shell profile, however this is not very convenient as I have to add it to every device where tedge is running before I can use it.

**Comment by didier-wenzek** [comment]
This is more than just less typing. Having a reconnect command is an opportunity to remove and recreate the bridge each time and to do it *only* when something changes in the bridge configuration (say the location of certificate). This is important because removing the bridge, as `tegde disconnect` does, leads to message loss.

We also need to understand why one needs so often to reconnect and when a mosquitto restart would be enough.

**Comment by NeilCondon** [comment]
I have observed that during a current restart process (using "disconnect", followed by "connect"), ```tedge-mapper-collectd``` stops functioning.   It doesn't crash, but it stops transferring messages from ```collectd/#``` to ```tedge/measurements```.   I'm not sure why this occurs but it seems likely that its linked to the restart of mosquitto.   Perhaps this could also be resolved by a more carefully orchestrated restart?

**Comment by reubenmiller** [comment]
> I have observed that during a current restart process (using "disconnect", followed by "connect"), `tedge-mapper-collectd` stops functioning. It doesn't crash, but it stops transferring messages from `collectd/#` to `tedge/measurements`. I'm not sure why this occurs but it seems possible that its linked to the restart of mosquitto? Perhaps this could also be resolved by a more carefully orchestrated restart?

Though if this is the case, then probably is worth creating a new issue to see what is behind it. As I don't want the `tedge reconnect` to be used by users to "temporarily fix" an issue, we should always strive to finding what the actual root cause is so that users don't have to use `tedge reconnect` at all.
