### ISSUE TITLE
On tedge reconnect to c8y, child devices are not recreated

### ISSUE THREAD

**Issue by gligorisaev** [thin-edge/thin-edge.io#1639]
**Describe the bug**
if from whatever reason device that has child devices is deleted from c8y, bu using:
`sudo tedge dissconnect c8y`
`sudo tedge connect c8y`
device will be recreated in c8y but the child devices will not be recreated ever and the folders in /etc/tedge/operations/c8y are existing

**To Reproduce**
on c8y delete the device that has child device/s
`sudo tedge dissconnect c8y`
`sudo tedge connect c8y`

observe device is recreated but child devices not

**Expected behavior**
Recreation not only of the device but also the child devices as well

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [e.g. 0.1.0]

**Additional context**

**Comment by 6367f766** [comment]
See how to test in #1569
