### ISSUE TITLE
Check if `tedge-dummy-plugin` can be removed

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#1662]
Check if the `tedge-dummy-plugin` can be removed from the project

**Checklist**

* Check where it is used
* Try to access why it is being used, and what values it adds compared to other plugins etc.

**Comment by didier-wenzek** [comment]
This dummy plugin can safely be removed. Only used by PySys tests and ignored integration tests.

- crates/core/plugin_sm/tests/plugin.rs
- crates/core/plugin_sm/tests/plugin_manager.rs
- tests/PySys/software_management_end_to_end/*
