### ISSUE TITLE
tedge-apt-plugin shows incorrect version when another version candidate is available

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#1664]
**Describe the bug**

There is a bug in the `tedge-apt-plugin` where the software list is showing the incorrect packages version when the `apt` cache has been updated and a newer version of the package is available.

The root cause seems to be a problem with the parsing of `apt --manual-installed list` as the currently installed version is not in the expected place.

**Example**

Running the `apt --manual-installed list` output shows that the `tedge` version `0.8.1` is installed but is upgraded to `0.8.1-127-gb7d7d599`.

The current parsing of the output then results in publishing that the current `tedge` version is incorrectly `0.8.1-127-gb7d7d599`

```sh
apt --manual-installed list
```

Output

```
Listing... Done
tedge/tedge-main 0.8.1-127-gb7d7d599 arm64 [upgradable from: 0.8.1]
tedge_agent/now 0.8.1 arm64 [installed,local]
```

Verifying with `dpkg` shows that `0.8.1` is definitely installed (not `0.8.1-127-gb7d7d599`).

```
dpkg -s tedge | grep "^Version: "
Version: 0.8.1
```

**To Reproduce**

The instructions assume that thin-edge is installed and it is connected to Cumulocity.

1. Configure a apt repository, where two versions (e.g. `1.0.0` and `1.0.1`) of the same package are available (do a `apt-get update` to be sure everything is working correctly)
2. Install the older version (e.g. `1.0.0`) of the package via Cumulocity IoT Device Management UI
3. Check the version of the package in the software list in the Cumulocit IoT Device Management UI. The version should be `1.0.0` not `1.0.1`

**Expected behavior**

The software list only shows the version that is currently installed and not the version that it could be upgraded to.

**Environment (please complete the following information):**
 - OS [incl. version]: Debian 11 (bullseye)
 - Hardware [incl. revision]: Running as a container on (aarch64)
 - System-Architecture [e.g. result of "uname -a"]: arm64
 - thin-edge.io version [e.g. 0.1.0]: 0.8.1

**Additional context**

I'm not sure if parsing `apt` output is the best way as it is generally built for humans and not scripts. [reference](https://manpages.debian.org/buster/apt/apt.8#SCRIPT_USAGE_AND_DIFFERENCES_FROM_OTHER_APT_TOOLS)

Another approach would be using a combination of `apt-mark showmanual` and `dpkg --list` (or `dpkg-query`) which might provide a more stable approach.

```sh
apt-mark showmanual
```

```sh
dpkg --list | grep "^ii"
```

```sh
dpkg-query --show --showformat "\${Package},\${Version}\\n" | grep "^install ok installed"
```

**Comment by gligorisaev** [comment]
Checked, bug not reproducable with: 3828864963
