### ISSUE TITLE
Support custom fragments in alarm creation

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#1682]
**Is your feature request related to a problem? Please describe.**

When creating an alarm via a json payload, custom fragments are ignored and not included when creating the Cumulocity IoT Alarm.

**Describe the solution you'd like**

Alarm creation via a json payload should include any custom fragments provided when creating the Cumulocity IoT Alarm.

Example

The following command publishes a CRITICAL alarm of type `myCustomAlarmType` to thin-edge.io. It also includes a custom fragment called `someOtherCustomFragment` which includes extra information about the alarm.

```
tedge mqtt pub tedge/alarms/critical/myCustomAlarmType/child_device_example '{ "text": "Some test alarm", "someOtherCustomFragment": {"nested":{"value": "extra info"}} }'
```

The above command should produce an alarm in Cumulocity IoT which the custom fragment `someOtherCustomFragment` is also present (the `source` fragment was left out for demonstrative purposes only).

```json
{
    "severity": "critical",
    "someOtherCustomFragment": {
        "nested": {
            "value": "extra info"
        }
    },
    "text": "Some test alarm",
    "time": "2023-01-17T09:42:28.804Z",
    "type": "myCustomAlarmType"
}
```

Event creation via json already supports custom fragments, so adding custom fragment support to alarm creation would provide a more consistent interface for users.

**Describe alternatives you've considered**

No other solution was considered.

**Additional context**

Note: If the alarm existing for the same type is already `ACTIVE` or `ACKNOWLEDGED` then the custom fragment information will be ignored by Cumulocity IoT, and only the `count` fragment will be incremented by 1. The custom fragment information is only accepted by Cumulocity IoT if the alarm is "new".

**Comment by PradeepKiruvale** [comment]
The issue here is the alarm message that is sent as a JSON message to the `tedge-mapper` is converted into a `smartrest` message and forwarded to the c8y cloud. While converting it into the `Smartrest` message it filters out the `custom` fragments. This is the reason why the `custom` fragment for the alarm does not work.

For example:

```
// Send an alarm message with custom fragments as below

tedge mqtt pub tedge/alarms/critical/temp_high '{ "text": "Some test alarm", "someOtherCustomFragment": {"nested":{"value": "extra info"}} }' -q 2 -r

// Sent to cloud as smartrest message
[c8y/s/us] 301,temp_high,"Some test alarm",2023-01-24T13:31:13.99172905Z

```

Since the `Smart rest` does not support the custom fragments, the incoming alarm message must be converted to a C8y JSON message and forwarded to the c8y.

**Comment by PradeepKiruvale** [comment]
Sending the below alarm message with custom fragments as below. 

 ``` 
tedge mqtt pub 'c8y/alarm/alarms/create' '{
    "severity": "critical",
    "someOtherCustomFragment": {
        "nested": {
            "value": "extra info"
        }
    },
    "text": "Some test alarm",
    "time": "2023-01-17T09:42:28.804Z",
    "type": "myCustomAlarmType"
}' -q 2 -r

```

Note: The c8y UI does not render these messages properly. So, these alarm messages are not visible on UI. One can get the alarm messages using the `REST` apis or using the cli framework `https://goc8ycli.netlify.app/` by querying `c8y alarms list --device childops_test | jq`
