### ISSUE TITLE
Split `tedge` into multiple crates

### ISSUE THREAD

**Issue by mneumann** [thin-edge/thin-edge.io#170]
- The `tedge` crate should only be the plumbing to produce the CLI binary.

- If we decide to put both `tedge` and `mapper` into a single binary ("busybox"), we can just plug in the `tedge_cli` crate and do some minor setup here and there.

- From a testing perspective, it favors unit tests (done in `tedge_cli` or the individual command crates) over tests where we execute the `tedge` binary (the latter belong in the `tedge` crate). 

- Much clearer dependencies and better reuse. For instance, I would put the command implementations into separate crates. `tedge_command_cert`, `tedge_command_connect`, ... and put all CLI parsing and mapping of the `TEdgeOpt` to `Box<dyn Command>` (BuildCommand implementations) into `tedge_cli`. That means, each Command implementation has zero knowledge about the CLI itself unless these are injected through it's command struct. This favors unit tests where we only test the command implementation and NOT the CLI parsing. 

- Simplifies refactoring, as you can make changes local to a crate (lets say migrating `tedge_command_config` to use a new data structure), without breaking other crates or the `tedge_cli`. 

# My proposal is to split them into:

- `tedge`: This is the driver, the plumbing, that creates the final `tedge` binary.
- `tedge_cli`: A library crate that does the CLI parsing and mapping of CLI TEdgeOpt into Commands. All structopt definitions are defined here.
- `tedge_command_cert`: This only provides the `impl Command` for CertCommand. It does not contains any structopt related code (that belongs to `tedge_cli`). Unit tests concerning CertCommand are local to that crate.
- `tedge_command_*`: Analog to tedge_command_cert
- utility crates....

For busybox we can have a separate binary that basically is a copy of the minimal plumbing done by `tedge` (10-20 lines of code).

Note, none of the `tedge_command_*` should depend on `tedge_cli`. But `tedge_cli` depends on `tedge_command_*`. 

Don't nail me down on the precise naming of the individual crates. It's more about the conceptual structure.

**Comment by makr11st** [comment]
Outdated.
