### ISSUE TITLE
Configurable timeout for custom operation handler

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#1703]
**Is your feature improvement request related to a problem? Please describe.**

If a custom operation handler/(process based) plugin does not return, then thin-edge will wait forever to return. In this instance it would cause problems with the transition of future operations of the same type (for some cloud providers), and it would use unexpected resources.

**Describe the solution you'd like**

The custom operation handler configuration file (e.g. `/etc/tedge/operations/c8y/c8y_Command`) should support a `timeout` field which lets the user specify the timeout in seconds for the process being called. If the process does not exit within the timeout period, then the process should be killed (by sending a `SIGTERM`), and if the process does not exit after 60 seconds, then a `SIGKILL` should be sent.

**Requirements**
* Add support for an optional `timeout` field in the custom operation handler configuration. The timeout should be defined in seconds (as an integer)
  * The timeout field should be optional. If it is not defined then it should assume a default of `300` seconds. The default should be configurable via the `tedge.toml` file.
* If the timeout expires, then a `SIGTERM` signal should be sent to the process. If after `60` seconds (after sending the `SIGTERM`), the process still has not exited, then the process should be forcefully shutdown by sending a `SIGKILL` signal. The default should be configurable via the `tedge.toml` file.
* If the process is killed, then the operation should be set to `FAILED` and the failure reason should say `Process timed out after {timeout} seconds\n{stderr}`

**Example: Custom operation handler configuration file with timeout defined**

```
[exec]
  topic = "c8y/s/ds"
  on_message = "511"
  command = "/usr/share/tedge-contrib/bin/handle_command.sh"
  timeout = 60
```

**Describe alternatives you've considered**

On a timeout, thin-edge.io could just send a forceful `SIGKILL` to the spawned process, however that could have unexpected negative effects. So it would be more useful to provide a mechanism for the process to gracefully shutdown (as you can trap `SIGTERM` but not `SIGKILL`)

**Additional context**

**Comment by reubenmiller** [comment]
Use `7200` seconds as a default value if the custom operation file does not include a `timeout` property

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.  
         ```tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_reload/dynamically_reload_operation.robot``` 
``` tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_timeout/custom_operation.robot ```
- [x] QA has tested the feature and it meets the required specifications.
