### ISSUE TITLE
Install script is not finding dependency plugin

### ISSUE THREAD

**Issue by janhumble** [thin-edge/thin-edge.io#1707]
**Describe the bug**
Latest 0.9.0:
2023-02-02T01:01:09.839837191Z  INFO c8y_log_plugin: Creating supported operation files
Selecting previously unselected package tedge-watchdog.
dpkg: considering removing tedge_watchdog in favour of tedge-watchdog ...
dpkg: yes, will remove tedge_watchdog in favour of tedge-watchdog
(Reading database ... 37044 files and directories currently installed.)
Preparing to unpack .../tedge-watchdog_0.9.0_arm64.deb ...
Unpacking tedge-watchdog (0.9.0) ...
Setting up tedge-watchdog (0.9.0) ...
curl: (22) The requested URL returned error: 404
Failed to install thin-edge.io
Reason: Could not download package from url: [https://github.com/thin-edge/thin-edge.io/releases/download/0.9.0/c8y-remote-access-plugin_0.9.0_arm64.deb]
Please create a ticket using the following link and include the console output
    [https://github.com/thin-edge/thin-edge.io/issues/new?assignees=&labels=bug&template=bug_report.md]

**To Reproduce**
From install doc ...
curl -fsSL https://raw.githubusercontent.com/thin-edge/thin-edge.io/main/get-thin-edge_io.sh | sudo sh -s

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [e.g. 0.1.0]

**Additional context**

**Comment by reubenmiller** [comment]
Yes sorry about this, it is fixed now.

**Comment by reubenmiller** [comment]
we were a bit too eager to release the new `c8y-remote-access-plugin` and it was added to the install script too early.

**Comment by reubenmiller** [comment]
@janhumble Out of curiosity why didn't you add the full script output to the ticket? We did some recent refactoring to make the script output easy to copy-paste to a ticket when something goes wrong...the output also includes what system you're on etc. But from the ticket above you didn't post any of it.

1. Can I someone how improve the error message to involve the user that they should be copying all of it into the ticket?
2. I would encourage using code blocks for pasting "output/code". Code blocks makes the ticket a lot easier to read for everyone. Here is a link to the [Fenced code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks) syntax.
