### ISSUE TITLE
No events shown in Azure on publish

### ISSUE THREAD

**Issue by mstoffel-sag** [thin-edge/thin-edge.io#173]
**Describe the bug**
When In follow the docs to publish to Azure. Connection to IoT Hub is fine. Publish works also. But I don't see the events when I subscribe in Azure like that:

az iot hub monitor-events --output table --hub-name msIoTHub

when I create a dummy device and use a simulator 

az iot hub monitor-events --output table --hub-name msIoTHub

I see the dummy events .....

**Expected behavior**
see the thinedge events in az monitor-events

**Environment (please complete the following information):**
Linux UbuntuTest 5.4.0-1043-azure #45-Ubuntu SMP Fri Mar 19 17:33:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - thin-edge.io version [e.g. 0.1.0]

**Additional context**

**Comment by PradeepKiruvale** [comment]
Hi Mstoffel-sag, 

Thanks for reporting. I hope you are sending the messages to the cloud from the device as below.

tedge mqtt pub az/messages/events/  '{"temperature": 20}'

I know the last "/" in the topic is missing in the document. We will update that soon.

Let me know if this works.

-Pradeep

**Comment by mstoffel-sag** [comment]
yes I send from my device, how should I send it then exactly?

**Comment by mstoffel-sag** [comment]
tedge mqtt pub az/messages/events/ '{"temperature": 20}'

Works thanks
