### ISSUE TITLE
software list in Cumulocity IoT is sometimes missing after thin-edge.io startup

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#1731]
**Describe the bug**

The software list is missing sometimes in Cumulocity IoT (under the `c8y_SoftwareList` fragment on the device managed object) when **thin-edge.io** starts up.

There seems to be a race condition between the communication between the `tedge-mapper-c8y` and `tedge-agent` services.

* The `tedge-agent` service does not publish a message to `tedge/commands/res/software/list` with a list of the devices.
* The `tedge-mapper-c8y` does publishes a request to `tedge-agent` to get a list via the `tedge/commands/req/software/list` topic, however no response is sent back.

**To Reproduce**

Since this error only occurs sporadically, it has been difficult to reproduce it reliably. It first appeared when running the `integration-tests` workflow on GitHub.

A minimal set of instructions on how to reproduce this error are still being investigated. The ticket will be updated once a procedure is found.

**Expected behavior**

The software list should always be sent when the Cumulocity IoT mapper is successfully connected.

The `c8y_SoftwareList` fragment should be present (with a list of the installed packages) in the Cumulocity IoT device managed object related to the device.

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]: Debian 11 (bullseye)
 - Hardware [incl. revision]: GitHub Runner Ubuntu 20.04 (x86_64)
 - System-Architecture [e.g. result of "uname -a"]: x86_64
 - thin-edge.io version [e.g. 0.1.0]: 0.9.0-180-gb61cd45a

**Additional context**

The following sections contain the logs (from journald) which shows the sequence when the software list is sent, and when it is not. The raw log files are also available on the ticket.

Note: The below log snippets were filtered to only includes lines which contained `/software/list`. Also the mosquitto service logs was redirected to journald, and the mosquitto debug level was activated.

**:muscle: PASS: Where the software list message is sent**

```sh
Feb 17 10:35:12 ff619c80960a mosquitto[479]: 1676630112:         tedge/commands/res/software/list (QoS 1)
Feb 17 10:35:12 ff619c80960a mosquitto[479]: 1676630112: tedge-mapper-c8y 1 tedge/commands/res/software/list
Feb 17 10:35:12 ff619c80960a mosquitto[479]: 1676630112: Received PUBLISH from tedge-mapper-c8y (d0, q1, r0, m6, 'tedge/commands/req/software/list', ... (30 bytes))
Feb 17 10:35:12 ff619c80960a mosquitto[479]: 1676630112: Sending PUBLISH to tedge_agent (d0, q1, r0, m1, 'tedge/commands/req/software/list', ... (30 bytes))
Feb 17 10:35:12 ff619c80960a mosquitto[479]: 1676630112: Sending PUBLISH to auto-C9E1F53E-1DC7-09D6-D559-C3B790100A09 (d0, q0, r0, m0, 'tedge/commands/req/software/list', ... (30 bytes))
Feb 17 10:35:15 ff619c80960a mosquitto[479]: 1676630115: Received PUBLISH from tedge_agent (d0, q1, r0, m2, 'tedge/commands/res/software/list', ... (51 bytes))
Feb 17 10:35:15 ff619c80960a mosquitto[479]: 1676630115: Sending PUBLISH to tedge-mapper-c8y (d0, q1, r0, m1, 'tedge/commands/res/software/list', ... (51 bytes))
Feb 17 10:35:15 ff619c80960a mosquitto[479]: 1676630115: Sending PUBLISH to auto-C9E1F53E-1DC7-09D6-D559-C3B790100A09 (d0, q0, r0, m0, 'tedge/commands/res/software/list', ... (51 bytes))
Feb 17 10:35:18 ff619c80960a mosquitto[479]: 1676630118: Received PUBLISH from tedge_agent (d0, q1, r0, m3, 'tedge/commands/res/software/list', ... (926 bytes))
Feb 17 10:35:18 ff619c80960a mosquitto[479]: 1676630118: Sending PUBLISH to tedge-mapper-c8y (d0, q1, r0, m2, 'tedge/commands/res/software/list', ... (926 bytes))
Feb 17 10:35:18 ff619c80960a mosquitto[479]: 1676630118: Sending PUBLISH to auto-C9E1F53E-1DC7-09D6-D559-C3B790100A09 (d0, q0, r0, m0, 'tedge/commands/res/software/list', ... (926 bytes))
Feb 17 10:35:49 ff619c80960a mosquitto[479]: 1676630149:         tedge/commands/res/software/list (QoS 1)
Feb 17 10:35:49 ff619c80960a mosquitto[479]: 1676630149: tedge-mapper-c8y 1 tedge/commands/res/software/list
Feb 17 10:35:51 ff619c80960a mosquitto[479]: 1676630151:         tedge/commands/res/software/list (QoS 1)
Feb 17 10:35:51 ff619c80960a mosquitto[479]: 1676630151: tedge-mapper-c8y 1 tedge/commands/res/software/list
Feb 17 10:35:51 ff619c80960a mosquitto[479]: 1676630151: Received PUBLISH from tedge-mapper-c8y (d0, q1, r0, m6, 'tedge/commands/req/software/list', ... (30 bytes))
Feb 17 10:35:51 ff619c80960a mosquitto[479]: 1676630151: Sending PUBLISH to tedge_agent (d0, q1, r0, m3, 'tedge/commands/req/software/list', ... (30 bytes))
Feb 17 10:35:51 ff619c80960a mosquitto[479]: 1676630151: Sending PUBLISH to auto-C9E1F53E-1DC7-09D6-D559-C3B790100A09 (d0, q0, r0, m0, 'tedge/commands/req/software/list', ... (30 bytes))
Feb 17 10:35:52 ff619c80960a mosquitto[479]: 1676630152: Received PUBLISH from tedge_agent (d0, q1, r0, m6, 'tedge/commands/res/software/list', ... (51 bytes))
Feb 17 10:35:52 ff619c80960a mosquitto[479]: 1676630152: Sending PUBLISH to tedge-mapper-c8y (d0, q1, r0, m7, 'tedge/commands/res/software/list', ... (51 bytes))
Feb 17 10:35:52 ff619c80960a mosquitto[479]: 1676630152: Sending PUBLISH to auto-C9E1F53E-1DC7-09D6-D559-C3B790100A09 (d0, q0, r0, m0, 'tedge/commands/res/software/list', ... (51 bytes))
Feb 17 10:35:53 ff619c80960a mosquitto[479]: 1676630153: Received PUBLISH from tedge_agent (d0, q1, r0, m7, 'tedge/commands/res/software/list', ... (1050 bytes))
Feb 17 10:35:53 ff619c80960a mosquitto[479]: 1676630153: Sending PUBLISH to tedge-mapper-c8y (d0, q1, r0, m8, 'tedge/commands/res/software/list', ... (1050 bytes))
Feb 17 10:35:53 ff619c80960a mosquitto[479]: 1676630153: Sending PUBLISH to auto-C9E1F53E-1DC7-09D6-D559-C3B790100A09 (d0, q0, r0, m0, 'tedge/commands/res/software/list', ... (1050 bytes))
```

**:broken_heart: FAIL: Where no software list message is sent**

```sh
Feb 17 11:04:29 ebcfa66b7083 mosquitto[477]: 1676631869:         tedge/commands/res/software/list (QoS 1)
Feb 17 11:04:29 ebcfa66b7083 mosquitto[477]: 1676631869: tedge-mapper-c8y 1 tedge/commands/res/software/list
Feb 17 11:04:29 ebcfa66b7083 mosquitto[477]: 1676631869: Received PUBLISH from tedge-mapper-c8y (d0, q1, r0, m6, 'tedge/commands/req/software/list', ... (30 bytes))
Feb 17 11:04:29 ebcfa66b7083 mosquitto[477]: 1676631869: Sending PUBLISH to auto-45DD583E-775A-B84E-1E6B-AD7C1CA03344 (d0, q0, r0, m0, 'tedge/commands/req/software/list', ... (30 bytes))
```

However the key seems to be the lack of a message being published on the `tedge/commands/res/software/list` topic. For example, the following snippet was found in the **PASS** case where everything worked as expected. This fragment was missing in the **FAILED** case.

```sh
Feb 17 10:35:52 ff619c80960a mosquitto[479]: 1676630152: Received PUBLISH from tedge_agent (d0, q1, r0, m6, 'tedge/commands/res/software/list', ... (51 bytes))
```

**Comment by didier-wenzek** [comment]
This is related to https://github.com/thin-edge/thin-edge.io/issues/1946

**Comment by PradeepKiruvale** [comment]
Addressed the issue here https://github.com/thin-edge/thin-edge.io/pull/2050#pullrequestreview-1512254056

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket created in the test suite. 
``` tests/RobotFramework/tests/cumulocity/supported_operations/mapper-publishing-agent-supported-ops.robot ```
- [x] QA has tested the feature and it is according descrition and expectations.
