### ISSUE TITLE
tedge reconnect should support aws

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#1733]
**Is your feature improvement request related to a problem? Please describe.**

Since AWS support has been added to the `main` branch, it should be supported in the `tedge reconnect <mapper>` command.

Currently when trying to use `tedge reconnect`, the following error is raised.

```sh
sudo tedge reconnect aws
error: Found argument 'aws' which wasn't expected, or isn't valid in this context

USAGE:
    tedge reconnect <SUBCOMMAND>

For more information try --help
```

**Describe the solution you'd like**

The following command should reconnect the aws mapper (similar to `tedge reconnect c8y`)
```
sudo tedge reconnect aws
```

**Describe alternatives you've considered**

**Additional context**

**Comment by Bravo555** [comment]
@reubenmiller this can probably get closed now?

**Comment by reubenmiller** [comment]
> @reubenmiller this can probably get closed now?

I’ll assign it to @gligorisaev foe verification, though we might need to work out some stuff on how to test aws cloud related stuff, but not a must for this ticket

**Comment by gligorisaev** [comment]
Tested and confirmed
