### ISSUE TITLE
AWS key not found

### ISSUE THREAD

**Issue by kawshol** [thin-edge/thin-edge.io#1735]
**Describe the bug**
I am just stating with thinedge, 

I am following https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/tutorials/connect-aws.md 

tedge version tedge 0.9.0

I have a AWS IOT core and set the cert and policy as mentioned in the guide 

sudo tedge config set aws.url axxxxxxxx-ats.iot.ap-southeast-1.amazonaws.com ( my aws url )
error: Invalid value "aws.url" for '<KEY>': Invalid key `aws.url'. See `tedge config list --doc` for a list of valid keys.

**To Reproduce**
Install tedge version tedge 0.9.0 and run the abouve command  as mentioned in the proble 

**Expected behavior**
Connection esablishment for the AWS 

**Screenshots**
![image](https://user-images.githubusercontent.com/165078/219830205-860496f0-a471-4d32-b371-13e8b9bac26f.png)

**Environment (please complete the following information):**
 - OS Ubuntu
 - Hardware [incl. revision] X86 
 - System-Architecture [e.g. result of "uname -a"] Linux edgehub 5.15.0-1023-intel-iotg #28-Ubuntu SMP Tue Jan 10 11:56:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - thin-edge.io version [e.g. 0.1.0] 0.9.0

**Additional context**

We would like to use thinegde framework with our node-red devices. 
We are a IOT devices manufactures for the energy sector , We wish to deploy this with our framework for edge devices https://edgemate.io

**Comment by reubenmiller** [comment]
Good and bad news. We just merged the AWS functionality yesterday, so we haven't done an "official" release, though we were a bit too eager in the preparation for the release, that we forgot to mention from which version the feature will be available, so it will only be part of the next release `0.10.0` (not `0.9.0`).

Now for the good news, we now have a way to test out new features as soon as they are merged to the `main` branch. We now publish the package to a public Debian repository. We have not made an official announcement regarding this yet, as it is also very new. We were hoping to do a bit more "fanfare" about it on the next community meetup.

If you want to try the AWS feature then checkout the docs on [how to install a pre-release version](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/developer/DEBIAN_PACKAGE_HOSTING.md#pre-releases)

**Comment by reubenmiller** [comment]
Sorry we accidentally linked the incorrect ticket number (1737)
