### ISSUE TITLE
Fix or remove flaky test `c8y_mapper_alarm_mapping_to_smartrest`

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#1741]
These tests are flaky and must be fixed or removed:

```
---- c8y::tests::c8y_mapper_alarm_mapping_to_smartrest stdout ----
thread 'c8y::tests::c8y_mapper_alarm_mapping_to_smartrest' panicked at 'Didn't receive all expected messages: ["302,temperature_alarm,\"Temperature high\""]
 Received: ["500\n", "105"]', /home/runner/work/thin-edge.io/thin-edge.io/crates/tests/mqtt_tests/src/test_mqtt_client.rs:89:5
```

See, for instance, test history for https://github.com/thin-edge/thin-edge.io/pull/1734 and for https://github.com/thin-edge/thin-edge.io/pull/1719.

```
---- c8y::tests::c8y_mapper_child_alarm_empty_payload stdout ----
thread 'c8y::tests::c8y_mapper_child_alarm_empty_payload' panicked at 'assertion failed: msg.contains(expected_msg)', crates/core/tedge_mapper/src/c8y/tests.rs:730:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

See test history of https://github.com/thin-edge/thin-edge.io/pull/1742

**Comment by Bravo555** [comment]
IMHO the problem with some of the tests is that they don't sufficiently isolate the unit under test and let the environment affect the tests. In this case, at a glance, we start and run a full fledged MQTT broker as part of the test, perhaps we should use mocking instead?

I've had a similar issue where the test fail while mosquitto service was running. The test spawns a tedge process to check the output of the binary:

https://github.com/thin-edge/thin-edge.io/blob/eff344debb50fab2541a9e9fc4b995885d9a0258/crates/core/tedge/tests/mqtt.rs#L54-L68

And I'm unsure if this is the best place for such a test. [_Test Organization_ chapter in the Rust Book](https://doc.rust-lang.org/book/ch11-03-test-organization.html) says that integration tests are mainly for testing the library's public API, and to me, spawning processes out of them feels kinda hacky. The test can easily be made to work though, if there's no better tool for the job.

**Comment by PradeepKiruvale** [comment]
These tests are isolated by running them in a `serial` manner. Every test starts its own `mapper` and then starts the test. But, still there is something wrong with the test, needs to look into.
