### ISSUE TITLE
Add support for pid files

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#1746]
**Is your feature improvement request related to a problem? Please describe.**

A pid file is often used in linux to help other applications to find out the PID of another running application. The pid file is a "weak" reference to the pid. If the process is killed via `SIGKILL` etc, then the pid inside the file could be stale, however most cases it is fairly trivial to verify if it is still correct or not (e.g. using `pgrep -F <pid>`).

Some monitoring software, such as [monit](https://mmonit.com/monit/documentation/monit.html), use pid files to check when the process id changes or if the pid exists or not, and then reacts to that (e.g. sending an alert, or running some other action). So having a pid file enables better compatibility with other linux tooling.

The pidfile is also service manager agnostic, so it provides a clean way to track the PID of the application when the process is not running under a service manager (e.g. systemd, init.d, open-rc etc.)

**Advantages**

* Adhere to linux conventions
* Better compatibility with other linux tooling (provides easy way for other process to look the (last known) pid of the process
* Service manager agnostic

**Describe the solution you'd like**

**Include the pid inside the existing lock files under `/run/lock/`**

Re-using the lock file would mean there would be no additional file to manage/write to. However the file would then be part of the "public" interface for users, which means we can't go changing its location without communicating a "breaking change". Though it would "go against the convention" of using the `.pid` extension to clearly communicate that it contains the pid.

**PID file contents**

Write the main process's id (PID) to the file without any leading or trailing whitespace (this means no closing newline character as well!), e.g. `1234`.

In normal circumstances, such receiving any of the following signals `SIGINT`, `SIGQUIT`, etc., the pid file should also removed. But it must be noted that it is not technically possible to cleanup the file if a `SIGKILL` signal is received, but this is ok.

**Describe alternatives you've considered**

Create a new pid file under `/run/<service_name>.pid`

`/run/*.pid` seems to be the preferred location for pid files. Below shows an example shown below in Debian bookworm)

```sh
ls -l /run/*.pid
-rw-r--r-- 1 root root 4 Feb 21 17:59 /run/crond.pid
-rw-r--r-- 1 root root 4 Feb 21 18:00 /run/dhcpcd.pid
-rw-r--r-- 1 root root 3 Feb 21 18:00 /run/docker.pid
-rw-r--r-- 1 root root 6 Feb 22 17:37 /run/monit.pid
-rw-r--r-- 1 root root 4 Feb 21 18:00 /run/privoxy.pid
-rw-r--r-- 1 root root 4 Feb 21 17:59 /run/rngd.pid
-rw-r--r-- 1 root root 4 Feb 21 17:59 /run/sshd.pid
```

**Additional context**

References

* https://www.baeldung.com/linux/pid-file
* https://en.wikipedia.org/wiki/Process_identifier

**Comment by didier-wenzek** [comment]
Option 1 is lighter to implement because the issue related to "ghost" file ownership has already been addressed.

**Comment by reubenmiller** [comment]
So we are going to go for Option 1.

**Comment by gligorisaev** [comment]
Tested and confirmed.

Test steps added to: /tests/RobotFramework/tests/configuration/lock_file.robot
PR: https://github.com/thin-edge/thin-edge.io/pull/1895
