### ISSUE TITLE
Command line reference missing commands

### ISSUE THREAD

**Issue by Bravo555** [thin-edge/thin-edge.io#1750]
**Is your documentation request related to a problem? Please describe.**

[Command line reference](https://thin-edge.github.io/thin-edge.io/html/references/references.html) chapter in the documentation doesn't include `tedge reconnect` command. Maybe other commands are also missing?

**Describe the improvement you'd like**

IMHO _Command Line Reference_ seems to mean _whatever usage information the binary generates, but on the website_. In such case, this should probably be automatically generated. mdBook does seem to support [preprocessors](https://rust-lang.github.io/mdBook/format/configuration/preprocessors.html) that modify the doc source before publishing on the website. Perhaps there might even be a third-party preprocessor specifically for generating manpages that we could use.

**Additional context**
I see that some parts of the manpages were generated automatically (#952), but I found only this one commit and these manpages are still edited manually. Ideally I think it'd be good to remove manpages completely out of the tree and have them generated automatically; if that's for some reason not possible, then we should at least have some automated way of being notified when the manpages are out of sync.

**Comment by didier-wenzek** [comment]
The mdBook  [preprocessors](https://rust-lang.github.io/mdBook/format/configuration/preprocessors.html) were not working as expected when this has been done. It would be good to try it again. Not only to have these pages generated automatically. 

A short term fix is to update the [gen-ref-docs.sh](https://github.com/thin-edge/thin-edge.io/blob/main/docs/gen-ref-docs.sh).

**Comment by didier-wenzek** [comment]
The script has been replaced with mdbook-cmdrun
