### ISSUE TITLE
tedge-mapper-c8y sends the incorrect service type when the service is down

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#1753]
**Describe the bug**

When the `tedge-mapper-c8y` service is stopped, the last will and testament sent to Cumulocity has the incorrect type (`thin-edge.io`, instead of the correct value `service`). The service type is fine when the service is `up`, so I suspect the LWT message is using the wrong default service type.

**To Reproduce**

1. Bootstrap tedge to Cumulocity IoT, and verify that the new services tab shows the `tedge-mapper-c8y` service. It should be set to up
2. Stop the `tedge-mapper-c8y` service
3. Check in the Services tab (in Device Management UI), and look at the **Type** column. It should have `service` not `thin-edge.io`

**Expected behavior**

* The service type should be set to `service` when both the `tedge-mapper-c8y` is `up` or `down`

**Screenshots**

<img width="1479" alt="image" src="https://user-images.githubusercontent.com/3029781/221040906-5369afac-8870-4e23-87ff-2c205d7a9ae4.png">

**Environment (please complete the following information):**
 - OS [incl. version]: Debian 11
 - Hardware [incl. revision]: arm64
 - System-Architecture [e.g. result of "uname -a"]: Linux 7f595e604eda 6.1.11-200.fc37.aarch64  Thu Feb  9 19:41:51 UTC 2023 aarch64 GNU/Linux
 - thin-edge.io version [e.g. 0.1.0]: 0.9.0-215-g54632d1a

**Additional context**

**Comment by gligorisaev** [comment]
Tested and confirmed as fixed
