### ISSUE TITLE
Potential firmware cache re-download and overwriting issue when receiving multiple operations

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#1757]
**Is your feature improvement request related to a problem? Please describe.**
`c8y-firmware-plugin` has a feature, which avoids downloading a file from the same URL. However, there are potential issue if user create multiple operations with the same firmware files at the same time.

The problematic scenario follows:

1. On the receive of the first operation, `c8y-firmware-plugin` will download the file from cloud or external server. Let's say it takes 3h.
2. While 1. is in progress, `c8y-firmware-plugin` receives the second operation that needs the same firmware file as 1.
3. Since the download of the 1. not finished so not available in cache storage yet, `c8y-firmware-plugin` starts downloading the same file for the second operation.
4. The download for the first operation is done. cache is now avaiable.
5. The download for the second operation is done. The cache created by the first operation gets overwritten.

**Describe the solution you'd like**
We need a mechanism 
- to know a download is in progress for a specific server URL.
- to hold the next operation(s) wait until the first download ends if they need the same firmware file.

The detail implementation level solution is opened topic.

**Describe alternatives you've considered**

**Additional context**
Technically, we need to consider to improve this function.
https://github.com/thin-edge/thin-edge.io/blob/d8bd3b3390536ffb43e50adec732bee123900da6/plugins/c8y_firmware_plugin/src/firmware_manager.rs#L558-L588

**Comment by reubenmiller** [comment]
@rina23q The firmware plugin does downloading sequentially so this is not a problem. A future improvement would be to allow more fine-grained control over how many parallel downloads are allowed to occur which would inturn require a locking mechanism, but this is better suited to the actor refactoring.
