### ISSUE TITLE
tedge-mapper: MQTT single level wildcards (+) not working as expected in mapper subscribe filters

### ISSUE THREAD

**Issue by Bravo555** [thin-edge/thin-edge.io#1763]
**Describe the bug**

MQTT channel is configured with the following subscribe filter patterns:

**Note: all below output is custom printlns I added, so you won't have this output**

```
[
    Filter = tedge/measurements/+, Qos = AtLeastOnce,
    Filter = tedge/alarms/+/+/+, Qos = AtLeastOnce,
    Filter = tedge/events/+/+, Qos = AtLeastOnce,
    Filter = tedge/health-check, Qos = AtLeastOnce,
    Filter = tedge/health-check/tedge-mapper-aws, Qos = AtLeastOnce,
]
```

But  it receives messages for topics it shouldn't subscribe to:

```
Topic = tedge/measurements/1/2/3, Qos = AtMostOnce, Retain = false, Pkid = 0, Payload Size = 22
Topic = tedge/measurements/1/2/3, Qos = AtMostOnce, Retain = false, Pkid = 0, Payload Size = 22
Topic = tedge/measurements/1/2, Qos = AtMostOnce, Retain = false, Pkid = 0, Payload Size = 22
```

We use a single level MQTT wildcard (`+`), but we receive messages as if we used `#` wildcard.

This can't be an issue with rumqttc itself, as this minimal program works correctly:

```rust
use rumqttc::{AsyncClient, Event, Incoming, MqttOptions, Outgoing, QoS, SubscribeFilter};
use std::time::Duration;

#[tokio::main]
async fn main() {
    let mut mqttoptions = MqttOptions::new("rumqtt-sync", "localhost", 1883);
    mqttoptions.set_keep_alive(Duration::from_secs(5));

    let subscriptions = [
        "tedge/measurements/+",
        "tedge/alarms/+/+/+",
        "tedge/events/+/+",
        "tedge/health-check",
        "tedge/health-check/tedge-mapper-aws",
    ]
    .map(|s| SubscribeFilter::new(s.into(), QoS::AtLeastOnce));

    let (client, mut connection) = AsyncClient::new(mqttoptions, 10);
    client.subscribe_many(subscriptions).await.unwrap();

    // Iterate to poll the eventloop for connection progress
    loop {
        match connection.poll().await {
            Ok(Event::Incoming(Incoming::PingResp)) | Ok(Event::Outgoing(Outgoing::PingReq)) => {}
            Ok(event) => println!("Notification = {:?}", event),
            _ => (),
        }
    }
}


```

**To Reproduce**

1. Use the following input topic filter in the AWS mapper:
    ```rust
        pub fn in_topic_filter() -> TopicFilter {
        vec![
            "tedge/measurements/+",
            "tedge/alarms/+/+/+",
            "tedge/events/+/+",
        ]
        .try_into()
        .unwrap()
    }
    ```
2. Run the AWS mapper
3. Publish on the `tedge/measurements/1/2/3` topic:
    `tedge mqtt pub tedge/measurements/1/2/3 '{"temperature": 21.3}'
4. Message is published on the remote bridge.

**Expected behavior**
Message is not received by the mapper and therefore not processed and not published on the remote bridge.

**Additional context**

Filing this for tracking purposes, or to see if maybe anybody knows whether it's an expected behaviour? Working on this right now.

**Comment by didier-wenzek** [comment]
Thank you for these detailed inputs

> maybe anybody knows whether it's an expected behaviour?

Definitely not expected.

Too soon to discard for sure the possibility of a bug. However, beware that MQTT subscriptions are persistent. If a *previous* version of the AWS mapper has subscribed to some extra topics under some session name, then a new version that use the same session name will continue to receive messages for those old topics even if no more requested .

To double check if this can be the root cause, there are two options:
* Run the rumqttc client using the same session name as the aws mapper.
* Run the aws mapper with another session name.

**Comment by Bravo555** [comment]
> However, beware that MQTT subscriptions are persistent. If a _previous_ version of the AWS mapper has subscribed to some extra topics under some session name, then a new version that use the same session name will continue to receive messages for those old topics even if no more requested .

That was exactly it, using another session name fixed the bug. I wonder, what necessitated such design choice? Perhaps this behaviour should be changed? Because to me it's unclear why we should be preserving subscriptions from previous sessions if they're the same. Does this feature target Cumulocity where the subscriptions can change between sessions?

**Comment by didier-wenzek** [comment]
> I wonder, what necessitated such design choice?

This is a design choice done at the MQTT level. The main reason is that, when a client is down, the server has to persist any messages the client subscribed to and then, on reconnect, to forward the messages received meantime. The default for MQTT is to keep all subscriptions valid until explicitly revoked (unsubscribed) or the whole session cleaned (with the clean flag on connect).

See fhttps://www.emqx.com/en/blog/mqtt-session

**Comment by Bravo555** [comment]
> This is a design choice done at the MQTT level. The main reason is that, when a client is down, the server has to persist any messages the client subscribed to and then, on reconnect, to forward the messages received meantime. The default for MQTT is to keep all subscriptions valid until explicitly revoked (unsubscribed) or the whole session cleaned (with the clean flag on connect).
> 
> See https://www.emqx.com/en/blog/mqtt-session

Okay, it makes perfect sense now. Then it was simply my misunderstanding and topic filters themselves are actually working as expected. Closing this, thank you very much for the explanation, @didier-wenzek!
