### ISSUE TITLE
Avoid or limit explicit init required by tedge components

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#1764]
**Is your feature improvement request related to a problem? Please describe.**

Most of the thin-edge daemons support an `--init` command with which the initialization of these daemons are performed. They use this option to prepare their initial state by creating the necessary files, directories etc. Doing this `-init` for each and every component is tedious and we should try to avoid such explicit inits as much as possible by doing as many initialization steps as possible dynamically during the runtime of these daemons.

**Describe the solution you'd like**

Deprecate the `--init` options of all the daemons to no-ops, so that they can be completely removed in future. These daemons may create their init state(necessary directories, files etc) dynamically, as and when they are required.

For initialization steps that can't be performed during the normal runtime of a component, like creating `/etc/tedge` directory that can only be done with elevated privileges, provide a `tedge init --user <user>` command which will perform these "essential" initializations with the provided `user`. If a `--user` value is not provided, use the default `tedge` user.

**Comment by albinsuresh** [comment]
### Test Plan

1. The `sudo tedge init --user <user-name> --group <group-name>` subcommand is used to initialize the following top-level directories such as `/etc/tedge`, `/var/tedge` and `/var/tedge/logs` which require elevated privileges to be created. The `--user` and `--group` args are optional and defaults to `tedge` user and group.
2. The `tedge --init` arg is deprecated with a warning in favour of the `tedge init` subcommand.
3. The `--init` arg was deprecated from all tedge daemons as well, namely:
    - `tedge-mapper`
    - `tedge-agent`
    - `c8y-configuration-plugin`
    - `c8y-log-plugin`
    - `c8y-fimware-plugin`
4. The directories/files created by these daemons using `--init` earlier(e.g: the `/etc/tedge/c8y/c8y-configuration-plugin` file created by the `c8y-configuration-plugin`) are now created dynamically during the startup of these services. Even if some of these files are deleted at some point, they are recreated on next startup.

**Comment by gligorisaev** [comment]
> ### Test Plan
> 1. The `sudo tedge init --user <user-name> --group <group-name>` subcommand is used to initialize the following top-level directories which require elevated privileges to be created:
>    
>    * /etc/tedge
>    * /etc/tedge/mosquitto-conf
>    * /etc/tedge/operations
>    * /etc/tedge/plugins
>    * /etc/tedge/device-certs
>    * /var/tedge
>    * /var/tedge/logs
> 2. The `--user` and `--group` args are optional and defaults to `tedge` user and group:
> 3. The `tedge --init` arg is deprecated with a warning in favour of the `tedge init` subcommand.
> 4. The `--init` arg was deprecated from all tedge daemons as well, namely:
>    
>    * `tedge-mapper`
>    * `tedge-agent`
>    * `c8y-configuration-plugin`
>    * `c8y-log-plugin`
>    * `c8y-fimware-plugin`
> 5. The directories/files created by these daemons using `--init` earlier(e.g: the `/etc/tedge/c8y/c8y-configuration-plugin` file created by the `c8y-configuration-plugin`) are now created dynamically during the startup of these services. Even if some of these files are deleted at some point, they are recreated on next startup.
> 6. All tedge components can be run as a user other than `tedge` as well, provided that the `tedge init` is performed for that user using the `--user` arg and the service definitions are updated to be started by that user instead of `tedge`.

In point 1 you mentioned /var/tedge/logs folder, this folder does not exists after setting up the device (without requesting logs)
Does point 5 mean that if I delete all folders, by restarting the device they will be created again (without running sudo tedge init)?
Point 6: "All tedge components can be run as a user other than tedge as well" is not accurate, for example /etc/tedge/device-certs remains with mosquitto user, can you pleace define which ones should change user and which not?

**Comment by albinsuresh** [comment]
> Does point 5 mean that if I delete all folders, by restarting the device they will be created again (without running sudo tedge init), please define what exactly is the startup?

No, none of the top-level directories created by `tedge init` command are recreated and can't be recreated automatically either as they need elevated privileges, which not all plugins have. That is which is why that single command must be done by a user with elevated privileges.

But, the services like mappers and plugins create files under these top-level directories on their startup (e.g: the `/etc/tedge/c8y/c8y-configuration-plugin` file created by the `c8y-configuration-plugin` or the `/etc/tedge/operations/c8y` directory and the `c8y_SoftwareUpdate` and `c8y_Restart` files under it, created by `tedge-mapper-c8y`). These files/directories, even if deleted, will be recreated on the next service startup.

> Point 6: "All tedge components can be run as a user other than tedge as well" is not accurate, for example /etc/tedge/device-certs remains with mosquitto user, can you pleace define which ones should change user and which not?

Yes, mosquitto is an exception as it is a third-party tool which can only be run as the `mosquitto` user as that software has defined. I meant all **tedge** components like the mappers, plugins etc. The service definitions of most of these components, except `c8y-config-plugin` and `c8y-log-plugin`, are defined to be run as `tedge` user. These can be changed to which ever user that `tedge init` is performed with. The `c8y-config-plugin` and `c8y-log-plugin` are designed to be run as `root` so that they can read/update any config files and log files, without any access restrictions. But, even those services can be run as a specific user if the limited access associated to that user is acceptable.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket created in the test suite. 
``` /tests/RobotFramework/tests/customizing/tedge_init.robot ```
- [x] QA has tested the feature and it is according descrition and expectations.
