### ISSUE TITLE
Refactor large error enums

### ISSUE THREAD

**Issue by Bravo555** [thin-edge/thin-edge.io#1767]
**Is your feature improvement request related to a problem? Please describe.**

When running `cargo clippy` locally, there are a lot of occurences of this error:

```
warning: the `Err`-variant returned from this function is very large
  --> crates/core/c8y_api/src/smartrest/alarm.rs:8:49
   |
8  | pub fn serialize_alarm(alarm: ThinEdgeAlarm) -> Result<String, SmartRestSerializerError> {
   |                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
  ::: crates/core/c8y_api/src/smartrest/error.rs:17:5
   |
17 |     FromCsvWriter(#[from] csv::IntoInnerError<csv::Writer<Vec<u8>>>),
   |     ---------------------------------------------------------------- the largest variant contains at least 376 bytes
   |
   = help: try reducing the size of `smartrest::error::SmartRestSerializerError`, for example by boxing large elements or replacing it with `Box<smartrest::error::SmartRestSerializerError>`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err
```

This happens, because a lot of the functions return the same very large error types - despite that these functions can't return most of the error variants. This is bad, because when we have a function that returns `Result<(), VeryBigError>`, we need to always prepare the space on the stack for the error variant, and need to copy all of it back and forth.

In the extreme case, we have `crates/core/tedge_mapper/src/core/size_threshold.rs`:

https://github.com/thin-edge/thin-edge.io/blob/10c86d09d7b47c5826e3d0d2a2c131d2b692fac5/crates/core/tedge_mapper/src/core/size_threshold.rs#L3-L22

Function `validate` uses `ConversionError` for result error type, but this type takes 384 bytes. 384 bytes just to know whether or not the payload is too large, which is effectively 1 bool.

The `ConversionError` itself has 23 variants, so besides performance, big errors also make understanding the code harder. When I look at the function returning such error and ask "what can possibly fail when running this function", the error type seems to answer "absolutely anything".

**Describe the solution you'd like**

There should be more error types in various modules (I think something like 1 error type for every non-trivial module), and functions from these modules should be more careful to actually return relevant error types. Error types should not have too much variants, so that it's actually viable to match on these errors and maybe do different things depending on the actual error returned.

To refactor this, I would start with the biggest errors in terms of number of variants, look at what functions return them, and whether or not is there a need to bubble this up, either replace it with another distinct error type or try to collapse some of the variants and be smarter when composing errors.

**Additional context**

This issue probably results from a combination of a need for fast prototyping and the relative ease of piling more and more variants into existing error types provided by `thiserror` crate, as well as developers being new to Rust, which takes a different approach to error handling than most programming languages. To developers new to the codebase, presented with multiple functions returning the same error type, adding a new variant to this error type when they need to handle their own errors seemed to be the most natural and straightforward course of action. That's why I think when we clean it up a little, most people reading the code would quickly pick up the new style.

References:

- https://mmapped.blog/posts/12-rust-error-handling.html
- https://www.lpalmieri.com/posts/error-handling-rust/

**Comment by didier-wenzek** [comment]
Thanks for this detailed description of the issue.

There are many things here. At least 3.

> large error types

This needs to be fixed and can be done quickly. There is already a ticket for that https://github.com/thin-edge/thin-edge.io/issues/1716. I'm okay to close the older ticket to keep only this new one - by far more detailed.

> number of variants  for an enum type

I don't understand what is the issue to have large number of variants for an enum (when this number is below what can be encoded into a byte). What could be the performance impact?  Compilation time? None, I believe.

> bad organization of the misc error types

Here, I can only agree. Some thin-edge error types are simply a random mix of io / user / system / logic issues.

However, I'm afraid this is not so easy to fix as this is also due the organization of the code.

That said, I'm okay that you give a try with the approach you propose:  *To refactor this, I would start with the biggest errors in terms of number of variants, look at what functions return them, and whether or not is there a need to bubble this up, either replace it with another distinct error type or try to collapse some of the variants and be smarter when composing errors.*

**Comment by didier-wenzek** [comment]
I think this can be closed as improved by https://github.com/thin-edge/thin-edge.io/pull/1874.
