### ISSUE TITLE
Implement a health-check actor for `c8y-device-management` plugin

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#1768]
Implement a health check actor and integrate it with the `c8y-device-management` plugin so that it can respond to health check requests. Since the health check is done for the entire daemon and not for individual actors, only the health check actor must respond to health check requests and not the individual actors.

The actor must listen on `tedge/health-check` and `tedge/health-check/c8y-device-management` topics for health check requests and respond to the `tedge/health/c8y-device-management` topic with its health status.

**Comment by didier-wenzek** [comment]
> The actor must listen on tedge/health-check and tedge/health-check/c8y-device-management topics for health check requests and respond to the tedge/health/c8y-device-management topic with its health status.

The name of the daemon used by this actor must be configurable (and not hardcoded as `c8y-device-management`.

**Comment by PradeepKiruvale** [comment]
#1815

**Comment by gligorisaev** [comment]
We hold back testing/verification of health check actor for a while till its used by the mappers.

**Comment by gligorisaev** [comment]
Test covered with 
``` /tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot ```
