### ISSUE TITLE
A broken image in the thin-edge.io docs

### ISSUE THREAD

**Issue by zhong-ys** [thin-edge/thin-edge.io#1779]
The first image in the chapter 3.1.13 can not be displayed. 
[Configuration management on child-devices](https://thin-edge.github.io/thin-edge.io/html/tutorials/child-device-config-management.html#configuration-management-on-child-devices) 
<img width="411" alt="Screenshot 2023-03-01 at 13 40 58" src="https://user-images.githubusercontent.com/73714994/222142207-b56ec93f-410f-4cb0-95cf-6065040b2f55.png">

**Comment by reubenmiller** [comment]
Thanks @zhong-ys for the info. Yes it looks like the browser is throwing a Cross-Origin error. The link is technically not broken (as copying the url works fine), however the browser seems to be block the display of the link.

```
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/architecture/images/device-concept.svg with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

**Comment by reubenmiller** [comment]
The diagram is now displayed correctly on the website. Thanks again for the tip @zhong-ys 

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/3029781/222232846-054077c1-3e3c-47b8-a07d-231437bbdc07.png">
