### ISSUE TITLE
Flaky test in tedge_agent

### ISSUE THREAD

**Issue by Bravo555** [thin-edge/thin-edge.io#1786]
**Describe the bug**

I think I have found yet another flaky test that can randomly fail. It's this one:

https://github.com/thin-edge/thin-edge.io/blob/f95be3a9b5403d8596ba2b77be32598bb14920a4/crates/core/tedge_agent/src/http_rest.rs#L279-L314

**To Reproduce**

Run the following command:

```
while true; do cargo test --package tedge-agent --bin tedge-agent -- http_rest::test::test_file_transfer_http_methods --nocapture || break; done
```

The loop should terminate in less than a minute.

**Expected behavior**
The loop should run indefinitely, or rather because that would be a bit hard to prove, at least more than 1 minute.

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [e.g. 0.1.0]

**Additional context**

**Comment by Bravo555** [comment]
And one more test that seems to exhibit the same behaviour for me in plugin_sm:

https://github.com/thin-edge/thin-edge.io/blob/f95be3a9b5403d8596ba2b77be32598bb14920a4/crates/core/plugin_sm/tests/plugin.rs#L340-L379

Run with:

```
while true; do cargo test --package plugin_sm --test plugin -- tests::plugin_command_update_list_fallback --exact --nocapture || break; done
```

**Comment by didier-wenzek** [comment]
No more flaky. Running in a while loop as suggested.

```
running 4 tests
test file_transfer_server::http_rest::tests::test_file_transfer_http_methods::method_delete_invalid_test_uri_statuscode_not_found_expects ... ok
test file_transfer_server::http_rest::tests::test_file_transfer_http_methods::method_delete_valid_test_uri_statuscode_accepted_expects ... ok
test file_transfer_server::http_rest::tests::test_file_transfer_http_methods::method_get_valid_test_uri_statuscode_ok_expects ... ok
test file_transfer_server::http_rest::tests::test_file_transfer_http_methods::method_get_invalid_test_uri_statuscode_not_found_expects ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 60 filtered out; finished in 0.00s
```

The second `plugin_command_update_list_fallback` is no more in the code base.
