### ISSUE TITLE
Allow the configuration directory to be specified globally via environment variables

### ISSUE THREAD

**Issue by jarhodes314** [thin-edge/thin-edge.io#1794]
**Is your feature improvement request related to a problem? Please describe.**
It's currently only possible to specify a custom config directory using a command line argument to `tedge`/`tedge-mapper`/`tedge-agent`. This means the core functionality of tedge can be configured using a `tedge.toml` located anywhere, but this breaks with plugins like the remote access plugin. Since the remote access plugin is a separate process, it has no clue about arguments passed to the mapper so it blindly assumes the configuration is stored in `/etc/tedge`. 

**Describe the solution you'd like**
`tedge_config` could determine the location of the config dir using an environment variable (e.g. `TEDGE_CONFIG_DIR`). This can then be passed from the mapper or agent to child processes. If the default behaviour of `TEdgeConfigRepository` is to read from `$TEDGE_CONFIG_DIR` (or `/etc/tedge` if that's not set), the remote access plugin (and other affected Rust-based plugins) would work without any changes (other than rebuilding them).

The interface to e.g. `tedge-mapper` doesn't necessarily need to change. It could have the configuration directory specified by a command line argument as it is now and then create the relevant environment variable from this when spawning a plugin process.

**Describe alternatives you've considered**
We could support this configuration as something a child process can query via MQTT/HTTP, but this would probably require deliberate support from the plugins and would be a lot more complicated. This also adds an extra requirement to plugins to be able to connect to tedge.

**Additional context**
If we use a `TEDGE_` prefixed environment variable for this, we will need to ignore it when reading the standard configuration which could be done [here](https://github.com/thin-edge/thin-edge.io/blob/2ee912f34d80641b3af3a5d4f47eb36b0b73e81d/crates/common/tedge_config/src/tedge_config_cli/figment.rs#L175) using [`Env::ignore`](https://docs.rs/figment/latest/figment/providers/struct.Env.html#method.ignore) from figment.

**Comment by reubenmiller** [comment]
Yes this would be very helpful as it makes it easier to control the custom components when using a custom config-dir location, and removes the need to use the `--config-dir` option when starting any of the components.

With the change the following should be possible:

```sh
export TEDGE_CONFIG_DIR=$HOME/tedge
tedge init
tedge-agent &
tedge mqtt sub '#'
```

**Comment by reubenmiller** [comment]
Implemented as described, the config-dir can now be controlled by setting the environment variable, `TEDGE_CONFIG_DIR`.

**Comment by gligorisaev** [comment]
Checked:
tests/RobotFramework/tests/customizing/config_dir.robot
and the respected document files and it is according the required
