### ISSUE TITLE
Support configuring location where http server data is stored

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#1804]
**Is your feature improvement request related to a problem? Please describe.**

`tedge-agent` uses the `/var/tedge` to store data related to the http server
* Configuration management (for downloads and uploads)
* Firmware artifact caching

On some devices the `/var` partition is volatile and is not persisted across device restarts. This can cause degraded functionality as any files under the `/var/tedge` folder are not persisted across reboots. It presents an initialization problem as the root folder `/var/tedge` is not automatically recreated (it requires initializing the components again using `tedge-agent --init; c8y-firmware-plugin --init` etc.).

**Describe the solution you'd like**

Add a new configuration setting which controls where the http server operates locally.

```toml
[data]
path = '/var/tedge'
```

The setting should also be updatable via the `tedge config set` command:

```sh
tedge config set data.path /opt/custompath
```

This configuration setting would be consistent with other configurable paths (for `logs.path` and `run.path`)

```toml
[logs]
path = '/var/log'

[run]
path = '/var/run'
```

**Describe alternatives you've considered**

**Additional context**

**Comment by albinsuresh** [comment]
Do we want to limit that key to just HTTP by keeping it under `[http]`. I see it more as a persistent root directory for tedge which is used not just by the HTTP server but for many other persistence use-cases as well, like storing in-progress operation metadata, act as a binary/file cache etc. So, how about keeping it under `[persistent]` table instead of `[http]`?

**Comment by reubenmiller** [comment]
> Do we want to limit that key to just HTTP by keeping it under `[http]`. I see it more as a persistent root directory for tedge which is used not just by the HTTP server but for many other persistence use-cases as well, like storing in-progress operation metadata, act as a binary/file cache etc. So, how about keeping it under `[persistent]` table instead of `[http]`?

Yeah I don't mind moving it, however `[persistent]` is a little too presumptuous that the user is configuring it to a persistent location...so maybe something like `[data]` would be a bit more generic.

**Comment by reubenmiller** [comment]
I've updated the ticket desciption to use the `[data]` section rather than `[http]`.

**Comment by albinsuresh** [comment]
### Inputs for Verification

The addition of the new `data.path` configuration is documented [here](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/howto-guides/018_update_config_paths.md)

A basic test validating the effect of this new configuration on `tedge-agent` and `c8y-firmware-plugin` is available [here](https://github.com/thin-edge/thin-edge.io/blob/main/tests/RobotFramework/tests/customizing/data_path_config.robot)

Two additional test cases that are worth adding:

1. On sending a configuration update operation to a child device, make sure that the file downloaded by the `c8y-configuration-plugin` is stored under `<updated-data-path>/file-transfer/{child-d}/config_update/{config-type}` (The existing `Validate updated data path used by c8y-firmware-plugin` Robot test is doing a similar validation)
2. When a file is uploaded to thin-edge via the tedge-agent's file-transfer HTTP endpoint, make sure that the uploaded file is stored under the specified data path under `<updated-data-path>/file-transfer` directory and not under the default `/var/tedge` path. The existing `Validate updated data path used by tedge-agent` only validates the creation of the updated data path on `--init`. This enhancement will make sure that it continues using the same data path during its runtime as well.

**Comment by reubenmiller** [comment]
This is related to #1732
