### ISSUE TITLE
On-prem support

### ISSUE THREAD

**Issue by krdpk17** [thin-edge/thin-edge.io#1823]
**Is your documentation request related to a problem? Please describe.**

From document, not able to understand if on-prem is supported or not. It birng scope of guessing. I am telling this since it appears that document talks about cloud alone..
**Describe the improvement you'd like**
May be we can have supportability matrix

**Additional context**
Could you please reply me if on-prem is supported or not. It is ask from corporate who is quite interested to use

**Comment by reubenmiller** [comment]
thin-edge.io supports the Cumulocity interface, and by "on-prem" you are referring to a self hosted Cumulocity IoT instance correct? If so then it should work just fine, as long as the Cumulocity IoT version supports certificates (e.g. >=10.11, if I recall correctly).

**Comment by krdpk17** [comment]
@reubenmiller Thanks for quick turnaround 
<<thin-edge.io supports the Cumulocity interface, and by "on-prem" you are referring to a self hosted Cumulocity IoT instance correct?>>
Deepakk>> I meant, on-prem Cumulocity IoT cluster as mentioned in https://cumulocity.com/releasenotes/release-10-5-0/platform-devices-10-5-0/.

**Comment by reubenmiller** [comment]
@krdpk17 I assume that the on-premise is providing the same Cumulocity IoT interface as provided by the cloud, so I think it is safe to say it should work fine (though again the Cumulocity IoT version needs to support device certificate authentication for MQTT to work).

**Comment by reubenmiller** [comment]
Closing as there should not be anything "special" about the on-prem Cumulocity as the on-prem provides the standard Cumulocity interface (assuming it is using a version that supports MQTT connectivity via device certificates).
