### ISSUE TITLE
It is not possible to configure a second mqtt listener

### ISSUE THREAD

**Issue by toewsar** [thin-edge/thin-edge.io#1852]
**Describe the bug**
The `tedge-mosquitto.conf` contains `per_listener_settings true`. 
This parameter has to be set once in the configuration files of mosquitto. 
Because is defined in `tedge-mosquitto.conf` it's not possible to define is second listener e.g. a public one with user authetication or a websocket.

**To Reproduce**
Add `per_listener_settings true` to global mosquitto config.
```
echo "per_listener_settings true" > /etc/mosquitto/conf.d/default.conf
```

Create an additional listener:
```
cat <<EOF >/etc/mosquitto/conf.d/websocket.conf
listener 9001
protocol websockets
allow_anonymous true
EOF
```

Restart the mosquitto service `sudo systemctl  restart mosquitto`.
The mosquitto service won't start due to errors.
```
Error: per_listener_settings must be set before any other security settings.
Error found at /etc/tedge/mosquitto-conf/tedge-mosquitto.conf:1.
Error found at /etc/mosquitto/mosquitto.conf:14.
``` 

**Expected behavior**
The `per_listener_settings true` parameter should not be part of `tedge-mosquitto.conf`.

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [e.g. 0.1.0]

**Additional context**
[How to configure multiple listeners](http://www.steves-internet-guide.com/mossquitto-conf-file/)

**Comment by reubenmiller** [comment]
Thanks @toewsar for the detailed ticket. It seems like a very sensible request. We'll double check if there was some other reason behind this setting to check if it can be removed or not.

**Comment by didier-wenzek** [comment]
@Bravo555 extracted this fix in a specific PR https://github.com/thin-edge/thin-edge.io/pull/1919

**Comment by toewsar** [comment]
I've not testet yet, but it should work according to the changes. What I still unsure if it is a good idea to put the `"per_listener_setting"` into the `tedge-mosquitto.conf`.
