### ISSUE TITLE
Need clarity on support for x86

### ISSUE THREAD

**Issue by krdpk17** [thin-edge/thin-edge.io#1872]
**Is your documentation request related to a problem? Please describe.**

In supported platform list, ARM based platforms are mentioned, but there is no mention of X86 platform. I wonder why.. Is X86 platform supported?

**Describe the improvement you'd like**

In industry, there are IoT devices which uses X86, so mentioning this info helps wider adoption of thin-edge.

**Additional context**

Might be, update of https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/supported-platforms.md will be needed.

**Comment by reubenmiller** [comment]
Though the good news is that you can compile thin-edge for linux x86 (32bit) devices.

To do this you can use the current build script (though the placement of the `build.sh` script is subject to change):

```sh
./ci/build_scripts/build.sh i686-unknown-linux-gnu
```

Though the musl build seems to have some problems cross compiling `jemalloc-sys` (on a `aarch64` machine)

**Comment by krdpk17** [comment]
@reubenmiller  Thanks. So, x86-32bit and 64 bit are both supported? BTW, i compiled for 64 bit and it passed.
<<do you happen to have some examples of such devices?>>
Microcontrollers are X86 processor with 32 bits.. These are used in many IoT devices mostly to save the cost of product :)

**Comment by krdpk17** [comment]
@reubenmiller  Appreciating your support

**Comment by reubenmiller** [comment]
Closing.
