### ISSUE TITLE
Refactor tedge_agent using tedge actors

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#1918]
The purpose is to rewrite, using actors, the 3 services of the `tedge_agent` daemon:

- [x] managing software management plugins and requests,
- [x] triggering device reboot,
- [x] serving local http requests.

This refactoring must be done without external changes. However, one needs  to untangle software management and reboot. Indeed these two services use the same file to store the state of the current operation. The simpler is to use two different files - keeping things unchanged for reboot as this use is critical on notifying the cloud of the reboot success (For software management, the running operation request is stored only to be cancelled on restart if not properly cleared on success).

The aim of this refactoring is to ease the re-organization of the thin-edge daemons into a single executable. Therefore, the messages expected and sent by the new actors for software management and device reboot must be [plain data structure from the `tedge_api`](https://github.com/thin-edge/thin-edge.io/blob/main/crates/core/tedge_api/src/messages.rs) and not serialized MQTT messages. This `From`/`Into` translation into MQTT will be done on the fly by connecting in `tedge_agent::main()` these protocol-independent actors to the MQTT actor.

In the future, one might consider to re-organize the code for software management to add the ability to have actor-based software plugin. This is out of scope for now.  A single actor will manage all the software plugins registered in `/etc/tedge/sm-plugins` and all these plugins are let unchanged using the [command API](https://thin-edge.github.io/thin-edge.io/html/tutorials/write-my-software-management-plugin.html).

It might be strange to implement the local file-transfer service using an actor, as there is no message in, no message out but only a back-ground task. This is not an issue: the point with actors is to have a consistent way to build and run independent units of computation. In the future, one might add request messages to that actor to control what is published, but this is out-of-scope for now.

Note that:
- The actor framework currently define nothing related to the `--init` and `--clear` features of the agent. It's simpler to keep these implementations unchanged. Especially, because they will be likely deprecated.

**Comment by albinsuresh** [comment]
> Therefore, the messages expected and sent by the new actors for software management and device reboot must be [plain data structure from the tedge_api](https://github.com/thin-edge/thin-edge.io/blob/main/crates/core/tedge_api/src/messages.rs) and not serialized MQTT messages

Definitely makes sense. So, I'm assuming that another mapping actor (A `TedgeMQTTActor`  or something like that) will be required to do the mapping of the `tedge/commands/software_xxx` MQTT messages received from the `MqttActor` to typed Tedge data structures(`SoftwareListRequest`, `RestartOperationRequest ` etc) and send those to the `SoftwareManagementActor`? Or can this be achieved using something lighter like a `MappingSender`?

**Comment by didier-wenzek** [comment]
> So, I'm assuming that another mapping actor (A TedgeMQTTActor or something like that) will be required to do the mapping of the tedge/commands/software_xxx MQTT messages received from the MqttActor to typed Tedge data structures(SoftwareListRequest, RestartOperationRequest etc) and send those to the SoftwareManagementActor

There are many alternative options here, from a [mapped input](https://github.com/thin-edge/thin-edge.io/blob/main/crates/core/tedge_actors/src/builders.rs#L130) to a [ConvertingActor](https://github.com/thin-edge/thin-edge.io/blob/main/crates/core/tedge_actors/src/converter.rs), the later being required if the conversion is state-full.

**Comment by gligorisaev** [comment]
Checked
