### ISSUE TITLE
Support SNI during TLS handshake

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#1920]
**Is your feature improvement request related to a problem? Please describe.**

Support SNI ([Server Name Indication](https://en.wikipedia.org/wiki/Server_Name_Indication)) resolution when connecting to servers which are hosting multiple SSL certificates. For example the Cumulocity custom domain name feature uses this to allow customers to use their own domain name whilst still hosting Cumulocity on the public cloud instance.

Currently during `tedge connect c8y`, connecting to a domain which has multiple certificates causes the following error:

```
ERROR: Custom { kind: InvalidData, error: InvalidCertificateData("invalid peer certificate: CertNotValidForName") }
```

The difference in certificates can be shown by using `openssl` without the `-servername` option.

```sh
# with SNI resolution
openssl s_client -showcerts -servername development.exampleiot.com -connect development.exampleiot.com:443 </dev/null

# without SNI resolution
openssl s_client -showcerts -connect development.exampleiot.com:443 </dev/null
```

**Describe the solution you'd like**

The SNI resolution should be enabled by default, and there should be no configuration required by the user.

**Describe alternatives you've considered**

**Additional context**

References:
* https://stackoverflow.com/questions/7885785/using-openssl-to-get-the-certificate-from-a-server

Using a custom domain is a feature of Enterprise Cumulocity Tenants. Information about the custom domain name can be found here:
* https://cumulocity.com/guides/users-guide/enterprise-tenant/#domain-name

There some notes about enabling SNI in rustls here (though the instructions are using a much older version):
* https://stephanheijl.com/rustls_sni.html

**Comment by Bravo555** [comment]
Nevermind, it was something far simpler. Server TLS configuration on port 8883 was to blame. Try the following:

```bash
openssl s_client -showcerts -servername development.exampleiot.com -connect development.exampleiot.com:8883 </dev/null
```

Server correctly responds with cert for CN specified in SNI on port 443, but on port 8883 which thin-edge uses, it responds with `*.us.cumulocity.com` certificate.
