### ISSUE TITLE
Supporting filtering criteria in apt-sm-plugin list output

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#1926]
**Is your feature improvement request related to a problem? Please describe.**

Depending on your setup the `tedge-apt-plugin` can return a large list of packages, sometimes > 256 packages. The large list can effect other related Cumulocity IoT processes on the server side (e.g. Cumuloity Datahub offboarding of the data to a data lake).

A large number of packages (e.g > 50) generally has very limited value for users as the list is too big to get a good overview over.  Instead people are more interested in selected packages related to their use case (e.g. users care more about their user applications rather than which libc package is installed).

**Describe the solution you'd like**

The `tedge-apt-plugin` should support the following filtering criteria:

* name (regex pattern)
* maintainer (regex pattern)

In addition, the max number of packages should be configured to prevent large number of packages from being sent to the cloud
* Add configuration to set the max number of software packages reported by each software management (sm) plugin (configurable via `tedge.toml`). The limit should be applied to each sm-plugin so that one rogue plugin producing 1000's of entries does not bump the output of other sm-plugins.

**Describe alternatives you've considered**

**Additional context**

**Comment by reubenmiller** [comment]
Maybe switching from using the `apt list --installed` command, we could use the `dpkg-query` command. For example you can list the package, version and maintainer using:

```
dpkg-query -f '${Package}\t${Version}\t${Maintainer}\n' -W
```

Though more investigation is needed to see if it returns the appropriate data.

**Comment by Ruadhri17** [comment]
We can replace `apt list --installed` with slight modification (`dpkg-query` does not support the `--installed` flag, but we can check package status and then `grep` all that are `installed` but print them without status information). We will also need to use grep when filtering by maintainers as `dpkg-query` filters only by names. However, I have a few questions: 

* Should we apply a maximum number of displayed packages when using a filter?  
* Should we set a maximum number of displayed packages by default? If so, what should be a default number?
* How do we want to provide filtering options? Initially, I wanted to add two flags: `--name` and `--maintainer`, but maybe you have a better suggestion.

**Comment by reubenmiller** [comment]
> Should we apply a maximum number of displayed packages when using a filter?

The maximum number of items should be applied by the tedge component that runs the plugin filters (not the plugin itself), as this will be common logic which can be applied across different software management plugins.

> Should we set a maximum number of displayed packages by default? If so, what should be a default number?

Use a default of 1000 items. This limit should always be applied to the software management list.

> How do we want to provide filtering options? Initially, I wanted to add two flags: --name and --maintainer, but maybe you have a better suggestion.

The filter options should be provided by the plugin configuration and not as command line parameters as there is no common command line interface which can be provided.

Instead specific plugins should have their own configuration which controls how they work. e.g. the `tedge-apt-plugin` could read in configuration which reads the `name` and `maintainer` settings.

**Comment by didier-wenzek** [comment]
- A new setting has been added to `tedge config` to limit the number of software packages forwarded to the cloud.
  - `software.plugin.max_packages` gives the maximum number of packages to be listed per software type.
  - The default is 1000 packages
  - 0 means no limit.
  - This affects only what is transmitted to the cloud. `tedge-apt-plugin list` lists all the installed packages.
- Two settings have been specifically added to `tedge-apt-plugin`.
  - `tedge-apt-plugin list --name $PATTERN` lists the packages which name matches the regular expression `$PATTERN`.
  -  `tedge-apt-plugin list --maintainer $PATTERN` lists the packages which maintainer matches the regular expression `$PATTERN`.
  - If both `--name` and `--maintainer` patterns are provided, `tedge-apt-plugin` lists packages which either the name *or* the maintainer matches.
  - These two settings  can stored in `/etc/tedge/tedge_config.toml` in an `apt` table.
  - If stored in `/etc/tedge/tedge_config.toml`, then the `apt.name` and `apt.maintainer` settings are used to filter packages listed to the cloud. 
  - No support is provided by `tedge config` so store `apt.name` and `apt.maintainer`.

**Comment by PradeepKiruvale** [comment]
> * A new setting has been added to `tedge config` to limit the number of software packages forwarded to the cloud.
>   
>   * `software.plugin.max_packages` gives the maximum number of packages to be listed per software type.
>   * The default is 1000 packages
>   * 0 means no limit.
>   * This affects only what is transmitted to the cloud. `tedge-apt-plugin list` lists all the installed packages.
> * Two settings have been specifically added to `tedge-apt-plugin`.
>   
>   * `tedge-apt-plugin list --name $PATTERN` lists the packages which name matches the regular expression `$PATTERN`.
>   * `tedge-apt-plugin list --maintainer $PATTERN` lists the packages which maintainer matches the regular expression `$PATTERN`.
>   * If both `--name` and `--maintainer` patterns are provided, `tedge-apt-plugin` lists packages which either the name _or_ the maintainer matches.
>   * These two settings  can stored in `/etc/tedge/tedge_config.toml` in an `apt` table.
>   * If stored in `/etc/tedge/tedge_config.toml`, then the `apt.name` and `apt.maintainer` settings are used to filter packages listed to the cloud.
>   * No support is provided by `tedge config` so store `apt.name` and `apt.maintainer`.

When `tedge-apt-plugin` is installed it will be installed as `apt` inside `/etc/tedge/sm-plugins`. So, for testing purposes use `/etc/tedge/sm-plugins/apt` instead of `tedge-apt-plugin` as the binary name.

**Comment by reubenmiller** [comment]
FYI: Just an example showing how useful this feature is:

Using the following package name and maintainer filter on a Raspberry Pi 3 returns 41 packages instead of 920 (unfiltered list). This enables me to concentrate on the packages which I am interested in monitoring.

```sh
/etc/tedge/sm-plugins/apt list --name '(vim|docker|nano).*' --maintainer '.*(raspberry|thin-edge.io).*'
```

The above filter will includes any packages matching any of the following:
* packages which start with, `vim`, `docker` or `nano`
* packages which include either `raspberry` or `thin-edge.io` in the maintainer property

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.  ``` tests/RobotFramework/tests/tedge/call_tedge_config_list.robot ``` and ``` tests/RobotFramework/tests/tedge/apt_plugin.robot ```
- [x]  Documment corrected: typo on ``` ../../docs/src/tutorials/send-thin-edge-data.md ``` 
- [x] QA has tested the feature and it meets the required specifications.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.  ``` tests/RobotFramework/tests/tedge/call_tedge_config_list.robot ``` and ``` tests/RobotFramework/tests/tedge/apt_plugin.robot ```  and ``` tests/RobotFramework/tests/cumulocity/software_management/sm-plugin.robot ```
- [x] QA has tested the feature and it meets the required specifications.
- [x] PR created: https://github.com/thin-edge/thin-edge.io/pull/2006 and https://github.com/thin-edge/thin-edge.io/pull/2198
