### ISSUE TITLE
Remove MQTT session initialization logic used by init commands

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#1946]
**Is your refactoring request related to a problem? Please describe.**

The init commands (e.g. `tedge-agent --init`) create an MQTT session so that the mosquitto sessions can be used as an offline buffer for messages whilst the process is not running. The init command are called during the post installation scripts. However this setup is broken (see this [discussion](https://github.com/thin-edge/thin-edge.io/pull/1922#discussion_r1178765586)) and causes problems and unnecessary warning messages when trying to install the packages on systems where the MQTT broker is not running.

**Describe the solution you'd like**

Remove the MQTT session creation logic in each of the init commands on all components (e.g. tedge, tedge-agent, tedge-mapper, c8y-configuration-plugin etc.). If a component has a dependency on a specific service then the `tedge/health/#` topic should be used to check if the service is capable of receiving messages (or at least as already registered a session with the MQTT broker).

**Describe alternatives you've considered**

**Additional context**

**Comment by didier-wenzek** [comment]
This has been implemented by https://github.com/thin-edge/thin-edge.io/pull/2001
