### ISSUE TITLE
Build script fails on Ubuntu 23.04 Python 3.11

### ISSUE THREAD

**Issue by Bravo555** [thin-edge/thin-edge.io#1951]
**Describe the bug**

When invoking `ci/build_scripts/build.sh`, I get the following error:

```sh
thin-edge.io on  feat/1931-c8y-different-http-mqtt-endpoints:main [$!⇣] is 📦 v0.10.0 via 🦀 v1.70.0-beta.2
❯ ci/build_scripts/build.sh x86_64-unknown-linux-musl
Using version set from git: 0.10.0-186-g10a78e49
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

Error seems to be from python, so looking at the script, I found the command which causes the error: `pip3 install ziglang`

```sh
thin-edge.io on  feat/1931-c8y-different-http-mqtt-endpoints:main [$!⇣] is 📦 v0.10.0 via 🦀 v1.70.0-beta.2 
❯ pip3 install ziglang
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

This behaviour was probably introduced in recent versions of python in order to make handling system python packages the sole responsibility of the system package manager, and use pip only on systems where there is no native package manager that can be used to manage python system packages.

On systems where a package manager is present, packages can be only installed in two ways:

- globally with a system package manager (like `apt install python3-ziglang` on Ubuntu)
- locally to a virtual environment by pip

On Ubuntu it's even more complicated because there are 2 package managers: `apt` and `snap`, and `ziglang` is only on snap. This starts to be hilariously overcomplicated, so trying to use a system package manager in our build script is probably not a good idea.

**Proposed solutions**

1. Add `--break-system-packages` to the `pip install ziglang` command. It works fine, but probably as long as the user does not have a `ziglang` snap installed, so it's probably a band-aid.
2. Use Python Virtual Environment to run the build. This sucks because that's more steps, but is probably the better long-term solution as more people upgrade their system distributions in the future, or if they use rolling release distros.

**To Reproduce**

Run `ci/build_scripts/build.sh` on Ubuntu 23.04.

**Expected behavior**

Build script builds.

**Comment by Bravo555** [comment]
Yeah I did get it working easily by adding `--break-system-packages` and will probably also install ziglang snap as well, but expect this issue will pop up for other people if they upgrade to python 3.11.

**Comment by reubenmiller** [comment]
This fix using `--break-system-packages` was included in https://github.com/thin-edge/thin-edge.io/pull/2165.

https://github.com/thin-edge/thin-edge.io/blob/f9ff1da498c0145f6b33b81c4fb72755566b6336/ci/build_scripts/build.sh#L125
