### ISSUE TITLE
Stopping `tedge-mapper-c8y` does not stop the FsWatcher actor gracefully

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#1983]
**Describe the bug**
When tedge-mapper-c8y is stopped using ^c or using `systemctl` it does not stop the `FsWacher` actor gracefully

**To Reproduce**

1. Install thin-edge.io
2. `tedge connect c8y`
3. wait for a while,  Stop mapper `sudo systemctl stop tedge-mapper-c8y`
4. Observe logs `sudo systemctl status tedge-mapper-c8y`
Observe there is an error log

**ERROR Runtime: Actor FsWatcher-6 has finished unsuccessfully: ChannelE>**

**Expected behavior**
Stopping mapper must stop all the actors properly/gracefully.

**Screenshots**
○ tedge-mapper-c8y.service - tedge-mapper-c8y converts Thin Edge JSON measurements to Cumulocity JSON format.
     Loaded: loaded (/lib/systemd/system/tedge-mapper-c8y.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Tue 2023-05-16 10:24:07 IST; 5s ago
    Process: 161123 ExecStart=/usr/bin/tedge-mapper c8y (code=exited, status=0/SUCCESS)
   Main PID: 161123 (code=exited, status=0/SUCCESS)
        CPU: 192ms

May 16 10:24:07 ubuntu tedge-mapper[161123]: 2023-05-16T04:54:07.44217156Z  INFO Runtime: Actor has finished: C8Y-REST-5
May 16 10:24:07 ubuntu tedge-mapper[161123]: 2023-05-16T04:54:07.44222366Z  INFO Runtime: Actor has finished: Timer-7
May 16 10:24:07 ubuntu tedge-mapper[161123]: 2023-05-16T04:54:07.442280461Z  INFO Runtime: Actor has finished: HTTP-4
**May 16 10:24:07 ubuntu tedge-mapper[161123]: 2023-05-16T04:54:07.442344261Z ERROR Runtime: Actor FsWatcher-6 has finished unsuccessfully: ChannelE>**
May 16 10:24:07 ubuntu tedge-mapper[161123]: 2023-05-16T04:54:07.442401861Z  INFO Runtime: Actor has finished: HealthMonitorActor-1
May 16 10:24:07 ubuntu tedge-mapper[161123]: 2023-05-16T04:54:07.442734662Z  INFO Runtime: Actor has finished: CumulocityMapper-8
May 16 10:24:07 ubuntu tedge-mapper[161123]: 2023-05-16T04:54:07.443021964Z  INFO Runtime: Actor has finished: Signal-Handler-0
May 16 10:24:07 ubuntu tedge-mapper[161123]: 2023-05-16T04:54:07.443083764Z  INFO Runtime: All actors have finished
May 16 10:24:07 ubuntu systemd[1]: tedge-mapper-c8y.service: Deactivated successfully.
May 16 10:24:07 ubuntu systemd[1]: Stopped tedge-mapper-c8y converts Thin Edge JSON measurements to Cumulocity JSON format..

**Environment (please complete the following information):**
 - OS [incl. version]: Ubuntu
 - Hardware [incl. revision] X64
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [e.g. 0.1.0] 0.10.0

**Additional context**

**Comment by albinsuresh** [comment]
Closed by https://github.com/thin-edge/thin-edge.io/pull/1984

To verify the fix, just follow the instructions in the ticket and make sure that the reported error log messages are not appearing when the mapper is stopped.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the bug and could not reproduce it anymore.
