### ISSUE TITLE
Refactor the internal config code to use new TedgeConfig

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2019]
**Is your refactoring request related to a problem? Please describe.**

A new `TedgeConfig` internal feature was introduced in https://github.com/thin-edge/thin-edge.io/pull/1936. This should be utilized by all components and the older configuration model should be removed.

**Describe the solution you'd like**

* [x] Refactor existing code base to make use of `TedgeConfig`

  * [x] `tedge-mapper` https://github.com/thin-edge/thin-edge.io/pull/2013
  * [x] `tedge-agent` https://github.com/thin-edge/thin-edge.io/pull/2073
  * [x] `tedge-firmware-plugin` https://github.com/thin-edge/thin-edge.io/pull/2064
  * [x] `tedge-configuration-plugin` https://github.com/thin-edge/thin-edge.io/pull/2064
  * [x] `tedge-log-plugin` https://github.com/thin-edge/thin-edge.io/pull/2064
  * [x] `tedge` https://github.com/thin-edge/thin-edge.io/pull/2077

* [x] Remove the older configuration logic

**Describe alternatives you've considered**

**Additional context**

**Comment by reubenmiller** [comment]
@didier-wenzek Do we need to complete the last task in the list, or is this outdated information?

**Comment by didier-wenzek** [comment]
> @didier-wenzek Do we need to complete the last task in the list before closing the ticket, or is this outdated information?

This outdated. I forgot to update it after https://github.com/thin-edge/thin-edge.io/pull/2143
