### ISSUE TITLE
Make tedge-apt-plugin installation to consistent with other thin-edge components

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#2028]
**Is your feature improvement request related to a problem? Please describe.**
The problem with the existing way of installing `tedge-apt-plugin` is not consistent with other `thin-edge` components.
The binary is installed into the `/etc/tedge/sm-plugins` and the `tedge-apt-plugin` is renamed as `apt`.

**Describe the solution you'd like**
Install the `tedge-apt-plugin` into /usr/bin and create a symlink to it in `/etc/tedge/sm-plugins/apt`

**Describe alternatives you've considered**

**Additional context**

**Comment by PradeepKiruvale** [comment]
Follow the steps below to test it.

1. Install `tedge-apt-plugin`
2. check if there is `tedge-apt-plugin` in `/usr/bin`
3. check if the symlink to `/etc/tedge/sm-plugins/apt is created using `/usr/bin/tedge-apt-plugin`.
    Just do `sudo ls -l /etc/tedge/sm-plugins/apt` see its linked to `/usr/bin/tedge-apt-plugin`.

**Comment by gligorisaev** [comment]
🔍
I'm pleased to announce that the QA process for this feature/issue has been successfully completed. Our diligent QA has meticulously gone through the QA checklist and everything looks good!

Throughout the testing phase, I focused on verifying each item on the checklist, ensuring that all required functionalities are functioning as expected, and identifying and addressing any potential issues.


✅ Functionality and behavior meet the specified requirements
✅ Performance and response times meet acceptable thresholds
✅ Edge cases and boundary conditions have been tested
✅ Integration and compatibility with other systems/components have been verified

Overall, I am confident that this feature/issue is ready for the next steps.
