### ISSUE TITLE
Unable to install thinEdgeIO in Ubuntu Docker container

### ISSUE THREAD

**Issue by junaid88** [thin-edge/thin-edge.io#2039]
Hi,

I have a running Ubuntu docker container in which I want to install thinEdge.io but when I run the following cmd it throws an error

**"curl -fsSL https://raw.githubusercontent.com/thin-edge/thin-edge.io/main/get-thin-edge_io.sh | sudo sh -s"**

**Error Logs**

```
Installing for architecture amd64

Downloading tedge...OK
Installing tedge...FAILED
Failed to install thin-edge.io

Reason: Failed to install package 'tedge'
Please create a ticket using the following link and include the console output
    https://github.com/thin-edge/thin-edge.io/issues/new?assignees=&labels=bug&template=bug_report.md

--------------- machine details ---------------------
date:           Thu Jun 15 20:19:12 UTC 2023
tedge:          0.11.0
Machine:        Linux 221d1a766e74 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Architecture:   amd64

--------------- error details ------------------------
Version argument has not been provided, installing latest: 0.11.0
To install a particular version use this script with the version as an argument.
For example: sudo ./get-thin-edge_io.sh 0.11.0
Installing for architecture amd64
(Reading database ... 5059 files and directories currently installed.)
Preparing to unpack .../tedge/tedge_0.11.0_amd64.deb ...
/var/lib/dpkg/tmp.ci/preinst: 16: cannot create /etc/sudoers.d/tedge: Directory nonexistent
dpkg: error processing archive /tmp/tedge/tedge_0.11.0_amd64.deb (--install):
 new tedge package pre-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 /tmp/tedge/tedge_0.11.0_amd64.deb
Failed to install thin-edge.io
Reason: Failed to install package 'tedge'
Please create a ticket using the following link and include the console output
    https://github.com/thin-edge/thin-edge.io/issues/new?assignees=&labels=bug&template=bug_report.md
------------------------------------------------------
```

**Comment by reubenmiller** [comment]
@junaid88 The thin-edge.io debian packages currently require you to have `sudo` installed (though this will change in the near future), however I would take one step back and ask what are you trying to achieve; do you want to run thin-edge.io inside a container just to try things out, or are you trying to build a container for production purposes?

If you wanting to get familiar with thin-edge.io then I would highly recommend looking at the [tedge-demo-container](https://github.com/thin-edge/tedge-demo-container) as it allows you to get everything setup in about 90 seconds (depending on your internet connection). This project is meant to simulate a real device by having everything installed (including systemd), however if you are looking at just running the binaries inside a slim container (e.g. without systemd), then just using the tarballs (e.g. `*.tar.gz` files) which container just the binaries, however we're looking to extend tedge-demo-container to also provide an example of this.

**Comment by reubenmiller** [comment]
Hi @junaid88, we've recently improved the installation story of thin-edge.io which should solve a lot of your pain points.

Check out the new [installation guide](https://thin-edge.github.io/thin-edge.io/next/install/) and let us know if that resolves your issue.

**Comment by reubenmiller** [comment]
Please open the ticket again if you are still having problems.
