### ISSUE TITLE
VNC Invalid Server Version 005.000

### ISSUE THREAD

**Issue by jhoo-sag** [thin-edge/thin-edge.io#2045]
**Describe the bug**
When using Raspberry Pi with thin-edge, I'm getting a 'Invalid server version 005.000' when trying to connect from Cumulocity IoT using VNC. This was done on a brand new installation of Pi and thin-edge.

**To Reproduce**
Follow the 'Getting Started' guide in the thin-edge docs, enable VNC on the Pi with 'raspi-config', and then try to connect VNC on port 5900 from Cumulocity IoT remote access.

**Screenshots**
![image](https://github.com/thin-edge/thin-edge.io/assets/96841914/84a4f2ed-1903-46fa-b92b-38918c6f82d9)

**Environment (please complete the following information):**
 - OS: Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
 - Hardware: Raspberry Pi 4
 - System-Architecture: Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
 - thin-edge.io version: 0.11

**Comment by reubenmiller** [comment]
@jhoo-sag this looks to be a problem with the Cumulocity Cloud Remote Access feature in the platform itself (not thin-edge.io). Tedge just Proxies TCP traffic between two ports so it does not actually know anything about the protocol. 

Can you please create a ticket in Cumulocity IoT?

**Comment by jhoo-sag** [comment]
Found out with some more digging that it's an issue with RealVNC, which is the default on raspbian. Uninstalling that and using TightVNC solved the issue. No issue with Cumulocity or Thin Edge!
