### ISSUE TITLE
don't include binary name and version when printing help of any of the binaries

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2051]
**Is your refactoring request related to a problem? Please describe.**

When printing the help text of a command (e.g. `c8y-firmware-plugin --help`), the binary name and version is displayed on the first line of the help text.

Having the information within the help text makes parsing the output more complicated for automation purposes (e.g. generating automatic do documents from the command output as the version changes more frequently than the help contents).

Below shows an example of the version information which is printed on the first line.

```sh
c8y-firmware-plugin 0.11.0-145-ge59e17be
```

Here is the full example:

**Command**

```sh
c8y-firmware-plugin --help
```

**Output**

```sh
c8y-firmware-plugin 0.11.0-145-ge59e17be
Thin-edge device firmware management for Cumulocity

USAGE:
    c8y-firmware-plugin [OPTIONS]

OPTIONS:
        --config-dir <CONFIG_DIR>
            [default: /etc/tedge]

        --debug
            Turn-on the debug log level.

            If off only reports ERROR, WARN, and INFO If on also reports DEBUG and TRACE

    -h, --help
            Print help information

    -i, --init
            Create required directories

    -V, --version
            Print version information
```

**Describe the solution you'd like**

* Don't display the binary name and version on the first line of the help/usage text for any of the project's release binaries (e.g. tedge, tedge-agent, tedge-mapper, c8y-*-plugin, tedge-apt-plugin etc.

In comparison with other tooling, it is more common to just display the version via `--version` (or something similar), rather than printing it out when using `--help`.

* `curl --help`
* `docker --help`
* `grep --help`

All of those commands have a dedicated version flag should the user want to know the version of the command they are using.

**Note**
* I realise this is a bit of a bike-shed issue, however if no-one really cares it will at least make documentation automation slightly easier. Also the requested behaviour has already been accepted as the default for [clap-rs PR4160](https://github.com/clap-rs/clap/pull/4160)

**Describe alternatives you've considered**

**Additional context**

**Comment by didier-wenzek** [comment]
Mostly a matter to upgrade to `clap ="4.10"` with some issues with deprecated methods:


```
error[E0599]: no method named `parse` found for struct `Arg` in the current scope
  --> crates/core/tedge/src/cli/mqtt/cli.rs:37:29
   |
37 |         #[clap(short, long, parse(try_from_str = parse_qos), default_value = "0")]
   |                             ^^^^^ method not found in `Arg`
``

**Comment by didier-wenzek** [comment]
As a side effect of [bumping clap version](https://github.com/thin-edge/thin-edge.io/pull/2206), `--help` no longer show the version, and this for all the `tedge-xxx` executables.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite. 
- [x] QA has tested the feature and it meets the required specifications.

Checked for:
- c8y-firmware-plugin
- tedge
- tedge-agent
- tedge-mapper
- tedge-apt-plugin
- c8y-configuration-plugin
- c8y-log-plugin
- c8y-remote-access-plugin
