### ISSUE TITLE
Simplify the installation guide

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#2063]
In the current version of the docs there is a [main install page](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/install/index.md)  and several [*dubious* installation howto ](https://github.com/thin-edge/thin-edge.io/tree/main/docs/src/operate/installation).

It would be good to have a single install page. Having more than one can be okay but with no weird methods as extracting the files form a deb package. 

- double check that the [main install page](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/install/index.md) is fully correct
- Do we really need two extra docs for manual install ([first](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/operate/installation/how_to_install_thin_edge_manually.md), [second](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/operate/installation/installation_without_deb_support.md)) ?
   -  If not squash these pages
 - Is this page on [how to install the apt software plugin](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/operate/installation/install_and_enable_software_management.md) up-to-date ?
- Are we missing pages to install the other plugins?

**Comment by reubenmiller** [comment]
Some progress has been made here:

* [x] double check that the [main install page](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/install/index.md) is fully correct. [updated-docs](https://thin-edge.github.io/thin-edge.io/next/install/)
* [x] Do we really need two extra docs for manual install ([first](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/operate/installation/how_to_install_thin_edge_manually.md), [second](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/operate/installation/installation_without_deb_support.md))? No, 
If not squash these pages. [updated-docs](https://thin-edge.github.io/thin-edge.io/next/operate/installation/init_systems/)
* [ ] Is this page on [how to install the apt software plugin](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/operate/installation/install_and_enable_software_management.md) up-to-date ?
* [ ] Are we missing pages to install the other plugins?

**Comment by reubenmiller** [comment]
Docs were updated
* Added **Software Management** Page under the device management. https://thin-edge.github.io/thin-edge.io/next/operate/c8y/software-management/

**Comment by gligorisaev** [comment]
QA has thoroughly checked the document and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has checked the documentation and it fits the function.
