### ISSUE TITLE
Implement a converter that bridges the old MEA topics to the new ones.

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#2079]
As we plan a [major refactoring of all the MQTT topics](https://github.com/thin-edge/thin-edge.io/pull/2030) used by thin-edge, we have to provide some backward compatibilities. During a transition period, thin-edge will support the old as well as the new schemes, using __a converter that re-publishes any measurement, event or alarm received on a `tedge/#` topic to the appropriate new `te/#` topic__.

- All the messages must be re-published unchanged - same content, QoS and retain flag, from the old to the new topic.
- There is only one exception for the severity of the alarms (that has to be extracted from the `tedge` topic and pushed into the json payload of the message).
- The complete specifications of this conversion are [here](https://github.com/thin-edge/thin-edge.io/pull/2030/files#diff-af802a095f72bbf84e172455307666c297802f0376506349420c5c2576aeaa88R658).
- The simpler is to use a [`Converter`](https://github.com/thin-edge/thin-edge.io/blob/main/crates/core/tedge_actors/src/converter.rs#L78) and to launch this actor inside the `tedge-agent`.

**Comment by PradeepKiruvale** [comment]
The table below shows mapping the `tedge` topic to the `te` topic and if there are any changes needed.

| tedge topic | te topic | other updates
|---|---|---|
|tedge/measurements| te/device/main///m/ ||
| tedge/measurements/child | te/device/child///m/ ||
| tedge/alarms/severity/alarm_type|te/device/main///a/alarm_type|add severity into payload|
|tedge/alarms/severity/child/alarm_type|te/device/child///a/alarm_type|add severity into payload|
|tedge/events/event_type|te/device/main///e/event_type||
|tedge/events/child/event_type|te/device/child///e/event_type||
|tedge/commands/res/software/list|te/device/main/cmd/software_list/<cmd_id>||
|tedge/commands/res/software/update|te/device/main/cmd/software_update/<cmd_id>||
|tedge/+/commands/res/config_snapshot|te/device/main/cmd/config_snapshot/<cmd_id>||
|tedge/+/commands/res/config_snapshot|te/device/child/cmd/config_snapshot/<cmd_id>||
|tedge/+/commands/res/config_update|te/device/main/cmd/config_update/<cmd_id>||
|tedge/+/commands/res/config_update|te/device/child/cmd/config_update/<cmd_id>||
|tedge/+/commands/res/firmware_update|te/device/main/cmd/firmware_update/<cmd_id>||
tedge/+/commands/res/firmware_update|te/device/child/cmd/firmware_update/<cmd_id>||
|tedge/commands/res/control/restart|te/device/main/cmd/restart/<cmd_id>||

**Comment by gligorisaev** [comment]
@PradeepKiruvale the test case that is part of your PR is not  verifiing the first point of Didier description:
'All the messages must be re-published unchanged - same content, QoS and retain flag, from the old to the new topic.'

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.  
         /tests/RobotFramework/tests/tedge_to_te_converter/convert_tedge_topics_to_te_topics.robot
- [x] QA has tested the feature and it meets the required specifications.
