### ISSUE TITLE
Implement an inventory / digital twin representation

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#2081]
With the [new MQTT topic scheme](https://github.com/thin-edge/thin-edge.io/pull/2030), the type of the target of an MQTT message can no more directly be derived from the message topic. Some auto-registration rules apply for the simple cases (when using the `te/device/+/service/+` scheme) but for the agent developer to be really free to define a domain-specific scheme, thin-edge must be enriched with a description of the misc entities, devices and services as well as their hierarchy. This is the aim of the [registration process](https://github.com/thin-edge/thin-edge.io/pull/2030/files#diff-9695a2a09b64f1cfa0ed7f9e9ff632abdc04a7fd3dc4c3849cf5b53a461e4addR13).

The point here is to implement a `struct DigitalTwin`  to keep an in-memory representation
of a device, its child-devices, and the services running on these devices.

The main feature of this struct is to map `+/+/+/+` entity identifiers to their:
- type: the main device? a child device? a service?
- parent, if any
- external device/service id: the id used on the cloud for this device/service. It can be the device certificate CN, an id given by the user or [derived from the entity identifier](https://thin-edge.github.io/thin-edge.io/next/references/mappers/c8y-mapper/)
- domain-specific data, such as a role or a location

The primary usage of this struct is for the c8y mapper, but not only as all the mappers might need it
as well as internal services as health checks.
- The c8y mapper needs to
  - get all the entities with their type, name and parent (to register these entities in the cloud)
  - be aware of any entity update (to register any new entity in the cloud)
  - get the device external id to which some telemetry data is related (`te/device/xyz///a/disk_full` => the child device named `child-xyz`)
  - get the entity identifier for from a device external id (a restart command for the device named `child-xyz` => `te/device/xyz///cmd/restart`)
- The health-check services needs to
  - get the list of services running on a device (in order to broadcast health-check messages)
- This map must be dynamic, with 
  - updates on registration messages received on [`te/+`, `te/+/+`, `te/+/+/+` or `te/+/+/+/+`](https://thin-edge.github.io/thin-edge.io/next/references/mappers/c8y-mapper/#registration)
  - updates on lookup request for an identifier in order to implement [auto-registration](https://thin-edge.github.io/thin-edge.io/next/contribute/design/mqtt-topic-design/#support-auto-registration-via-inference)
  - notification of any update on an identifier.

Hence, the needs are to:
- create empty twin with a function to derive a name from an (identifier, entity) pair
- get/set an entity struct for an entity identifier `+/+/+/+`
- derive an external id for each entity (indexing this external ids)
- get the entity identifier of a device - given its external id.
- get the main device identifier
- list child devices of a device or child device
- list the service running on a device
- provide a channel where updates are notified

## Steps

- I would start focusing on a `struct` rather than on an `actor` and introduce the latter only in a second step.
- For a first drop, I would only populate the digital twin using the auto-registration mechanism.
- For a second drop, I would add support to handle the registration messages.

## Alternatives

The c8y mapper needs to cache device internal ids.
One can argue that this should be the responsibility of the in-memory digital twin.
However, *only* c8y requires the devices to use either internal or external ids depending on the API.
Hence, it's simpler to let the c8y mapper use a separate cache from `+/+/+/+` identifier to c8y internal id.

The same argument can also apply to the bidirectional mapping from an identifier to a name.
This logic to derive a cloud name from an entity identifier and to retrieve back the identifier from the cloud name,
can be seen as a cloud specific concern and this would notably simplify the in-memory digital twin.
However, using a function to derive the name from an (identifier, entity) pair helps to encapsulate the specificities
and to benefit a shared reverse index from names to identifiers.

**Comment by didier-wenzek** [comment]
@Bravo555 I updated this ticket using the term "external device id" instead of "name" which was not aligned with the specifications. This external id is the id used on the cloud to identify the device.

@reubenmiller some points need to be clarified on how to derive a (child) device id from an entity identifier. 
The specifications detail what is an [entity identifier](https://thin-edge.github.io/thin-edge.io/next/references/mqtt-api/) but only give [device name examples](https://thin-edge.github.io/thin-edge.io/next/references/mappers/c8y-mapper/).
Am I correct when I understand that:
- The external id of the main device is the CN of the device certificate whatever its entity identifier (`te/device/main//` or `te/factory01/hallA/packaging/belt001`).
- If an `@id` is given by the registration message published for some entity, than this `@id` is used as is - with no transformations (even for the main device).
- If no `@id` is given for an entity, then the external id is derived from the main device external id and the device entity identifier. The root `te` prefix is substituted with the main device external id and all the slash chars `/`are replaced by columns `:`.  This rule applies to child devices and services.

**Comment by reubenmiller** [comment]
> @Bravo555 I updated this ticket using the term "external device id" instead of "name" which was not aligned with the specifications. This external id is the id used on the cloud to identify the device.
> 
> @reubenmiller some points need to be clarified on how to derive a (child) device id from an entity identifier. The specifications detail what is an [entity identifier](https://thin-edge.github.io/thin-edge.io/next/references/mqtt-api/) but only give [device name examples](https://thin-edge.github.io/thin-edge.io/next/references/mappers/c8y-mapper/). Am I correct when I understand that:
> 
> * The external id of the main device is the CN of the device certificate whatever its entity identifier (`te/device/main//` or `te/factory01/hallA/packaging/belt001`).
> * If an `@id` is given by the registration message published for some entity, than this `@id` is used as is - with no transformations (even for the main device).
> * If no `@id` is given for an entity, then the external id is derived from the main device external id and the device entity identifier. The root `te` prefix is substituted with the main device external id and all the slash chars `/`are replaced by columns `:`.  This rule applies to child devices and services.

Yes with the slightly modification:

> If an @id is given by the registration message published for some entity, than this @id is used as is - with no transformations (even for the main device)

If an explicit `@id` is provided, then it should still go through a normalizing process, e.g. replace `/` with `:`, otherwise this will allow user to misconfigure ids...however the normalization could be left up to the cloud specific mappers, so the `/` to `:` transformation could just be done by the mapper itself when messages are published to the cloud or received from the cluod.

**Comment by didier-wenzek** [comment]
Follow-up tasks : https://github.com/thin-edge/thin-edge.io/issues/2179
