### ISSUE TITLE
Update the mappers to consume MEA from the new topics

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#2082]
With the [new MQTT topic scheme](https://github.com/thin-edge/thin-edge.io/pull/2030), the mappers will have to consume messages from the `te/# ` and no more the `tedge/#`.

Once implemented the [automatic conversion from the old to new topics](https://github.com/thin-edge/thin-edge.io/issues/2079), the c8y, az and aws mapper must be updated accordingly.
- This has to done for measurements, events and alarms.
- The payload of these messages is unchanged with an exception for the severity of an alarm (previously attached on the topic, now inside the message payload) 
- See [this issue for the details](https://github.com/thin-edge/thin-edge.io/issues/2079).
- For c8y, the auto-registration process must be adapted too. Hence, this task might depend on the [implementation of an inventory / digital twin representation](https://github.com/thin-edge/thin-edge.io/issues/2081).
  - As first step, this task can address only auto registration using the `te/device/+/service/+` scheme.
  - The inventory / digital twin representation can be used as a second step when available.
 
Tasks:

- [x] Measurements for c8y are consumed from `te/+/+/+/+/m/+`
- [x] Measurements are published on `te/+/+/+/+/m/+` by collectd mapper
- [x] #2215
- [x] #2214
- [x] #2243
- [x] https://github.com/thin-edge/thin-edge.io/pull/2304
- [x] #2244
- [x] #2274
- [x] #2351

To be done only later:
- [x] #2288
- [x] [Software List&Update operations  on child devices](https://github.com/thin-edge/thin-edge.io/pull/2307)

**Comment by PradeepKiruvale** [comment]
`c8y-mapper` specific topics info is here https://github.com/thin-edge/thin-edge.io/pull/2030/files?short_path=9695a2a#diff-9695a2a09b64f1cfa0ed7f9e9ff632abdc04a7fd3dc4c3849cf5b53a461e4add

**Comment by didier-wenzek** [comment]
Tasks:

- [x] Measurements for c8y are consumed from `te/+/+/+/+/m/+`
- [x] Measurements are published on `te/+/+/+/+/m/+` by collectd mapper
- [ ] Forward measurement type to c8y.
- [ ] Events for c8y  are consumed from `te/+/+/+/+/e/+`
- [ ] Alarms for c8y  are consumed from `te/+/+/+/+/a/+`
- [ ] Azure mapper consumes MEA from `te` topics.
- [ ] AWS mapper consumes MEA from `te` topics.
- [ ] Health check and status for c8y on `te/+` (here the topics have to be properly defined)

To be done only later:
- [ ] Restart operation
- [ ] Software List and Update operations
