### ISSUE TITLE
flaky system test - Check PID number in lock file after restarting the services

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2087]
**Is your refactoring request related to a problem? Please describe.**

The following flaky integration tests have been identified

* `Check PID number in lock file after restarting the services` - Sometimes multiple PIDs are found matching the `pgrep -f <service-name>` command.

Failed tests appeared in the following runs:

* https://github.com/thin-edge/thin-edge.io/actions/runs/5621059749

**Describe the solution you'd like**

The integration tests should be reliable and not fail sporadically.

**Describe alternatives you've considered**

**Additional context**

**Comment by rina23q** [comment]
I got this test failure in my doc PR. Obviously the PR did nothing on Rust code: https://github.com/thin-edge/thin-edge.io/actions/runs/5761656396/job/15620114100?pr=2127

**Comment by reubenmiller** [comment]
Suspected root cause:

[systemctl restart](https://man7.org/linux/man-pages/man1/systemctl.1.html) does not wait for all file descriptors to be flushed before returning which is most likely the reason why some pid information is still being detected via pgrep -f. Using stop/start does not suffer from this problem.
