### ISSUE TITLE
tedge-apt-plugin does not show supported flags for subcommands

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2110]
**Describe the bug**

The new `tedge-apt-plugin` binary (introduced in 0.12.0) does not print out the subcommand help when prompted via `--help`. This makes it difficult to check which flags are supported by the sub command (most notably in the `tedge-apt-plugin list --help` command).

For example, the `list` subcommand does not document that `--name` and `--maintainer` flags are supported.

The apt filter settings are documented [here](https://thin-edge.github.io/thin-edge.io/operate/installation/install_and_enable_software_management/#filter-packages-by-name-and-maintainer)

**To Reproduce**

1. Show the help for the list subcommand of `tedge-apt-plugin`

    ```sh
    tedge-apt-plugin list --help
    ```

    The above command only shows the help of the root command (`tedge-apt-plugin`) and not the help of the subcommand `list`. There is not mention of support for `--name` and `--maintainer` flags even though they are supported.

    ```text
    tedge-apt-plugin

    USAGE:
        tedge-apt-plugin <SUBCOMMAND>

    OPTIONS:
        -h, --help    Print help information

    SUBCOMMANDS:
        finalize       Finalize a sequences of install/remove commands
        help           Print this message or the help of the given subcommand(s)
        install        Install a module
        list           List all the installed modules
        prepare        Prepare a sequences of install/remove commands
        remove         Uninstall a module
        update-list    Install or remove multiple modules at once
    ```

**Expected behavior**

* Requesting the `--help` of a subcommand should print out the usage of the subcommand and not that of the main command.
* The help should detail all of the available flags

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]: Debian 11
 - Hardware [incl. revision]: Docker running on aarch64
 - System-Architecture [e.g. result of "uname -a"]: 
 - thin-edge.io version [e.g. 0.1.0]: 0.12.0

**Additional context**

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.  
         /tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
- [x] QA has tested the feature and it meets the required specifications.
