### ISSUE TITLE
c8y-remote-access-plugin should support the --config-dir flag to allow for custom config directories

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2112]
**Is your feature improvement request related to a problem? Please describe.**

When using a custom tedge configuration directory, `c8y-remote-access-plugin` does not support running the `--init` option using the custom location.

For example if the user wants to create a custom folder to store the tedge configuration in (e.g. `/custom`), then they would create the initial folder structure using the new `tedge init` command included in 0.12.0:

```sh
tedge --config-dir /custom init
```

However, when trying to init `c8y-remote-access-plugin`, it does not support the `--config-dir` flag, meaning that it will create a file under `/etc/tedge/operations/c8y/c8y_RemoteAccessConnect` instead of the custom directory.

```sh
c8y-remote-access-plugin --init
```

**Describe the solution you'd like**

* `c8y-remote-access-plugin` should support the `--config-dir` flag to be able to specify the base tedge configuration directory (similar to the behaviour of the other tedge binaries, e.g. `tedge-agent`, `c8y-log-plugin`, `c8y-configuration-plugin` etc.).

**Describe alternatives you've considered**

**Additional context**

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the bug and could not reproduce it anymore.
