### ISSUE TITLE
disable file locking mechansim when lock directory does not exist or is not writable

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2131]
**Is your feature improvement request related to a problem? Please describe.**

The lock file mechanism used by some thin-edge.io components assumes there is always a `lock` folder under the `/run` path. This implicit requirement prevent the components from being able to start until the folder is created by some other process.

For example, the default `run.path` setting is `/run`, which means lock files are always placed under the `/run/lock/` directory. If the `/run` directory exists, but the `/run/lock` directory does not, then the tedge components which rely on the locking mechanism will fail to start with the following reason:

```text
$ tedge-agent

2023-08-06T07:40:47.166927176Z ERROR flockfile::unix: Lock file path: /run/lock/tedge-agent.lock
Error: Couldn't create file lock.

Caused by:
    No such file or directory (os error 2)
```

In addition, since the `/run` directory is typically a volatile one (e.g. it is not persisted across device reboots), then even if a process were to created the `/run/lock` directory, it would need to create it each time the device is rebooted.

This problem is most notably visible when using thin-edge.io in containers as some images (e.g. alpine linux) do not create a `/run/lock` directory (though `/run` does exist).

**Describe the solution you'd like**

The locking mechanism should be DISABLED in the following situations.

* If the configuration `run.lock_files` is set to `false` (this functionality is already implemented)
* If the `run.path` directory does not exist
* If the `{run.path}/lock` directory does not exist or is not writable

When the locking mechanism is disabled, a log entry (at INFO level) should be added to indicate that the locking mechanism is not active. This would help user's understand the behaviour of the system better.

**Describe alternatives you've considered**

An alternative solution would be to create the `lock` folder if it does not exist, however this would be lead to unpredictable behaviour as the logic to create the folder would have to exist in each tedge component which would lead to race conditions between the components. Whilst such race conditions might not have any adverse functional risks at first, it adds potential future pitfalls should the directory creation procedure change (e.g. change user/group ownership) during any kind of upgrade scenarios.

**Additional context**

**Comment by rina23q** [comment]
The first proposal described under "Describe the solution you'd like" is implemented by #2190.

**Comment by gligorisaev** [comment]
From QA perspective it is running as requested but, @reubenmiller we need to talk about it, I have not understand the point for this change

**Comment by didier-wenzek** [comment]
I got a [very suspicious error](https://github.com/thin-edge/thin-edge.io/actions/runs/6039298596/job/16387985890?pr=2108), that is more than likely related to this change.

<h3 dir="auto">Failed Tests</h3>


Name | Message | ⏱️ Duration | Suite
-- | -- | -- | --
Check PID number in lock file after restarting the services | 1262 1290 != 1262 | 2.607 s | Lock File


Meaning that the process with `pid = 1290` managed to write in the lock file *without* acquiring the lock owned by the process with `pid = 1262`.

@reubenmiller Ignoring some errors while acquiring a lock is a source of complications. Is this a good idea as there is already a setting to disable locks (`run.lock_files = false`)?

**Comment by didier-wenzek** [comment]
The new issue with lock is quite frequent: https://github.com/thin-edge/thin-edge.io/actions/runs/6051803835/job/16424280837

**Comment by reubenmiller** [comment]
> The new issue with lock is quite frequent: https://github.com/thin-edge/thin-edge.io/actions/runs/6051803835/job/16424280837

Actually this test has been flakey (for reasons unknown) for a while, even before the lock file handling was changed. There is an open ticket already for it (https://github.com/thin-edge/thin-edge.io/issues/2087)

**Comment by reubenmiller** [comment]
> From QA perspective it is running as requested but, @reubenmiller we need to talk about it, I have not understand the point for this change

The reason for the change is that not all devices have a `/run/lock` folder, so the absence of the folder resulted in blocking all services (which use a locking file) from working. So it was counter intuitive for a locking mechanism which should prevent multiple services of the same process from running results in 0 services from starting.

And since the `/run/lock` folder is more like an operating system level folder, tedge should NOT create that folder as this could cause other problems to other non-tedge components if we don't create the folder with the expected permissions etc (e.g. `0777` vs. `1777`).

And the value of the locking mechanism is becoming less important when we talk about distributed components, where they don't share the same file system which bypasses the whole locking mechanism.

**Comment by didier-wenzek** [comment]
> And the value of the locking mechanism is becoming less important when we talk about distributed components, where they don't share the same file system which bypasses the whole locking mechanism.

Sure, file-based locking makes less and less sense for the thin-edge daemons. In order to prevent two processes running using the same MQTT session name, we need to find another tactic.
