### ISSUE TITLE
c8y-remote-access cannot start child-process if the bin is located in /usr/bin

### ISSUE THREAD

**Issue by toewsar** [thin-edge/thin-edge.io#2132]
**Describe the bug**
The c8y-remote-access-plugin ist called by the mapper according to the command in the `c8y_RemoteAccessConnect` file.
By default the file contains:
```toml
[exec]
command = "/usr/bin/c8y-remote-access-plugin"
topic = "c8y/s/ds"
on_message = "530"
``` 
But if the binary is not located in `/usr/bin` the execution fails, because the plugin tries to start the hardcoded child process `/usr/bin/c8y-remote-access-plugin`.

**To Reproduce**
Shift `/usr/bin/c8y-remote-access-plugin` to e.g. `~/.local/bin` and adopt `/etc/tedge/operations/c8y/c8y_RemoteAccessConnect`.
If you will now try to connect from c8y the `c8y-remote-access-plugin` will fail.

**Expected behavior**
The `c8y-remote-access-plugin` should use internaly the same path as used to call itself.

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [e.g. 0.1.0]

**Additional context**

**Comment by reubenmiller** [comment]
@toewsar Yes you're right. I didn't think this was the case, but I can confirm that path to the `c8y-remote-access-plugin` is NOT being read from `/etc/tedge/operations/c8y/c8y_RemoteAccessConnect`.

Here is the offending line: [c8y_remote_access_plugin/src/main.rs](https://github.com/thin-edge/thin-edge.io/blob/ab4e0787daf7344c0d7c99644b117b7085bc4d3e/plugins/c8y_remote_access_plugin/src/main.rs#L99)

```rust
let mut command = tokio::process::Command::new("/usr/bin/c8y-remote-access-plugin")
```

It should be an easy fix though.

**Comment by didier-wenzek** [comment]
Addressed with https://github.com/thin-edge/thin-edge.io/pull/2277

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the bug and could not reproduce it anymore.
