### ISSUE TITLE
tedge legacy health messages are not being republished on the te/ topic with the retained flag

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2147]
**Describe the bug**

Messages published on `tedge/health/#` topic are not being republished to the `te/` topic with the retained flag.

**To Reproduce**

1. Assuming all of the thin-edge.io packages have been installed, then stop all of the services.

    ```sh
    sudo systemctl stop \
        tedge-mapper-c8y \
        tedge-agent \
        c8y-configuration-plugin \
        c8y-log-plugin \
        c8y-firmware-plugin
    ```

2. Clear the retained messages

    ```sh
    sudo systemctl stop tedge-agent
    sudo systemctl stop c8y-configuration-plugin

    mosquitto_pub -n -r -t 'tedge/health/c8y-configuration-plugin'
    mosquitto_pub -n -r -t 'te/device/main/service/c8y-configuration-plugin/status/health'
    ```

3. Open a new console, and subscribe to a the following topics (legacy and v1)

    ```sh
    mosquitto_sub \
        -t 'tedge/health/c8y-configuration-plugin' \
        -t 'te/device/main/service/c8y-configuration-plugin/status/health' \
        -F '%t\t%r\t%p'
    ```

4. Start the tedge-agent service

    ```sh
    sudo systemctl start tedge-agent
    ```

5. Start the c8y-configuration-plugin

    ```sh
    sudo systemctl start c8y-configuration-plugin
    ```

    In the mosquitto_sub console, you should see two messages which should match (except for the topic name)

    ```
    tedge/health/c8y-configuration-plugin	0	{"pid":6820,"status":"up","time":1691686145}
    te/device/main/service/c8y-configuration-plugin/status/health	0	{"pid":6820,"status":"up","time":1691686145}
    ```

6. Stop the mosquitto client (using ctrl+c), then resubscribe to the same topics (as the health messages should be retained)

    After resubscribing to the topics, it is expected that the same two messages from the previous step appear.

    However with the bug, the message published on the new health check topic is not retained, so it does not appear in the subscription list.

    ```sh
    tedge/health/c8y-configuration-plugin	1	{"pid":6820,"status":"up","time":1691686145}
    ```

    **Notes*

    For some reason restarting tedge-agent causes the messages to be sent correctly as retained messages.

**Expected behavior**

Messages which are published with the retain flag on the legacy (`tedge/`) topic are republished to the new v1 topic with the retain flag.

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]: `Debian 11`
 - Hardware [incl. revision]: `Raspberry Pi Zero 2 W`
 - System-Architecture [e.g. result of "uname -a"]: `Linux pippin 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
 - thin-edge.io version [e.g. 0.1.0]: `0.12.1~66+g1fca0d9c`

**Additional context**

**Comment by didier-wenzek** [comment]
This is caused by the behavior of retained messages.

1. As explained in [this comment](https://github.com/thin-edge/thin-edge.io/pull/2122#discussion_r1288719427), a client receives the retained messages with the flag properly set retained *only when the subscription is new*.
2. But (in the current settings), `tedge-agent` publishes translated messages without touching the retained flag (assumed that it is set).
3. Hence, the health messages are (incorrectly) published without the retained flag on the new `te/device/main/service/+/status/health` *except* when `tedge-agent` starts.

The fix is simple:
- force the retained flag for messages published on   `te/device/main/service/+/status/health`
- do the same for alarms published on `te/device/main/+/+/a/+`.

**Comment by PradeepKiruvale** [comment]
>    *_Notes_
>    For some reason restarting tedge-agent causes the messages to be sent correctly as retained messages.

I feel when the `tedge-agent` is restarted, the tedge-agent will receive the retain message from the `tedge/health` topic and converts and sends it on to `the` topic, that's the reason why the `health status` will be visible on `the` topic.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.  
         /tests/RobotFramework/tests/tedge_to_te_converter/convert_tedge_topics_to_te_topics.robot
- [x] QA has tested the feature and it meets the required specifications.
