### ISSUE TITLE
Clearing an alarm causes an EOL error

### ISSUE THREAD

**Issue by toewsar** [thin-edge/thin-edge.io#2151]
**Describe the bug**
If clear an alarm according to the [docs](https://thin-edge.github.io/thin-edge.io/start/raise-alarm/#clearing-alarms) I receive a `tedge/error`.

**To Reproduce**

1. Clear the alarm:
```shell
mosquitto_pub -r -q 2 -t 'tedge/alarms/critical/temperature_alarm' -m ''
```

2. Watch the MQTT bus:
```shell
tedge/alarms/critical/temperature_alarm (null)
c8y/s/us 306,temperature_alarm
c8y-internal/alarms/critical/temperature_alarm (null)
tedge/errors EOF while parsing a value at line 1 column 0
```

**Expected behavior**
I would expect no error.

**Screenshots**

**Environment (please complete the following information):**
 - thin-edge.io version 0.12.0

**Additional context**

**Comment by didier-wenzek** [comment]
This is due to the converter recently introduced to convert messages [from the old topics to the new ones](https://github.com/thin-edge/thin-edge.io/issues/2079).

This converter wrongly try to insert a severity in the empty message.

@PradeepKiruvale I think the simpler to fix that issue (and to prevent other similar issues) is to simply copy the alarm messages unchanged from `tedge/#` to `te/#` when the severity cannot be inserted.

**Comment by PradeepKiruvale** [comment]
> This is due to the converter recently introduced to convert messages [from the old topics to the new ones](https://github.com/thin-edge/thin-edge.io/issues/2079).
> 
> This converter wrongly try to insert a severity in the empty message.
> 
> @PradeepKiruvale I think the simpler to fix that issue (and to prevent other similar issues) is to simply copy the alarm messages unchanged from `tedge/#` to `te/#` when the severity cannot be inserted.

What happens when there is an issue with the topic itself? For example, if the `alarm/event type` is missing/empty then one must throw an error or not.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.  
         /tests/RobotFramework/tests/tedge_to_te_converter/convert_tedge_topics_to_te_topics.robot
- [x] QA has tested the feature and it meets the required specifications.
