### ISSUE TITLE
change tedge mosquitto configuration file permissions from 600 to 644

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2154]
**Is your feature improvement request related to a problem? Please describe.**

Running mosquitto as a non-root user is not possible as the tedge mosquitto files under `/etc/tedge/mosquitto-conf/*.conf` are only readable by the root user (e.g. the files have the permission `0o0600`). Changing the tedge mosquitto configuration files to `0o0644` would fix this, and it would also align the file permissions to those used by the `/etc/mosquitto/mosquitto.conf`.

Below shows the difference between the tedge and mosquitto configuration files.

*tedge configuration files*

```
$ ls -l /etc/tedge/mosquitto-conf/
total 8
-rw------- 1 root root 1149 Jul 19 16:07 c8y-bridge.conf
-rw------- 1 root root  261 Jul 19 15:58 tedge-mosquitto.conf
```

*tedge configuration files*

```
$ ls -l /etc/mosquitto/mosquitto.conf
-rw-r--r-- 1 root root 392 Jun 27 22:07 /etc/mosquitto/mosquitto.conf
```

**Describe the solution you'd like**

Change the file permissions from `0o0600` to `0o0644` for all files created under the `/etc/tedge/mosquitto-conf/` directory.

**Describe alternatives you've considered**

**Additional context**

**Comment by didier-wenzek** [comment]
I would consider to do this along https://github.com/thin-edge/thin-edge.io/issues/2012

**Comment by reubenmiller** [comment]
The implementation was done exactly as described in the ticket description.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite. 
- [x] QA has tested the feature and it meets the required specifications.

**Comment by reubenmiller** [comment]
This issue was only partially closed. The `c8y-bridge.conf` file still need to have its permissions set to `644` instead of `600` to allow non-root users to read it.

A PR was opened to included system tests to verify this functionality. https://github.com/thin-edge/thin-edge.io/pull/2334
