### ISSUE TITLE
use MQTT clean session for the mosquitto c8y bridge connection

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2159]
**Is your feature improvement request related to a problem? Please describe.**

The [Cumulocity Iot guide](https://cumulocity.com/guides/device-integration/mqtt/#mqtt-clean-session) on the MQTT clean sessions indicates the a clean session should always be used. Having the sessions persisted in the platform is not required as Cumulocity uses the `500` static smart rest message to request any pending operations in the platform, so it does not rely on the MQTT session persistence for reliable communication with the platform.

**Describe the solution you'd like**

In the Cumulocity IoT (c8y) mosquitto bridge connection, the following settings should be used:

```text
cleansession true
local_cleansession false
```

See the [official mosquitto docs](https://mosquitto.org/man/mosquitto-conf-5.html) for a description of the settings.

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite. 
- [x] QA has tested the feature and it meets the required specifications.
