### ISSUE TITLE
Requesting a Cumulocity IoT token not returning a response on newly connected device

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2167]
**Describe the bug**

Publishing to the Cumulocity IoT `c8y/s/uat` topic sometimes does not return a Token published to `c8y/s/dat`.

**To Reproduce**

**Pre-requisites**

Before running the steps, you need to make sure that device's identity, managed object, device credential are removed from Cumulocity. When in double please use a randomized/unique device id

If you want to use purge an existing device id then you can run the following go-c8y-cli command (where you should update)

```sh
DEVICE_ID=rmi_helloworld
c8y identity get --name "$DEVICE_ID" | c8y devices delete --cascade
c8y users delete --id "device_$DEVICE_ID"
c8y devicemanagement certificates list --filter "name like $DEVICE_ID" -p 2000 | c8y devicemanagement certificates delete
```

1. Create a device certificate, but don't upload the cert to Cumulocity IoT. This will result in the c8y bridge not being able to connect
2. Let all other tedge components run for a while (to let them request tokens), > 2 minutes
3. Upload the device certificate to Cumulocity IoT
4. Observe that the requests to `c8y/s/uat` don't return a c8y token
5. Restart mosquitto, and observe that subsequent requests to `c8y/s/uat` topic return a response on the `c8y/s/dat` topic.

**Expected behavior**

After a device certificate is uploaded to Cumulocity, subsequent c8y token requests should be successful without having to restart mosquitto.

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]: `Alpine linux (3.18)`
 - Hardware [incl. revision]: `Docker (aarch64)`
 - System-Architecture [e.g. result of "uname -a"]: `Linux 908d8708d400 5.15.68-0-virt #1-Alpine SMP Fri, 16 Sep 2022 06:29:31 +0000 aarch64 Linux`
 - thin-edge.io version [e.g. 0.1.0]: `0.12.1~99+g3e0fe253`

**Additional context**

Below shows the mosquitto message which shows that publishing to `c8y/s/uat` is not returning a response on `c8y/s/dat` despite the c8y bridge being connected (e.g.  `[tedge/health/mosquitto-c8y-bridge] 1`).

```text
# tedge mqtt sub '#'
INFO: Connected
[tedge/health/mosquitto-c8y-bridge] 1
[tedge/health/tedge-mapper-az] {"pid":139,"status":"up","time":1692352254}
[tedge/health/tedge-mapper-c8y] {"pid":143,"status":"up","time":1692352254}
[tedge/health/c8y-firmware-plugin] {"pid":160,"status":"up","time":1692352254}
[tedge/health/tedge-agent] {"pid":146,"status":"up","time":1692352254}
[tedge/health/tedge-mapper-aws] {"pid":141,"status":"up","time":1692352254}
[tedge/health/c8y-configuration-plugin] {"pid":157,"status":"up","time":1692352254}
[tedge/health/tedge-mapper-collectd] {"pid":133,"status":"up","time":1692352254}
[tedge/health/c8y-log-plugin] {"pid":155,"status":"up","time":1692352254}
[te/device/main/service/mosquitto-c8y-bridge/status/health] 1
[te/device/main/service/tedge-mapper-az/status/health] {"pid":139,"status":"up","time":1692352254}
[te/device/main/service/tedge-mapper-c8y/status/health] {"pid":143,"status":"up","time":1692352254}
[te/device/main/service/c8y-firmware-plugin/status/health] {"pid":160,"status":"up","time":1692352254}
[te/device/main/service/tedge-agent/status/health] {"pid":146,"status":"up","time":1692352254}
[te/device/main/service/tedge-mapper-aws/status/health] {"pid":141,"status":"up","time":1692352254}
[te/device/main/service/c8y-configuration-plugin/status/health] {"pid":157,"status":"up","time":1692352254}
[te/device/main/service/tedge-mapper-collectd/status/health] {"pid":133,"status":"up","time":1692352254}
[te/device/main/service/c8y-log-plugin/status/health] {"pid":155,"status":"up","time":1692352254}
[c8y/s/uat] 
[c8y/s/uat] 
[c8y/s/uat] 
[c8y/s/uat] 
[c8y/s/uat] 
[c8y/s/uat] 
[c8y/s/uat] 
[c8y/s/uat] 
[c8y/s/uat] 
[c8y/s/uat] 
[c8y/s/uat] 
[c8y/s/uat]
```

**Comment by reubenmiller** [comment]
I should qualify this ticket after doing a bit more digging...This mentioned behaviour occurs when the device has not been registered before the bridge is connected for the first time. If the device is registered prior to the creation of the bridge then everything works as expected.

The registration of the device is done via the `tedge connect c8y` command, however the command does not only pre-register the device, it also creates the bridge config, restarts mosquitto, etc. In a container environment, the other steps are not desired as generally the broker won't be running under an init system, and the bridge configuration generally will exist already.

I'm doing some more research into possible solutions for the container scenario to make the process easier and more transparent.

**Comment by didier-wenzek** [comment]
Unfortunately, this is a design bug. The jwt token is given by the c8y mapper to the agent. If the token expires before being used, then the agent has no way to refresh it.

The solution proposed for the [`tedge-configuration-plugin`](https://thin-edge.github.io/thin-edge.io/next/references/c8y-configuration-management/) is to give to the c8y mapper the responsibility to download the files. The same approach can be used for software updates. The agent will only have to operate local files.

**Comment by reubenmiller** [comment]
This is related to https://github.com/thin-edge/thin-edge.io/issues/2412 and has already been solved by publishing with QoS 0
