### ISSUE TITLE
Avoid subscribing to Cumulocity IoT s/dcr topic

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2168]
**Is your feature improvement request related to a problem? Please describe.**

`s/dcr` and `s/ucr` topics are reserved for non-certificate based device registration. Since thin-edge.io only supports certificated based connection to Cumulocity IoT, these topics should not be used in the Cumulocity IoT bridge configuration.

**Describe the solution you'd like**

* Don't subscribe to the `s/dcr` topic in the Cumulocity bridge configuration
* Don't forward message to `s/ucr`.

**Describe alternatives you've considered**

**Additional context**

**Comment by reubenmiller** [comment]
This can be verified by:

1. Recreating the c8y cloud connection (mosquitto bridge), via `sudo tedge reconnect c8y`
2. Verify that `/etc/tedge/mosquitto-conf/c8y-bridge.conf` does not contain the topics `s/dcr` and `s/ucr`

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite. 
- [x] QA has tested the feature and it meets the required specifications.
