### ISSUE TITLE
tedge connect c8y --test returns exit code 0 when mosquitto is not running

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2170]
**Describe the bug**

The `tedge connect c8y --test` command returns an exit code of `0` though mosquitto is not running and therefore can't be successful.

**To Reproduce**

1. Connect thin-edge.io to Cumulocity IoT

    ```sh
    sudo tedge connect c8y
    ```

2. Check that the connection is ok

    ```sh
    sudo tedge connect c8y --test
    ```

3. Stop the mosquitto service

    ```sh
    sudo systemctl stop mosquitto
    ```

4. Check that the connection, the exit code should not be 0, as 0 represents no error

    ```sh
    sudo tedge connect c8y --test
    echo $?
    ```

**Expected behavior**

The command `tedge connect c8y --test` is a test to see if something is working or not, so it should follow the process convention that a non-zero exit code when the test is not successful.

Only use an exit code 0, if the Cumulocity test/check was successful.

**Screenshots**

The following shows the console output from the check.

```sh
$ sudo tedge connect c8y --test
The system config file '/etc/tedge/system.toml' doesn't exist. Use '/bin/systemctl' as a service manager.

Sending packets to check connection. This may take up to 2 seconds.

ERROR: Io(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })

Make sure mosquitto is running.
Connection check to Cumulocity cloud failed.

reubenmiller@lumber:~ $ echo $?
0
```

**Environment (please complete the following information):**
 - OS [incl. version]: `Debian 11`
 - Hardware [incl. revision]: `Raspberry Pi 4`
 - System-Architecture [e.g. result of "uname -a"]: `Linux lumber 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
 - thin-edge.io version [e.g. 0.1.0]: `0.12.1~82+gfefb27f7`

**Additional context**

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite. 
- [x] QA has tested the feature and it meets the required specifications.
