### ISSUE TITLE
`/bin/sh: 1: robot: not found` when running integration tests

### ISSUE THREAD

**Issue by Bravo555** [thin-edge/thin-edge.io#2187]
**Describe the bug**

When running the integration test suite via `just integration-test`, If I haven't activated the python virtual environment, importing the `robot` module fails.

**To Reproduce**

1. Navigate into `tests/RobotFramework` directory.
2. Ensure that `tests/RobotFramework/.venv` directory does not exist, so that `tests/RobotFramework/bin/setup.sh` scripts recreates it from scratch.
3. Run `bin/setup.sh`
4. Run `just integration-test` without having activated the environment via `. .venv/bin/activate`
5. Immediately after starting, all the test suites quit with an error message: `/bin/sh: 1: robot: not found`

**Expected behavior**

The test suite runs with `robot` imported correctly, as the virtual environment have the package installed.

**Screenshots**

**Environment (please complete the following information):**
 - OS `thin-edge development container Debian GNU/Linux 11 (bullseye)`
 - System-Architecture `Linux 1f863c4572b5 6.2.0-27-generic #28-Ubuntu SMP PREEMPT_DYNAMIC Wed Jul 12 22:39:51 UTC 2023 x86_64 GNU/Linux`
 - thin-edge.io version `0.11`

**Additional context**

Running the test suite works if I activate `.venv` beforehand. I suspect that running `.venv/bin/python3 -m invoke build --local tests {{ARGS}}` doesn't update the paths correctly for some reason.

So looking at the log of `invoke test`, the command that launches the test suite is:

```
/workspace/tests/RobotFramework/.venv/bin/python3 -m pabot.pabot --processes 10 --outputdir /workspace/tests/RobotFramework/output --listener RetryFailed:0 --consolecolors on --consolemarkers on tests
```

It launches `pabot` which is a python script which is located at `.venv/bin/pabot`. `robot` is also at `.venv/bin/robot`, but for some reason `pabot` or one of its spawned processes doesn't look for `robot` inside that directory.

Launching `pabot` directly with `--verbose` flag: `pabot --verbose tests`

It prints the following:

```
Suite names resolved in 0.0058362483978271484 seconds
2023-08-24 10:35:29.586077 [PID:35185] [2] [ID:8] EXECUTING PARALLEL Tests.Cumulocity.Jwt.Jwt Request with command:
robot --suite 'Tests.Cumulocity.Jwt.Jwt Request' --variable CALLER_ID:f1389fa3808042209bfaade6891d1af8 --variable PABOTLIBURI:127.0.0.1:8270 --variable PABOTEXECUTIONPOOLID:2 --variable PABOTISLASTEXECUTIONINPOOL:0 --variable PABOTNUMBEROFPROCESSES:12 --variable PABOTQUEUEINDEX:8 --variable PABOTLASTLEVEL:Tests.Cumulocity.Jwt --listener RobotStackTracer --log NONE --report NONE --xunit NONE --outputdir ./pabot_results/8 --consolecolors off --consolemarkers off tests
```

So it tries to launch a `robot` process relying on `$PATH` to discover `robot`, but as we haven't activated the virtual environment, it's not able to find `robot` and it fails.

I think the best solution would be to just revert to previous `integration-test` recipe in `justfile`, where virtual environment was activated. If we have packages that besides importing from libraries also try to spawn processes and rely on the environment variables like $PATH, then just to be sure we should activate the virtual environment.

**Comment by reubenmiller** [comment]
I'll make the required adjustments
