### ISSUE TITLE
sm-plugin packages are not published to c8y in a consistent/stable order

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2199]
**Describe the bug**

The package listed generated by multiple sm-plugins are not published to Cumulocity in a stable order, for example if you have two sm-plugins called dummy1 and dummy2, sometimes the dummy1 packages appear before dummy2, and sometimes the other way around.

**To Reproduce**

1. Create multiple dummy plugins (use the code in the "Dummy plugin script" section)
    * /etc/tedge/sm-plugins/dummy1
    * /etc/tedge/sm-plugins/dummy2
2. Restart the tedge-mapper-c8y service
3. Check the list of software in Cumulocity Software tab (repeat >5 times to see if the packages for each plugin are always in the same order)

**Dummy plugin script**

```sh
#!/bin/bash
NAME="$(basename "$0")"
case "$1" in
  list)
      for i in {1..1500}; do
          printf '%s-%04g\t1.0.0\n' "$NAME" "$i"
      done
      exit 0
      ;;
  prepare)
      exit 0
      ;;
  update-list)
      exit 0
      ;;
  finalize)
      exit 0
      ;;
  *)
     exit 0
     ;;
esac
```

**Expected behavior**

The sm-plugins should be uploaded in a consistent order. The plugins should be executed in order based on an alphabetical sorting within the `/etc/tedge/sm-plugins` folder, e.g. `dummy1` should be processed before `dummy2`.

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]: `Debian 11`
 - Hardware [incl. revision]: `rpi 4`
 - System-Architecture [e.g. result of "uname -a"]: `aarch64`
 - thin-edge.io version [e.g. 0.1.0]: `0.12.1~168+g11b23a3`

**Additional context**

The problem seems to occur because the code is iterating over a hashmap which results in an undefined order.

The hash map is defined here:
[plugin_map: HashMap::new(),](https://github.com/reubenmiller/thin-edge.io/blob/11b23a36f84f5dd752cd942ed29bcb93d3d92614/crates/core/plugin_sm/src/plugin_manager.rs#L105)

And then iterated over here:
[for (software_type, plugin) in self.plugin_map.iter() {](https://github.com/reubenmiller/thin-edge.io/blob/11b23a36f84f5dd752cd942ed29bcb93d3d92614/crates/core/plugin_sm/src/plugin_manager.rs#L235)

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite. 
- [x] QA has tested the feature and it meets the required specifications.
