### ISSUE TITLE
too many packages are returned by sm-plugin handler

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2200]
**Describe the bug**

1 too many packages are returned by the sm-plugins processing when using the `software.plugin.max_packages` tedge setting. For example if set to `5`, then `6` packages are returned (where as the expected value is 5).

**To Reproduce**

Note, there is a PR which includes an integration test for this, so you can add the fix to [this PR](https://github.com/thin-edge/thin-edge.io/pull/2197).

1. Create a custom sm-plugin in (`/etc/tedge/sm-plugins/dummy1`) using the code below under the "Dummy sm-plugin"

2. Set the max packages to 5

    ```sh
    sudo tedge config set software.plugin.max_packages 5
    ```

3. Reconnect the tedge mapper

    ```sh
    sudo tedge reconnect c8y
    ```

4. Observe the total software packages for the dummy1 plugin in the Software tab in the Device Management UI in Cumulocity IoT.

**Dummy sm-plugin**

```sh
#!/bin/bash
NAME="$(basename "$0")"
case "$1" in
  list)
      for i in {1..1500}; do
          printf '%s-%04g\t1.0.0\n' "$NAME" "$i"
      done
      exit 0
      ;;
  prepare)
      exit 0
      ;;
  update-list)
      exit 0
      ;;
  finalize)
      exit 0
      ;;
  *)
     exit 0
     ;;
esac
```

**Expected behavior**

Per sm-plugin, the total packages published should be less than or equal to the `software.plugin.max_packages` value.

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]: `Debian 11`
 - Hardware [incl. revision]: `rpi 4`
 - System-Architecture [e.g. result of "uname -a"]: `aarch64`
 - thin-edge.io version [e.g. 0.1.0]: `0.12.1~168+g11b23a3`

**Additional context**

The problem is caused by:

[crates/core/plugin_sm/src/plugin.rs#L458](https://github.com/thin-edge/thin-edge.io/blob/11b23a36f84f5dd752cd942ed29bcb93d3d92614/crates/core/plugin_sm/src/plugin.rs#L458]

```rust
.nth(usize::try_from(self.max_packages).unwrap_or(usize::MAX))
```

It should be max_packages minus 1 (as `.nth` uses a zero based index)

```rust
.nth(usize::try_from(self.max_packages - 1).unwrap_or(usize::MAX))
```

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite. 
   tests/RobotFramework/tests/cumulocity/software_management/sm-plugin.robot 
- [x] QA has tested the feature and it meets the required specifications.
