### ISSUE TITLE
Create an integration test for c8y-remote-access-plugin

### ISSUE THREAD

**Issue by Bravo555** [thin-edge/thin-edge.io#2201]
When making a change to `c8y-remote-access-plugin` to remove `webpki` dependency in #2185, a regression was manually caught. To reproduce:

1. [feature `tokio-rustls-native-certs` was disabled which resulted in TLS support being disabled](https://github.com/thin-edge/thin-edge.io/pull/2185/files#r1308444194)
2. Modified `c8y-remote-access-plugin` replaced the original binary in `/usr/bin/c8y-remote-access-plugin`
3. Initiate a remote connection from Cumulocity. Any parameters should trigger the error, but what I used was:
    - **Protocol**: SSH
    - **Sign-in method**: Username and password
    - **Host**: 127.0.0.1
    - **Port**: 22

**Expected**: Remote connection is successfully created, prompt is displayed and one can invoke commands.

**Observed**:

- remote access terminal window printed the following message:
  
  ```text
  Device disconnected.  
  
  Websocket connection was closed.
  ```

- the following was published on the MQTT broker:

```
[c8y/s/us] 502,c8y_RemoteAccessConnect,"

Error:   × Connecting to Websocket
  ├─▶ URL error: TLS support not compiled in
  ╰─▶ TLS support not compiled in

"
```

This seems like it could be easily caught by an automated integration test, but no such test existed for `c8y-remote-access-plugin`, so it should be created.

The challenging portion is that remote connections are initiated by Cumulocity and the plugin needs to verify Cumulocity's TLS certificate.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- [x] QA has tested the function and it's functioning according
