### ISSUE TITLE
`tedge connect c8y --test` returns exit code 0 when network is unreachable

### ISSUE THREAD

**Issue by dtimotijevic** [thin-edge/thin-edge.io#2207]
**Describe the bug**
The tedge connect c8y --test command returns an exit code of 0 when the network interface is not reachable, despite the standard output and standard error indicating a failed connection check to Cumulocity cloud. According to the documentation, the exit code should be 1 if the connection check is unsuccessful.

**To Reproduce**
1. Ensure that the used network interface is up.
2. Run the command tedge connect c8y. 
3. Bring down the network interface `sudo up link set wlan down` or just disconnect your network cable.
4. Run the command `tedge connect c8y --test.`
5. Observe the standard output and standard error.
6. Check the exit code by running `echo $?` immediately after executing the `tedge connect c8y --test` command.

**Expected behavior**
If the connection check to Cumulocity cloud fails, as indicated by the standard output and standard error messages, the exit code returned by `tedge connect c8y --test` should be 1, as per the documentation.

**Screenshots**
![Screenshot 2023-09-01 093741](https://github.com/thin-edge/thin-edge.io/assets/43826338/0fdc3a7a-5755-4813-8726-c6a485c9c464)

**Environment (please complete the following information):**
 - OS [incl. version]: `Raspbian GNU/Linux 11 (bullseye)`
 - Hardware [incl. revision]: `Raspberry Pi 4 Model B Rev 1.5`
 - System-Architecture: `Linux 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
 - thin-edge.io version: `tedge 0.11.0`

**Additional context**
This issue is critical because automation scripts that rely on the exit code to determine the connection state will be misinformed, potentially leading to undetected issues in system health.

**Comment by dtimotijevic** [comment]
Also reproduced with tedge version `0.12.0`.

**Comment by didier-wenzek** [comment]
This has been fixed - but not released yet, by https://github.com/thin-edge/thin-edge.io/issues/2170.

@gligorisaev can you double check that this is indeed the case. Thanks.

**Comment by didier-wenzek** [comment]
That said, testing it myself I found another issue.

`tedge connect test --c8y` returns false positive when jwt tokens have been published since the previous connection test. The connection check is done using a persistent MQTT subcription. It must not.

=> I will push a fix for that.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite. 
- [x] QA has tested the feature and it meets the required specifications.

**Comment by dtimotijevic** [comment]
Thank you for resolving this. When are you planning to release 0.13?

**Comment by reubenmiller** [comment]
0.13.0 should drop by end of next week (2023-09-22)
