### ISSUE TITLE
Events for c8y  are consumed from `te/+/+/+/+/e/+`

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#2214]
c8y-mapper should consume `te/+/+/+/+/e/+` instead of `tedge/events/+` or `tedge/events/+/+`. 
It is a subtask of #2082.

The setting of the event type should be set as per the following order of precedence (stopping at the first non-empty value).

1. From the `type` property of the MQTT message payload
2. From the topic
3. From the default value (ThinEdgeEvent)

Note: User can still use `tedge/events/<type>` and `tedge/events/<type>/<child>` topics, thanks to #2125, `tedge-agent` converts `tedge/events/...` topics to `te/.../e/...` topics.

**Comment by reubenmiller** [comment]
Ideally the setting of the event type should also follow a similar pattern as used by the measurement topic.

https://github.com/thin-edge/thin-edge.io/issues/2215#issuecomment-1706351798

**Comment by rina23q** [comment]
> Ideally the setting of the event type should also follow a similar pattern as used by the measurement topic.
> 
> [#2215 (comment)](https://github.com/thin-edge/thin-edge.io/issues/2215#issuecomment-1706351798)

What is the expected behaviour when user adds `type` field (without dot) in payload? An error? Ignore it?

**Comment by rina23q** [comment]
Resolved by #2221.

The next step is to simplify the user experience as commented https://github.com/thin-edge/thin-edge.io/pull/2221#discussion_r1317499361. As of now, depending on the given fields in the message payload, c8y-mapper converts the message to either SmartREST or JSON over MQTT. We will convert event messages only to JSON over MQTT. The reason is to make the string validatiton much easier. CSV-like style requires more validation, like a string containing `,`, `"`.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite. 
- tests/RobotFramework/tests/cumulocity/telemetry/child_device_telemetry.robot
- tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
- tests/RobotFramework/tests/mqtt/custom_sub_topics_tedge-mapper-c8y.robot
- tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
- [x] QA has tested the feature and it meets the required specifications.
