### ISSUE TITLE
Forward measurement type to c8y

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#2215]
When a measurement is received by the c8y mapper on a topic `te/+/+/+/+/m/<measurement-type>`, the suffix is to be used as the [measurement type](https://github.com/thin-edge/thin-edge.io/issues/770).
- If the message provides a `type`, then this type is used instead of the type provided by the topic.
- If the topic suffix is the empty string and the message doesn't provide a `type`, then `"ThinEdgeMeasurement"` is used as a default.

**Comment by reubenmiller** [comment]
The setting of the measurement type should be set as per the following order of precedence (stopping at the first non-empty value).

1. From the `.type` property of the MQTT message payload
2. From the topic name
3. From the default value defined in the tedge.toml file (e.g. ThinEdgeMeasurement)

The reason behind supporting the value being set in the MQTT message body, as it allows users to provide a way to rename a type without breaking any devices which currently subscribe to that specific topic on the local MQTT bus. Typically this will only be done by advanced users, however it offers a powerful tool to potentially decouple the MQTT topic type to the topic type which is published to the cloud. Yes this could add a bit of "confusion", but it will only be for select use-cases.

**Comment by rina23q** [comment]
@reubenmiller I have two questions:
1. What is the expected behaviour when user adds not nested `type` field (withiout dot) like `{"type": "payload type"}`? An error? Ignore it?
2. In entity store, the reserved keywords is marked with `@`. Do you want to use `.` for telemetry?

**Comment by reubenmiller** [comment]
> @reubenmiller I have two questions:
> 
> 1. What is the expected behaviour when user adds not nested `type` field (withiout dot) like `{"type": "payload type"}`? An error? Ignore it?

No I meant that the property name is called `type` not (`.type`). Using `.type` is just common dot-notation nomenclature.

> 2. In entity store, the reserved keywords is marked with `@`. Do you want to use `.` for telemetry?
Not applicable, see first comment.

**Comment by didier-wenzek** [comment]
This has been implemented as described by https://github.com/thin-edge/thin-edge.io/pull/2219

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite. 
- tests/RobotFramework/tests/cumulocity/telemetry/child_device_telemetry.robot
- tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
- [x] QA has tested the feature and it meets the required specifications.
