### ISSUE TITLE
Update tedge-agent to work with new topics

### ISSUE THREAD

**Issue by Bravo555** [thin-edge/thin-edge.io#2223]
**Is your refactoring request related to a problem? Please describe.**

Currently tedge-agent contains a `tedge_to_te_converter`, which republishes messages from the old topic scheme into the new topic scheme.
However, it still uses old topics internally:

https://github.com/thin-edge/thin-edge.io/blob/5546ee912152243e93871fae36d1c359e3aa37c9/crates/core/tedge_agent/src/tedge_operation_converter/actor.rs#L73-L97

To be able to expand tedge-agent to work on child devices, as well as in scenarios where the main device MQTT topic identifier is different from the default scheme, it's necessary to make tedge-agent work with our [new topic scheme](https://thin-edge.github.io/thin-edge.io/next/references/mqtt-api) internally.

**Describe the solution you'd like**

To be able to generate and work with topics under the new MQTT topic scheme, tedge-agent needs to use `tedge_api/mqtt_topics` API. This results in the following improvements:

- removal of obsolete topic scheme
- separation of an identifier and a channel, in `tedge-agent` we define only `channel`-portion of the topic, and the agent can therefore work with any identifier out of the box
- we don't have to handle variable MQTT root; it's only setup once, and the rest is handled by `tedge_api::mqtt_topics::MqttSchema`
- all the MQTT parsing logic moved to `tedge_api`

**Describe alternatives you've considered**

I don't think there is any, it has to be done sooner or later.

**Additional context**

**Comment by reubenmiller** [comment]
@didier-wenzek Can you please verify that we can close this ticket and also link to the related PR/issue?

**Comment by didier-wenzek** [comment]
This has been addressed with https://github.com/thin-edge/thin-edge.io/pull/2307.
