### ISSUE TITLE
tedge-mapper-aws prints errors for known non-json mosquitto bridge health status messages

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2236]
**Describe the bug**

The tedge-mapper-aws service prints errors on mqtt payloads which aren't valid json. This is a problem because the mosquitto bridge health status is published as a single integer `1` or `0` which is the most likely root cause of these messages.

```sh
$ journalctl -fu tedge-mapper-aws -n 100
-- Journal begins at Tue 2023-08-15 14:24:36 CEST. --
Sep 08 00:54:04 lumber tedge-mapper[32138]: 2023-09-07T22:54:04.089756196Z ERROR aws_mapper_ext::converter: Mapping error: invalid type: integer `0`, expected a map at line 1 column 1
Sep 08 00:54:04 lumber tedge-mapper[32138]: 2023-09-07T22:54:04.08980177Z ERROR aws_mapper_ext::converter: Mapping error: invalid type: integer `0`, expected a map at line 1 column 1
```

**To Reproduce**

1. Install thin-edge.io
2. Configure the tedge-mapper-c8y to connect to AWS (this [gist](https://gist.github.com/reubenmiller/0aa9dfb6fabbfdbe76156e9c3af4f33f) can help guide you through the setup)
3. Publish a message to simulate the mosquitto bridge health message

    ```sh
    tedge mqtt pub tedge/health/mosquitto-aws-bridge 0
    ```
4. Inspect the tedge-mapper-aws logs for any error messages related to mapping/parsing errors
    ```sh
    journalctl -u tedge-mapper-aws -n 50
    ```

**Expected behavior**

The aws mapper should ignore parsing errors for known topics like `tedge/health/mosquitto-aws-bridge` and `tedge/health/mosquitto-c8y-bridge` etc.

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]: `Debian 11 (bullseye)`
 - Hardware [incl. revision]: `Raspberry Pi 4`
 - System-Architecture [e.g. result of "uname -a"]: `Linux lumber 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
 - thin-edge.io version [e.g. 0.1.0]: `tedge 0.12.1~237+g7f58cd2`

**Additional context**

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the bug and could not reproduce it anymore.
