### ISSUE TITLE
tedge-mapper-aws health message uses two different timestamp formats for up and down messages

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2237]
**Describe the bug**

Inconsistent `time` format between the outgoing `aws/td/health/tedge-mapper-aws` up/down messages.

The status up message uses a unix timestamp:

```
[aws/td/health/tedge-mapper-aws] {"pid":33547,"status":"up","time":1694131076}
```

Where as the down message uses RFC3339 format:

```sh
[aws/td/health/tedge-mapper-aws] {"pid":33394,"status":"down","time":"2023-09-07T23:57:56.732011163Z"}
```

The root cause seems to be due to the up message knows the timestamp upfront and is set in the payload using a unix timestamp, then the aws converted preserves the timestamp in the original format. The down message is sent via the MQTT broker LWT (Last Will and Testament) message and does not include a timestamp as LWT message are static and defined when the process is started, not when the process stops, therefore when the LWT message is processed by the AWS converter, it add the `time` property using the RFC3339 formatted timestamp.

Below shows the difference in payloads which leads to the inconsistency being added by the converter:

```sh
# Up message
[tedge/health/tedge-mapper-aws] {"pid":33394,"status":"up","time":1694130288}

# Down message
[tedge/health/tedge-mapper-aws] {"pid":33394,"status":"down"}
```

Using different formats for different properties makes it harder for other components to reliably subscribe to the data, as they need to cater for different format types which makes parsing the payloads more difficult in some programming languages.

**To Reproduce**

1. Install thin-edge.io
2. Configure the tedge-mapper-c8y to connect to AWS (this [gist](https://gist.github.com/reubenmiller/0aa9dfb6fabbfdbe76156e9c3af4f33f) can help guide you through the setup)
3. Subscribe to the `aws/#` topics on the local broker

    ```sh
    tedge mqtt sub 'aws/#'
    ```

4. In another console, publish a message to simulate the health message messages, both up and down

    ```sh
    tedge mqtt pub -r tedge/health/tedge-mapper-aws '{"pid":33394,"status":"up","time":1694130288}'
    tedge mqtt pub -r tedge/health/tedge-mapper-aws '{"pid":33394,"status":"down"}'
    ```

5. Inspect the subscribed messages from subscription step and view the `time` property. The expectation is that the `time` property are both in the same format

**Expected behavior**

The `time` property should be in the same format (e.g. either unix timestamp or RFC3339) for both the up and down messages.

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]: `Debian 11 (bullseye)`
 - Hardware [incl. revision]: `Raspberry Pi 4`
 - System-Architecture [e.g. result of "uname -a"]: `Linux lumber 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`
 - thin-edge.io version [e.g. 0.1.0]: `tedge 0.12.1~237+g7f58cd2`

**Additional context**

**Comment by PradeepKiruvale** [comment]
This applies to `Azure` mapper as well.

**Comment by albinsuresh** [comment]
For the sake of consistency with the rest of thin-edge that already uses the rfc3339 format, the proposal makes sense. But, we may want to re-evaluate this choice before 1.0 as generating `time` in rfc3339 format is always extra effort for ourselves as well as our users. Something like the the UNIX epoch time format would be much easier for everyone.

**Comment by reubenmiller** [comment]
> For the sake of consistency with the rest of thin-edge that already uses the rfc3339 format, the proposal makes sense. But, we may want to re-evaluate this choice before the 1.0 release, as generating `time` in rfc3339 format is always extra effort for ourselves as well as external components/users. Something like the the UNIX epoch time format would be much easier for everyone.

Yes I would tend to agree that using a unix timestamp is much easier in most cases (both to generate and to consume). You get many nice properties out of the box, such as:

* Easy calculation and comparison of two timestamps
* Parsing is easier (it is just a number)
* Reduce overhead in messages

Though we would still have to decide on some specifics like:
* Should we use seconds or milliseconds since 1970-01-01...I believe seconds might be more "standard" and expected
* Do we allow floats as the timestamps so that we can represent milliseconds and microseconds and how does floating points impact on precision (e.g. rounding errors)

**Comment by gligorisaev** [comment]
@PradeepKiruvale is the part "5. Inspect the subscribed messages from subscription step and view the time property. The expectation is that the time property are both in the same format" implemented?

**Comment by PradeepKiruvale** [comment]
> ```shell
> ```shell
> tedge mqtt pub -r tedge/health/tedge-mapper-aws '{"pid":33394,"status":"down"}'
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

In this case, we don't need to publish the messages done in step 5. Observe the timestamp format in `up` and `down` messages. Both must be the same.

```
Start the AWS mapper and observe a health status message as below

[te/device/main/service/tedge-mapper-aws/status/health] {"pid":273664,"status":"up","time":"2023-10-17T05:21:47.072375024Z"}
[az/messages/events/] {"pid":273664.0,"time":"2023-10-17T05:21:47.072375024Z"}

For a down message, stop the AWS mapper and observe the below message

[te/device/main/service/tedge-mapper-aws/status/health] {"pid":273664,"status":"down"}
[az/messages/events/] {"pid":273664.0,"time":"2023-10-17T05:23:43.066712735Z"}

```

**Comment by gligorisaev** [comment]
@reubenmiller I am assigning you to review this ticket because the expected behaviour is not as you have described, so please verify if the solution for this bug is sufficient for your expectation (maybe something else was agreed without to be reflewcted in this ticket)

**Comment by didier-wenzek** [comment]
> @reubenmiller I am assigning you to review this ticket because the expected behaviour is not as you have described, so please verify if the solution for this bug is sufficient for your expectation (maybe something else was agreed without to be reflewcted in this ticket)

Responding on behalf of @reuben miller.

The expected behavior is that *all* status messages include a `"time"` property using the __rfc3339__ format (when forwarded to the cloud).
- This must be the case for aws, azure and c8y.
- This must be the case for `up` and `down` status.

__note__ some confusion on this ticket is related to a broader topic: [do we have to change our mind about thin-edge preferred format for dates?](https://github.com/thin-edge/thin-edge.io/issues/2337). For now, we *keep*  rfc3339 as the format to be used for all date values produced by thin-edge. The point of this ticket is to fix remaining outliers.
