### ISSUE TITLE
Alarms for c8y  are consumed from `te/+/+/+/+/a/+`

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#2243]
Cumulocity mapper should consume `te/+/+/+/+/a/+` topic instead of `tedge/alarms/+` and `tedge/alarms/+/+`.

The details is described in https://github.com/thin-edge/thin-edge.io/issues/2082.

**Comment by rina23q** [comment]
Done with #2267

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite. 
- tests/RobotFramework/tests/cumulocity/telemetry/c8y_child_alarms_rpi.robot
- tests/RobotFramework/tests/cumulocity/telemetry/child_device_telemetry.robot
- tests/RobotFramework/tests/cumulocity/telemetry/raise_alarms.robot
- tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
- tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
- [x] QA has tested the feature and it meets the required specifications.
