### ISSUE TITLE
AWS mapper consumes MEA from `te` topics.

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#2244]
Consume:
- measurements from te/+/+/+/+/m/+
- events from te/+/+/+/+/e/+
- alarms from te/+/+/+/+/a/+
- health status from te/+/+/+/+/status/health

Use the EntityStore to get the device names from device topic identifiers and use the device name in the aws topic.

**Comment by didier-wenzek** [comment]
@reubenmiller one needs to clarify the expectation about device identification in the aws output topics.

- Do we change nothing? i.e `te/device/child-xyz///m/m-type` is sent to `aws/td/device/child-xyz///m/m-type` ?
- Do we replace the device topic id by the device name:  .e `te/device/child-xyz///m/m-type` is sent to `aws/td/device-xyz/m/m-type` ?

**Comment by reubenmiller** [comment]
> @reubenmiller one needs to clarify the expectation about device identification in the aws output topics.
> 
> * Do we change nothing? i.e `te/device/child-xyz///m/m-type` is sent to `aws/td/device/child-xyz///m/m-type` ?
> * Do we replace the device topic id by the device name:  .e `te/device/child-xyz///m/m-type` is sent to `aws/td/device-xyz/m/m-type` ?

Yes this raises interesting questions. Someone will need to invest some time to finding out about AWS handling of child devices. Otherwise if time is not available then I would do the "as is" approach (option 1).

**Comment by gligorisaev** [comment]
> > @reubenmiller one needs to clarify the expectation about device identification in the aws output topics.
> > 
> > * Do we change nothing? i.e `te/device/child-xyz///m/m-type` is sent to `aws/td/device/child-xyz///m/m-type` ?
> > * Do we replace the device topic id by the device name:  .e `te/device/child-xyz///m/m-type` is sent to `aws/td/device-xyz/m/m-type` ?
> 
> Yes this raises interesting questions. Someone will need to invest some time to finding out about AWS handling of child devices. Otherwise if time is not available then I would do the "as is" approach (option 1).

Attached is an doc that I was using as info how AWS IoT is handling groups, does not handle child devices as such but hierarchy groups (which is same, I guess), maybe it can help
[iot-dg.pdf](https://github.com/thin-edge/thin-edge.io/files/12761748/iot-dg.pdf)

**Comment by PradeepKiruvale** [comment]
> > @reubenmiller one needs to clarify the expectation about device identification in the aws output topics.
> > 
> > * Do we change nothing? i.e `te/device/child-xyz///m/m-type` is sent to `aws/td/device/child-xyz///m/m-type` ?
> > * Do we replace the device topic id by the device name:  .e `te/device/child-xyz///m/m-type` is sent to `aws/td/device-xyz/m/m-type` ?
> 
> Yes this raises interesting questions. Someone will need to invest some time to finding out about AWS handling of child devices. Otherwise if time is not available then I would do the "as is" approach (option 1).

Went with Option 1 as of now, and the topics will be below

```
Te/device/main///m/m_type ->aws/td/device:main/m/m_type
Te/device/main/service/s-name/m/m_type->aws/td/device:main:service:s-name/m/m_type

Te/device/child///m/m_type ->aws/td/device:child/m/m_type
Te/device/child/service/s-name/m/m_type->aws/td/device:child:service:s-name/m/m_type
```

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/RobotFramework/tests/mqtt/custom_sub_topics_tedge-mapper-aws.robot
- tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
- [x] QA has tested the bug and could not reproduce it anymore.
