### ISSUE TITLE
tedge-log-plugin does not detect file changes to tedge-log-plugin.toml

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2246]
**Describe the bug**

The tedge-log-plugin must be restarted after changes to `/etc/tedge/plugins/tedge-log-plugin.toml` are made. This should not be the case as any file changes should be detected without a service restart.

**To Reproduce**

Run the integration tests without the `ThinEdgeIO.Restart Service    tedge-log-plugin` line.

* `Successful log operation` in [tests/RobotFramework/tests/cumulocity/log/log_operation.robot](https://github.com/thin-edge/thin-edge.io/pull/2213/files#diff-e7eadaf42c4bc9422a832d8a9e307e1bdefbc74fc680187c90454f15c04f1120)

**Expected behavior**

Any file changes should be detected without a service restart, 
* The list of supported log file types should be updated in Cumulocity
* New log file types should be able to be requested 

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]: `Debian Bullseye`
 - Hardware [incl. revision]: `Docker`
 - System-Architecture [e.g. result of "uname -a"]: `aarch64`
 - thin-edge.io version [e.g. 0.1.0]: https://github.com/thin-edge/thin-edge.io/pull/2213

**Additional context**

**Comment by Ruadhri17** [comment]
I extended this ticket to all plugins that use `Fsfilewatcher` as the change is basically the same for all of them.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.  
- tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot
- tests/RobotFramework/tests/cumulocity/log/log_operation.robot
- tests/RobotFramework/tests/cumulocity/log/log_operation_child.robot
- [x] QA has tested the bug and could not reproduce it anymore.
