### ISSUE TITLE
tedge-mapper-c8y clears log_upload commands which did not originate from it

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2251]
**Describe the bug**

The tedge-mapper-c8y is clearing `log_upload` operations which were not requested by it, which results in the chance to give the original requestor confirmation that they have seen the result before the retained operation message is cleared.

**To Reproduce**

1. Install thin-edge.io
2. Make sure the following services are running
    * tedge-mapper-c8y
    * tedge-agent
    * tedge-log-plugin

3. Open a new bash shell and subscribe to the log_upload command types. Leave 

    ```
    tedge mqtt sub 'te/+/+/+/+/cmd/log_upload/+'
    ```

4. Open a new bash shell and paste the following snippet to define a function helper which will be used to create the log file request mqtt messages in the following step

    ```sh
    get_log() {
        MAX_LINES="10000"
        SEARCH_TEXT=""
        LOG_TYPE="example"
        device_id=$(tedge config get device.id)
        cmd_id=$(echo "id-$RANDOM")
        payload=$(printf '{
            "status":"init",
            "tedgeUrl":"http://127.0.0.1:8000/tedge/file-transfer/%s/log_upload/example-%s",
            "type":"%s",
            "dateFrom":"2023-09-12T00:10:27Z",
            "dateTo":"2023-09-13T00:11:27Z",
            "searchText":"%s",
            "lines":%s
        }' "$device_id" "$cmd_id" "$LOG_TYPE" "$SEARCH_TEXT" "$MAX_LINES")
        set -x
        tedge mqtt pub --retain "te/device/main///cmd/log_upload/$cmd_id" "$payload"
        set +x

        echo ""
        echo "You can download the log file from"
        echo "  curl -f http://127.0.0.1:8000/tedge/file-transfer/$device_id/log_upload/example-$cmd_id"
        echo
    }
    ```

    **Note** It assumes that you have configured an "example" log file type in the `/etc/tedge/plugins/tedge-log-plugin.toml` file. If you have trouble setting it up, use the integration test under: `tests/RobotFramework/tests/cumulocity/log/log_operation.robot`

5. Create a log_upload request by using the helper function defined in the previous step

    ```sh
    get_log
    ```

6. Inspect the `tedge mqtt sub` command in the other shell to check which messages have been published.

    The expectation is that you should NOT see the publishing of an empty MQTT payload which will manifest in the form of (where the id will vary as it uses a randomly generated id):

    ```sh
    te/device/main///cmd/log_upload/id-1234
    ```

**Expected behavior**

As stated in the upcoming docs in [PR2235](https://github.com/thin-edge/thin-edge.io/pull/2235/files), only the requester should clear the operation (e.g. send an empty retained message to clear the stored retain message). This will ensure that the original requester has definitely seen the result of the operation before it is cleared.

The below snippet was taken from [PR2235](https://github.com/thin-edge/thin-edge.io/pull/2235/files) indicating the clearing should be done by the requester

```
done(finally cleared by the requester)
````

**Screenshots**

The following logs clearly show that the `tedge-mapper-c8y` is clearing the `log_upload` operation even it is is not the requester. When the `tedge-mapper-c8y` service is stopped, then the `log_upload` operation is not cleared for manually created operations.

**With the tedge-mapper-c8y stopped**

```sh
get_log
```

```text
[te/device/main///cmd/log_upload/id-28463] {
    "status":"init",
    "tedgeUrl":"http://127.0.0.1:8000/tedge/file-transfer/TST_shift_glossy_skew/log_upload/example-id-28463",
    "type":"example",
    "dateFrom":"2023-09-12T00:10:27Z",
    "dateTo":"2023-09-13T00:11:27Z",
    "searchText":"",
    "lines":10000
}
[te/device/main///cmd/log_upload/id-28463] {"status":"executing","tedgeUrl":"http://127.0.0.1:8000/tedge/file-transfer/TST_shift_glossy_skew/log_upload/example-id-28463","type":"example","dateFrom":"2023-09-12T00:10:27Z","dateTo":"2023-09-13T00:11:27Z","searchText":"","lines":10000}
[te/device/main///cmd/log_upload/id-28463] {"status":"successful","tedgeUrl":"http://127.0.0.1:8000/tedge/file-transfer/TST_shift_glossy_skew/log_upload/example-id-28463","type":"example","dateFrom":"2023-09-12T00:10:27Z","dateTo":"2023-09-13T00:11:27Z","searchText":"","lines":10000}
```

**With tedge-mapper-c8y running**

```
get_log
```

```text
[te/device/main///cmd/log_upload/id-1574] {
        "status":"init",
        "tedgeUrl":"http://127.0.0.1:8000/tedge/file-transfer/TST_shift_glossy_skew/log_upload/example-id-1574",
        "type":"example",
        "dateFrom":"2023-09-12T00:10:27Z",
        "dateTo":"2023-09-13T00:11:27Z",
        "searchText":"",
        "lines":10000
    }
[te/device/main///cmd/log_upload/id-1574] {"status":"executing","tedgeUrl":"http://127.0.0.1:8000/tedge/file-transfer/TST_shift_glossy_skew/log_upload/example-id-1574","type":"example","dateFrom":"2023-09-12T00:10:27Z","dateTo":"2023-09-13T00:11:27Z","searchText":"","lines":10000}
[te/device/main///cmd/log_upload/id-1574] {"status":"successful","tedgeUrl":"http://127.0.0.1:8000/tedge/file-transfer/TST_shift_glossy_skew/log_upload/example-id-1574","type":"example","dateFrom":"2023-09-12T00:10:27Z","dateTo":"2023-09-13T00:11:27Z","searchText":"","lines":10000}
[te/device/main///cmd/log_upload/id-1574]           <-- THIS IS THE ERRONEOUS MESSAGE
```

**Environment (please complete the following information):**
 - OS [incl. version]: `Debian Bullseye`
 - Hardware [incl. revision]: `docker aarch64`
 - System-Architecture [e.g. result of "uname -a"]: `Linux 98b0f76a84ef 5.15.68-0-virt #1-Alpine SMP Fri, 16 Sep 2022 06:29:31 +0000 aarch64 GNU/Linux`
 - thin-edge.io version [e.g. 0.1.0]: `0.12.1~266+g2eb30d5`

**Additional context**

**Comment by didier-wenzek** [comment]
The proposal is to add a requester-specific prefix to each command id.

Hence, `tedge-mapper-c8y`:
- generates `cmd_id` with a `mapper-c8y` prefix.
- ignore any command which prefix doesn't have this prefix.

**Comment by didier-wenzek** [comment]
See https://github.com/thin-edge/thin-edge.io/pull/2235

**Comment by reubenmiller** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- [x] QA has tested the bug and could not reproduce it anymore.
