### ISSUE TITLE
azure tedge mapper fails to translate health status messages

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#2256]
**Describe the bug**

When `tedge-mapper-az` is started and receives the `health status messages`, mapper fails to translate these messages and throws the error below

```
023-09-13T06:23:22.76119982Z ERROR az_mapper_ext::converter: Mapping error: Invalid JSON: invalid type: integer `1694586060`, expected a borrowed string at line 1 column 44: `0}
`    
2023-09-13T06:23:22.76150372Z ERROR az_mapper_ext::converter: Mapping error: Invalid JSON: invalid type: integer `1694581730`, expected a borrowed string at line 1 column 42: `0}
`    
2023-09-13T06:23:22.76159542Z ERROR az_mapper_ext::converter: Mapping error: Invalid JSON: invalid type: integer `1694581730`, expected a borrowed string at line 1 column 42: `0}
```

**To Reproduce**
1. Install thin-edge.io

2. Configure the tedge-mapper-c8y to connect to [azure ](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/start/connect-azure.md)

3. Publish a message to simulate the mosquitto bridge health message

    ```
    tedge mqtt pub tedge/health/tedge-mapper-az '{"pid":19753,"status":"up","time":1694586060}'
    ```

4. Inspect the tedge-mapper-az logs for any error messages related to mapping/parsing errors

    ```
    journalctl -u tedge-mapper-az -n 50
    ```

**Expected behavior**

The az mapper should properly parse the `health` status message and output on `az/messages/events` topic.

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version] : `ubuntu 21`
 - Hardware [incl. revision]: `x86`
 - System-Architecture [e.g. result of "uname -a"]:
 - thin-edge.io version [e.g. 0.1.0]: `0.12.1~237+g7f58cd2`

**Additional context**

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the bug and could not reproduce it anymore.
