### ISSUE TITLE
Health check and status for c8y mapper on `te/`

### ISSUE THREAD

**Issue by Bravo555** [thin-edge/thin-edge.io#2274]
The `c8y` mapper is changed to use health status from the `te/+/+/+/+/status/health` and health check from `te/+/+/+/+/cmd/health/check` instead of `tedge/health/+` and `tedge/health-check` topics.

### Feature-related

- [x] #2349
- [x] #2348
- [x] [Use new `te/.../cmd/health/check` command](https://github.com/thin-edge/thin-edge.io/issues/2308)

### Cleanup

- [ ] Rewrite sending service startup registration message so there's less boilerplate
- [ ] Clean up `ServiceTopicId`, `EntityTopicId`, `DeviceTopicId`, `Service`, etc. abstractions
- [ ] fill `serviceType` default in mapper instead of the store
- [ ] Simplify passing of ancestors to functions which need to know ancestors of the given entity

**Comment by didier-wenzek** [comment]
See also:
- https://github.com/thin-edge/thin-edge.io/issues/2253
- https://github.com/thin-edge/thin-edge.io/issues/2308

**Comment by Bravo555** [comment]
Because of the upcoming 0.13 release and all feature-related work has been done, this issue can be closed. A new issue(s) will be created for the remaining clean-up tasks.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/RobotFramework/tests/MQTT_health_check/MQTT_health_endpoints.robot
- tests/RobotFramework/tests/MQTT_health_check/health_tedge-mapper-collectd.robot
- tests/RobotFramework/tests/cumulocity/service_monitoring/service_monitoring.robot
- tests/RobotFramework/tests/cumulocity/software_management/software.robot
- tests/RobotFramework/tests/cumulocity/supported_operations/mapper-publishing-agent-supported-ops.robot
- tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
- tests/RobotFramework/tests/tedge_to_te_converter/convert_tedge_topics_to_te_topics.robot
- tests/RobotFramework/tests/cumulocity/supported_operations/mapper-publishing-agent-supported-ops.robot
- tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
- tests/RobotFramework/tests/tedge_to_te_converter/convert_tedge_topics_to_te_topics.robot
- tests/RobotFramework/tests/tedge_to_te_converter/convert_tedge_topics_to_te_topics.robot
- tests/RobotFramework/tests/tedge_to_te_converter/convert_tedge_topics_to_te_topics.robot
- [x] QA has tested the bug and could not reproduce it anymore.
