### ISSUE TITLE
Phase 1: package thin-edge.io as a multi-call binary to reduce resource requirements

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2281]
**Is your feature improvement request related to a problem? Please describe.**

Consolidate the tedge binaries into one multi-call binary to reduce

* Reduce memory usage by removing duplicated runtime environments (e.g. actor runtime)
* Reduce total disk space required to install all required binaries to offer the same functionality

This has already been requested by some other tickets, and conversations with some users:

* https://github.com/thin-edge/thin-edge.io/issues/1459

**Describe the solution you'd like**

Initial work will have to be done to view the merits of making a multi-call binary and how to package it. The initial goal will be to create a working multi-call binary, and then we will work on how to package it based on the improvements to the install and memory usage.

The main takes of this ticket should include:

1. Create single (multi-call) binary which includes the same functionality as the current individual binaries
    * tedge
    * tedge-mapper
    * tedge-agent
    * tedge-log-plugin
    * c8y-configuration-plugin
    * c8y-firmware-plugin
    * tedge-watchdog

    **Note**

    `tedge-apt-plugin` and `c8y-remote-access-plugin` are considered out of scope at the moment. We will evaluate whether creating a [Multi-Call binary](https://man.archlinux.org/man/busybox.1.en#:~:text=BusyBox%20is%20a%20multi%2Dcall,a%20large%20number%20of%20utilities.) (similar to busybox) is feasible or not

2. Implement a way to enable/disable specific features based on configuration (and possibly flags to facilitate starting a dedicated mapper instance?)

3. Compare disk space used between 0.12.0 and the new multi-call binary setup

4. Compare memory consumption of running multiple services (as of 0.12.0) and running one (or two) services.

5. Assess whether included `tedge-apt-plugin` and `c8y-remote-access-plugin` should also be included in the multi-call binary, and check how much work would need to be done to cover this scenario

**Describe alternatives you've considered**

**Additional context**

The current total size of the thin-edge.io binaries is around 38MB (as of `0.12.1~298+g7e6da86`), however each binary uses very similar dependencies, so there is very significant space saving to be made by making a multi-call binary. Below shows the list of binaries currently included part of thin-edge.io:

```sh
# ls -lh /usr/bin/c8y* /usr/bin/tedge*
-rwxr-xr-x 1 root  root  5.4M Sep 20 00:54 /usr/bin/c8y-configuration-plugin
-rwxr-xr-x 1 root  root  5.0M Sep 20 00:55 /usr/bin/c8y-firmware-plugin
-rwxr-xr-x 1 root  root  2.9M Sep 20 00:51 /usr/bin/c8y-remote-access-plugin
-rwxr-xr-x 1 root  root  4.9M Sep 20 00:53 /usr/bin/tedge
-rwxr-xr-x 1 root  root  5.1M Sep 20 00:50 /usr/bin/tedge-agent
-rwxr-xr-x 1 root  root  2.3M Sep 20 00:53 /usr/bin/tedge-apt-plugin
-rwxr-xr-x 1 root  root  4.7M Sep 20 00:52 /usr/bin/tedge-log-plugin
-rwxr-xr-x 1 root  root  5.7M Sep 20 00:52 /usr/bin/tedge-mapper
-rwxr-xr-x 1 root  root  3.7M Sep 20 00:51 /usr/bin/tedge-watchdog
```

**Comment by reubenmiller** [comment]
@jarhodes314 There was some work done already which started to combine some functionality together into one single binary, [c8y-device-management](https://github.com/thin-edge/thin-edge.io/tree/main/crates/bin/c8y-device-management), so you can use that as the shell for the multi-call binary (if it makes sense).

**Comment by didier-wenzek** [comment]
> Implement a way to enable/disable specific features based on configuration (and possibly flags to facilitate starting a dedicated mapper instance?)

The c8y mapper use a `tedge-config` flag: [`c8y.enable.log_management`](https://github.com/thin-edge/thin-edge.io/blob/main/crates/common/tedge_config/src/tedge_config_cli/tedge_config.rs#L378).

We can do the same with flags such as `enable.c8y_mapper` or `enable.log_management`.

**Comment by jarhodes314** [comment]
So far, I've established that making a multicall binary is pretty trivial using clap, so having a single `tedge` executable that behaves differently depending on what the executable name is (like what busybox does) would be a simple first step. Running a build locally (with ` cargo zigbuild --target x86_64-unknown-linux-musl --release -p tedge`) gives the following results (I haven't spent any time investigating the discrepancy between the baseline result and the released versions, I simply made sure that musl was used):

```bash
$ ls -lh ./target/x86_64-unknown-linux-musl/release/tedge # just tedge as it exists on main
-rwxr-xr-x 2 jrh all users 6.0M Sep 25 13:04 ./target/x86_64-unknown-linux-musl/release/tedge
$ ls -lh ./target/x86_64-unknown-linux-musl/release/tedge # tedge + tedge-mapper
-rwxr-xr-x 2 jrh all users 7.9M Sep 25 12:51 ./target/x86_64-unknown-linux-musl/release/tedge
$ ls -lh ./target/x86_64-unknown-linux-musl/release/tedge # tedge + tedge-agent
-rwxr-xr-x 2 jrh all users 8.4M Sep 25 12:56 ./target/x86_64-unknown-linux-musl/release/tedge
```

So the results are definitely promising in terms of disk space, and as far as I can tell, this should work as pretty much a drop in replacement for the existing binaries, with symlinks to `tedge` for `tedge-mapper`, `tedge-agent`, etc. I haven't yet investigated multiple services in the same process, but I think regardless of how that works, there is significant overlap in the work involved (namely converting existing binaries to libraries
