### ISSUE TITLE
Improve the health status messages to azure cloud

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#2283]
**Is your feature improvement request related to a problem? Please describe.**
The current way of sending the health status messages to the Azure Cloud via Azure Mapper does not contain

- Information about whether the service belongs to the `main or the child` device
- Information about for which `service` the health status belongs 

**Describe the solution you'd like**
To address the above-mentioned issues the health status message that is forwarded by the Azure mapper to the Azure cloud must be
- Translated properly and added the required device and service information
- The translated messages format must be in accordance with Azure IoT cloud specifications

**Describe alternatives you've considered**

**Additional context**

**Comment by didier-wenzek** [comment]
Closing as implemented
