### ISSUE TITLE
Restart operation on child devices

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#2288]
`tedge-agent` can run on a child device as well as on the main device.

As this is a work in progress, only one operation is implemented: restarting the device.
See the specifications: here https://github.com/thin-edge/thin-edge.io/pull/2235

This first step includes the following:

- `tedge-agent` can be launched on a child-device using `--mqtt-topic-root` and ` --mqtt-device-topic-id` to specify the topic used for the child. For instance, running `tedge-agent --mqtt-device-topic-id device/child-001//`  on the child-device `child-001`, starts the agent on this device and makes it accessible to c8y via the c8y mapper.
- An alternative way to launch `tedge-agent` on a child device is to specify the child topic using `tedge config`. For instance, `tedge config set mqtt.device_topic_id "device/child-001//"` then simply running `tedge-agent`.
- When `tedge-agent` is launched on a child device and when the main device is connected to c8y, then the child-device is registered on c8y. The restart capability is also registered. The child device can then be restarted from c8y.

**Comment by didier-wenzek** [comment]
Child device restart has been implemented by https://github.com/thin-edge/thin-edge.io/pull/2245.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the bug and could not reproduce it anymore.

**Comment by reubenmiller** [comment]
> QA has thoroughly checked the feature and here are the results:
> 
> * [ ]  Test for ticket exists in the test suite.
> * [x]  QA has tested the bug and could not reproduce it anymore.

System tests are included here:
* https://github.com/thin-edge/thin-edge.io/blob/main/tests/RobotFramework/tests/cumulocity/restart/restart_device_child.robot
