### ISSUE TITLE
Entity registration API for child devices and services with c8y mapping

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#2294]
**Is your feature request related to a problem? Please describe.**

Provide entity registration APIs for child devices and services. The following registration cases must be supported:

1. Immediate child devices of main device (where `@parent` is optional)
2. Nested child devices of other child devices at any level (by explicitly specifying the parent using `@parent`)
3. Registration of services on main device as well as child devices
4. Support registration of entities following custom topic schemes other than the default `tedge/device/<device-id>/service/<service-id>` scheme. E.g: `tedge/custom/device/<device-family>/<device-id>`, `tedge/custom/<device-id>/<service-id>` etc

These registration messages should be mapped to their equivalent Cumulocity representation by the c8y-mapper.

**Describe the solution you'd like**

Implement the registration APIs exactly as specified in in [this specification](https://thin-edge.github.io/thin-edge.io/next/references/mqtt-api/#entity-registration) and the mapping logic by the c8y-mapper as described in the [mapper specification](https://thin-edge.github.io/thin-edge.io/next/references/mappers/c8y-mapper/#registration)

**Comment by albinsuresh** [comment]
Implemented by #2266 and to be verified as described in the description. Most of the basic cases already covered by https://github.com/thin-edge/thin-edge.io/blob/main/tests/RobotFramework/tests/cumulocity/registration/device_registration.robot

One additional side effect was the change in the c8y device registration behaviour of child devices, when they are created by using the file system based APIs (creating a directory for a child device under `/etc/tedge/operations/c8y`). Earlier, when a directory named, `child-1` was created, the corresponding device twin was created in c8y with the same external id. But, with this work, the external id of the same device would be `<main-device-id>:device:child-1`, which is consistent with how the external id is generated for a device created using the MQTT registration APIs by publishing to `te/device/child-1//` topic. Existing system tests using the file system mechanism has already been updated.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the bug and could not reproduce it anymore.

**Comment by reubenmiller** [comment]
System tests are covered here:
* https://github.com/thin-edge/thin-edge.io/blob/main/tests/RobotFramework/tests/cumulocity/registration/device_registration.robot
