### ISSUE TITLE
Replace current upload mechanism with the uploader actor in new tedge plugins

### ISSUE THREAD

**Issue by Ruadhri17** [thin-edge/thin-edge.io#2301]
**Is your feature request related to a problem? Please describe.**

Currently, both tedge-configuration-plugin and tedge-log-plugin use tedge_http_actor for uploading content to the tedge file repository. That generates two problems:

- Plugins are "blocked" until the upload request is finished.
- There is no retry mechanism when a client-side issue occurs, e.g. temporary network connection lost.

**Describe the solution you'd like**

Add uploader_actor that will work similarly to downloader_actor. It should support a retry mechanism, e.g. using a backoff strategy.

This ticket should consist of two steps:

- [x] Add the upload library and uploader_actor. #2302
- [x] Replace the current upload mechanism with the new uploader_actor. #2302

**Describe alternatives you've considered**

**Additional context**

**Comment by Ruadhri17** [comment]
PR with uploader actor was marged into main branch. Uploader actor is currently used in two plugins:
- tedge-configuration-plugin
- tedge-log-plugin

**Comment by gligorisaev** [comment]
@Ruadhri17  Please include in the ticket more information about the final solution/how to verify the change.

**Comment by Ruadhri17** [comment]
@gligorisaev In both plugins uploader actor is responsible for uploading file to `tedge file transfer repository`. Thanks to that plugins can process next requests without waiting for upload to finish and in case of some network connection issues it will retry the upload and not just return `FAILED` status of the request.

As for testing: I created rust [test](https://github.com/thin-edge/thin-edge.io/blob/57ae569814d8c42b28200018bd66aa191adec7d9/crates/common/upload/src/upload.rs#L240) that simulates server behavior: file is sent to server and it responses with http error code 500 to force upload retry. What need to be thoroughly verifed is that uploader successfully uploads file to `tedge file transfer repository` and correctly reacts to different kind of errors (client side errors, file errors, permission errors etc.).

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the bug and could not reproduce it anymore.
