### ISSUE TITLE
Explicit registration for tedge and c8y services

### ISSUE THREAD

**Issue by Bravo555** [thin-edge/thin-edge.io#2328]
**Is your feature request related to a problem? Please describe.**

The `Test if all c8y services are using configured service type` integration test checks if after changing `service.type` config setting services are registered in Cumulocity using a new service type. That worked because [service type was part of a health status message](https://github.com/thin-edge/thin-edge.io/blob/8e785256e38146ee2f2d9ccf6a017b3bcceb173b/crates/extensions/c8y_mapper_ext/src/service_monitor.rs#L14). Now, as confirmed with @reubenmiller, since defining the entity should only happen on a local registration topic (i.e. `te/device/main/service/c8y-configuration-plugin`), service type was removed from a health status message payload.

This however presents a problem, where upon restarting the entity, correct service type is not applied because our services currently do not explicitly register themselves and rely on auto-registration. As when a c8y mapper is started with `service.type` set to value `A`, and a service publishes a message, a registration message is published by the mapper during an auto-registration process where `type` property is set to `A`. Because registration messages are retained, even if after changing `service.type` to `B` the c8y-mapper is restarted, it will pick up the previous registration message which contained `"type": "A"`.

**Possible solutions**

1. **Do not include cloud-specific properties in a local registration message published by the mapper during an auto-registration process**: these properties are of no concern to other local entities and when published in a registration message and after restarting the mapper, the mapper can't know that these fields are the defaults filled in by the previous invocation of itself, so it will be forced to use previous, invalid properties. Instead of publishing these cloud-specific properties, the mapper should not put them inside the local registration message, so that when a next invocation of the mapper picks the local registration message again, it can use updated defaults to register with the cloud.
 
   This is by far the simplest option, but it may have an undesirable effect of re-registering every service on Cumulocity when the c8y-mapper is restarted and `service.type` has been changed. Is this something that would be disruptive for the users?

2. **Make all services publish explicit registration messages**: this is probably something that we will have to do eventually, and as it should fix the problem with leftover service types from auto-registration, I might as well do it now.

**Comment by albinsuresh** [comment]
I'm not even sure if I would call this behaviour buggy. The `service.type` was more of a default value, to be used if any service registration messages did not explicitly provide a `type`. So, if 3 services are already registered with `type: A`, and then this `service.type` config is updated to `B`, I wouldn't expect the types of all the already registered entities to change. The updated `service.type` will only be applied to any new service that is registered without an explicit `type`.

In fact, going and changing the types of all the existing entities might even be undesirable to the user. What if he wanted them to stay on the old types? Because when he registered those services, `A` was his expected type.

**Comment by reubenmiller** [comment]
Just a few notes:

Services should always be registered every time the service is started (this ensures that the cloud representation is up to date...alternatively we could do a reconciliation with the cloud and only send the missing data, however this should only be considered as a follow up optimization). If the service is registered each time, then the messages should contain the updated `service.type` value.

**Comment by albinsuresh** [comment]
I think we're agreeing here. Yes, when a service is registered it should definitely pickup the `service.type` value from the config. So, if the service is designed in such a way that it'll re-register itself every time it is started up, then obviously its `type` will change the next time it restarts after `service.type` is updated.

What I was trying to say was that, once the service is registered, it'll have its `type` set and further `health_status` updates to it shouldn't try to update its `type`, even if the `service.type` is updated in the config. The updated `type` will get applied only when that service tries to re-register itself and not while sending regular `status` updates.

**Comment by Bravo555** [comment]
Was implemented in e73be3ccea44d2dad939f8e83f82006ef8ef6503.
