### ISSUE TITLE
tedge-mapper-c8y should use uploader actor for uploading files

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#2345]
**Is your refactoring request related to a problem? Please describe.**
In the current implementation, if uploading files takes so long time, it blocks all tedge-mapper-c8y. Now #2301 introduced the uploader actor, `tedge-mapper-c8y` should use the actor.

**Describe the solution you'd like**
Apply uploader actors to those operations.
- log_upload 
- config_snapshot 

**Describe alternatives you've considered**

**Additional context**

**Comment by rina23q** [comment]
Resolved by #2361. It's only internal refactoring.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the function and it's functioning according description.
