### ISSUE TITLE
Document health status and health check messages

### ISSUE THREAD

**Issue by Bravo555** [thin-edge/thin-edge.io#2348]
This issue encompasses updating all previous references of old health topics (`tedge/health`, `tedge/health-check`), as well as adding new documentation describing health status and health check messages.

- [x] Update documentation pages which still refer to old health topics:
   - [_How to monitor health of tedge services_](https://thin-edge.github.io/thin-edge.io/next/operate/troubleshooting/monitor_tedge_health/)
   - [_How to monitor health of service from Cumulocity IoT_](https://thin-edge.github.io/thin-edge.io/next/operate/c8y/c8y_service_monitoring/)
   - [_Enabling the systemd watchdog feature for a tedge service_](https://thin-edge.github.io/thin-edge.io/next/operate/monitoring/enable_tedge_watchdog_using_systemd/#debugging)
   - [_How to control which MQTT topics the mappers subscribe to_](https://thin-edge.github.io/thin-edge.io/next/operate/configuration/config-mapper-mqtt-topics/#check-the-subscribed-mqtt-topics/)
- [x] _Health status_ section should be added to [_Telemetry_ section of _Cumulocity Mapper_ page](https://thin-edge.github.io/thin-edge.io/next/references/mappers/c8y-mapper/#telemetry)

**Comment by Bravo555** [comment]
Implemented by #2375

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/RobotFramework/tests/MQTT_health_check/health_tedge_mapper_c8y.robot
- tests/RobotFramework/tests/aws/aws_telemetry.robot
- tests/RobotFramework/tests/azure/azure_telemetry.robot
- tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
- [x] QA has tested the bug and could not reproduce it anymore.
