### ISSUE TITLE
Support client authentication for the c8y-auth-proxy server

### ISSUE THREAD

**Issue by jarhodes314** [thin-edge/thin-edge.io#2363]
**Is your feature improvement request related to a problem? Please describe.**
At the moment, the c8y-auth-proxy serves over HTTP and the connection is both unencrypted and unauthenticated (anyone with access to the exposed port on the thin-edge main device can access all of the Cumulocity API).

**Describe the solution you'd like**
c8y-auth-proxy should serve data over HTTPS, and use client certificates for authentication, like thin-edge already uses for MQTT (via mosquitto). This should be independently configurable from the external mosquitto settings, although it should remain simple to configure the two with the same settings (e.g. to have the same set of trusted root certificates).

**Describe alternatives you've considered**
The auth proxy server could use passwords or tokens to add a local authentication layer, but people using authentication for external mosquitto connectivity are already well set up for configuring certificate-based authentication for another service. Using certificate authentication also means we leave open the abiliity to pass an `Authorization` header to override the device JWT if people wish.

**Additional context**

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the function and it's functioning according description.
