### ISSUE TITLE
User doc that describes sending telemetry to child device, nested child device and the associated services

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#2371]
**Is your documentation request related to a problem? Please describe.**
Sending the telemetry to the child/nested-child device and their services has to be documented to help the user to understand the feature and make it easy to use the features. The documentation must describe:

- [ ] The mqtt topics that can be used to send the telemetry (Measurements, Events, and Alarms)
- [ ] Sending telemetry without pre-registering the child/nested-child device and their services
- [ ] Sending the telemetry with Auto registration, if it's supported

The document must describe sending telemetry to:

- [ ] Child device
- [ ] Nested child device
- [ ] Child device services
- [ ] Nested child device services

**Describe the improvement you'd like**

**Additional context**

**Comment by didier-wenzek** [comment]
This has to be written as a tutorial / starting guide, the reference material being already there (a bit too scattered though).

**Comment by didier-wenzek** [comment]
Closing as completed
