### ISSUE TITLE
use independent tedge.toml settings to access the http server provided by tedge-agent

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2391]
**Is your feature improvement request related to a problem? Please describe.**

The `http.bind.address` setting is used by two different components but for different purposes,

1. tedge-agent interprets this setting as the bind address where the http server should be made available
2. tedge-mapper-c8y interprets this setting as the target ip address when uploading files to the tedgeUrl.

The different in the interpretation of the two settings makes it difficult to configure the tedge-mapper-c8y address, as it needs to know the ip address of the tedge-agent, and it can't use a hostname (as the setting only accepts an ip address, in the form of `x.x.x.x`). When using thin-edge.io in containers generally the container does not know the ip address of each other upfront, but rather at runtime, that is where using a hostname would be more useful when telling the tedge-mapper-c8y when creating the tedgeUrl. 

This problem is not too dissimilar to the changes which prompted splitting the `mqtt.bind.address` and `mqtt.client.host` settings.

**Describe the solution you'd like**

Create the following new settings which are used by the tedge-mapper-c8y when it needs to communicate with the http server provided by the tedge-agent.

* `http.client.host` - ip or hostname of the http server provided by the tedge-agent
* `http.client.port` - port of the http server provided by the tedge-agent

**Describe alternatives you've considered**

**Additional context**

**Comment by Bravo555** [comment]
# QA Reproduction instructions

1. Create two containers (or physical devices, but I'll call them containers for simplicity):
	1. **container-A**: full thin-edge.io except tedge-agent
	2. **container-B**: only tedge-agent

2. Configure containers to point to each other:
  ```
  # on containter A:
  $ tedge config set mqtt.bind.address 0.0.0.0
  $ tedge config set http.client.host <container-B>

  # on container B:
  $ tedge config set mqtt.client.host <container-A>
  $ tedge config set http.bind.address 0.0.0.0
  ```

3. Verify that all services on `<container-A>` and `<container-B>` correctly start up
4. For operations which contain `tedgeUrl` property, ensure that the hostname is equal to `http.client.host`

**Comment by gligorisaev** [comment]
QA has thoroughly checked the improvement and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/alpine-s6/children/operations.robot
- tests/RobotFramework/tests/config_management/child_conf_mgmt_plugin.robot
- tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot
- tests/RobotFramework/tests/cumulocity/firmware/firmware_operation_child_device.robot
- tests/RobotFramework/tests/cumulocity/log/log_operation.robot
- tests/RobotFramework/tests/cumulocity/log/log_operation_child.robot
- [x] QA has tested the improvement and it's functioning according description.
