### ISSUE TITLE
c8y_http_proxy API `create_event` doesn't support child device

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#2394]
**Describe the bug**
While debugging the [test failure](https://github.com/thin-edge/thin-edge.io/actions/runs/6696173895/job/18193851947?pr=2361), I found that the `create_event()` function works only for the main device.

https://github.com/thin-edge/thin-edge.io/blob/928f43e08e95f1bff9a97acaf677cb3d87773f21/crates/extensions/c8y_http_proxy/src/actor.rs#L296-L299

This means, if the size of an event exceeds the MQTT size threshold, creating an event via HTTP for child devices doesn't work. It will be created for the main device instead.

https://github.com/thin-edge/thin-edge.io/blob/928f43e08e95f1bff9a97acaf677cb3d87773f21/crates/extensions/c8y_mapper_ext/src/converter.rs#L451

P.S. we have a [system test for such a large event](https://github.com/thin-edge/thin-edge.io/blob/928f43e08e95f1bff9a97acaf677cb3d87773f21/tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot#L45), but two issues.
1. It was not created for child device.
2. The test didn't test to publish via HTTP.

Here is the output of `tedge mqtt sub "#"` of the test. You can see the event is created via MQTT.

```text
[te/device/main///e/largeEvent] {"text":"Large event","large_text_field":"x"}
[c8y/event/events/create] {"type":"largeEvent","time":"2023-10-31T17:16:15.227539999Z","text":"Large event","large_text_field":"x"}
```

**To Reproduce**
Publish an event for a child device with a large payload (> 16KiB), then the event will be created for its main device.

**Expected behavior**
If an event is supposed for a child device, the event must be created under the child device in c8y.

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [0.12.0]

**Additional context**
The root cause is, c8y requires **different** payload to create an event, via REST or MQTT.

#### REST (HTTP)
One must provide the `source` field with `id`. The `id` must be c8y's **internal** device ID. If the event is supposed to belong to a child device, the `id` must be the internal ID of the child device. `externalSource` will be ignored. 

```json
{
    "source": { "id":"4431203" },
    "type": "TestEvent",
    "text": "sensor was triggered",
    "time": "2023-10-31T12:03:27.845Z"
}
```

#### MQTT
One doesn't have to provide the `source` field. If you are intending to create an event for child device, the `externalSource` field can be used together with the child device's **external** ID.

```json
{
    "type": "TestEvent",
    "text": "sensor was triggered",
    "time": "2023-10-31T12:03:27.845Z",
    "externalSource":{"externalId":"rina0005:device:rtchild1","type":"c8y_Serial"}
}
```

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/RobotFramework/tests/cumulocity/telemetry/child_device_telemetry.robot
- tests/RobotFramework/tests/cumulocity/telemetry/thin-edge_device_telemetry.robot
- [x] QA has tested the bug and could not reproduce it anymore.
