### ISSUE TITLE
misleading log entry when state file does not exist in tedge-agent

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2413]
**Describe the bug**

tedge-agent prints the following ERROR in its logs during "normal" (non-error) behaviour.

```
tedge-agent[1221]: 2023-11-05T14:11:20.952597287Z ERROR tedge_agent::restart_manager::actor: Fail to read tedge-agent state: No such file or directory (os error 2)
```

The "ERROR" log level should be reserved for events which are unexpected.

**To Reproduce**

1. Install thin-edge.io

2. Restart the tedge-agent
    ```
    sudo systemctl restart tedge-agent
    ```
3. View the log

    ```
    journalctl -u tedge-agent -n 100
    ```

**Expected behavior**

The listed log entry should not be be printed on the `ERROR` level if it "expected behaviour" during normal operation of tedge-agent.

The suggested log entries for the different scenarios would be:

**Case 1:** When the "tedge-agent state" file exists:

```
ERROR tedge_agent::restart_manager::actor: Fail to read tedge-agent state: No such file or directory (os error 2)
```

**Case 2:** When the "tedge-agent state" file does not exist

```
INFO tedge_agent::restart_manager::actor: tedge-agent state file is not present
```

**Screenshots**

**Environment (please complete the following information):**

|Property|Value|
|--------|-----|
|OS [incl. version]|`Debian GNU/Linux 12 (bookworm)`|
|Hardware [incl. revision]|`Raspberry Pi 3 Model B Rev 1.2`|
|System-Architecture|`Linux ginger 6.1.0-rpi4-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.54-1+rpt2 (2023-10-05) aarch64 GNU/Linux`|
|thin-edge.io version|`tedge 0.13.1~12+g5dcb430`|

**Additional context**

**Comment by PradeepKiruvale** [comment]
Went with Case 2.
To verify follow the steps mentioned above and observe the below log message

```
INFO tedge_agent::restart_manager::actor: tedge-agent state file is not present
```

**Comment by gligorisaev** [comment]
QA has thoroughly checked the bug and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the bug and could not reproduce it anymore.
