### ISSUE TITLE
use qos 0 when publishing to c8y/s/uat to request a Cumulocity IoT token

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2417]
**Is your feature improvement request related to a problem? Please describe.**

Publishing with qos=1 when requesting a Cumulocity IoT does not makes sense as these requests should not be buffered in case the bridge connection to Cumulocity is down (e.g. due to lack of connectivity). The buffered messages would just unnecessary multiple requests for a token upon reconnection.

This causes some other unexplained consequences as described here: https://github.com/thin-edge/thin-edge.io/issues/2412

**Describe the solution you'd like**

Use qos=0 when publishing to the `c8y/s/uat` topic.

**Describe alternatives you've considered**

**Additional context**

**Comment by didier-wenzek** [comment]
We also need to fix the bridge definition, where `s/uat` and `s/dat` are currently bridged with QoS 2. Should be 0.

**Comment by PradeepKiruvale** [comment]
Steps to test:

```

1. Install the thin-edge

2. apt get install mosquitto_clients
 
3. On one terminal run below commands to subscribe to check the qos of the messages that are being sent
4. mosquitto_sub -t 'c8y/s/#' -v -d
 
5. On the other terminal run the below command 
   tedge connect c8y

6. Observe the below messages on the subscribe terminal, **q0** must be there.

 c8y/s/uat (null)
Client null received PUBLISH (d0, **q0,** r0, m0, 'c8y/s/dat', ... (795 bytes))
 
7. If failed to capture those messages, then run below command
 
8. tedge connect c8y --test

9. Then observe the above mentioned message (The jwt request message)

```

**Comment by didier-wenzek** [comment]
> 6. Observe the below messages on the subscribe terminal, **q0** must be there.

Beware, that QoS is extremely misleading: this is the QoS of the message received by the `mosquitto_sub` command and *not* the QoS of the message published by the mapper or the tedge command. By default,  `mosquitto_sub`  uses `-q 0`. To observe the original QoS you have to run mosquitto_sub`  with `-q 2`. In this case, messages will be received with their original QoS (the minimum between 2 and the original QoS).

So the command to run is:

```
$ mosquitto_sub -t 'c8y/s/#' -v -d -q 2
```

**Comment by reubenmiller** [comment]
> > 6. Observe the below messages on the subscribe terminal, **q0** must be there.
> 
> Beware, that QoS is extremely misleading: this is the QoS of the message received by the `mosquitto_sub` command and _not_ the QoS of the message published by the mapper or the tedge command. By default, `mosquitto_sub` uses `-q 0`. To observe the original QoS you have to run mosquitto_sub` with`-q 2`. In this case, messages will be received with their original QoS (the minimum between 2 and the original QoS).
> 
> So the command to run is:
> 
> ```
> $ mosquitto_sub -t 'c8y/s/#' -v -d -q 2
> ```

Thanks for that tip. I also updated the instructions to reflect your recommendation.

**Comment by gligorisaev** [comment]
> > > 6. Observe the below messages on the subscribe terminal, **q0** must be there.
> > 
> > 
> > Beware, that QoS is extremely misleading: this is the QoS of the message received by the `mosquitto_sub` command and _not_ the QoS of the message published by the mapper or the tedge command. By default, `mosquitto_sub` uses `-q 0`. To observe the original QoS you have to run mosquitto_sub` with`-q 2`. In this case, messages will be received with their original QoS (the minimum between 2 and the original QoS).
> > So the command to run is:
> > ```
> > $ mosquitto_sub -t 'c8y/s/#' -v -d -q 2
> > ```
> 
> Thanks for that tip. I also updated the instructions to reflect your recommendation.

@reubenmiller does @PradeepKiruvale needs to do some changes in the code as well?

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the bug and could not reproduce it anymore.
