### ISSUE TITLE
tedge-apt-plugin: support settings to control if configuration files are kept or replaced when included in a debian package

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2418]
**Is your feature improvement request related to a problem? Please describe.**

When installing debian packages via the tedge-apt-plugin (software management plugin), there is no way for the user to configure how debian should handle overriding any configuration files that is included as part of the debian package (.deb file). When no option is provided, the installation always fails.

Below is an example of the software update logs of a failure due to the lack of configuration during an installation of a debian package via the tedge-apt-plugin:

```
Preparing to unpack .../tedge-collectd-setup_0.0.1_all.deb ...
Unpacking tedge-collectd-setup (0.0.1) ...
Setting up tedge-collectd-setup (0.0.1) ...

Configuration file '/etc/collectd/collectd.conf'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** collectd.conf (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package tedge-collectd-setup (--configure):
 end of file on stdin at conffile prompt
Errors were encountered while processing:
 tedge-collectd-setup
EOF

stderr <<EOF
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
E: Sub-process /usr/bin/dpkg returned an error code (1)
EOF
```

**Describe the solution you'd like**

New configuration option in the tedge.toml (similar to the apt.name, apt.maintainer options) which controls the handling of the configuration file overriding (e.g. keep the old config or use the new config).

The configuration option should be passed to `apt` via the `-o DPkg::Options::=<option>` syntax when called from within `tedge-apt-plugin` when installing a package. Below shows an example of both options

**Option 1: To keep the new files by default**

```
sudo apt-get -o DPkg::Options::=--force-confnew -y install package-name
```

**Option 2: keep the old version**

```
sudo apt-get -o DPkg::Options::=--force-confold -y install package-name
```

**Describe alternatives you've considered**

The dpkg setting can be configured on an operating system level, however that would caused unexpected consequences as the global setting would affect both tedge-apt-plugin installations as well as manual ones, the latter being more problematic for local installs. Local installs should be prompted as normal as the user is there to decide what makes more sense (e.g. keep the old config file, or use the new one).

A suggestion of the setting name (please update if the configuration names are changed in the implementation):

```
[apt]
dpk.options.config = "keepold|keepnew"
```

**Additional context**

Reference describing the passing of the configuration override preferences:
* https://stackoverflow.com/questions/7156320/apt-error-file-on-system-created-by-you-or-by-a-script

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/RobotFramework/tests/plugin_apt/install_overwrite_config_files.robot
- [x] QA has tested the function and it's functioning according description.
