### ISSUE TITLE
tedge cert upload c8y: ambiguous file/folder not found error - missing path in error message

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2419]
**Is your feature improvement request related to a problem? Please describe.**

When trying to upload the device certificate to Cumulocity IoT using `tedge cert upload c8y`, the command failed with a `No such file or directory` error, however it did not mention which file/folder does not exists which makes it very difficult to fix the issue.

The following shows the error messages printed to the console:

```
$ tedge cert upload c8y --user myuser@example.com
Enter password:
Error: failed to upload root certificate

Caused by:
    0: I/O error
    1: No such file or directory (os error 2)
```

After doing my own debugging it was found that the `ca-certificates` package was not installed, so most likely the command was failing because the `/etc/ssl/certs` folder did not exist.

**Describe the solution you'd like**

The above error message should always included the path to the file/directory which does not exist to better explain to the user why the command failed so that they can fix the issue.

**Describe alternatives you've considered**

**Additional context**

**Comment by PradeepKiruvale** [comment]
To verfiy the fix:

```
Install   thin-edge
```
```
sudo tedge config set c8y.root_cert_path /etc/ssl/certs_test

```

```    
sudo tedge cert upload c8y --user <user>
```

The output of the above command must be as below
```
Root certificate path /etc/ssl/certs_test does not exist
```
   
Revert the root path to default value
```    
sudo tedge config unset c8y.root_cert_path
```

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/RobotFramework/tests/tedge/tedge_upload_cert.robot
- [x] QA has tested the function and it's functioning according description.
