### ISSUE TITLE
flaky system test: Test if all c8y services are using configured service type

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2423]
**Describe the bug**

Flaky system test detected:

Test name:

```
Test if all c8y services are using configured service type
```

Flaky runs:
* https://github.com/thin-edge/thin-edge.io/actions/runs/6771457307/job/18402278699?pr=2422

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/thin-edge/thin-edge.io/assets/3029781/6e6d0b13-d278-4f29-9a38-4ace3290a5d8)

**Environment (please complete the following information):**
 - OS [incl. version]: `Debian 11`
 - Hardware [incl. revision]: `ci runner`
 - System-Architecture [e.g. result of "uname -a"]: `x86_64`
 - thin-edge.io version [e.g. 0.1.0]: `0.13.x`

**Additional context**

**Comment by reubenmiller** [comment]
flaker-finder report after only 10 iterations:

```
DOCKER_OPTIONS_CPU_QUOTA=5000
DOCKER_OPTIONS_CPU_PERIOD=20000

Overall: FAILED
Results: 10 iterations, 7 passed, 3 failed
Elapsed time: 0:25:59.420904
Failed iterations: [4, 7, 9]
```

[issue-2423-log-files.zip](https://github.com/thin-edge/thin-edge.io/files/13272164/issue-2423-log-files.zip)

**Comment by albinsuresh** [comment]
Another failure instance: https://github.com/thin-edge/thin-edge.io/actions/runs/7276029491/job/19825181171?pr=2540

**Comment by reubenmiller** [comment]
Closing as issue has not been seen for 2 weeks after merging the fix. Please reopen if it is seen again
