### ISSUE TITLE
Merge all tedge plugins into a single service

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#2433]
**Is your feature request related to a problem? Please describe.**

Customers wanting the complete device management capabilities need to install too many separate plugins/components and manage them. It leads to high memory usage as well. So, it would be better if all the device management functionalities were served by a single component.

**Describe the solution you'd like**

Merge the following components into `tedge-agent`:
* [x] tedge-config-plugin
* [x] tedge-log-plugin

The upcoming `tedge-firmware-plugin` (created out of the `c8y-firmware-plugin`) will also be merged into it later, once available.
The mappers will stay as separate components and won't be merged.

The merging must be done by re-using the existing plugin actors, by just connecting them all into a single binary. The existing plugins won't be replaced by this task. The new plugin will only act like an auxiliary all-in-one plugin for now but will replace all the other plugins eventually, in a separate task.

**Comment by reubenmiller** [comment]
> Why yet another `tedge-device-management` plugin? Why not adding support for log, config and firmware to `tedge-agent`.
> 
> I do think it's better to keep the former name. Too many changes would be confusing.
> 
> I thought that this `tedge-device-management` plugin was only a way to experiment and to change `tedge-agent` packaging only when fully ready. Is this the plan?

The `tedge-device-management` is only a place holder until we are ready to replace the existing tedge-agent (as this will be done across multiple PRs)

**Comment by reubenmiller** [comment]
I've update the description to reflect the current state (merging plugins into `tedge-agent`)

**Comment by reubenmiller** [comment]
Testing is fairly simple as it requires checking that the same functionality as previously provided by tedge-log-plugin and tedge-configuration-plugin are now provided in tedge-agent. The former packages are no longer installed by default.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the function and it's functioning according description.
