### ISSUE TITLE
custom operation quoting causes operation results to be parsed incorrectly on the server

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2438]
**Is your feature improvement request related to a problem? Please describe.**

The Cumulocity IoT smart rest message id `503` expects the "results" from the operation to be provide in the format of csv.

Currently the standard output of the custom operation script/binary is processed and converted to a single csv entry, e.g.

```
[c8y/s/us] 503,c8y_Command,"some random output"
```

However for the `c8y_RelayArray` operation (related to the [519](https://cumulocity.com/guides/reference/smartrest-two/#relayarray-519) message id), the double quotes surrounding the result causes the server to interpret the operation's results incorrectly, as the server is expecting the values to be unquoted.

The  following shows the current behaviour (as of 0.13.0) and the expected behavior.

**Current (erroneous) - as of 0.13.0**

```
[c8y/s/ds] 519,ginger,CLOSED,OPEN
[c8y/s/us] 501,c8y_RelayArray
[c8y/s/us] 503,c8y_RelayArray,"CLOSED,OPEN"
```

**Expected**
```
[c8y/s/ds] 519,ginger,CLOSED,OPEN
[c8y/s/us] 501,c8y_RelayArray
[c8y/s/us] 503,c8y_RelayArray,CLOSED,OPEN
```

**Describe the solution you'd like**

An new option that can be used in the custom operation definition file to declare what the format of the result is provided in by the custom operation handler (e.g. the script/binary being called).

The `result_format` (string value) declares one of the following options:
* text - the result should be treated as one value when creating the SmartREST message (this is currently the default functionality, and should remain unchanged)
* csv - the result should be treated as multiple values and no quoting should be applied around the result as this would change how the server would interpret the results.

For example the following is a custom operation definition:

**File: /etc/tedge/operations/c8y/c8y_RelayArray**

```toml
[exec]
topic = "c8y/s/ds"
on_message = "519"
result_format = "csv"    # <== New option to control whether the result is handled as a single or multiple values
command = "/usr/bin/run-control-gpio.sh"
```

**Describe alternatives you've considered**

Previous suggestion:

Use a `quote_result` property to control whether the result is quoted or not. However this approach is not as future proof/flexible as the `result_format` option.

**File: /etc/tedge/operations/c8y/c8y_RelayArray**

```toml
[exec]
topic = "c8y/s/ds"
on_message = "519"
quote_result = false    # <== New property which disables quoting, default = true
command = "/usr/bin/run-control-gpio.sh"
```

**Additional context**

* https://cumulocity.com/guides/reference/smartrest-two/#updating-operations

**Comment by albinsuresh** [comment]
Instead of doing this at a per-operation level, how about updating our main SmartREST quoting logic itself, to add those quotes only when required: when the provide text contains white-space characters or other special characters that requires quoting?

**Comment by reubenmiller** [comment]
> Instead of doing this at a per-operation level, how about updating our main SmartREST quoting logic itself, to add those quotes only when required: when the provide text contains white-space characters or other special characters that requires quoting?
> 
> Even for this specific case, I'd just update the 503 response logic of custom operations to **not** not sanitize the output when `,` chars are already present in the provided text, as the SmartREST protocol [allows sending multiple parameters](https://cumulocity.com/guides/10.11.0/reference/smartrest-two/#503) in a 503 response. We should not assume that it is a single value and sanitize it by putting quotes around it.
> 
> Obviously, if the command output contains some random `,` chars as part of some text, it would mess up this logic, and to avoid such cases, we can use the `quote_result` option that you proposed, where the user will have to explicitly set it to `true`, as `false` would be the default to support multiple parameters.

Unfortunately this is not possible as there are other smart rest messages which are "free-form" (e.g. c8y_Command) which do not limit which characters are allowed or not so the result can include commas.

The per-operation setting is the way to go as the contact with the server is on a per operation basis (as detail in the [Cumulocity IoT updating operations](https://cumulocity.com/guides/10.11.0/reference/smartrest-two/#updating-operations) section.

Though maybe the name "quote_result" is not 100% correct, it is more saying that it expects N csv fields in the response, where as something like the c8y_Command output only expects 1 csv field to be returned. However having an "expected number of csv fields" the result is meant to return might proof more difficult as we would have to do proper csv parsing then (e.g. split on commas, except when included in quotes etc.)

**Comment by albinsuresh** [comment]
> The per-operation setting is the way to go as the contact with the server is on a per operation basis (as detail in the [Cumulocity IoT updating operations](https://cumulocity.com/guides/10.11.0/reference/smartrest-two/#updating-operations) section.

Yeah, I'm completely fine with the per operation control, but the disagreement in only on what the default behaviour should be. Currently, we're always putting quotes around the output text, even though the 503 contract supports multiple parameters. That assumption seems wrong to me. So, all I'm saying is that the default behaviour should expect `,` chars in the output and not quote them, which can be overridden by that `quote_result` option by explicitly asking the output to be quoted when needed (for ops like `c8y_Command`).

**Comment by reubenmiller** [comment]
Though given that the `c8y_RelayArray` is the only operation that is expected to provide multiple results, I think it is much safer as a default to assume the response of the custom operation is related to a single csv field

**Comment by reubenmiller** [comment]
Or what about an option like this:

```
# For multiple csv formated results
result_format = "csv"

# For simple text
result_format = "text"
```

**Comment by albinsuresh** [comment]
> Or what about an option like this:
> 
> ```
> # For multiple csv formated results
> result_format = "csv"
> 
> # For simple text
> result_format = "text"
> ```

Looks better. In future, when we switch from SmartREST to notifcations 2.0 API, we might even wanna support a `result_format = "json"`.

**Comment by reubenmiller** [comment]
I've updated the issue description with the new proposal and kept the previously proposed solution in the "alternative solutions"  section.

**Comment by reubenmiller** [comment]
Implementation was done as per the issue description.

* system tests - [custom_operation_c8y_RelayArray/operation_relay_array.robot](https://github.com/thin-edge/thin-edge.io/blob/02dc80d097e3e15716adcc9758b777b0c7b9bae1/tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_c8y_RelayArray/operation_relay_array.robot)

**Comment by reubenmiller** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- [x] QA has tested the bug and could not reproduce it anymore.

**Detailed results**

Using a custom operation definition for the `c8y_RelayArray` operation and using the new `result_format = "csv"` option, everything works as expected.

**File: /etc/tedge/operations/c8y/c8y_RelayArray**

```toml
[exec]
# c8y_RelayArray
topic = "c8y/s/ds"
on_message = "519"
result_format = "csv"
command = "/usr/bin/run-control-gpio.sh"
```

Then sending the c8y_RelayArray operation from Cumulocity to thin-edge.io results in the expected 503 smart rest message:

```
[c8y/s/ds] 519,ginger,OPEN,CLOSED
[c8y/s/us] 501,c8y_RelayArray
[c8y/s/us] 503,c8y_RelayArray,OPEN,CLOSED
```
