### ISSUE TITLE
create sm-plugin directory by default as part of initialization

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2444]
**Is your feature improvement request related to a problem? Please describe.**

The software management plugin folder (default path `/etc/tedge/sm-plugins`) is not created by default.

On Debian OS, the `tedge-apt-plugin` is usually installed which will create the above folder, however non Debian based systems, this folder does not exist, and it is not so obvious to users which folder the software plugins should be placed in without having to look up documentation.

**Describe the solution you'd like**

The software plugin folder should be created by default so that it is easier for users to discover where to put custom software management plugins and so the permissions of the folder are set to the expected values (required by the tedge-agent to access the folder).

**Describe alternatives you've considered**

**Additional context**

**Comment by rina23q** [comment]
Resolved by @2469. The directory gets created by `tedge init`

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the function and it's functioning according description.
