### ISSUE TITLE
use independent tedge.toml settings to access the c8y proxy server provided by tedge-mapper-c8y

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2445]
**Is your feature improvement request related to a problem? Please describe.**

The `c8y.proxy.bind.address` setting is used by two different components but for different purposes,

1. tedge-mapper-c8y interprets this setting as the bind address where the c8y proxy server should be made available
2. tedge-mapper-c8y interprets this setting as the address when providing a url for child devices/components to reach the c8y proxy server from (for example, the c8y proxy endpoint is used in Cumulocity IoT software update commands)

The different in the interpretation of the two settings makes it difficult to configure the tedge-mapper-c8y address, as it needs to know the ip address of the tedge-mapper-c8y, and it can't use a hostname (as the setting only accepts an ip address, in the form of `x.x.x.x`). When using thin-edge.io in containers generally the container does not know the ip address of each other upfront, but rather at runtime, that is where using a hostname would be more useful when telling the tedge-mapper-c8y when creating the url which child devices can access the c8y proxy server from. 

This problem is not too dissimilar to the changes which prompted splitting the `mqtt.bind.address` and `mqtt.client.host` settings.

**Describe the solution you'd like**

Create the following new settings which are used by the tedge-mapper-c8y:

* `c8y.proxy.client.host` - ip or hostname of the http server (c8y proxy service) provided by the tedge-mapper-c8y
* `c8y.proxy.client.port` - port of the http server (c8y proxy service) provided by the tedge-mapper-c8y

**Describe alternatives you've considered**

**Additional context**

**Comment by Bravo555** [comment]
# QA reproduction instructions

Following things need to be checked:

- new config options are present
- `c8y.proxy.client.host` can use a hostname
- when C8y proxy server and other components that talk to it run on separate devices (or containers), setting newly added options allow the component running in the container `B` to reach C8y container running on container `A`.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/RobotFramework/tests/tedge/call_tedge_config_list.robot
- [x] QA has tested the function and it's functioning according description.
