### ISSUE TITLE
support running thin-edge.io pre start initialization tasks with elevated rights

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2448]
**Is your feature improvement request related to a problem? Please describe.**

When installing thin-edge.io on systems where the `/var/log` folder is volatile (e.g. on default settings of Yocto Linux) and does not allow other non-root users to create sub-folders (e.g. `/var/log/tedge`), it causes the `tedge-agent` to fail on startup.

If if the `/var/log` permissions were changed at runtime, the `/var/log` is re-created on every system boot (since it is volatile), so any initialization logic that would have to be run every time the service starts.

**Describe the solution you'd like**

The solution entails being able to run some initialization logic with elevated privileges before the main binary is called. This would allow the correct initialization of folder which the service user might not normally have access to be modified without having to run the main binary as root.

To be able to provide this solution it involves two parts:

1. The `tedge init` command should create the required log folder (e.g. default `/var/log/tedge`)

2. Modify the thin-edge.io service definitions to include an extra initialization (namely running `tedge init`)

    The `tedge init` command should be executed when the service starts up and executed as root.
    
    In systemd, this can be done by using a combination of the `ExecStartPre` command along with prefixing a "+" sign which indicates that the command should be executed with root privileges, see the [systemd docs](https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#Command%20lines) for more details. Note `ExecStart` will still start as the user defined by `User=`.

    Below shows an example of a modified tedge-agent.service systemd definition:

    ```sh
    [Service]
    User=tedge
    ExecStartPre=+-/usr/bin/tedge init
    ExecStart=/usr/bin/tedge-agent
    ```
    Note: both "+" and "-" are used here together to indicate that `ExecStartPre` should be executed with elevated privileges and "-" to ignore if the `tedge init` fails for any reason that the agent should still try to start (in case if there are any init issues)
    

**Describe alternatives you've considered**

**Alternative 1: Start as root then switch to tedge user**

The service could be called as root, do the required initialization, then switch to the `tedge` user. This is what [mosquitto does](https://github.com/eclipse/mosquitto/blob/master/service/systemd/mosquitto.service.simple).

**Alternative 2: Run as root**
The only valid alternative would be to force users to have to specify another folder where the tedge has write access to, however this would then be further customization required for different installation environments, rather than an out-of-the-box solution.

**Additional context**

Note: The usage of the `+` prefix is only supported in systemd versions >= 231.

thin-edge.io will be dropping support out-of-the-box support for systemd < 231. Most linux distributions which use an older systemd version are either in End-Of-Line (EOL) or will be soon EOL (e.g. CentOS 7 will be [EOL in June 2024](https://www.redhat.com/en/topics/linux/centos-linux-eol))

User's can still use thin-edge.io with older systemd versions, however they will have to modify the service definitions to:

```
PermissionsStartOnly=true
ExecStartPre=-/usr/bin/tedge init
```

Below shows a list of versions across different linux distributions, however it is not exhaustive, but it gives an overview that there are still some older distributions which use systemd < 231.

https://repology.org/project/systemd/versions

**Comment by reubenmiller** [comment]
Checkout the updated robot tests which show how using custom paths no longer have to manually created before starting the service:

* tests/RobotFramework/tests/customizing/data_path_config.robot
* tests/RobotFramework/tests/customizing/log_path_config.robot

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/RobotFramework/tests/customizing/data_path_config.robot
- tests/RobotFramework/tests/customizing/log_path_config.robot
- [x] QA has tested the function and it's functioning according description.
