### ISSUE TITLE
logs.path location should be explicit rather than implicit

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2449]
**Is your feature improvement request related to a problem? Please describe.**

The tedge configuration item `logs.path` does not explicitly indicate the folder used by thin-edge.io

Currently thin-edge.io creates an implicit sub-folder `tedge` under the path configured by `logs.path`. This implicit nature makes it harder for users and other applications to consume.

For example some problems would be:

* Custom cleanup tasks (e.g. manually delete the `logs.path` folder used by tedge, user's would have to guess that the sub-folder is called `tedge`)
* Using a custom path like `tedge config set logs.path /opt/logs/tedge` leads to thin-edge.io creating double tedge nested folders, e.g. `/opt/logs/tedge/tedge`. Alternatively users could set `/opt/logs` however it would mean that `/opt/logs` would have to be writable by the tedge user (which may not be the case since the name is so generic). Though this would be solved by https://github.com/thin-edge/thin-edge.io/issues/2448

**Describe the solution you'd like**

The solution is simple:
* thin-edge.io components should use the `logs.path` as the base folder, and the nested folder `tedge` should not be implied
* the `logs.path` config should have a default value of `/var/log/tedge`

**Describe alternatives you've considered**

**Additional context**

**Comment by PradeepKiruvale** [comment]
Steps to verify the PR:
1. Install the thin-edge
2. Verify the logs.path default value using the `tedge` tool
list the tedge config
 ```
 sudo tedge config list
```
The logs.path must be set to `/var/log/tedge`
Note: In the older version, the default value was `/var/log`.

3. Set logs.path to some value and verify
```
sudo tedge config set logs.path /tmp/test
```
Start the tedge-agent
```
sudo systemctl start tedge-agent.service
```
Verify that the `agent` directory that is set inside the /tmp/test directory
```
ls /tmp/test/agent
```
the directory must exist

Note: In the earlier version it used to be `/tmp/test/tedge/agent`.
