### ISSUE TITLE
Updating `/etc/tedge/plugins/tedge-log-plugin.toml` results in multiple `log_upload` metadata messages being sent

### ISSUE THREAD

**Issue by Bravo555** [thin-edge/thin-edge.io#2451]
**Describe the bug**

When saving a modification to `/etc/tedge/plugins/tedge-log-plugin.toml`, multiple `log_upload` messages are created, resulting in multiple `118` Smartrest messages being sent:

```
(`tedge-log-plugin.toml` saved)

[te/device/main///cmd/log_upload] {"types":[]}
[te/device/main///cmd/log_upload] {"types":[]}
[c8y/s/us] 118,
[c8y/s/us] 118,
[te/device/main///cmd/log_upload] {"types":["mosquitto","software-management"]}
[te/device/main///cmd/log_upload] {"types":["mosquitto","software-management"]}
[te/device/main///cmd/log_upload] {"types":["mosquitto","software-management"]}
[te/device/main///cmd/log_upload] {"types":["mosquitto","software-management"]}
[c8y/s/us] 118,mosquitto,software-management
[c8y/s/us] 118,mosquitto,software-management
[c8y/s/us] 118,mosquitto,software-management
[c8y/s/us] 118,mosquitto,software-management
```

Messages with empty `"types"` parameter can appear when saving the file with `vim`. Here's the relevant log output:

```
2023-11-14T16:57:49.406620439Z DEBUG Log Manager: recv Some(FsWatchEvent(Modified("/etc/tedge/plugins/tedge-log-plugin.toml")))    
2023-11-14T16:57:49.40664234Z  INFO log_manager::config: Using the configuration from /etc/tedge/plugins/tedge-log-plugin.toml    
2023-11-14T16:57:49.40667632Z  WARN log_manager::config: The config file /etc/tedge/plugins/tedge-log-plugin.toml does not exist or is not readable.    
```

When this file can't be read, an empty types list is used. It would be better not to send the message in this case.

Additionally, to not produce duplicate messages, a debouncer can be used, as described in [`notify` crate documentation](https://docs.rs/notify/latest/notify/#installation). 

**To Reproduce**

1. Open `/etc/tedge/plugins/tedge-log-plugin.toml` with vim.
2. Modify the file (optional, in my case duplicate messages are produced even if no modifications were introduced)
3. Save the file
4. Duplicate messages are sent to `te/device/main///cmd/log_upload`

**Expected behavior**

At most 1 `log_upload` metadata message should be sent.

**Comment by reubenmiller** [comment]
Yes this is a by-product for the multiple inotify events that get produced in very short succession which triggers the actor messages.

**Comment by reubenmiller** [comment]
After doing some more testing, editing the `tedge-log-plugin.toml` using `vi` yields multiple messages (though `vim.tiny` is ok).

For example:

```sh
vi /etc/tedge/plugins/tedge-log-plugin.toml
```

Yields the following mqtt messages:

```
[te/device/main///cmd/log_upload] {"types":["c8y_Command","firmware_update","software-management"]}
[te/device/main///cmd/log_upload] {"types":["c8y_Command","firmware_update","software-management"]}
[te/device/main///cmd/log_upload] {"types":["c8y_Command","firmware_update","software-management"]}
[c8y/s/us] 118,c8y_Command,firmware_update,software-management
[c8y/s/us] 118,c8y_Command,firmware_update,software-management
[c8y/s/us] 118,c8y_Command,firmware_update,software-management
```

`vi` is still preferred on some devices (e.g. it is the default in yocto as vi is included in busybox).

**Comment by Bravo555** [comment]
# QA instructions

For configuration files of `tedge-log-plugin` and `tedge-configuration-plugin`, for any single change made with any editor (I tested vi, vim, neovim and nano), only one message is emitted on a given topic.

In case of `tedge-configuration-plugin`, an edit results in 2 messages being published, one each for 2 topics: `te/device/main///cmd/config_snapshot` and `te/device/main///cmd/config_update`, which is expected.

I haven't written a Robot Framework test for it because the editors are interactive programs, so I expect trying to spawn them and simulate inputs in a test would be tricky, and I'm not sure if worth the effort. However I added a Rust unit test to `notify` crate to make sure that on the API side at least, debouncing works as expected.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the bug and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the bug and it's not reproducable anymore
