### ISSUE TITLE
create public operations/c8y folder on init to prevent user misconfiguration from other packages

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2452]
**Is your feature improvement request related to a problem? Please describe.**

Reduce the potential for misconfiguration of the `operation/c8y` folder by creating it during the intialization process.

Since the `/etc/tedge/operations/c8y` is a public folder where custom operation configurations are placed by users, it opens up the potential for accidentally creating the `/etc/tedge/operations/c8y` folder with the incorrect ownership resulting in the inability for the thin-edge.io components to create files under the folder.

For example, this happened in the community plugin, [c8y-command-plugin](https://github.com/thin-edge/c8y-command-plugin). This package added the file `/etc/tedge/operations/c8y/c8y_Command` with the owner `tedge`, however if the parent folder (`/etc/tedge/operations/c8y`) does not exist when the package is installed, then the parent folder is created with root permissions (due to how the OS's package manager handles these situations).

**Describe the solution you'd like**

The exact solution is unclear (and up for discussion), but so far the options would be:

**Option 1: Create folder during tedge init**

Initialize the following folder when `tedge init` is called

* `/etc/tedge/operations/c8y`

**Describe alternatives you've considered**

**Additional context**

* [nfpm definition](https://github.com/thin-edge/c8y-command-plugin/blob/5f648395936519e2d0e9d05b7ab8a2aca6e3012e/nfpm.yaml#L17) used to create the c8y-command-plugin package

**Comment by rina23q** [comment]
Resolved by @2469. The directory gets created by `tedge init`

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the function and it's functioning according description.
