### ISSUE TITLE
Support HTTPS and client authentication for the file transfer service

### ISSUE THREAD

**Issue by jarhodes314** [thin-edge/thin-edge.io#2475]
Following the completion of #2363, it makes sense to add the same functionality to the file transfer service, (configured using keys under `http.` instead of `c8y.proxy.`).

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/RobotFramework/tests/cumulocity/configuration/configuration_with_file_transfer_https.robot
- tests/RobotFramework/tests/cumulocity/log/log_operation.robot
- tests/RobotFramework/tests/mqtt/remote_mqtt_broker.robot
- [x] QA has tested the function and it's functioning according description.
