### ISSUE TITLE
Finalize Operation Workflow

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#2478]
## For 1.0:
- [x] Use script exit status when there is no JSON output
      See comments: https://github.com/thin-edge/thin-edge.io/pull/2071#discussion_r1268024883
      and https://github.com/thin-edge/thin-edge.io/pull/2071#discussion_r1394172319
      and https://github.com/thin-edge/thin-edge.io/pull/2071#discussion_r1401621879
- [x] Find a better to define a restart action
      See https://github.com/thin-edge/thin-edge.io/pull/2479#discussion_r1405693285
      and https://github.com/thin-edge/thin-edge.io/pull/2479#discussion_r1405695594
      and https://github.com/thin-edge/thin-edge.io/pull/2479#discussion_r1411677398
- [x] Log workflow execution 
- [x] Set timeouts on operation steps
- [x] Trigger a device restart (which is triggered by the workflow script itself)
- [x] Trigger an agent coordinated device restart
- [x] Clarify the purpose of the *owner* setting
      See comments: https://github.com/thin-edge/thin-edge.io/pull/2071#discussion_r1268026377
      and https://github.com/thin-edge/thin-edge.io/pull/2071#discussion_r1268207295
- [x] Update the example used in the doc
      See comments: https://github.com/thin-edge/thin-edge.io/pull/2071#discussion_r1401610417
- [x] Clarify the concurrency/ sequential model

## For 1.0, if useful to support firmware management:
- [x] Clarify how a json excerpt is extracted from script output
      See https://github.com/thin-edge/thin-edge.io/pull/2479#discussion_r1411695470
- [ ] Download action making a cloud file locally available
      See comments: https://github.com/thin-edge/thin-edge.io/pull/2071#discussion_r1392990394
- [ ] Consider to add the source state causing an error
      See comments: https://github.com/thin-edge/thin-edge.io/pull/2071#discussion_r1267972097
 
## For later:
- [ ] Consider to combine and override several workflow definitions
      See comments: https://github.com/thin-edge/thin-edge.io/pull/2071#discussion_r1268016020
      and https://github.com/thin-edge/thin-edge.io/pull/2071#discussion_r1268042933
- [ ] Consider a way to publish events/alarms when reaching a state
      See comments: https://github.com/thin-edge/thin-edge.io/pull/2071#discussion_r1266393389
- [ ] Ensure there is one and only one workflow responsible for moving forward a command in a given state
      See comments: https://github.com/thin-edge/thin-edge.io/pull/2071#discussion_r1322842781

**Comment by didier-wenzek** [comment]
Agent restart has been implemented by https://github.com/thin-edge/thin-edge.io/pull/2479

- Documentation: https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/references/agent/operation-workflow.md#restart-action
- Example workflow: https://github.com/thin-edge/thin-edge.io/blob/main/tests/RobotFramework/tests/tedge_agent/workflows/custom_restart.toml
- Test: https://github.com/thin-edge/thin-edge.io/blob/main/tests/RobotFramework/tests/tedge_agent/workflows/custom_operation.robot#L29

**Comment by didier-wenzek** [comment]
Workflow logging has been implemented by https://github.com/thin-edge/thin-edge.io/pull/2479

- All the steps of each operation instance are logged in a file specific to the operation instance.
- These logs are stored in the `agent` sub-directories of the `$(tedge config get logs.path)` directory.
- Each log file is named after the operation name and the command instance identifier .e.g. `workflow-software_list-c8y-mapper-2023-11-30T20:02:32.970449918Z.log`

**Comment by didier-wenzek** [comment]
The following points have been addressed by this PR: https://github.com/thin-edge/thin-edge.io/pull/2496

- Use script exit status when there is no JSON output
- Use script stdout excerpt not only on success but also expected exit codes.
- A better to define a restart action (using a single state setting for now, the proposal for restart/restarting states has not been implemented yet).
- Set timeouts on running a script (timeout persisting across restart has not been implemented yet)
- Support for background scripts, a use-case being to trigger a device restart. There is still a caveat: the user has to provide its own script to detect a successful reboot/restart.
- The `owner` and `next` settings have been deprecated.
- The example has been updated

**Comment by didier-wenzek** [comment]
The main concurrency bug https://github.com/thin-edge/thin-edge.io/issues/2495 is addressed by https://github.com/thin-edge/thin-edge.io/pull/2527

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the function and it's functioning according description.
