### ISSUE TITLE
Config setting to disable auto-registration of entities

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#2483]
**Is your feature improvement request related to a problem? Please describe.**

When a customer wants to use explicit entity registration, while still using the default topic scheme (`te/device/<device-id>/service/<service-id>`), there is the possibility of the auto-registration logic conflicting with the explicit registration messages, resulting in the creation of entities with the wrong metadata.

**Describe the solution you'd like**

When a user has committed to use explicit registration, he should be able to completely disable the auto-registration mechanism using the following config setting:

```toml
[c8y.entity_store]
auto_register = false
```

The default value should be `true`.

**Describe alternatives you've considered**

Instead of a mapper specific setting, it could have been global tedge setting as well. But, since the auto-registration is currently handled differently by each mapper, it is better to keep it at a mapper level. In future, we can consider adding a global setting, which can be overridden at mapper level.

**Additional context**

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/RobotFramework/tests/aws/aws_telemetry.robot
- tests/RobotFramework/tests/cumulocity/registration/device_registration.robot
- [x] QA has tested the function and it's functioning according description.
- [x] Documentation existing
- docs/src/references/mappers/c8y-mapper.md
