### ISSUE TITLE
Workflow script of failed state not tolerant to failures

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#2484]
**Is your feature improvement request related to a problem? Please describe.**

If your workflow has `script` specified for the `failed` state with a command that does not generate the desired JSON output as follows:

```toml
[failed]
script = "tedge mqtt pub --retain ${.topic} ''"
next = []
```

If the workflow execution transitions to the `failed` state (due to the failure of an intermediate state), it will result in an infinite loop of failed status messages sent to the broker by the agent as follows:

```
te/device/main///cmd/software_list/robot-123 {"status":"init"}
te/device/main///cmd/software_list/robot-123 {"reason":"Script /etc/tedge/operations/init-software-list.sh ${.topic} failed with: ","status":"failed"}
te/device/main///cmd/software_list/robot-123 {"reason":"Script /etc/tedge/operations/init-software-list.sh ${.topic} failed with: ","status":"failed"}
te/device/main///cmd/software_list/robot-123 {"reason":"Script /etc/tedge/operations/init-software-list.sh ${.topic} failed with: ","status":"failed"}
te/device/main///cmd/software_list/robot-123 {"reason":"Script /etc/tedge/operations/init-software-list.sh ${.topic} failed with: ","status":"failed"}
te/device/main///cmd/software_list/robot-123 {"reason":"Script /etc/tedge/operations/init-software-list.sh ${.topic} failed with: ","status":"failed"}
...
```

This is because the failure of the script execution in any state makes the workflow execution move to the terminal `failed` state. But, since it is the `script` in the failed state itself that fails here, it will keep moving to the `failed`state again, script execution will fail again and this loop will go on forever.

**Describe the solution you'd like**

Even if the `script` of the `failed` state fails, it should result in a hard failure without reattempting the same `script` execution again and again.

**Describe alternatives you've considered**

Not allowing any scripts to be attached to the terminal states will also solve this problem.

But the ability to execute a command on terminal states could be useful in certain cases like automatically clearing those commands once they are complete (as attempted in the above workflow example)

**Comment by didier-wenzek** [comment]
Fixed by https://github.com/thin-edge/thin-edge.io/pull/2537.

Warning: the implemented solution is not the proposed one, but the alternative : __Not allowing any scripts to be attached to the terminal states will also solve this problem.__

If a script is attached to the `failed` state or the `successful` the operation workflow is rejected by the agent on start. The error is logged but doesn't prevent the agent to start.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/RobotFramework/tests/tedge_agent/workflows/custom_operation.robot
- [x] QA has tested the function and it's functioning according description.
