### ISSUE TITLE
Cumulocity operation failureReason field cannot contain quotes

### ISSUE THREAD

**Issue by jarhodes314** [thin-edge/thin-edge.io#2487]
**Is your feature improvement request related to a problem? Please describe.**
In #2474, I modified the code to debug print some values in errors that later get turned into failure reasons for operations. I was surprised to discover that the mapper removes quotes from failure reasons when serialising them to SmartREST, so this didn't work as intended.

**Describe the solution you'd like**
Quotes in the error message should be preserved when they are sent to Cumulocity.

**Describe alternatives you've considered**

**Additional context**

**Comment by rina23q** [comment]
Double quotes in failure reason must be escaped by two double quotes like below.
```text
502,c8y_UploadConfigFile,"contains""double""quote"
```

This sanitize function escapes double quotes by two double quotes, so maybe our failure reason generation doesn't use this function?
https://github.com/thin-edge/thin-edge.io/blob/b2162397cfef4c73dd7d5b794fdd3adb6d55b604/crates/core/c8y_api/src/smartrest/message.rs#L37-L46

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot
- tests/RobotFramework/tests/cumulocity/configuration/configuration_with_file_transfer_https.robot
- tests/RobotFramework/tests/cumulocity/log/log_operation.robot
- [x] QA has tested the function and it's functioning according description.
