### ISSUE TITLE
New tedge cli command to renew current self-signed certificate

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2489]
**Is your feature request related to a problem? Please describe.**

Renewing the self-signed certificate created by `tedge cert create` requires both the public and private device certificates to be deleted. Also it is annoying for users as the user must get the existing device-id from the public certificate and use it in the `tedge cert create --device-id <name>` command again which makes it very easy for users to misconfigure (e.g. accidentally changing the device-id, or deleting the public cert before reading the device-id thus losing the information.)

**Describe the solution you'd like**

Add a new tedge cli subcommand to handle the recreation of the the public device certificate.

```sh
tedge cert renew
```

The `cert renew` command should:

* Fail (return a non-zero exit code) if an existing public certificate does not exist
* Read the Common Name from the existing certificate (note, reading must be possible even when the certificate is outside the validity period!)
* ~Leave the private cert in-tact (e.g. there is no need to recreate the private key as it does not expire, only the public cert does)~ This requirement will be covered in a different ticket https://github.com/thin-edge/thin-edge.io/issues/2512
* Generate a new public (self-signed) certificate with a new validity period (we can use the existing default of 1 year)
* Print a message on the console that warns the user that they need to upload the public certificate again and that the until this is done the device's connectivity to the cloud will be disrupted

Though it must be noted, that currently `tedge cert renew` is used for self-signed certificates only! The current advice is to still use a PKI service to do certificate signing in production use cases, e.g. Nexus, SmallStep etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/RobotFramework/tasks/E2E_Tutorials/Connect_to_c8y.robot
- tests/RobotFramework/tests/tedge/tedge_upload_cert.robot
- [x] QA has tested the function and it's functioning according description.
- [x] Documentation existing
- docs/src/operate/security/registration.md
