### ISSUE TITLE
don't restart tedge-agent service when using tedge connect or tedge reconnect

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2494]
**Is your feature improvement request related to a problem? Please describe.**

Executing `tedge connect c8y` or `tedge reconnect c8y` rebuilds the bridge configuration and automatically restarts the tedge-agent regardless if it is running. The restarting of the tedge-agent is problematic and no longer required since the decoupling of the tedge-agent to any mapper specific logic.

Being able to update the c8y bridge configuration is useful when performing firmware updates, however if the tedge-agent is restarted, this causes teh firmware update workflow to be interrupted as the tedge-agent is responsible for running the firmware update workflow (e.g. the workflow step would essentially kill the process which is running it.)

**Describe the solution you'd like**

Don't restart `tedge-agent` if the service is already running when running the following commands:
* `tedge reconnect c8y`
* `tedge connect c8y`

Generally service managers already support starting a service in an idempotent way, so it should be a simple case of just using starting the service rather than restarting (you probably don't even need to check if the service is already running yourself)

**Describe alternatives you've considered**

**Additional context**

**Comment by reubenmiller** [comment]
Test included under:
* tests/RobotFramework/tests/tedge_connect/tedge_connect_test.robot

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/RobotFramework/tests/tedge_connect/tedge_connect_test.robot
- tests/RobotFramework/tests/config_management/child_conf_mgmt_plugin.robot
- tests/RobotFramework/tests/cumulocity/configuration/configuration_operation.robot
- tests/RobotFramework/tests/cumulocity/configuration/configuration_with_file_transfer_https.robot
- tests/RobotFramework/tests/cumulocity/firmware/firmware_operation_child_device.robot
- [x] QA has tested the function and it's functioning according description.
- [x] Documentation existing
- docs/src/references/init-system-config.md
