### ISSUE TITLE
restart tedge-agent after the agent is updated via the cloud

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2501]
**Is your feature request related to a problem? Please describe.**

Currently the tedge-agent service is not restarted after the package is updated, as the service is responsible for orchestrating the software update, so restarting the service during the postinst maintainer script would be destructive and result in a "half-installed" package.

However, not restarting the tedge-agent service results in unexpected behaviour where the older tedge-agent binary is still running but there is no visible signs that the older version is running, and thus debugging any erroneous behaviour very difficult.

**Describe the solution you'd like**

During a software update, if the tedge-agent detects that it's binary has been changed, then the process should be restarted cleanly after all of the packages have been processed.

Due to complications introduced by the [default KillMode=control-group](https://www.freedesktop.org/software/systemd/man/latest/systemd.kill.html#KillMode=) in Systemd, the restart cannot occur during the linux package management. Instead just "cleanly exiting" might be the best strategy, and rely on the service supervision to restart the service.

* Feature flag to enable/disable this "auto exit" behaviour (this enable users that are not using a process supervisor to opt-out of this behaviour, as it would be catastrophic for them otherwise).
* Detect if the tedge-agent version (e.g. `tedge-agent --version`) after a software installation, and exit cleanly (if enabled)

**Notes**
* Don't assume you are running under a specific service manager
* Don't detect if an agent update is being done by looking at the incoming software update changes, as there is no easy way to determine if the tedge-agent is part of it or not (e.g. if the users are using virtual packages, which pull in dependencies automatically)

**Describe alternatives you've considered**

**Additional context**

**Comment by didier-wenzek** [comment]
The fix cannot be implemented by the **tedge-agent** itself, as this must work even when updating an old version of the agent.

A solution is to trigger a restart of the agent from the mapper when a new version of `tedge-agent` is detected after a software update. Indeed, thanks to the all-in-one `tedge` executable, the mapper and the agent will be simultaneously updated, and, after a successful update of thin-edge from the cloud, the mapper will be in position to restart the agent in case the latter is not running the freshly installed version of `tedge`.

The c8y mapper needs to be extended with the following checks and actions:

1. On any software update request, probe `tedge-agent --version`
2. Forward the software update request to the agent as usual.
3. When the outcome of the software update request is received and is successful,
      1. Probe again `tedge-agent --version` and compare the result with the version returned before the update.
      2. If the two versions, before and after software updates, are different then trigger a restart of tedge-agent.
      3. Report to c8y the success of the software update request only after a successful restart of the agent.

Open questions:
- What about child devices?
- How to probe the version of the agent when the agent is not running on the same box as the mapper?
- How the mapper can restart tedge-agent? Currently there is no agent-restart command but only a device restart command.

**Comment by didier-wenzek** [comment]
There is another related issue.

The file used by tedge-agent to detect a restart operation has a new format (my bad :-(). It means that if the mapper triggers a a restart on agent still running an old version, this agent will create a restart state file the new agent will be unable to read.

**Comment by didier-wenzek** [comment]
> There is another related issue.
> 
> The file used by tedge-agent to detect a restart operation has a new format (my bad :-(). It means that if the mapper triggers a a restart on agent still running an old version, this agent will create a restart state file the new agent will be unable to read.

This is not an issue in practice: see https://github.com/thin-edge/thin-edge.io/pull/2547

**Comment by albinsuresh** [comment]
### Test

The main behavioural change with this fix is that the agent process will get restarted after a self update. This fix will not work for an upgrade from any earlier 0.x version or even the 1.0.0.rc1 version to the current version, but only work for upgrades from a release with this fix commit (fd91232ceac8f5b6d63f45662f3f401eacd48c54) to any higher versions.

The newly added `tedge_self_update::Update tedge version from base to current using Cumulocity` tests this behaviour by using a dummy version built from this commit as the source version, which is upgraded to the latest version.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/RobotFramework/tests/cumulocity/self-update/tedge_self_update.robot
- [x] QA has tested the function and it's functioning according description.
