### ISSUE TITLE
Replace references to legacy tedge plugins with tedge-agent in docs

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#2503]
**Is your documentation request related to a problem? Please describe.**

After the tedge-agent was updated to provide both configuration management and log management capabilities as well, the corresponding docs need to be updated to replace the references to old `tedge-configuration-plugin` and `tedge-log-plugin` with `tedge-agent` as the daemon that provides these functionalities.

**Describe the improvement you'd like**

The following docs still have references to the old plugins:

1. getting-started.md
2. tedge-agent.md
3. operate/c8y/config_management_plugin.md
4. operate/c8y/tedge_log_management.md
5. domain-model.md
6. update_config_paths.md
7. DEBIAN_PACKAGE_HOSTING.md

**Comment by reubenmiller** [comment]
The references to the legacy plugins have been removed from the above listed docs.

**Comment by gligorisaev** [comment]
Looks OK
