### ISSUE TITLE
`tedge connect az` generates a broken mosquitto configuration

### ISSUE THREAD

**Issue by jarhodes314** [thin-edge/thin-edge.io#2514]
**Describe the bug**
When running `tedge connect az`, it restarts mosquitto and then fails the connection check. After modifying the code to skip rolling back the broken configuration change on failure. I've established and fixed the root cause, so I'll create a PR immediately for this.

**To Reproduce**
Follow the guide at https://thin-edge.github.io/thin-edge.io/start/connect-azure/

**Expected behavior**
`moqsuitto` should connect successfully and `tedge-mapper-az` should start.

**Additional context**
Without modifying the code and recompiling `tedge`, it was essentially impossible to determine what was in the broken mosquitto configuration. This is not going to be a priority this side of 1.0, but I think it may be valuable in future to capture the broken configuration somewhere, so it's less involved to debug similar issues in future.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the bug and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the bug and it's not reproducable anymore
