### ISSUE TITLE
only call tedge-write with sudo if sudo is installed and enabled (via tedge config)

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2523]
**Describe the bug**

The internal calling of `tedge-write` should only use sudo if sudo is installed (e.g. checking if it is available) and the setting is enabled (e.g. `enable.sudo` is set to `true`).

It could be argued that this is more an improvement rather than a bug, however given that we have had similar improvements in the past regarding the usage of sudo, it could be suggested that it is a subtle regression. See the related ticket below:

* https://github.com/thin-edge/thin-edge.io/issues/2096

**To Reproduce**

1. Install thin-edge.io and setup Cumulocity mapper
2. Uninstall sudo on the device
3. Try to update configuration by sending a Update Configuration operation from the Cumulocity IoT Device Management UI

**Expected behavior**

The `tedge-write` command should only be called using sudo if BOTH the following conditions are met:
* The `sudo` command is available (e.g. `which sudo`)
* The tedge config setting, `enable.sudo` is set to `true`

**Screenshots**

If sudo is not installed on the device, then the config_update operation fails with the following failure reason:

```
config-manager failed writing updated configuration file: Starting tedge-write process failed
```

**Environment (please complete the following information):**

|Property|Value|
|--------|-----|
|OS [incl. version]|`Alpine Linux v3.18`|
|Hardware [incl. revision]|`unknown`|
|System-Architecture|`Linux 57f358e21c09 6.5.0-14-generic #14-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 15:13:47 UTC 2023 aarch64 Linux`|
|thin-edge.io version|`tedge 0.13.2~185+ge79edb6`|

**Additional context**

**Comment by reubenmiller** [comment]
Ready for testing. It can be verify by following the procedure detailed in ticket description.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the bug and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the bug and it's not reproducable anymore
