### ISSUE TITLE
flaky system test: Software list should be populated during startup 

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#2533]
**Describe the bug**
The robot integration test `Software list should be populated during startup` is failing.

**To Reproduce**
It is only reproducible in the CI pipeline

**Expected behavior**
The test must pass successfully.

**Screenshots**
```
2023-12-18 08:53:11.905489 [PID:118937] [5] [ID:45] still running Tests.Library.Test-Commands after 35.0 seconds
2023-12-18 08:53:12.299763 [PID:119210] [0] [ID:46] still running Tests.Library.Test-Mqtt after 35.0 seconds
2023-12-18 08:53:13.107[268](https://github.com/thin-edge/thin-edge.io/actions/runs/7243060704/job/19735977032?pr=2518#step:9:269) [PID:119367] [4] [ID:47] still running Tests.MQTT health check.Health Tedge Mapper C8Y after 35.0 seconds
2023-12-18 08:53:14.804844 [PID:119210] [0] [ID:46] PASSED Tests.Library.Test-Mqtt in 37.5 seconds
2023-12-18 08:53:14.805453 [PID:135029] [0] [ID:51] EXECUTING Tests.MQTT health check.Health Tedge-Mapper-Collectd
2023-12-18 08:53:17.235746 [PID:74476] [1] [ID:32] Execution failed in Tests.Cumulocity.Software Management.Software-Update-Child with 1 failing test(s)
==============================================================================
Tests                                                                         
==============================================================================
Tests.Cumulocity                                                              
==============================================================================
Tests.Cumulocity.Software Management                                          
==============================================================================
Tests.Cumulocity.Software Management.Software-Update-Child                    
==============================================================================
Software list should be populated during startup                      | FAIL |
Managed object does not have a c8y_SoftwareList fragment
------------------------------------------------------------------------------
Install software via Cumulocity                                       | PASS |
------------------------------------------------------------------------------
Tests.Cumulocity.Software Management.Software-Update-Child            | FAIL |
2 tests, 1 passed, 1 failed
==============================================================================
Tests.Cumulocity.Software Management                                  | FAIL |
2 tests, 1 passed, 1 failed
==============================================================================
Tests.Cumulocity                                                      | FAIL |
2 tests, 1 passed, 1 failed
==============================================================================
Tests                                                                 | FAIL |
2 tests, 1 passed, 1 failed
==============================================================================
Output:  /home/runner/work/thin-edge.io/thin-edge.io/tests/RobotFramework/output/pabot_results/32/output.xml

[ WARN ] Failed to get device managed object. 
[ WARN ] Failed to get device managed object.

```

More info can be found here: https://github.com/thin-edge/thin-edge.io/actions/runs/7243060704/job/19735977032?pr=2518
**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [e.g. 0.1.0]

**Additional context**

**Comment by reubenmiller** [comment]
Another failure on run:
* https://github.com/thin-edge/thin-edge.io/actions/runs/7783245596

**Comment by albinsuresh** [comment]
The missing software list is a result of a race condition between the child device creation via MQTT and updating its software list via HTTP immediately, without waiting for the device creation to complete. If the HTTP request reaches the cloud first, before the device is even created, the `get_internal_id` logic which is part of that HTTP call is going to fail with a 404, as can be seen in the mapper logs:

```
Feb 05 10:58:01 11409c557bba tedge-mapper[539]: 2024-02-05T10:58:01.122805738Z ERROR c8y_mapper_ext::converter: Mapping error: Failed with HTTP error status 404 Not Found
```

The easiest fix for this issue is to retry the `get_internal_id` logic on 404, for a brief amount of time, giving enough time for the device creation message to reach the server, post which the `get_internal_id` would succeed.

**Comment by albinsuresh** [comment]
### Test Plan

As described in the previous comment, the `get_internal_id` logic, which is part of all HTTP API invocations done by the mapper (like the update software list call in this case), would be retried up to 3 times with a 5 second interval between retries, if the initial attempts return a 404 error (when the device is not yet created).

**Comment by gligorisaev** [comment]
QA has thoroughly checked the bug and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the bug and it's not reproducable anymore
