### ISSUE TITLE
operations are not being processed after updating thin-edge.io

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2545]
**Describe the bug**

Due to an unfortunately combination of the following two ticket, the existing c8y-bridge mosquitto file will lack the `devicecontrol` topic subscription, however the tedge-mapper only listens to this `devicecontrol` topic thus resulting in the mapper not reacting to any of the operations.

* https://github.com/thin-edge/thin-edge.io/issues/2192
* https://github.com/thin-edge/thin-edge.io/pull/2482

Only the unofficial releases since `>= 0.13.2~223+g9e20481` are affected.

**To Reproduce**

1. Install any thin-edge.io version older than `0.13.2~223+g9e20481`
2. Upgrade thin-edge.io to version `0.13.2~223+g9e20481`
3. Try to send any operation to thin-edge.io via the Cumulocity IoT UI

The bug is present if the operation remains in `PENDING` state despite the thin-edge.io having a healthy bridge connection to Cumulocity IoT.

**Expected behavior**

Operations should be processed by thin-edge.io

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]: Any
 - Hardware [incl. revision]: Any
 - System-Architecture [e.g. result of "uname -a"]: Any
 - thin-edge.io version [e.g. 0.1.0]: `>= 0.13.2~223+g9e20481`

**Additional context**

**Comment by reubenmiller** [comment]
Fixed in >= `0.13.2~241+g9ff6d57`

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the function and it's functioning according description.
