### ISSUE TITLE
Cleanup documentation for 1.0.0

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#2551]
In its current state, the documentation for 1.0.0-rc.1 still contains some content related to deprecated features and former design. One must at least __remove and cleanup what is confusing__.

- [x] Remove content related to `tedge-configuration-plugin` and `tedge-log-plugin`  from the [`tedge-agent` overview](https://thin-edge.github.io/thin-edge.io/understand/tedge-agent/). https://github.com/thin-edge/thin-edge.io/pull/2554
- [x] Move the section ["Connecting an external device"](https://thin-edge.github.io/thin-edge.io/operate/monitoring/connect_external_device/)  under ["Security and access-control"](https://thin-edge.github.io/thin-edge.io/operate/security/) - https://github.com/thin-edge/thin-edge.io/pull/2560
- [x] Update the section ["Use MQTT authentication for local broker"](https://thin-edge.github.io/thin-edge.io/operate/security/mqtt_local_broker_authentication/) to include certificate-based authentication for HTTPS. https://github.com/thin-edge/thin-edge.io/pull/2585
- [x] Update the section ["Configuration management on child-devices"](https://thin-edge.github.io/thin-edge.io/operate/configuration/child-device-config-management/) to remove references to `c8y-configuration-plugin`. https://github.com/thin-edge/thin-edge.io/pull/2593
- [x] Update or deprecate [`child_device_agent.py`](https://github.com/thin-edge/thin-edge.io_examples/blob/main/child-device-agent/child_device_agent.py) and remove reference to this plugin from the section ["Configuration management on child-devices"](https://thin-edge.github.io/thin-edge.io/operate/configuration/child-device-config-management/) . https://github.com/thin-edge/thin-edge.io/pull/2593
- [x] Remove the section ["How to retrieve a JWT (JSON Web Token) to authenticate on Cumulocity"](https://thin-edge.github.io/thin-edge.io/operate/c8y/retrieve_jwt_token_from_cumulocity/) - https://github.com/thin-edge/thin-edge.io/pull/2558
- [x] Move the section ["Device Firmware Management using Cumulocity"](https://thin-edge.github.io/thin-edge.io/references/c8y-firmware-management/) under ["Extend/Firmware"](https://thin-edge.github.io/thin-edge.io/extend/firmware-management/) with an explicit note that this is the legacy API. - https://github.com/thin-edge/thin-edge.io/pull/2581
- [x] Consider to add a "Legacy / Porting to 1.0" section telling how to move from the `tedge` to the `te` topics, how to port a custom log/config/firmware plugin from the `req`/`res` model to the `cmd` model. - https://github.com/thin-edge/thin-edge.io/pull/2581
- [x] Move ["Enable configuration management on child devices"](https://thin-edge.github.io/thin-edge.io/operate/c8y/child_device_config_management_agent/) under a "Legacy" section. - https://github.com/thin-edge/thin-edge.io/pull/2581
- [x] Update the section ["thin-edge.io platform support"](https://thin-edge.github.io/thin-edge.io/references/supported-platforms/) with accurate numbers and supported platforms. https://github.com/thin-edge/thin-edge.io/pull/2594
- [x] Remove the section ["thin-edge Domain Model"](https://thin-edge.github.io/thin-edge.io/references/domain-model/) - https://github.com/thin-edge/thin-edge.io/pull/2559

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the function and it's functioning according description.
