### ISSUE TITLE
Rename configuration enable.sudo to sudo.enable

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2566]
**Is your feature improvement request related to a problem? Please describe.**

The tedge configuration item, `enable.sudo` is not consistent with out configuration items like `http`, `c8y`, where the first part of the configuration item represents a category and not an action.

```
enable.sudo=true
```

For example you just need to look at other configuration items with `enable` in their names:

```sh
# tedge config list | grep enable
c8y.enable.log_upload=true
c8y.enable.config_snapshot=true
c8y.enable.config_update=true
c8y.enable.firmware_update=true
agent.enable.config_update=true
agent.enable.config_snapshot=true
agent.enable.log_upload=true
enable.sudo=true
```

**Describe the solution you'd like**

Rename `enable.sudo` to `sudo.enable`.

**Describe alternatives you've considered**

**Additional context**

**Comment by reubenmiller** [comment]
Merged. The solution was implemented as suggested in the ticket description.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the function and it's functioning according description.
