### ISSUE TITLE
Allow arguments/subcommands in custom operations

### ISSUE THREAD

**Issue by scfx** [thin-edge/thin-edge.io#2568]
**Is your feature improvement request related to a problem? Please describe.**
If my tests were correct, there is currently no possibility to have any whitespaces in the  [custom operation commands](https://thin-edge.github.io/thin-edge.io/operate/c8y/supported_operations/#working-with-custom-operations). So, having custom operations like:

```
[exec]
  topic = "c8y/s/ds"
  on_message = "511"
  command = "python /etc/tedge/operations/command.py"
  timeout = 10
```

will not work, as the thin-edge will try to find end execute the file "python3 /etc/tedge/operations/command.py"

**Describe the solution you'd like**
I would like to see an exec structure similar to what Docker uses. So:

```
[exec]
  topic = "c8y/s/ds"
  on_message = "511"
  command = ["python", "/etc/tedge/operations/command.py"]
  timeout = 10
```
If you try to do this in version (0.13.0), Thin-Edge won't provide any supported operations. I haven't tried it in 1.0.0-rc1, so apologies if that is already fixed.

**Comment by reubenmiller** [comment]
@didier-wenzek Would you be open to supporting this for 1.0.0?

**Comment by didier-wenzek** [comment]
> @didier-wenzek Would you be open to supporting this for 1.0.0?

Yes, this can be done, using [shell-words](https://lib.rs/crates/shell-words), to allow plain commands as in `command = "python /etc/tedge/operations/command.py"`

**Comment by reubenmiller** [comment]
thin-edge.io now supports commands with multiple arguments (in a string form):

```toml
command = "python /etc/tedge/operations/command.py"
```

**System tests**

* [custom_operation_multiple_args/operation_multiple_arguments_in_command.robot](https://github.com/thin-edge/thin-edge.io/blob/main/tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_multiple_args/operation_multiple_arguments_in_command.robot)

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/RobotFramework/tests/cumulocity/custom_operation/custom_operation_multiple_args/operation_multiple_arguments_in_command.robot
- [x] QA has tested the function and it's functioning according description.

**Comment by AjayItHub** [comment]
Hi @reubenmiller , thank you for addressing this issue and we are looking for something like this.  We are evaluating thin-edge to work with Cumulocity.  If I am not wrong, seems like we can use command something like for c# "dotnet filename.dll".  We are not able to make it work, any advice?

**Comment by reubenmiller** [comment]
@AjayItHub Following this Guide on how to create a [Custom operation handler](https://thin-edge.github.io/thin-edge.io/operate/c8y/smartrest-templates/), I just adjusted the `command` to use the dummy `dotnet` console app that I built.

```toml
[exec]
command = "/opt/dotnet/dotnet /opt/myapp/bin/Debug/net7.0/myapp.dll"
topic = "c8y/s/dc/custom_devmgmt"
on_message = "dm101"
```

Maybe the part that part you're missing is that you are not using the full paths to the `dotnet` binary or the `.dll`?

The [debugging section](https://thin-edge.github.io/thin-edge.io/operate/c8y/smartrest-templates/#debugging) might be worth a read as well.

**Comment by AjayItHub** [comment]
Thank you @reubenmiller for quick response.  Not sure what I am missing, but I tried exactly you mentioned in above comment.  My thin-edge version is 1.0.0-rc.1

**Works**:

[exec]
command = "/usr/bin/set-wifi.sh"
topic = "c8y/s/dc/custom_devmgmt"
on_message = "dm101"

**Doesn't Work**
[exec]
command = "/usr/bin/set-wifi.sh"
topic = "c8y/s/dc/custom_devmgmt"
on_message = "dm101"

**I receive below error**

Operation execution failed: No such file or directory (os error 2). Command: /opt/dotnet/dotnet /opt/ConsoleApp5/ConsoleApp5.dll. Operation name: set_wifi

**Comment by reubenmiller** [comment]
> /opt/dotnet/dotnet /opt/ConsoleApp5/ConsoleApp5.dll

Are you sure that `dotnet` is actually installed at the `/opt/dotnet/dotnet` location? The error message suggestions that `dotnet` is not located there on your system.

You can verify by just running the same command from the console, e.g.

```
/opt/dotnet/dotnet /opt/ConsoleApp5/ConsoleApp5.dll
```

**Comment by AjayItHub** [comment]
yes @reubenmiller , I confirm dotnet was installed /opt/dotnet/dotnet.
![dotnet](https://github.com/thin-edge/thin-edge.io/assets/36364221/83b4701c-be92-4309-b500-358ee8110531)

**Comment by reubenmiller** [comment]
From this information it looks ok, but try the following steps to gather a bit more info to tell what is going on:

1. Restart the `tedge-agent` service (to eliminate the off chance that an older version of the binary is actually running which does not support this feature)

    ```
    sudo systemctl restart tedge-agent
    ```

2. Try running the command as the `tedge` user (maybe it does not have access to those files for some reason)

    ```sh
    sudo -u tedge /opt/dotnet/dotnet /opt/ConsoleApp5/ConsoleApp5.dll
    ```

3. Trigger an operation by publishing on the local MQTT broker (as this is easier/quicker to verify rather than creating an operation on the cloud side)

    ```sh
    tedge mqtt pub 'c8y/s/dc/custom_devmgmt' "dm101,$(tedge config get device.id),example"
    ```

    There should of been a log file created under `/var/log/tedge/agent`, for example you can list the newest files under the directory using:

    ```
    ls -ltr /var/log/tedge/agent
    ```

    There should be a file like:

    ```
    set_wifi-2024-02-08T17:51:06.366509289Z.log
    ```

    If you still have an error, then maybe it would be worth while creating a new ticket, so we can track this cleaner.

**Comment by AjayItHub** [comment]
hi @reubenmiller , thank you so much for your help, upgrading tedge helped resolving the issue.
