### ISSUE TITLE
Refactor the c8y remote access plugin to use the c8y auth proxy.

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#2591]
Can the c8y remote access plugin be refactored to use  c8y auth proxy instead of requesting JWT tokens? 
Can the remote access feature be built-in the c8y mapper, instead of having a plugin instead of having to configure a plugin ?

**Comment by reubenmiller** [comment]
If websockets were also supported, then it would also allow usage of the following Cumulocity IoT API:

* [realtime](https://cumulocity.com/api/core/#tag/Alarm-notification-API)
* [Notification-2.0-API](https://cumulocity.com/api/core/#tag/Notification-2.0-API)

Other potential applications:
* [opcua-device-gateway](https://github.com/thin-edge/opcua-device-gateway-container) which makes use of the realtime c8y api (and not MQTT)

**Comment by reubenmiller** [comment]
Test Procedure:

1. Configure the Cumulocity IoT remote access feature (e.g. web ssh is the easiest one) and connect to the device. If you can bring up a shell then that should be enough to check that it works as expected.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the function and it's functioning according description.
