### ISSUE TITLE
Create a plugins page to list available community plugins

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2595]
**Is your documentation request related to a problem? Please describe.**

The documentation does not mention which community plugins are available for use. This makes it hard for users to discover plugins to use, or if they just want a reference implementation for creating their own plugin.

**Describe the improvement you'd like**

Add a new plugins section to the documentation listing each of the plugins which are currently available.

**Additional context**

**Comment by reubenmiller** [comment]
The community plugins page has been merged and is available both in the "next"  and "1.0.0-rc.1" (official) doc version:

* `official` version: https://thin-edge.github.io/thin-edge.io/operate/plugins/
* `next` version: https://thin-edge.github.io/thin-edge.io/next/operate/plugins/

**Comment by gligorisaev** [comment]
QA has thoroughly checked the document and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has checked the documentation and it fits the function.
