### ISSUE TITLE
tedge-mapper-c8y panics when entity_store.jsonl is owned by root

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#2598]
**Describe the bug**
When the `entity_store.jsonl` file is owned by `root:root` and trying to start `tedge-mapper-c8y` by the `tedge` user, the process `tedge-mapper-c8y` panics due to the permission denied error.
The error message is not kind enough to debug for users. It will be nice to improve the error message.

**To Reproduce**
1. Change the owner of `/etc/tedge/.tedge-mapper-c8y/entity_store.jsonl` from `tedge:tedge` to `root:root`. For example, run
```sh
sudo chmod root:root /etc/tedge/.tedge-mapper-c8y/entity_store.jsonl
```
2. Run `tedge-mapper-c8y` by `tedge` user somehow. The easiest way might be just run 
```sh
sudo systemctl restart tedge-mapper-c8y.service
```
3. Check the log of tedge-mapper-c8y. If you use `systemctl`, run
```sh
sudo journalctl -xe -u tedge-mapper-c8y --no-pager
```
Log:
```text
Jan 17 20:33:24 SAG-CFPPNV2-U tedge-mapper[44115]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromStdIoError(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', crates/extensions/c8y_mapper_ext/src/converter.rs:265:10
Jan 17 20:33:24 SAG-CFPPNV2-U tedge-mapper[44115]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**
Giving a better error message, like saying which file/directory causes permission denied.

**Screenshots**

**Environment (please complete the following information):**
 - OS [Ubuntu 20.04.4 LTS]
 - Hardware [incl. revision]
 - System-Architecture [Linux SAG-CFPPNV2-U 5.4.0-169-generic 187-Ubuntu SMP Thu Nov 23 14:52:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux]
 - thin-edge.io version [tedge 1.0.0-rc.1]

**Additional context**
Since the owner of the entity_store.jsonl file is `tedge:tedge` by default, it hardly occurs that the file is owned by `root:root`. However, for advanced user, it can happen by accident. If it happens, giving a better error message is helpful.

**Comment by reubenmiller** [comment]
The following changes should be done to ensure a robust product:

* Change `tedge init` to also fix the permissions of the file and directory `/etc/tedge/.tedge-mapper-c8y/entity_store.jsonl`
* Don't panic if the `entity_store.jsonl` store file can not be read

**Comment by albinsuresh** [comment]
### Test Plan

The issue was fixed as described in the previous comment. Test for the same exists at `recover_and_publish_software_update_message.robot::Recovery from corrupt entity store file`

**Comment by gligorisaev** [comment]
QA has thoroughly checked the bug and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/RobotFramework/tests/cumulocity/mapper_recovery/recover_and_publish_software_update_message.robot
- [x] QA has tested the bug and it's not reproducable anymore
