### ISSUE TITLE
Update Cumulocity IoT tutorial instructions to align with thin-edge.io

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2604]
**Is your documentation request related to a problem? Please describe.**

The instructions to install thin-edge.io are outdated on the Cumulocity IoT tutorial page:

* https://cumulocity.com/guides/device-integration/integration-tutorials/

**Describe the improvement you'd like**

Update the instructions to align with the official project's documentation:
* https://thin-edge.github.io/thin-edge.io/install/

The c8y docs should also include a link to thin-edge.io's documentation (if it does not already have it)

**Additional context**

**Comment by didier-wenzek** [comment]
Here is the PR on c8y-docs: https://github.com/SoftwareAG/c8y-docs/pull/1651

**Comment by reubenmiller** [comment]
If we are going to keep the c8y docs, then I'd wait until this PR is merged as it will affect some of the links. https://github.com/thin-edge/thin-edge.io/pull/2636

**Comment by reubenmiller** [comment]
Update: the c8y-docs are being updated to only include a link to the thin-edge.io docs.

**Comment by didier-wenzek** [comment]
We agreed that C8Y docs will only contains a link to thin-edge docs with a short overview, the point being to reduce maintenance.

Here is the PR on the c8y docs: https://github.com/SoftwareAG/c8y-docs/pull/1671

**Comment by reubenmiller** [comment]
Closing as this has been merged, however please note that there might be a delay before the c8y-docs is published on the website.
