### ISSUE TITLE
Configuration flag to bypass duplicate message filtering on mapper startup

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#2605]
**Is your feature improvement request related to a problem? Please describe.**

The mapper currently avoids sending duplicate entity registration messages to the cloud on startup, by ignoring the resent registration messages for the entities that are already present in the restored persistent entity store. But, if someone intentionally/accidentally wipes the entities from the cloud, they will never be recreated again by the mapper, due to this filtering mechanism. So, a mechanism to disable this filtering on startup is desired to ease the syncing of the entire entity state on tedge to the cloud.

**Describe the solution you'd like**

Introduce a `c8y.entity_store.sync_on_startup` boolean config flag to enable the above mentioned forced syncing on startup. The default value should be `false`, to keep the current filtering mechanism as the default.

**Comment by didier-wenzek** [comment]
A new tedge config settings has been added: `c8y.entity_store.clean_start`

- On a clean start, the whole state of the device, services and child-devices is resent to the cloud.
- The default for `c8y.entity_store.clean_start` is to be false. Only new services and child-devices, created while the c8y mapper was down, are published to the Cumulocity IoT on mapper restart.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the function and it's functioning according description.
