### ISSUE TITLE
avoid using ERROR log level for non errors

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2634]
**Is your refactoring request related to a problem? Please describe.**

The following log entries on the ERROR level were observed from a recent system test run. The following errors should not be an ERROR but rather on the WARN level as the actions are expected behaviour.

```
Jan 30 17:06:23 0944471c5d4e tedge-agent[536]: 2024-01-30T17:06:23.301225503Z ERROR tedge_agent::software_manager::actor: Tedge-agent is no more running the latest-version => a restart is required
```

```
Jan 30 17:06:23 0944471c5d4e tedge-agent[536]: 2024-01-30T17:06:23.301257933Z ERROR Runtime: Actor SoftwareManagerActor-11 has finished unsuccessfully: ActorError(NotRunningLatestVersion)
```

```
Jan 30 17:06:28 0944471c5d4e tedge-agent[1333]: 2024-01-30T17:06:28.361681348Z ERROR sm-agent: tedge_agent::state_repository::state: Cannot use "/data/tedge/agent" to store tedge-agent state: No such file or directory (os error 2)
```

**Describe the solution you'd like**

* Use WARN log levels on the above messages instead of ERROR

**Describe alternatives you've considered**

**Additional context**

**Comment by Ruadhri17** [comment]
The errors messages mentioned in this ticket were converted to warn messages.
