### ISSUE TITLE
Cumulocity IoT software list uses incorrect type field

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2653]
**Describe the bug**

With the introduction of support for the Cumulocity IoT software type information, https://github.com/thin-edge/thin-edge.io/pull/2613, an error was spotted where the `type` property name was incorrectly specified in the ticket instead of `softwareType` as per the [Cumulocity IoT specification](https://cumulocity.com/guides/10.18.0/reference/device-management-library/#software)

Using the wrong property name results in the type information not being displayed correctly in the Cumulocity IoT Device Management Application (on the device view).

**To Reproduce**

1. Start thin-edge.io
2. Inspect the device managed object in Cumulocity IoT, and see that the `c8y_SoftwareList` should contain an array of software items where `type` is used instead of the correct `softwareType` property.

**Expected behavior**

The software list should use the `softwareType` property

**Screenshots**

**Environment (please complete the following information):**

|Property|Value|
|--------|-----|
|OS [incl. version]|`Debian GNU/Linux 12 (bookworm)`|
|Hardware [incl. revision]|`Raspberry Pi 5 Model B Rev 1.0`|
|System-Architecture|`Linux rpi5-d83addab8e9f 6.1.0-rpi4-rpi-2712 #1 SMP PREEMPT Debian 1:6.1.54-1+rpt2 (2023-10-05) aarch64 GNU/Linux`|
|thin-edge.io version|`tedge 1.0.0-rc.2~255+g5088517`|

**Additional context**

**Comment by reubenmiller** [comment]
The software list sent to Cumulocity IoT now uses the `softwareType` property.

1. Install thin-edge.io
2. Check the software list (after the agent has started, you may need to refresh the Cumulocity IoT UI). Each software item should have a "type" visible in the UI

Here is an example (notice the badge next to each of the software item names):

<img width="1283" alt="image" src="https://github.com/thin-edge/thin-edge.io/assets/3029781/5800a99f-e413-4fec-a65f-cd617b5b2770">

**Comment by gligorisaev** [comment]
QA has thoroughly checked the bug and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/RobotFramework/tests/cumulocity/self-update/tedge_self_update.robot
- tests/RobotFramework/tests/cumulocity/software_management/sm-plugin.robot
- tests/RobotFramework/tests/cumulocity/software_management/software.robot
- [x] QA has tested the bug and it's not reproducable anymore
