### ISSUE TITLE
tedge-apt-plugin should ignore installing recommended packages

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2670]
**Is your feature improvement request related to a problem? Please describe.**

tedge-apt-plugin does not use the `--no-install-recommends` flag when installing packages which results in additional packages being installed.

Installing the recommended packages often leads to software bloat, and on the edge installations should be as minimal as possible.

**Describe the solution you'd like**

Use the `--no-install-recommends` flag when installing debian packages.

**Describe alternatives you've considered**

Alternatively the `/etc/apt/apt.conf` settings file could be used to control the default value of the install-recommends, however this would change the overall default for people using the commands line, and when they might want this behaviour (as there is a person there to determine if this is actually desired or not)

```
APT::Install-Recommends "false";
```

**Additional context**

**Comment by rina23q** [comment]
Since #2669 fixes the same part of the code, this ticket will be addressed as part of #2669.

**Comment by reubenmiller** [comment]
The tedge-apt-plugin uses the `--no-install-recommends` when installing packages. After installing software you can review that it is included by checking the logs `/var/log/tedge/agent/software-update-*.log` which are associated with the `apt` sm plugin.

1. Install `collectd` via Cumulocity IoT
2. Inspect the related software-update logs (under `/var/log/tedge/agent/software-update-*.log`) and see if the `--no-install-recommends` flag is included in the `apt-get install` command

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test for ticket exists in the test suite.
- tests/RobotFramework/tests/plugin_apt/install_overwrite_config_files.robot
- [x] QA has tested the function and it's functioning according description.
