### ISSUE TITLE
cargo-udeps fails due to compilation error of `ahash` crate

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#2686]
**Describe the bug**
`cargo-udeps` starts failing. See [this run](https://github.com/thin-edge/thin-edge.io/actions/runs/7798548054/job/21267810517?pr=2683).

```
   Compiling ahash v0.7.7
    Checking hex v0.4.3
error[E0635]: unknown feature `stdsimd`
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.7.7/src/lib.rs:33:42
   |
33 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^
For more information about this error, try `rustc --explain E0635`.
error: could not compile `ahash` (lib) due to previous error                                ^^^^^^^
```

This issue has already been captured in https://github.com/tkaitchuck/aHash/issues/200, however, we don't have direct dependency on `ahash`. Actually chain dependency starting from `rumqttd`.

rumqttd 0.18.0 (upgrading to 0.19.0 has breaking change, meaning that we have to change our code)
-> metrics-exporter-prometheus 0.12.2: ^0.12.1 (latest 0.13.0)
-> indexmap 1.9.3: ^1 (latest 2.x)
-> hashbrown 0.12.3: ^0.12 (latest 0.14.3)
-> ahash 0.7.7: ^0.7.0 (latest 0.8.7, which has the fix)  

Unfortunately, upgrading `rumqttd` to `0.19.0` won't help as it still has a dependency on `metrics-exporter-prometheus ^0.12.1`.

**To Reproduce**
Run `cargo-udeps` job.

**Expected behavior**
No compilation error.

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [e.g. 0.1.0]

**Additional context**

**Comment by reubenmiller** [comment]
Pinning to a specific nightly build has fixed the issue for now.
