### ISSUE TITLE
Too many "No operation update required" messages on te/errors

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#2694]
**Is your feature improvement request related to a problem? Please describe.**

While subscribed to `te/errors` topic we see too many `No operation update required` messages, presumably whenever the mapper detects that the supported operations list of the device need not be updated while processing a command capability message (e.g: on a duplicate capability message).

**Describe the solution you'd like**

Do not publish these errors to the `te/errors` topic or even log them as errors. Info level logging would be more than sufficeint

Even when a duplicate capability message results in no updates to the supported operations list, it's nothing more than a regular info level event and definitely not an error. So, these error messages are just false alarms that could mislead the users.

**Additional context**

Not sure if there was any historical context to why this event was labelled as an error in the first place.

**Comment by reubenmiller** [comment]
Duplicated by https://github.com/thin-edge/thin-edge.io/issues/3252
