### ISSUE TITLE
Cleanup the code of deprecated plugins

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#2698]
**Is your refactoring request related to a problem? Please describe.**
We have deprecated those plugins and they are already part of tedge-agent.

- c8y-configuration-plugin
- ~~c8y-firmware-plugin~~
- c8y-log-plugin
- tedge-configuration-plugin
- tedge-log-plugin

Hence, we should be able to remove the related crates of these plugins from this [directory](https://github.com/thin-edge/thin-edge.io/tree/main/plugins).

**Describe the solution you'd like**
Remove deprecated plugins from our repository safely

**Describe alternatives you've considered**

**Additional context**

**Comment by reubenmiller** [comment]
We might need to keep `c8y-firmware-plugin` for now as it still provides some advanced features such as firmware binary caching.

**Comment by reubenmiller** [comment]
The unused code has now been removed.

Verification involves checking that the existing functionality "still works" (though high confidence is there as the tests passed, and only the c8y-configuration-plugin related system tests were removed). See the linked PR for more details what was actually removed.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [ ] Test for ticket exists in the test suite.
- [x] QA has tested the function and it's functioning according description.
