### ISSUE TITLE
Add docs how to unregister a device/service from the entity store

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2700]
**Is your documentation request related to a problem? Please describe.**

The [documentation](https://thin-edge.github.io/thin-edge.io/references/mappers/c8y-mapper/#registration) inform users how to register new child devices and services, however it does not detail how to remove a device or service (including the information that a device/service is not removed from the cloud, only locally).

**Describe the improvement you'd like**

Add a section detailing how to unregister/remove a child device and service.

For example:

```sh
tedge mqtt pub "te/device/mychild//" "" -r

tedge mqtt pub "te/device/mychild/service/myservice/" "" -r
```

Or if you want to unregister multiple devices using a pattern, then you can use `mosquitto_sub`:

**Example: Unregister all services for a child device**

```sh
mosquitto_sub -t "te/device/mychild/service/+" --remove-retained
```

**Example: Unregister all child devices**

```sh
mosquitto_sub -t "te/device/+//" -T "te/device/main//" --remove-retained
```
*Note:* The above command subscribes to the child devices and but excludes the `te/device/main//` device (if present)

**Note**
* Unregistering a device/child from the local thin-edge.io MQTT broker does not delete the device from the cloud. This is a protection mechanism to ensure the edge device does not delete any historical information from the cloud (e.g. measurements from an older service used for analysis).

**Additional context**

**Comment by didier-wenzek** [comment]
What's the status of this ticket? Do we need still need to improve the documentation to register/unregister devices?

**Comment by gligorisaev** [comment]
> What's the status of this ticket? Do we still need to improve the documentation to register/unregister devices?

The content provides comprehensive guidance on deregistering entities, covering various scenarios and considerations. It effectively balances technical detail with practical instructions, including explanations for MQTT-related concepts.

From my point of view it is OK
