### ISSUE TITLE
sudo.enable config is not respected everywhere

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2749]
**Is your feature improvement request related to a problem? Please describe.**

The `sudo.enable` setting is not respected by all components. This makes it more difficult to run thin-edge.io under and environment that either does not have sudo, or the user does not want to use sudo.

The following source files do not respect the `sudo.enable` setting:

* crates/core/tedge_agent/src/restart_manager/actor.rs
* crates/core/tedge_agent/src/software_manager/actor.rs

**Describe the solution you'd like**

The usage of sudo in all thin-edge.io components should only be used if:
* `sudo.enable` is set to true
* and `sudo` is available to be used

**Describe alternatives you've considered**

**Additional context**

**Comment by Bravo555** [comment]
No functional changes, only a refactor, so there's nothing to verify by QA.

**Comment by reubenmiller** [comment]
I'll test with my original setup which was the reason for creating the ticket

**Comment by reubenmiller** [comment]
I've verified that `sudo.enabled` is now respected by both the software and reboot functionality.
