### ISSUE TITLE
Setup yocto build machine

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2766]
**Is your feature improvement request related to a problem? Please describe.**

Building and verifying for Yocto requires dedicated hardware as the build times for Yocto are in the hours, which generally exceeds the timeouts for the Github free runners.

**Describe the solution you'd like**

Setup a new build server to build nightly image of Yocto images

**Describe alternatives you've considered**

**Additional context**

**Comment by gligorisaev** [comment]
My intention is to use:

Architecture:            x86_64
CPU op-mode(s):        32-bit, 64-bit
Address sizes:         39 bits physical, 48 bits virtual
Byte Order:            Little Endian
CPU(s):                  8
On-line CPU(s) list:   0-7
Vendor ID:               GenuineIntel
Model name:            Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
CPU family:          6
Model:               142
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
Stepping:            10
CPU max MHz:         4100.0000
CPU min MHz:         400.0000
BogoMIPS:            4800.00

RAM: 16 GB
HDD: 500 GB
