### ISSUE TITLE
Invoking a sub-command from an operation workflow

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#2790]
An operation workflow uses a combination of scripts and built-in actions to define the steps moving forward an operation request. Having, the __ability to trigger a command defined by another workflow__  would not only add flexibility but also help to be consistent, enforcing a systematic process to handle operations.

For instance, to support [device profile](https://github.com/thin-edge/thin-edge.io-roadmap/issues/39), a profile update workflow will have to combine configuration updates with software and firmware updates.  Having the ability to delegate steps from this main workflow to other workflows will ease the implementation of consistent processes - where all individual updates are following the same rules.

**Proposed Solution**

A command defined by another workflow can be used to handle an operation step.

- A step on which a `operation = <operation-name>` has been attached, is processed using the workflow for the given `<operation>`.
- The workflow definition include all the parameters to be passed to the operation.
- Data extracted from the calling workflow can be injected into the parameters for the inner workflow - using the same conventions as those used for the script handlers. 
- The agent handles the sub command from its initialization steps up to its completion.
   - Notably, the agent assigns a command  identifier to the sub-command instance,
   - populates the init state of the sub-command with the data extracted form the calling workflow
   - monitors the sub-command till its completion
   - awake the calling workflow when a success, a failure or a timeout is reach
   - finally, clean-up MQTT topic used for the sub-command instance
- The calling workflow defines how to handle successes, failures or timeouts using the same conventions as those used for the script handlers.

**Alternatives**

A sub-command could be triggered from a workflow using a script. It would be a bit tricky, though, to monitor the sub-command and to block the script till the sub-command reaches completion.

**Additional context**

See [device profile](https://github.com/thin-edge/thin-edge.io-roadmap/issues/39)

**Comment by gligorisaev** [comment]
Documentation:
- The documentation provides a clear explanation of how to trigger sub-operations from within a workflow and how to handle their execution.
- The explanation of providing operation-specific arguments to the sub-operation instance is thorough and easy to understand.

Test Case:
- The test ensures that the tedge-agent service is restarted properly and verifies the success of the operation through MQTT messages and PID comparison using a sub-command trigger

From my point of view the feature is correctly documented and the step(s) in the Test Case:
[tests/RobotFramework/tests/tedge_agent/workflows/custom_operation.robot](https://github.com/thin-edge/thin-edge.io/pull/2792/files#diff-7612d6129e7c835d64875c3c2a47a2652b61ef6c1a8150e6bdec565e371c3b68)
are verifiing the correct function of the feature
