### ISSUE TITLE
Investigate rauc integration for firmware updates

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2825]
**Is your feature request related to a problem? Please describe.**

Extend support for different firmware update technologies to allow users who are already using rauc to integrate more easily with thin-edge.io

**Describe the solution you'd like**

Create support for [rauc](https://rauc.readthedocs.io/en/latest/) by creating a yocto integration to building custom images which support OTA updates using rauc.

**Describe alternatives you've considered**

**Additional context**

**Comment by reubenmiller** [comment]
An initial integration has been created, though there is refactoring going on in the [meta-tedge project](https://github.com/thin-edge/meta-tedge/issues/71) to combine both the meta-tedge and meta-tedge-bin which will influence the rauc example.

**Comment by reubenmiller** [comment]
The meta-tedge-project has been updated and the default thin-edge.io docs have been instructions to use the tedge-rauc image now.

You can read the new docs [here](https://thin-edge.github.io/thin-edge.io/next/extend/firmware-management/building-image/yocto/tutorial/#building-an-image)

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- Checked the functioning according the documentation and it works fine
- [x] Documentation changes have been reviewed and the de3scription is accurate  
- [x] QA has tested the function and it's functioning according description.
