### ISSUE TITLE
Unified log file for software management operations

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#2835]
**Is your feature improvement request related to a problem? Please describe.**

When a software management operation like software update is executed, two different log files are generated at `/var/log/tedge/agent` directory:

1. The plugin execution log: `software-update-YY-MM-DD:HH:MM:SS.log`
2. The workflow log: `workflow-software_update-c8y-mapper-YY-MM-DD:HH:MM:SS.log`

This makes debugging harder as the user needs to gather both the logs and correlate them.

**Describe the solution you'd like**

Integrate the plugin execution log also into the workflow log itself.

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

 Test changes has been reviewed.

- tests/RobotFramework/tests/cumulocity/software_management/software.robot
- tests/RobotFramework/tests/tedge_agent/workflows/custom_operation.robot

 QA has tested the function and it's functioning according description.
