### ISSUE TITLE
tedge-apt-plugin should support exclude patterns based on name and maintainer

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2848]
**Is your feature improvement request related to a problem? Please describe.**

It is difficult to filter out uninteresting apt packages from the software list as the current filters only support known names. This makes it difficult to filter out packages such as `libc.*`, `iptables-module-.*`, `kernel-.*` (packages which are common in Yocto builds when including the apt package manager). In Yocto builds this means that from the ~2000 packages which part of the base image, that only 200 packages are interesting for the user (e.g. not kernel modules, iptables module etc.)

Below shows the currently support apt package filters (which are only "include" filters).

```toml
[apt]
name = ".+"
maintainer = ".+"
```

The Rust standard regex create does not support Regex negative look behinds, so it makes virtually impossible to filter out known packages.

**Describe the solution you'd like**

Extend the `tedge-apt-plugin` filtering possibility to also support exclude patterns for both the package name and maintainer.

```toml
[apt]
exclude.name = ""
exclude.maintainer = ""
```

The additional settings should behave as follows:

* The new properties would also support regular expressions
* If `apt.exclude.name` is empty, then the filter will be ignored
* If `apt.exclude.maintainer` is empty, then the filter will be ignored
* The `apt.include.*` patterns take precedence over the exclude logic, meaning that if the include patterns match, then the package SHOULD appear in the software list.

**Describe alternatives you've considered**

**Additional context**

**Comment by Ruadhri17** [comment]
This logic was moved from `apt` plugin to `sm-plugin` module. Two new configs were added: `software.plugin.include` and `software.plugin.exclude`. Following rules are applied to filtering depending on what option is used:

- if only `software.plugin.include` is provided, keep a package if its name matches
- if only `software.plugin.exclude` is provided, keep a package if its name doesn't match
- if both are provided, the logic is to keep a package if its name matches the `software.plugin.include` regex or doesn't match the `software.plugin.exclude`. 

New robot framework tests were added [here](https://github.com/thin-edge/thin-edge.io/blob/main/tests/RobotFramework/tests/cumulocity/software_management/sm-plugin.robot).

New doc entry exists [here](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/references/agent/software-management.md).

**Comment by gligorisaev** [comment]
QA has thoroughly checked the feature and here are the results:

- [x] Test Suite has been reviewed.
        tests/RobotFramework/tests/cumulocity/software_management/sm-plugin.robot
- [x] Documentation has been reviewed
        docs/src/references/agent/software-management.md
- [x] QA has tested the function and it's functioning according description.
