### ISSUE TITLE
tedge init: only create multi-call binary symlinks if they do not exist

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2873]
**Is your feature improvement request related to a problem? Please describe.**

Forcefully recreating the thin-edge.io executable symlinks (for the multi-call binary setup) even though the symlinks already exist causes problems when running on a read-only root filesystem (namely Fedora IoT).

`tedge init` is called on the systemd `ExecStartPre` property to ensure that the required folders exist prior to the service starts (e.g. https://github.com/thin-edge/thin-edge.io/blob/main/configuration/init/systemd/tedge-agent.service#L8). Whilst that a non-zero exit in the `ExecStartPre` phase does not prevent the service from starring, it does introduce noise for the user as they might think something is wrong.

The code below shows the current logic which blindly deletes the symlinks if they exist, then recreates them:

[let file_exists = meta.is_ok();](https://github.com/thin-edge/thin-edge.io/blob/main/crates/core/tedge/src/cli/init.rs#L68-L96)

**Describe the solution you'd like**

Symlinks should only be created if they do not already exist. This would avoid ExecStartPre errors when running services on a read-only root filesystem.

**Describe alternatives you've considered**

**Additional context**

**Comment by reubenmiller** [comment]
There is sufficient test coverage provided by the unit tests as part of the linked PR.

**Comment by gligorisaev** [comment]
I am confirming that with the unit tests, part of the PR, are covering this feature, no need to duplicate with sstem test
