### ISSUE TITLE
unexpected backoff durations when using built-in mqtt bridge when network is disconnected

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2935]
**Describe the bug**

Whilst exploring the backoff algorithm used by the built-in bridge (inside the mapper), the observed backoff durations were unexpected when the network was disconnected at the beginning of the test.

Given, that the network was disconnected on the device under test, the following sequence shows the backoff durations over time (in chronological order):

1. 42s
2. 31s
3. 166s
4. 307s
5. 591s
6. 371s
7. 672s
8. 325s
9. 757s
10. 823s
11. 640s
12. 806s

The above values of the backoff duration displays the following unexpected characteristics:

* the backoff duration does not just continue getting larger/longer (e.g. 42s -> 31s?) when the network remains disconnected
* the backoff duration is not capped by the `mqtt.bridge.reconnect_policy.maximum_interval` (default of `10m`)

It is possible that the above durations could be explained by documenting the backoff algorithm (or maybe I missed that docs?).

**To Reproduce**

1. Configure thin-edge.io to connect to Cumulocity IoT and use the built-in bridge (with the default backoff settings)
2. Connect to Cumulocity IoT (and confirm a)
3. Disconnect the network (e.g. disconnect Wifi or unplug network cable)
4. Monitor the logs of the `tedge-mapper-c8y` service (assuming you're using systemd to run the services)

    ```sh
    journalctl -fu tedge-mapper-c8y
    ```

**Expected behavior**

Expected characteristics (though if good arguments can be provided to disqualify some of the requirements, then that is also acceptable):

* the backoff duration should have jitter to prevent the thundering herd problem if all clients are disconnected by the server at the same time.
* the backoff duration max limit should limit the maximum value used (+/- a jitter)
* the backoff duration should always increase if the connect is still disconnected

**Screenshots**

**Environment (please complete the following information):**

|Property|Value|
|--------|-----|
|OS [incl. version]|`Debian GNU/Linux 12 (bookworm)`|
|Hardware [incl. revision]|`container`|
|System-Architecture|`Linux fe9669c87b15 6.5.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 27 00:18:38 UTC 2024 aarch64 GNU/Linux`|
|thin-edge.io version|`tedge 1.1.2~99+g58c2812`|

**Additional context**

Below shows the raw log entries from the backoff duration:

```log
Jun 11 11:07:08 96136f6a6861 tedge-mapper[664]: 2024-06-11T11:07:08.290996385Z ERROR tedge_mqtt_bridge::health: MQTT bridge failed to connect to cloud broker: Mqtt state: Last pingreq isn't acked
Jun 11 11:07:08 96136f6a6861 tedge-mapper[664]: 2024-06-11T11:07:08.291562797Z  INFO tedge_mqtt_bridge: Waiting 42.364672733s until attempting reconnection to cloud broker
Jun 11 11:07:55 96136f6a6861 tedge-mapper[664]: 2024-06-11T11:07:55.661903584Z ERROR tedge_mqtt_bridge::health: MQTT bridge failed to connect to cloud broker: Network timeout
Jun 11 11:07:55 96136f6a6861 tedge-mapper[664]: 2024-06-11T11:07:55.662404081Z  INFO tedge_mqtt_bridge: Waiting 31.148926306s until attempting reconnection to cloud broker
Jun 11 11:08:31 96136f6a6861 tedge-mapper[664]: 2024-06-11T11:08:31.816031825Z  INFO tedge_mqtt_bridge: Waiting 166.308976605s until attempting reconnection to cloud broker
Jun 11 11:11:23 96136f6a6861 tedge-mapper[664]: 2024-06-11T11:11:23.12983324Z  INFO tedge_mqtt_bridge: Waiting 307.24118924s until attempting reconnection to cloud broker
Jun 11 11:16:35 96136f6a6861 tedge-mapper[664]: 2024-06-11T11:16:35.376356Z  INFO tedge_mqtt_bridge: Waiting 591.728497009s until attempting reconnection to cloud broker
Jun 11 11:26:32 96136f6a6861 tedge-mapper[664]: 2024-06-11T11:26:32.110234515Z  INFO tedge_mqtt_bridge: Waiting 371.731146621s until attempting reconnection to cloud broker
Jun 11 11:32:48 96136f6a6861 tedge-mapper[664]: 2024-06-11T11:32:48.852636154Z  INFO tedge_mqtt_bridge: Waiting 672.795422391s until attempting reconnection to cloud broker
Jun 11 11:44:06 96136f6a6861 tedge-mapper[664]: 2024-06-11T11:44:06.652456895Z  INFO tedge_mqtt_bridge: Waiting 325.056665411s until attempting reconnection to cloud broker
Jun 11 11:49:36 96136f6a6861 tedge-mapper[664]: 2024-06-11T11:49:36.718619169Z  INFO tedge_mqtt_bridge: Waiting 757.760905934s until attempting reconnection to cloud broker
Jun 11 12:02:19 96136f6a6861 tedge-mapper[664]: 2024-06-11T12:02:19.486978375Z  INFO tedge_mqtt_bridge: Waiting 823.928368644s until attempting reconnection to cloud broker
Jun 11 12:16:08 96136f6a6861 tedge-mapper[664]: 2024-06-11T12:16:08.421557928Z  INFO tedge_mqtt_bridge: Waiting 640.372358488s until attempting reconnection to cloud broker
Jun 11 12:26:53 96136f6a6861 tedge-mapper[664]: 2024-06-11T12:26:53.803845551Z  INFO tedge_mqtt_bridge: Waiting 806.980342336s until attempting reconnection to cloud broker
```

**thin-edge.io bridge related configuration**

```sh
# tedge config list | grep bridge
c8y.bridge.include.local_cleansession=auto
c8y.bridge.topic_prefix=c8y
mqtt.bridge.built_in=true
mqtt.bridge.reconnect_policy.initial_interval=30s
mqtt.bridge.reconnect_policy.maximum_interval=10m
mqtt.bridge.reconnect_policy.reset_window=5m
```

**Comment by reubenmiller** [comment]
Another unexpected behaviour is that the `mqtt.bridge.reconnect_policy.initial_interval` setting is not treated as hard minimum value, but it is the value before the jitter is added (see the log entry below which shows a possible value of 17s, which is less than the "initial_interval" of 30s)

```log
Jun 11 13:01:25 96136f6a6861 tedge-mapper[664]: 2024-06-11T13:01:25.329372422Z  INFO tedge_mqtt_bridge: Waiting 17.568652105s until attempting reconnection to cloud broker
```

**Comment by reubenmiller** [comment]
Though I did finally look up the [backoff crate's documentation](https://docs.rs/backoff/latest/backoff/) which explains most of the behaviour, however I would question the approach used by the crate.

**Comment by jarhodes314** [comment]
The logic for the exponential backoff is [straight from the backoff crate](https://docs.rs/backoff/latest/backoff/exponential/struct.ExponentialBackoff.html). I believe the algorithm used is to keep track of the current interval (initially 30s), and on each iteration, generate a random value within a range of the current interval ± half its value.

According to this, all the values are behaving as expected.

1. 30s -> [15s, 45s] -> 42s
2. 60s -> [30s, 90s] -> 31s
3. 120s -> [60s, 180s] -> 166s
4. 240s -> [120s, 360s] -> 307s
5. 480s -> [240s, 720s] -> 591s
6. 600s (maximum interval) -> [300s, 900s] -> 371s

The range doesn't change after that, and all the values are within the range [300s, 900s]
    672s
    325s
    757s
    823s
    640s
    806s

We can change the randomization factor (currently set to 0.5, hence the ± half the value), and we can also hard bound the minimum value if we want to (although if we're cautious enough to set it to 30s, I'd say we should be cautious enough to add jitter (although we could set the initial interval of the underlying algorithm to be `configured initial interval / randomization factor`, so the `initial_interval` setting is actually a hard lower bound on the value).

**Comment by reubenmiller** [comment]
Yeah the crate's documentation was indeed helpful, so maybe it is more a documentation problem.

Though for initial values, the backoff isn't exactly exponential (not sure if this will be problematic or not)

**Comment by reubenmiller** [comment]
> we can also hard bound the minimum value if we want to (although if we're cautious enough to set it to 30s, I'd say we should be cautious enough to add jitter

Though there is an alternative approach to calculating the backoff factor, and it is to take a value between [value, value*2.0]...that way you can enforce such things as minimum values (but with jitter).

**Comment by reubenmiller** [comment]
I'll try to get some numbers so that we can compare the algorithms as I found some good materials that should be fairly easy compare:

Based on this write-up, https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/, using the [aws-arch-backoff-simulator]( https://github.com/aws-samples/aws-arch-backoff-simulator) repository, the current backoff algorithm will be compared with the other algorithms listed in the write-up.

**Comment by reubenmiller** [comment]
I'm closing this as I've compared the selected backoff algorithm (including jitter), and it seems to be on-par with the other methods (according to the others mentioned in the above aws blog post). The selected algorith takes slightly longer "to complete", however this might be a good thing when the server is in "overload" and gives a bit more time for the server function to be restored.

<img width="534" alt="image" src="https://github.com/thin-edge/thin-edge.io/assets/3029781/68187bc2-e45f-442a-9aa9-2e76a98856d9">
