### ISSUE TITLE
tedge mqtt sub ignores ctrl+c if MQTT broker is not available

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2949]
**Describe the bug**

`tedge mqtt sub` does not react to `ctrl+c` (`SIGINT`) when it is in a reconnect loop when the MQTT broker is not available.

```sh
# tedge mqtt sub '#'
ERROR: I/O: Address not available (os error 99)
ERROR: I/O: Address not available (os error 99)
ERROR: I/O: Address not available (os error 99)
ERROR: I/O: Address not available (os error 99)
^CERROR: I/O: Address not available (os error 99)
ERROR: I/O: Address not available (os error 99)
^C^C^CERROR: I/O: Address not available (os error 99)
ERROR: I/O: Address not available (os error 99)
```

**To Reproduce**

1. Stop the MQTT broker

    ```sh
    # if using systemctl and mosquitto
    sudo systemctl stop mosquitto
    ```

3. Subscribe to any topic

    ```sh
    tedge mqtt sub '#'
    ```

4. Try and stop the process using ctrl+c

The robot test would look something like this:

```
Stops the subscription on SIGINT even when broker does not exist
    Execute Command    sudo systemctl stop mosquitto
    Execute Command    cmd=timeout --signal=SIGINT 2 tedge mqtt sub '#'    timeout=5
```

**Expected behavior**

* `tedge mqtt sub` should stop on Ctrl+C (SIGINT).

**Screenshots**

**Environment (please complete the following information):**

|Property|Value|
|--------|-----|
|OS [incl. version]|`Debian GNU/Linux 12 (bookworm)`|
|Hardware [incl. revision]|`unknown`|
|System-Architecture|`Linux e7f905341c36 6.5.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 22:58:57 UTC 2024 aarch64 GNU/Linux`|
|thin-edge.io version|`tedge 1.1.2~124+g8502b28`|

**Additional context**

**Comment by gligorisaev** [comment]
Bug is not reproducable anymore
Test Step is added as part of:
https://github.com/thin-edge/thin-edge.io/pull/2944
