### ISSUE TITLE
tedge cert upload c8y does not respect the c8y.root_cert_path setting

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#2951]
**Describe the bug**

The `c8y.root_cert_path` path is not respected by `tedge cert upload c8y` and also when using a custom config-dir location. This results in the following errors:

**Error 1: UnknownIssuer**

Uploading the certificate fails due the server certificate not being able to be validated, however the custom cert location is not found:

```sh
# mv /etc/ssl/certs /etc/ssl/certs.bak
# tedge config set c8y.root_cert_path /etc/ssl/certs.bak
# tedge cert upload c8y --user myuser.example.com
Enter password:
Error: failed to upload root certificate

Caused by:
    HTTP Connection Problem: invalid peer certificate: UnknownIssuer
    Hint: Server certificate validation error.
```

**Error 2: tedge.toml file is not being found**

The `config-dir` value is not respected when running `tedge cert upload c8y`, resulting in the tedge command looking for the ca certificate in the incorrect location.

```sh
# tedge cert upload c8y --config-dir /data --user reuben.d.miller@softwareag.com
Enter password:
Error: failed to upload root certificate

Caused by:
    Root certificate path /etc/ssl/certs does not exist
```

**To Reproduce**

1. Use a custom config-dir to store thin-edge.io configuration
    
    ```sh
    tedge --config-dir /data init
    tedge --config-dir /data cert create --device-id testname
    ```

2. Move the existing certs

    ```sh
    mv /etc/ssl/certs /etc/ssl/certs.bak
    tedge config set --config-dir /data c8y.root_cert_path /etc/ssl/certs.bak
    tedge config set --config-dir /data c8y.url mytenant.c8y.example.com
    ```

3. Try uploading the device certificate to Cumulocity IoT

    ```sh
    tedge cert upload c8y --config-dir /data --user <username>
    ```

**Expected behavior**

The `c8y.root_cert_path` path should be respected when communicating with Cumulocity IoT via HTTP or MQTT. The setting should be allowed to be set in the default tedge.toml location, or in custom locations as controlled by the `--config-dir <path>` flag on each of the thin-edge.io binaries.

**Screenshots**

**Environment (please complete the following information):**

|Property|Value|
|--------|-----|
|OS [incl. version]|`Alpine Linux v3.18`|
|Hardware [incl. revision]|`container`|
|System-Architecture|`Linux 0e1925ccd1a0 6.5.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 22:58:57 UTC 2024 aarch64 GNU/Linux`|
|thin-edge.io version|`tedge 1.1.2~125+ged0b7fd`|

**Additional context**

**Comment by reubenmiller** [comment]
It looks like that the bug is further reaching than just the `tedge cert upload c8y`. The mapper seems to be also affects (which makes sense, since the http component is probably shared in the code).

**Comment by reubenmiller** [comment]
Apologies, I have accidentally overwritten the original ticket description (as I was copying some markdown to create a new ticket, and accidentally posted in the same window!)...I will try to reconstruct the ticket description soon!

**Comment by gligorisaev** [comment]
Bug is not reproducable anymore
