### ISSUE TITLE
c8y bridge misses "s/us/#" topic

### ISSUE THREAD

**Issue by reey** [thin-edge/thin-edge.io#300]
**Describe the bug**
The configuration for the mosquitto bridge to c8y (/etc/tedge/mosquitto-conf/c8y-bridge.conf) does not bridge the `s/us/#` topic.

**To Reproduce**
Execute `tedge mqtt pub 'c8y/s/us/test123' '211,25'`.

**Expected behavior**
The above command should create a new temperature measurement for a child device with the external id `test123`. If the device does not already exist it will be created.

**Screenshots**
--

**Environment (please complete the following information):**
 - Raspbian GNU/Linux 10 (buster)
 - Raspberry Pi 4
 - Linux raspberrypi 5.10.17-v7l+ #1414 SMP Fri Apr 30 13:20:47 BST 2021 armv7l GNU/Linux
 - thin-edge.io version 0.2.0

**Additional context**
This can be easily fixed by adding `topic s/us/# out 2 c8y/ ""` at the bottom of the `/etc/tedge/mosquitto-conf/c8y-bridge.conf` file and restarting mosquitto.

**Comment by didier-wenzek** [comment]
Thank you. Indeed, the very first releases of thin-edge don't provide any support for child devices. But, as you said, this can be easily fixed at the bridge level and so will be done shortly. A full support of child devices is not planned for the short term, though.

**Comment by didier-wenzek** [comment]
This has been fixed on the main code branch.
