### ISSUE TITLE
Support multiple cloud connections of the same type in container environments

### ISSUE THREAD

**Issue by reubenmiller** [thin-edge/thin-edge.io#3011]
**Is your feature improvement request related to a problem? Please describe.**

In a container deployment and using the built-in bridge feature, it should be possible to run two instances of the tedge-mapper to connect to two different Cumulocity IoT instance where both mappers are connected to the same local MQTT broker.

This is stage 1 of a 2 stage process to support connecting multiple instances of the same mapper type (e.g. n x c8y/aws/az) to two different cloud instances. The first stage assumes that two independent `tedge-mapper-<cloud>` instances can run in different connections to provide an isolated environment for both settings and certificates.

**Describe the solution you'd like**

The following items needs to be changed in order to support multiple connections to clouds of the same type, however a full running demo should be used to check that there are no other changes required.

* Add new config to support configurable topic prefixes for Azure and AWS
    * `az.bridge.topic_prefix`
    * `aws.bridge.topic_prefix`
    
* `te/` commands should use the `c8y.bridge.topic_prefix` setting when generating the command id which is used to associate a `te/` command to a specific mapper instance

    For example, the following code shows that the `c8y-mapper` command id is hardcoded instead of using the `c8y.bridge.topic_prefix` configuration value.

    [let topic_name = if cmd_id.starts_with("c8y-mapper") {](https://github.com/reubenmiller/thin-edge.io/blob/50ddf67b134bc84fa1115a3eebed70a703daa77a/crates/extensions/c8y_mapper_ext/src/compatibility_adapter.rs#L149-L154)

    After the code change, a command instance in the `/cmd/` topic should follow the below pattern:

    ```sh
    te/device/main///cmd/config_snapshot/${c8y.bridge.topic_prefix}-mapper-${cloud-operation-id}
    ```

**Describe alternatives you've considered**

**Additional context**

**Comment by gligorisaev** [comment]
LGTM

Will create Tests to cover this as soon as the keywords are created (part of other PR)
