### ISSUE TITLE
tedge-mapper-c8y: registered child-device does not receive data anymore after restart

### ISSUE THREAD

**Issue by ButKor** [thin-edge/thin-edge.io#3051]
**Describe the bug**
I have a connected thin-edge.io instance and registered a child-device via a dedicated registration message. Everything works fine - until I restart tedge-mapper-c8y. After restart the child-device does not receive data anymore in Cumulocity. 

**To Reproduce**
```sh
$ tedge --version
tedge 1.2.0
$ sudo tedge config set c8y.url example.eu-latest.cumulocity.com
$ sudo tedge config set c8y.entity_store.auto_register false
$ sudo tedge cert create --device-id "my-tedge-main-device"
$ sudo tedge cert upload c8y --user "john.doe"
...
$ sudo tedge connect c8y
...
$ tedge mqtt pub "te/device/main///e/heartbeat" '{ "text": "Heartbeat event" }' # works fine
$ tedge mqtt pub "te/device/my-child-1//" '{
    "@type": "child-device",
    "@id": "my-child-1-id",
    "name": "my-child-1-name",
    "type": "my-child-1-type"
}' # successfully created a Cumulocity Device with name=my-child-1-name, type=my-child-1-type, external-id (c8y_Serial) = my-child-1-id
$ tedge mqtt pub "te/device/my-child-1///e/heartbeat" '{ "text": "Heartbeat event" }' # works fine
$ sudo systemctl restart tedge-mapper-c8y
$ tedge mqtt pub "te/device/my-child-1///e/heartbeat" '{ "text": "Heartbeat event" }' # nothing received by the platform anymore
```

**Expected behavior**
Expected to still send events towards the platform via `tedge mqtt pub "te/device/my-child-1///e/heartbeat" '{ "text": "Heartbeat event" }'` after restart of tedge-mapper-c8y. 

**Environment (please complete the following information):**
 - Happening on a raspberry-pi 5 with debian-bookworm
 - Reproducible with: https://github.com/thin-edge/tedge-demo-container
 - tedge version 1.2.0

**Additional context**
* When using `sudo tedge config set c8y.entity_store.auto_register true` thin-edge.io creates a new device named 'my-child-1' with last command of the reproduction steps. It seems not to be aware that there is already an entity registered for 'my-child-1'. 
* Before mapper restart, the test-event for child-device resulted in:
```
$ mosquitto_sub -t '#' -h localhost -v
te/device/my-child-1///e/heartbeat { "text": "Heartbeat event" }
c8y/event/events/create {"type":"heartbeat","time":"2024-08-04T16:23:05.189246923Z","text":"Heartbeat event","externalSource":{"externalId":"my-child-1-id","type":"c8y_Serial"}}
```

After restart, same event:
```
$ mosquitto_sub -t '#' -h localhost -v
te/device/my-child-1///e/heartbeat { "text": "Heartbeat event" }
```
Not seeing an error - missing the event towards c8y/event/events/create though.

Is that a bug - or am I missing a step here?

**Comment by reubenmiller** [comment]
@ButKor registration messages need to be published with the retain flag so they are persisted on the mqtt broker, so I’m pretty sure that is why the mapper does not know of the child device after being restarted.

So retest with the retain flag (as it might be something else)

**Comment by ButKor** [comment]
Thanks, that explains it! Retested and adding `-r` to registration message solved my problem.
