### ISSUE TITLE
Software updates are downloaded multiple times when update-list isn't supported by the relevant plugin

### ISSUE THREAD

**Issue by jarhodes314** [thin-edge/thin-edge.io#3062]
**Is your feature improvement request related to a problem? Please describe.**
If a plugin returns exit code 1 on an `update-list` operation to indicate that it doesn't support `update-list`, `tedge-agent` will fall-back to calling `install` multiple times, but in doing so it will re-download the relevant software package(s). This uses both additional data and disk space (as the original file is left in tact while we download the new `.tmp` file).

**Describe the solution you'd like**
`tedge-agent` should use the existing downloaded files when falling back from `update-list` to `install`

**Describe alternatives you've considered**

**Additional context**

**Comment by rina23q** [comment]
Resolved by #3065

**Comment by gligorisaev** [comment]
Reviewed the linked PR, the improvement is implemented
