### ISSUE TITLE
Software installation fails due to prompt of restarting service

### ISSUE THREAD

**Issue by mbay-ODW** [thin-edge/thin-edge.io#3096]
**Describe the bug**
When I want to install e.g. nano on my system I do get the info that I need to restart services due to outdated libraries.

**Expected behavior**
Prompt will be handled accordingly

**Screenshots**
Find attached the prompt that appears while installing manually on site.

**Environment (please complete the following information):**
 - OS - Linux
 - System-Architecture - armv71
 - thin-edge.io version [1.2

Not sure maybe its not a bug but a feature request on how those or other prompts should be handled.

![image](https://github.com/user-attachments/assets/0833075c-c1b6-4403-a48f-50e95ae8eb91)

**Comment by reubenmiller** [comment]
@mbay-ODW What OS are you using? Debian?

**Comment by reubenmiller** [comment]
Just a quick google search showed some direction, https://stackoverflow.com/questions/73397110/how-to-stop-ubuntu-pop-up-daemons-using-outdated-libraries-when-using-apt-to-i.

The pop-up seems to come from the `needrestart` command where you should be able to configure your OS to take the desired action (e.g. automatically restart or not etc.)

**Comment by reubenmiller** [comment]
(taken from the above link), the needrestart command can be configured using the following one-liner, however it would still be advised reading the manual for needrestart to make sure it behaves as you want.

```sh
sed "/#\$nrconf{restart} = 'i';/s/.*/\$nrconf{restart} = 'a';/" /etc/needrestart/needrestart.conf
```

**Comment by reubenmiller** [comment]
@mbay-ODW Have you had a chance to try it out yet?

**Comment by mbay-ODW** [comment]
Yes in deed, that worked. Thanks for the pointing. Can be closed.
