### ISSUE TITLE
ThinEdge requires glibc 2.29, severely limiting OS compatibility 

### ISSUE THREAD

**Issue by m-kostira** [thin-edge/thin-edge.io#310]
I'm playing around with thin-edge, installing it to a debian 10 VM using the script from github 

```
curl -fsSL https://raw.githubusercontent.com/thin-edge/thin-edge.io/main/get-thin-edge_io.sh | sudo sh -s 0.2.0
```

It installs fine and I'm able to generate a cert and connect to c8y. However, the mapper fails to start. In the journalctl logs I see:
 
```
Jun 14 09:52:10 debian tedge_mapper[1464]: /usr/bin/tedge_mapper: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/bin/tedge_mapper)
Jun 14 09:52:10 debian systemd[1]: tedge-mapper-c8y.service: Main process exited, code=exited, status=1/FAILURE
```

This implies ThinEdge is incompatible with many fairly recent Linux versions, such as the latest Debian release. Upgrading glibc is risky (see for example https://red.ht/3d6nWy0). This could be a show-stopper for many potential adopters that have devices out there in the field running incompatible OSes.

**Comment by didier-wenzek** [comment]
@m-kostira Thank you for evaluating thin-edge. Regarding your issue, I'm surprised that you got an error with the mapper but not with the main `tedge` command. Indeed, both should have the same system dependencies.

Can you, please, send us the output of `ldd /usr/bin/tedge` and `ldd /usr/bin/tedge_mapper`? Thank you.

**Comment by itsyitsy** [comment]
As there was no more comment answer we have to close this issue, please open a new issue if you face this problem again
