### ISSUE TITLE
ERROR log in tedge-agent log on every software list operation execution

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#3251]
**Describe the bug**

The following error is logged in the tedge-agent log on every software list operation execution:

```
Nov 14 07:28:03 33ac3a38e5b1 tedge-agent[494]: 2024-11-14T07:28:03.824623986Z ERROR tedge_agent::operation_workflows::persist: Fail to remove the workflow copy at /etc/tedge/.agent/workflows-in-use/software_list-builtin.toml: No such file or directory (os error 2)
```

**To Reproduce**

1. Watch the tedge-agent log with `journalctl -f -u tedge-agent`
2. Trigger a software update operation from the C8y cloud or a software list operation locally
3. Observe the error log after the operation execution completes

**Expected behavior**

No error log on successful operation execution.

**Comment by reubenmiller** [comment]
Resolved. The log message is no longer present.
