### ISSUE TITLE
Workflow script is triggered twice

### ISSUE THREAD

**Issue by mstoffel-sag** [thin-edge/thin-edge.io#3281]
**Describe the bug**
I have a workflow for the software update operation [software_update.toml](https://github.com/user-attachments/files/18009244/software_update.txt)
It triggers a shell script [tedge-op-software-update-confirm-redis.sh](https://github.com/user-attachments/files/18009365/tedge-op-software-update-confirm-redis.txt)

```bash
#!/bin/bash
CHANNEL=$1
SOFTWARE=$2
echo "publish to redis $CHANNEL $SOFTWARE"
redis-cli publish "$CHANNEL" "$SOFTWARE"
echo "subscribing to $CHANNEL wait for confirmaiton"
while read -r MESSAGE; do
        if  [ "$MESSAGE" = "0" ] ; then
            echo "confirmed: $MESSAGE"
            exit 0
        elif [ "$MESSAGE" = "100" ] ; then
            echo "discard: $MESSAGE"
            exit 100
        else
            echo "no valid command: $MESSAGE"
        fi
done < <(redis-cli SUBSCRIBE "$CHANNEL")
```

the script that is executed in the confirm state is executed two time. I also have to execute the confirm action two times to make the workflow proceed.

![image](https://github.com/user-attachments/assets/2ba30a95-f0f2-4b2e-984e-4bab4734b353)

<img width="1503" alt="image" src="https://github.com/user-attachments/assets/8caecb2f-c2c9-4727-9384-bec59f429ebd">

after first confirmation:

<img width="1507" alt="image" src="https://github.com/user-attachments/assets/d6612b2e-715f-4c14-a6be-6f18467685fd">

after second confirmation:

<img width="980" alt="image" src="https://github.com/user-attachments/assets/2aab5eba-49d3-4414-8ae6-c4d8197188b2">

[workflow-software_update-c8y-mapper-28250.log](https://github.com/user-attachments/files/18009478/workflow-software_update-c8y-mapper-28250.log)

**To Reproduce**
The script will publish to a redis topic and excpects either 0 confirm or 100 on the same topic as confirmation. Script needs to be placed in /usr/bin

**Expected behavior**
only one script is started

**Screenshots**

**Environment (please complete the following information):**
 - OS 22.04.1-Ubuntu SMP PREEMPT_DYNAMIC
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
Linux taotech 6.8.0-49-generic

 - thin-edge.io version 1.3.1

**Additional context**

**Comment by reubenmiller** [comment]
@mstoffel-sag Can you please include the tedge-agent logs as well during a run?

**Comment by reubenmiller** [comment]
I can't see an evidence of thin-edge.io launching two processes. @mstoffel-sag Can you please provide the command that you're using two show the different processes...maybe the command is actually showing tasks and not processes (where there can definitely be more than 1 task associated to a process).

**Comment by mstoffel-sag** [comment]
Hi Reuben,

I used ps auxww

**Comment by mstoffel-sag** [comment]
yeah sorry, it looks the same when I run it by myselfe. But its weird that I can trigger it with just one publish when I run it manually and two publishes when thinEdge executes it...

**Comment by mstoffel-sag** [comment]
yeah sorry, it looks the same when I run it by myself. This must be an issue with my script altogether.
