### ISSUE TITLE
Certificate can't be uploaded

### ISSUE THREAD

**Issue by JoergWende** [thin-edge/thin-edge.io#403]
**Describe the bug**
I want to connect based on this tutorial: https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/tutorials/connect-c8y.md to a trial instance of cumulocity.
Certificate cant be uploaded / added due to 'Access denied / 404' error

**To Reproduce**
tried: 
sudo tedge cert upload c8y --user xxx
Enter password:
Error: failed to upload root certificate

Caused by:
    HTTP status client error (401 Unauthorized) for url (https://xyz.eu-latest.cumulocity.com/tenant/currentTenant)

**Expected behavior**
certificate added ...

**Environment (please complete the following information):**
 - Raspberry Pi 4
 - thin-edge.io version [ 0.2.0]

**Comment by vaillant** [comment]
IMHO the documentation should be updated to avoid this problem in the future.
