### ISSUE TITLE
Improve user experience for first-time thin-edge.io users

### ISSUE THREAD

**Issue by vaillant** [thin-edge/thin-edge.io#424]
First time users, especially coming from thin-edge.io, do not have a nice and complete user experience.

I would expect that
* thin-edge.io links to a "Quick start guide" (?) under "Getting Started"
* The Quickstart guide demonstrates how to install and use most of the functionality of thin-edge. That includes measurement sending, device monitoring and device OTA software mgmt.
* We somehow would need to deal with C8Y and Azure differences. I would propose to have two quickstart guides, one for C8Y and one for Azure. Idea: Maybe another tuturial "Quickstart without cloud"

Problems with the approach today is:
* The script get-thin-edge_io.sh does not ensure that all components are installed.
* https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/howto-guides/002_installation.md does not describe the installation of all components, at least not explicitly.
* The current tutorial "entry point" (https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/tutorials/connect-c8y.md ) does not link to additional tutorials like monitoring and OTA software management.
* In https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/tutorials/device-monitoring.md additional installation steps are needed. This makes the complete experience pretty bad. Why is that not done in the curl shell script?

**Comment by didier-wenzek** [comment]
About the documentation, are you looking for something similar to [this tutorial](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/tutorials/connect-c8y.md).
* We will need to add an overview of device monitoring and software management or at least links to [this](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/tutorials/device-monitoring.md) and [this](https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/tutorials/software-management.md) tutorial.
* And sure we will have to change the landing page for those coming from thin-edge.io,
* But I wonder what you see as truly missing for a new user.

About the packaging, this is indeed a good idea to have an install-all scripts along more specific ones.

**Comment by vaillant** [comment]
Additional ideas to simplify first time UX:
* Should the self-signed certificate be generated automatically on installation?
* As a meta-comment, we should ask newcomers for their experience on the first time usage experience.
* The main comment is that someone needs to read (at least) four web pages to experience the product. IMHO we should simplify the documentation experience.

**Comment by didier-wenzek** [comment]
The first time UX will be improved notably by [improving the documentation](https://github.com/thin-edge/thin-edge.io/issues/1238)
