### ISSUE TITLE
Make thin-edge.io capable for running on low-footprint Linux distros 

### ISSUE THREAD

**Issue by marco2901** [thin-edge/thin-edge.io#505]
It would be cool to have thin-edge.io running on thin linux distros like alpine, debian-slim, etc. Current limitations are the systemd dependency as well as apt dependency. Thin linux OS are often not based on systemd and use alternative package managers like apk or even no one. Also the installation on plc systems is not easy due to these issues. 
As an improvement and to get rid at least of the apt dependency, an installation script installing all needed (sub)dependencies for tedge and moquitto would be helpful.

**Comment by reubenmiller** [comment]
This is covered by the new installation script and packages.

Check out the new [install guide](https://thin-edge.github.io/thin-edge.io/next/install/)
