### ISSUE TITLE
Functionalities for Softwaremanegement of Docker Containers missing

### ISSUE THREAD

**Issue by mbay-ODW** [thin-edge/thin-edge.io#506]
**Is your feature request related to a problem? Please describe.**
Currently with 0.4 only the initial run or the deletion of an docker container is triggered. However there is more to the orchestration and management of containers. Currently no environmentals, port or volume mappings are provided. Same is true for the actual status of the container. That way the central distribution and management of containers can hardly be used in production.

**Describe the solution you'd like**
Parameters for the container such as -p, -v or -e could be added as additional fragment to the operation. However this would need an extension of the current ui. Same is true for the actual status of the container. Maybe collectd is capable of monitoring containers as well, however somehow the status should be displayed within the device management. Additionaly it should be possible to start, stop and restart containers.

**Comment by reubenmiller** [comment]
@mbay-ODW This is now addressed by a community plugin which supports deploying a container or a container-group (docker compose file). The container-group allows you to control how the container is deployed (e.g. which ports should be published, volume mounting etc.).

Checkout the plugin here: https://github.com/thin-edge/tedge-container-plugin
