### ISSUE TITLE
Mapping of events and alarms

### ISSUE THREAD

**Issue by mbay-SAG** [thin-edge/thin-edge.io#507]
**Is your feature request related to a problem? Please describe.**
Currently only measurements are mapped via tedge/measurements. Gateways commonly send alarms or event information such that a mapping to e.g. tedge/events or tedge/alarms would be necessary.
**Describe the solution you'd like**
An event and alarm mapper on e.g. tedge/alarms and tedge/events that can be used to send alarms and events to Cumulocity. Since the measurement mapping also relays on json based payloads this can be adapted to events as well. For alarms this somehow needs to be extended for the lifecycle of alarms e.g. tedge/alarms/Alarm-ID or similar.

**Describe alternatives you've considered**
Currently thin-edge.io allows sending of alarms and events

**Comment by itsyitsy** [comment]
Alarms was already handled in milestone: https://github.com/thin-edge/thin-edge.io/milestone/5

Development of events is going to be handled in https://github.com/thin-edge/thin-edge.io/milestone/10

**Comment by itsyitsy** [comment]
https://github.com/thin-edge/thin-edge.io/issues/809
