### ISSUE TITLE
tedge config set mqtt.BROKERURL not provided

### ISSUE THREAD

**Issue by mbay-ODW** [thin-edge/thin-edge.io#520]
**Is your feature request related to a problem? Please describe.**
We tried an multi container setup where MQTT Broker and sedge-mapper are running in two different containers. Within the mapper the MQTT Broker address can not be configured.

**Describe the solution you'd like**
Use mqtt.url= as a new key value pair for config.

**Comment by mbay-SAG** [comment]
Is the function tedge config set mqtt.external.bind_address meant for that?

**Comment by didier-wenzek** [comment]
The `mqtt.external.bind_address` is related but not what you expect.

* This setting creates a second listener so the MQTT bus will accept both local and remote connections. However the tedge-mapper will still try to connect to the local bus.
* In the multi-container use-case, the MQTT broker could be started with such a setting, but the mapper would require a parameter to connect its neighbor container. Something that cannot currently be done.

**Comment by mbay-SAG** [comment]
Could you point us to the files where this needs to be added, thus we would fork here probably. We searched for "mqtt.port" and did find out that these settings seems to be done in several rust files such that it was not clear to us where to add that function in detail.

**Comment by didier-wenzek** [comment]
If you wish to add this feature, I see two approaches.

## Add a `--host` parameter to the `tedge_mapper` daemon.
* This is done with a new field of the [`MapperOpt` struct](https://github.com/thin-edge/thin-edge.io/blob/d868279ba030de1488e49480dd95f440e5bab085/mapper/tedge_mapper/src/main.rs#L37)
* This parameter will have to be passed to the [`start`](https://github.com/thin-edge/thin-edge.io/blob/d868279ba030de1488e49480dd95f440e5bab085/mapper/tedge_mapper/src/component.rs#L6) function of all the mappers implementation.
* And used in the [`create_mapper`](https://github.com/thin-edge/thin-edge.io/blob/d868279ba030de1488e49480dd95f440e5bab085/mapper/tedge_mapper/src/mapper.rs#L32) function.

The second step might be a bit tedious.

## Add a `mqtt.host` parameter in `tedge config`.
* Add a new setting in the `tedge_config` along the lines of what has been done for [`mqtt.port`](https://github.com/thin-edge/thin-edge.io/blob/d868279ba030de1488e49480dd95f440e5bab085/tedge_config/src/settings.rs#L149).
* Use that setting in the [`mqtt_config`](https://github.com/thin-edge/thin-edge.io/blob/d868279ba030de1488e49480dd95f440e5bab085/mapper/tedge_mapper/src/mapper.rs#L38) function of the mapper.

The first step impacts numerous files but is not difficult.

**Comment by reubenmiller** [comment]
Good news, this is solved by #1773. The feature has been merged into main already, and is under official verification.
