### ISSUE TITLE
tedge.toml does not include device-id under [device]

### ISSUE THREAD

**Issue by mbay-SAG** [thin-edge/thin-edge.io#531]
**Is your feature request related to a problem? Please describe.**
Currently the device id is not stored within the tedge.toml which might be needed by other plugins or modules.
**Describe the solution you'd like**
Write the device id into the toml
**Describe alternatives you've considered**
I can get the device id also from tedge config list but there is no reason why only the device id is missing on the toml.

**Comment by itsyitsy** [comment]
As @rina23q pointed out rightfully this is expected behaviour and done on purpose. We do not want to have inconsistency regarding device-id and therefore the device certificate is and will be the only place where the device-id gets stored.
