### ISSUE TITLE
Fail to create bridge on WSL 2

### ISSUE THREAD

**Issue by simeonthefirst** [thin-edge/thin-edge.io#539]
**Describe the bug**
When installed and registered as described in the How To, `sudo tedge connect c8y` fails to create bridge.

**To Reproduce**
execute `sudo tedge connect c8y` on WSL

**Expected behavior**
Successful connection 

**Screenshots**
``` 
sudo tedge connect c8y

Checking if systemd is available.

Checking if configuration for requested bridge already exists.

Validating the bridge certificates.

Saving configuration for requested bridge.

Restarting mosquitto service.

Error: failed to create bridge to connect Cumulocity cloud.

Caused by:
Systemd returned unspecific error for service mosquitto while performing restart it.
Hint: Lacking permissions or service's process exited with error code.
``` 

**Environment (please complete the following information):**

* OS System: Ubuntu 20.04.3 LTS  **WSL 2**
* System-Architecture x86_64
* thin-edge.io version 0.4.0

**Additional context**
I think WSL has no **systemd** but it prints a `Checking if systemd is available.` without an error on this line.

Permissons should be alright:

```
ls -l /etc/tedge
total 16
drwxr-xr-x 3 root      root      4096 Oct 28 15:11 contrib
drwxr-xr-x 2 mosquitto mosquitto 4096 Oct 28 17:38 device-certs
drwxr-xr-x 2 tedge     tedge     4096 Oct 29 09:16 mosquitto-conf
-rw-rr-- 1 tedge     tedge      119 Oct 29 09:16 tedge.toml
``` 

and mosquitto:

```
ls -l /usr/sbin/mosquitto
-rwxr-xr-x 1 root root 297280 Oct 27 23:00 /usr/sbin/mosquitto
``` 

AC:

* If systemd is not available on the system create error at the end of the printout:
** The user has to start/restart components manually (With reference what actions are required)
** Configuration of mosquitto is created
** The UX of thin-edge is better with systemd

**Comment by itsyitsy** [comment]
Hallo @simeonthefirst
yes systemd is usually missing in WSL. We will look into why the systemd check in connect is not working.

Please use a systemd supported system to install thin-edge.io on.
