### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by EricSand** [thin-edge/thin-edge.io#564]
**Describe the bug**
Link to "Cumulocity UI" is leading to 404 page.

**To Reproduce**
- Go to: https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/howto-guides/004_connect.md
- in the part "You can upload root certificate via Cumulocity UI or with tedge cert upload as described below.", click on "Cumulocity UI"
- It links to https://cumulocity.com/guides/10.7.0-beta/device-sdk/mqtt/#device-certificates, which gives back 404

**Expected behavior**
Link to correct spot in c8y documentation to upload device certificate: https://cumulocity.com/guides/users-guide/device-management/#trusted-certificates

**Screenshots**
![image](https://user-images.githubusercontent.com/51123902/140765371-2e9348aa-7d03-49d4-b733-43221e1ec14e.png)

**Comment by PradeepKiruvale** [comment]
Hi EricSand, 
Thanks for raising the issue. Fixed the issue with [PR](https://github.com/thin-edge/thin-edge.io/pull/566)
