### ISSUE TITLE
`cargo oudated` is failing on commit workflow

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#590]
**Describe the bug**
"cargo outdated" is failing on commit CI workflow. Because of this the PRs can not be merged.

**To Reproduce**
Every commit pushed onto the thin-edge.io repo is causing this issue

**Expected behavior**
"cargo outdated" check should pass.

**Screenshots**
Find the error logs below

Run actions-rs/cargo@v1
  with:
    command: outdated
    use-cross: false
  env:
    CARGO_TERM_COLOR: always
/usr/share/rust/.cargo/bin/cargo outdated
thread 'main' panicked at 'package cache lock is not currently held, Cargo forgot to call `acquire_package_cache_lock` before we got to this stack frame', /usr/share/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.57.0/src/cargo/util/config/mod.rs:1542:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: The process '/usr/share/rust/.cargo/bin/cargo' failed with exit code 101

**Environment (please complete the following information):**
 - OS [ubuntu]
 - Hardware [x86]
 - System-Architecture [github hosted runner]
 - thin-edge.io version [e.g. 0.4.2]

**Additional context**
The workaround is to remove the mandatory check on `cargo outdated` so that the PRs can be merged.

**Comment by rina23q** [comment]
It seems specific combination of cargo version and cargo-outdated fails to compile. For example, with cargo 1.52.0 version, failed to compile cargo-outdated 0.10.2 (latest). 
It's fine with the combination of 
- cargo 1.52.0 & cargo-outdated 0.9.17
- cargo 1.56.0 & cargo-outdated 0.10.2
I think the first step we should take is to print out cargo version and cargo plugin versions in our pipeline. I'm doing now. It's difficult to debug without version infos...

**Comment by rina23q** [comment]
Our workflow uses cargo `1.56.0` and cargo-outdated `0.10.0`. Unfortunately, this combination brings an error when we run `cargo outdated`. The fix is to use cargo-outdated `0.10.2`.

**Comment by rina23q** [comment]
#595 moved this to commit-workflow-optional. At least we don't block merging or triggering other workflows.

**Comment by rina23q** [comment]
With cache, `cargo` always uses version `0.10.0`, which is broken even though we have a step `cargo install cargo-outdated --version 0.10.2`. Now we disable whole commit-workflow-optional as all jobs there are failing. Keep this ticket open.

**Comment by rina23q** [comment]
As of now, we have `cargo outdated` in our commit-workflow-optional, and there is no issue. Hence, I'd close this issue.
