### ISSUE TITLE
Improve `tedge connect` to address a race condition

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#626]
**Is your feature request related to a problem? Please describe.**
In the existing `tedge connect c8y` the bridge will be created first and then a `device create` message will be sent to cumulocity.
The device-create message will have device-name and device-type fields. The values for these will be the name of the device and  thin-edge.io respectively.
The problem is if any message is sent to the cumulocity on `c8y/s/us` before sending a device creation message, then still the device will get created on the Cumulocity cloud with `MQTT-device-name` and `MQTT-device-type` as name and type respectively.

**Describe the solution you'd like**
So, to avoid this race condition the proposed solution is to do `directly connect to the cumulocity over MQTT and send the device create message`, once the device is successfully created, create the bridge and connect the device to the Cumulocity over the bridge for further communications.

**Describe alternatives you've considered**

**Additional context**

**Comment by didier-wenzek** [comment]
This has been implemented by https://github.com/thin-edge/thin-edge.io/issues/710
