### ISSUE TITLE
Remove the dependency on systemd

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#639]
**Motivation**
Thin-edge currently requires `systemd`. More precisely the `tedge connect` command and the `tedge disconnect` command use `systemd` to restart the misc daemons that connect the device to the cloud (namely `mosquitto` and the mapper).

This is really inconvenient on a device without `systemd` (notably on [`WSL`](https://github.com/thin-edge/thin-edge.io/issues/539) and [small-footprint Linux distributions](https://github.com/thin-edge/thin-edge.io/issues/505)) or [Bsd, gentoo ...](https://github.com/thin-edge/thin-edge.io/issues/178)). Thanks to this [commit](https://github.com/thin-edge/thin-edge.io/pull/568), the `tedge connect` command can be used to create the bridge configuration, but the device owner has to restart himself the connection-related daemons.

It would be convenient to:
* remove any hard-coded dependency to `systemd`, letting the choice of an init system to the device owner.
* have the `tedge connect` and `disconnect` commands actually connecting and disconnecting the device and not just configuring the connection.

**Describe the solution you'd like**

The current code base already contains an abstraction ([`SystemServiceManager`](https://github.com/thin-edge/thin-edge.io/blob/main/crates/core/tedge/src/system_services/manager.rs)) with 3 implementations (`systemd`, `openrc`, `bsd`). However, one has to recompile the `tedge` command to switch to a different init system. See the function [`service_manager` in `tedge/src/main.rs`](https://github.com/thin-edge/thin-edge.io/blob/400ecc7ec9cb90d4422eed03bf5eb32a6c6e8a6c/crates/core/tedge/src/main.rs#L52).

The proposal is to implement and make the default a `SystemServiceManager` that uses a configuration file providing the commands to manage all the daemons required by thin-edge.

* This configuration is stored in `/etc/tedge/system.conf`, owned by root, and along the Toml format.
* This file provides the command line for each of the method of the [`SystemServiceManager`](https://github.com/thin-edge/thin-edge.io/blob/main/crates/core/tedge/src/system_services/manager.rs) trait.
* One needs a convention to pass the service name. The proposal is to use `{}` as a placeholder for the service name.
* Something along the lines (say for open-rc):
    ```
    start = "/sbin/rc-service {} start"
    stop =  "/sbin/rc-service {} stop"
    enable =  "/sbin/rc-update add {}"
    disable =  ["/sbin/rc-update", "{}", "delete"]
    restart = ["/sbin/rc-update", "{}", "restart"]     <-- preferred syntax example
    ```
* An open question is: do we need a specific configuration for each of the [target services](https://github.com/thin-edge/thin-edge.io/blob/main/crates/core/tedge/src/system_services/services.rs)?
* A default configuration file will be provided for the supported init system, but the owner will be free to configure its own system.
* Bonus: this configuration file can be later completed with other system wise command (e.g for reboot).

**Describe alternatives you've considered**

1) Simply use the current architecture with a binary compiled for each specific init system.
    * This requires proper documentation
    * and requires an implementation of the `SystemServiceManager` trait for each supported init system.
2) Instead of a compilation flag, uses a runtime configuration flag.
    * Something along the line `tedge config set system.init openrc`. 
    * This still requires a implementation of the `SystemServiceManager` trait for each supported init system.

**Additional context**

AC:
 * systemd shouldnt be called in the code only SystemServiceManager
 * SystemServiceManager uses /etc/tedge/system.conf with array type format to get configs.
 * Debian packages should still contain a valid configuration for systemd

**Comment by emit-jb** [comment]
We would like to operate thin-edge in a container.
It would help us a lot if we could resolve the dependencies on Systemd and also on Mosquitto.

We have found the following issues for this
#505 
#504 

Thumbs up

**Comment by rina23q** [comment]
Leftovers:
- Add a how-to-guide "How to configure your service manager" (title can be changed)
- System tests.
