### ISSUE TITLE
Make download path configurable

### ISSUE THREAD

**Issue by toewsar** [thin-edge/thin-edge.io#651]
**Is your feature request related to a problem? Please describe.**
The download path for software packages is fixed to `/tmp`. In our case `/tmp` limited to 16MB.
Larger Packages cannot be installed.

**Describe the solution you'd like**
Make download path configureable (e.g. in `tedge.toml`)

**Describe alternatives you've considered**
Pass download path via environment.

AC:
 * "/tmp" should stay the default.
 * Make tmp a configuration in tedge.toml
 * E.g. "tedge config set tmp.path"

**Comment by itsyitsy** [comment]
Hello @toewsar 
Sounds like a good proposal, we expected already that this needs to be configurable in some time. We will pick that up.
