### ISSUE TITLE
As a device owner I want to push raised alarms (drop1)

### ISSUE THREAD

**Issue by cstoidner** [thin-edge/thin-edge.io#667]
As a thin-edge device owner I want to be able to raise alarms and push these to the cloud.

Therefore thin-edge public alarm API (MQTT topic "tedge/alarms") shall be introduced. C8Y Mapper to be extended to support that API with thin-edge JSON (alarm) format, as specified in
    https://github.com/thin-edge/thin-edge.io-specs/blob/82d4dd269887ab69544df616aa9244752319f8cb/src/alarms/alarm-handling.md

AC:
  - Scope of that ticket is realization of alarms support for C8Y. Other clouds (e.g. Azure) are not yet in scope.
  - C8Y mapper shall support thin-edge JSON alarm format (as defined in spec linked above) 
  - C8Y mapper shall avoid duplicates (as defined in spec linked above) 
  - Reliable Data chain shall be provided (as defined in spec linked above) 
  - Both functionalities "Raw payload format" and "Addressing Child-Devices" from Spec above, are not in scope of that drop1 implementation.

**Comment by itsyitsy** [comment]
We agreed in the grooming that we will go with mqtt(not REST) for now. @cstoidner will check back with c8y team about the behaviour for ack of .
