### ISSUE TITLE
Problem by Connection to cumulocity(c8y)

### ISSUE THREAD

**Issue by CyntiaPola** [thin-edge/thin-edge.io#668]
while trying to connect, my url does not work .

The format to be used is: <your-tenant>.cumulocity.com after given this command (sudo tedge config list --doc) to verify .
but mine(c8y url) does not end this way given that for the works it is rather <my-tenant>.xxxx.com
so i wonder if this may be the problem.Because I was forced to upload the tedge certificate manually(through my GUI)

When I enter the command "tedge connect c8y"
I have this warning:  Bridge has been configured, but Cumulocity connection check failed.

what I have:
 - OS [Linux ubuntu. v20.04]
 - thin-edge.io version 0.4.3

**Comment by rina23q** [comment]
Hi, `c8y.url` depends on where you have Cumulocity tenant. If you have a tenant, named `test` on the instance `cumulocity.com`, then the expected `c8y.url` is`test.cumulocity.com`. If you have a tenant on another instance, named `xxx.com`, then you need to configure `<tenant name>.xxx.com`.

Regarding certificate upload, check your user role's permission. If you are not the admin of the tenant, you need to have `Tenant management` ADMIN role to upload the certificate.

The last one, regarding the warning `Bridge has been configured, but Cumulocity connection check failed.`, the message indicates `tedge` published messages to your configured tenant via MQTT, but got no reply from it. Many possibilities, internet connection is lost, your configured URL is wrong, your instance doesn't support MQTT, etc.

**Comment by CyntiaPola** [comment]
thank you rina23q could you please also have an idea if the problem could be because my configuration is done on another server?.

**Comment by rina23q** [comment]
The `iottest.xxx.com` is valid URL? If you ping to the domain from your device that you install thin-edge.io, can it reach to the server?

**Comment by CyntiaPola** [comment]
exactly it is not reachable but making the same ping from the same server it works(So It is valid) but not reacheable from the server where thin-edge.io is installed.

**Comment by rina23q** [comment]
Then you need to fix the connection from the device where thin-edge.io installed to your cumulocity instance.
