### ISSUE TITLE
Azure roundtrip test does not work anymore when executed via GitHub Actions

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#669]
**Describe the bug**

The Azure roundtrip test does not work anymore when executed via GitHub Actions.
Works fine, when executed manually.
The Action secrets seem to be correct.

**To Reproduce**

Set Environment  Variables: AZUREENDPOINT, AZUREEVENTHUB, SASKEYIOTHUB, IOTHUBNAME, C8YDEVICE
Run script:

    ci/ci_smoke_test_az.sh

Run Workflow:
https://github.com/thin-edge/thin-edge.io/actions/workflows/integration-test-workflow.yml

**Expected behavior**

All sent messages are received from the built in Azure Endpoint

**Screenshots**

Does not work:
![Screenshot at 2021-12-07 10-55-15](https://user-images.githubusercontent.com/75477722/145022193-b5652366-ca8f-406b-8e53-f09d4e9ff63b.png)

https://github.com/thin-edge/thin-edge.io/runs/4441357390?check_suite_focus=true

Worked:
![Screenshot at 2021-12-07 12-36-05](https://user-images.githubusercontent.com/75477722/145022652-effe16f6-08a9-4d89-a101-712b97970df4.png)

https://github.com/thin-edge/thin-edge.io/runs/4324681457?check_suite_focus=true

**Environment (please complete the following information):**
 - OS : Debian Bullseye / Buster
 - Hardware: Rpi 3B/+ (local)
 - thin-edge.io version [e.g. 0.4.2]

**Additional context**

Stopped to work with unrelated commit:
https://github.com/thin-edge/thin-edge.io/commit/400ecc7ec9cb90d4422eed03bf5eb32a6c6e8a6c
Assumed to be not related to thin-edge code.

**Comment by abelikt** [comment]
Resolved by switching the IoT hub to a new official one.
Root cause of issue still un-kown but closing this issue for now.

**Comment by rina23q** [comment]
Now we don't use Azure roundtrip test in our pipeline. We can close it.
