### ISSUE TITLE
Installing/Removing apama project and mon files together fails

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#706]
**Describe the bug**
When an apama software update (install/remove) request contains installing the mon files and project files in the same request, then the apama plugin fails to complete the operation successfully.

**To Reproduce**
From the c8y software management UI select the "project and mon files" to be installed/removed.
Click on "apply"
Then the operation will fail.

**Expected behavior**
The apama plugin successfully installs the project and mon files.

**Screenshots**
```
[tedge/commands/req/software/update] {"id":"bhkSB6l2w7jiqEjEIJ32i","updateList":[{"type":"apama","modules":[{"name":"tedge-demo-test::project","action":"remove"},{"name":"TedgeDemoMonitor::mon","action":"remove"},{"name":"TedgeTestMonitor::mon","action":"remove"}]}]}
[tedge/commands/res/software/update] {"id":"bhkSB6l2w7jiqEjEIJ32i","status":"executing"}
[c8y/s/us] 501,c8y_SoftwareUpdate
```
```
[tedge/commands/res/software/update] {"id":"bhkSB6l2w7jiqEjEIJ32i","status":"failed","reason":"1 error, see device log file /var/log/tedge/agent/software-update-2021-12-10T11:25:45Z.log","currentSoftwareList":[{"type":"apama","modules":[]}],"failures":[{"type":"apama","modules":[{"name":"TedgeDemoMonitor::mon","action":"remove","reason":"Failed to connect to engine: Failed to connect to localhost:15903: Connection refused\nERROR: Execution of `/opt/softwareag/Apama/bin/apama_env` failed with exit status exit status: 2\n"},{"name":"TedgeTestMonitor::mon","action":"remove","reason":"Failed to connect to engine: Failed to connect to localhost:15903: Connection refused\nERROR: Execution of `/opt/softwareag/Apama/bin/apama_env` failed with exit status exit status: 2\n"}]}]}
[c8y/s/us] 502,c8y_SoftwareUpdate,"1 error, see device log file /var/log/tedge/agent/software-update-2021-12-10T11:25:45Z.log"
```

**Environment (please complete the following information):**
 - OS : ubuntu
 - Hardware :x86
 - System-Architecture: Linux thinedge 5.11.0-41-generic #45-Ubuntu SMP Fri Nov 5 11:37:01 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - thin-edge.io version 0.4.3

**Additional context**
Maybe the order in which the project and the mon files are present in the request is the issue.

**Comment by makr11st** [comment]
Is this still an issue?

**Comment by rina23q** [comment]
@reubenmiller 
Shall we close this issue as `tedge_apama_plugin` is now supported by Apama Team? Regarding https://github.com/thin-edge/thin-edge.io/issues/1584

**Comment by reubenmiller** [comment]
Closing stale issue. Installing/removing packages can either be done using a single operation, or using debian package dependencies.
