### ISSUE TITLE
Dead links in doc

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#725]
There are some dead links in our doc after the changes of our resources hierarchy. 

- bottom of https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/tutorials/write-my-software-management-plugin.md

We should find all dead links.
We may use dead link checker.

**Comment by didier-wenzek** [comment]
There is link checker for mdbook. Unfortunately [commented out in our config](https://github.com/thin-edge/thin-edge.io/blob/main/docs/book.toml)
