### ISSUE TITLE
Mqtt problem while connecting to cumulocity

### ISSUE THREAD

**Issue by CyntiaPola** [thin-edge/thin-edge.io#727]
while trying to connect, I have a problem with cumulocity .

I succedde already to upload the certificate(That means the url is correct)

When I enter the command "tedge connect c8y"
I have this this:
 ..............
Local MQTT publish has timed out.
... No response.
Warning: Bridge has been configured, but Cumulocity connection check failed.

what I have:

OS [Linux ubuntu. v20.04]/ tried with rapsberry too
thin-edge.io version 0.5.0

**Comment by PradeepKiruvale** [comment]
@CyntiaPola Could you please check if the mosquito broker running on your system?

**Comment by CyntiaPola** [comment]
Thank You @PradeepKiruvale 
It works. I think the problem is the port.I have to add an xternal port(8883) but still not succeding.
