### ISSUE TITLE
Make device type configurable

### ISSUE THREAD

**Issue by itsyitsy** [thin-edge/thin-edge.io#733]
Currently the device type is hard set to thin-edge.io. 

AC:
- Make the device type a tedge configuration
- Leave thin-edge.io as the default
- device.type should be the key for the config 
- add url field to c8y agent fragment with `"https://thin-edge.io"` default value

**Comment by initard** [comment]
https://github.com/thin-edge/thin-edge.io/issues/686#issuecomment-1020504217
