### ISSUE TITLE
Security Checkup (Software Management incl. Plugin Framework)

### ISSUE THREAD

**Issue by itsyitsy** [thin-edge/thin-edge.io#743]
Entrance point: [CIT-361 Questionare](https://vmsecprg01.eur.ad.sag:9036/?iTrac=CIT-361)

**Comment by TheNeikos** [comment]
Heya! You've linked a seemingly internal ticket, can you please update this issue with the information therein or otherwise make it public as right now one cannot access the link. 

Thank you!
