### ISSUE TITLE
Security Checkup (Thin Edge Certificate Handling/ Self signed cert)

### ISSUE THREAD

**Issue by itsyitsy** [thin-edge/thin-edge.io#745]
Entrance point: [CIT-19 Questionare](https://vmsecprg01.eur.ad.sag:9036/?iTrac=CIT-19)

**Comment by TheNeikos** [comment]
Heya! You've linked a seemingly internal ticket, can you please update this issue with the information therein or otherwise make it public as right now one cannot access the link. 

Thank you!
