### ISSUE TITLE
System-test is failing: sm_mapper_fail_and_reconnect

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#752]
**Describe the bug**

Test case SoftwareManagement.sm_mapper_fail_and_reconnect
is failing everyhwhere in CI but not locally and not when manually run. We should investigate.

**To Reproduce**

    pysys.py run -v DEBUG SoftwareManagement.sm_mapper_fail_and_reconnect -Xfakeplugin=fakeplugin -XmyPlatform='smcontainer'

**Expected behavior**

Test passes 

**Screenshots**

![image](https://user-images.githubusercontent.com/75477722/148948806-ed8ed53d-513b-44a9-af08-9deaf8f4e38c.png)

**Environment (please complete the following information):**
All our Pis in the Pipeline

**Comment by abelikt** [comment]
I will skip execution in CI until we have a solution

**Comment by abelikt** [comment]
There are also some misleading comments

**Comment by rina23q** [comment]
We are going to move to a new system test framework. The test will be ported to the new framework and tested. With the current test, it is difficult to investigate what is the root case. Therefore, I would close the issue.
