### ISSUE TITLE
Running thin-edge on an Alpine Linux Docker/Podman 

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#758]
**Is your feature request related to a problem? Please describe.**

This is a first step toward:
* #505
* #504

Thin-edge is [no more dependent on systemd](https://github.com/thin-edge/thin-edge.io/issues/639) and provides a configuration to use OpenRc on `tegde connect`. However, running thin-edge on Alpine is still not direct.

We are missing:
* Non-debian install scripts
* OpenRC init scripts for the mapper and agent services.
* Bare minimum information - notably how to configure `tedge` to use OpenRc on `connect`.

**Describe the solution you'd like**

The point is not to have Alpine Packages nor a full fledged Docker/Podman solution, but to give all the details required to implement such support. I expect:

* OpenRC configuration for `tedge connect`
* OpenRC init files for `tedge-mapper-c8y`, `tedge-mapper-az`, `tedge-mapper-collectd` and `tedge-agent`.
* An install script that creates all the necessary users, groups, directories and files - copying the tedge binaries from a cargo `target` directory.
* Running `git clone`, `cargo build`, `sudo install` on an Alpine box should be enough to install thin-edge on a dev box.

**Describe alternatives you've considered**
* A Docker file that create an Alpine Linux image for thin-edge given a user-specific `tedge.toml` configuration file.

**Additional context**
- None

**Comment by mbay-SAG** [comment]
We wanted to share our learnings from trying installing thin-edge within an Alpine Docker container. Alpine uses muslc instead of glibc as C-Library. Thus we managed to install it only on an amd64 architecture with alpine as an base image, not with arm64, since glibc has no arm64 package.

**Comment by makr11st** [comment]
> We wanted to share our learnings from trying installing thin-edge within an Alpine Docker container. Alpine uses muslc instead of glibc as C-Library. Thus we managed to install it only on an amd64 architecture with alpine as an base image, not with arm64, since glibc has no arm64 package.

Hi @mbay-SAG,

Rust [supports](https://doc.rust-lang.org/rustc/platform-support.html#tier-2-with-host-tools) `arm64` (`aarch64`) compilation with `musl` instead glibc.
I believe we also have some [builds](https://github.com/thin-edge/thin-edge.io/blob/main/.github/workflows/build-workflow.yml#L113) available through the GH Actions, even though we may not package them, please feel free to reach out on discord if you need assistance on how to use those.

**Comment by rina23q** [comment]
The outcome is available on the PR in the example repository. https://github.com/thin-edge/thin-edge.io_examples/pull/23
