### ISSUE TITLE
As a Device Owner I want to execute thin-edge upgrade from Cloud

### ISSUE THREAD

**Issue by cstoidner** [thin-edge/thin-edge.io#759]
To allow a Device Owner to execute thin-edge updates from Cloud, thin-edge Software Management shall provide a module type "tedge", that specifically handles thin-edge updates (self-update).

TODO: Add ref to spec.

Therefore Software Management Plugin „apt“ and Software Management Agent need to be extended/modified as follows:

Changes to be applied to Software Management Plugin „apt“
---------------------------------------------------------

1) Plugin has to manage both module types „apt“ and „tedge“:
    - Same executable shall be used for both module types, so a softlink must be located in „/etc/tedge/sm-plugins/„ named „tedge“, that points to the plugin’s executable „apt“.

2) For specific handling of module type "tedge" (see topics below) the plugin executable must detect whether it was called as „apt“ or with softlink „tedge“.
    - Example:
```
$ cat src/main.rs 
fn main() {
   println!("  {:?}", std::env::current_exe());
}

$ ln -s target/debug/myRustCmd ./just-a-link

$ ls -la target/debug/myRustCmd ./just-a-link
-rwxr-xr-x   target/debug/myRustCmd
lrwxr-xr-x   ./just-a-link -> ./target/debug/myRustCmd

$ ./target/debug/myRustCmd
  Ok("/tmp/myRustCmd/target/debug/myRustCmd")
 
$ ./just-a-link
  Ok("/tmp/myRustCmd/just-a-link")
$ 
```

3) As the plugin serves both module types "tedge" and "apt", the SM Agent will execute the plugin twice with the LIST command; once for each mode type. To distinguish packages listed by APT package manager per module type all packages prefixed with "tedge_" are assumed as module type "tedge".
   - When the plugin is called with LIST command for module type "tedge", packages prefixed with "tedge_" must be reported.
   - When the plugin is called with LIST command for module type "apt", all packages withoutprefix "tedge_" must be reported.

4) For module type „tedge“ the plugin must instruct APT to first download all package that are part of the entire update request:
   - Therefore implementation of plugin command `update-list` calls APT separately for download and for installation.
     - First all packages are downloaded by calling APT with command line option `—-download-only`.
     - When all packages were successfully downloaded packages are installed by calling APT again with option `--no-download`.
     - If one or more downloads fails, the plugin will not install any package, but return with error.

   Important: For module type „apt“ behavior must be kept as it is currently implemented. That means packages must be downloaded by APT as needed as part of the installation.
              Otherwise disc space could explode in case of large update requests.

5) When installation of all packages was processed exit-code must be published as retain message to MQTT topic `tedge/plugins/software/tedge`.

Change to be applied to Software Management Agent
-------------------------------------------------

1) Module type „tedge“ must appear exclusively in update requests:
   The SM Agent must reject any update request that contains module type „tedge“ and other module types.
      If a request appears that contains "tedge" and any other module type the SM Agent must report error to Cloud and shall create the log message „Update failed since request contains module type ‚tedge‘ and others, but module type ‚tedge‘ must be used exclusively.“

2) Handling restart of SM Agent during update:
   - At the place where the SM Agent stores an upcoming software update request in the `persistance_store`, the name of the module types must be added to be also stored.
   - At the place where SM Agent (re)starts and checks the `persistance_store` for any update request, it must not send error to the Cloud when the update request contains module type „tedge“
      NOTE: Restart of SM Agent by module type tedge is valid, and even expected.

3) Transfer of plugin’s exit code to SM Agent:
NOTE: During execution of plugin for module type „tedge“ it might happen that SM Agent will restart, and restarted SM Agent process will be disconnected from plugin process and it's exit code.
   - The SM Agent must subscribe to MQTT topic `tedge/plugins/software/tedge`.
      A received message must be treated as exit code from a prior execution of plugin for module type "tedge".
      For such a received exit-code an update result message must be sent to the Mapper.
   - It might happen that the SM Agent does not restart and keeps connected to plugin for module type "tedge" (e.g. when it is not part of the update request, or the update fails). Also then the exit code that is reported by the plugin via MQTT must be used, instead of the exit code reported from plugin's process exit.
   - After sending update result message to the Mapper, the SM Agent must clear the retain message in MQTT topic `tedge/plugins/software/tedge`.

AC: 
   - SM plugin "apt" behaves as above.
   - SM Agent behaves as above.

**Comment by didier-wenzek** [comment]
The agent is given a lot of responsibilities to manage this plugin with care (exclusivity, detach process, status on restart).
I wonder if we can move these responsibilities to the plugin.
If not, I think that it would be simpler  to acknowledge that only the agent can do that and not use a plugin here.

**Comment by cstoidner** [comment]
> 

I agree. I changed some details to make clear Agent should not contain details for that self-update plugin.

**Comment by TheNeikos** [comment]
Do I understand correctly that the complexity comes from `apt` (or any other package manager) potentially restarting the tedge services on update?

If so, why is it configured to be this way? In the case of systemd (and I am sure others) there is no default to 'update on change' for files (afaik), so it must come from the package manager itself. 

If the above is true, then I think this issue is potentially going at it from the wrong direction and the operators should instead split updating into two seperate steps (which they are):

1. Update on disk files (The normal update process)
2. Restart tedge

It is clear that any errors in the first step would point to a serious issue, but it should not change the _running_ services, even on a successful update. If this is the current observed mechanism then I think a lot of complexity will be lost by configuring the system daemon correctly: don't just restart system services on update.

**Comment by makr11st** [comment]
@TheNeikos this is great suggestion with the exception the cloud operator may not have access to operation in step 2 (eg afaik c8y doesn't provide such operation), but I suppose it could be handled either by a custom operation or command sent directly to the device.

**Comment by cstoidner** [comment]
>

**Comment by cstoidner** [comment]
> Do I understand correctly that the complexity comes from `apt` (or any other package manager) potentially restarting the tedge services on update?
> 
> If so, why is it configured to be this way? In the case of systemd (and I am sure others) there is no default to 'update on change' for files (afaik), so it must come from the package manager itself.
> 
> If the above is true, then I think this issue is potentially going at it from the wrong direction and the operators should instead split updating into two seperate steps (which they are):
> 
>     1. Update on disk files (The normal update process)
> 
>     2. Restart tedge
> 
> 
> It is clear that any errors in the first step would point to a serious issue, but it should not change the _running_ services, even on a successful update. If this is the current observed mechanism then I think a lot of complexity will be lost by configuring the system daemon correctly: don't just restart system services on update.

Hi @TheNeikos,

thanks for your feedback.

Doing the restart by the SM Agent is see problems:

- We cannot delegate the restart of all services to the SM Agent, since the SM Agent can not know which services need to be restarted. That is since:
    - The agent has no knowledge which services are part of which package.
    - The packages are of a newer thin-edge version as the running SM Agent (sure, we are running an update). So the old SM Agent even more can not know which services are part of those newer thin-edge version packages (Imaging in a new version some services were merged or added).

- Instead, if we delegate just the SM Agent restart to the SM Agent it-self, the not yet restarted SM Agent process (that is from an older version) would talk to a newer Mapper (that was already restarted). Here we would run into some coupling of old Agent and new Mapper, that I really want to avoid.

     Finally I see some advantages for the device owner with the given concept where the package manager handles all restarts:

     * Since also the restart is managed by the plugin and the underlying package manager, the whole thin-edge should be up running after package manager has completed it's work and returned to the plugin.
       At that place the device owner could add some runtime validation check into the plugin to verify whether the functionality of thin-edge is given (e.g. check for cloud connection).
       If some failure is detected the transcational package manager (if the device support those) can step back to the last working state.

**Comment by TheNeikos** [comment]
> We cannot delegate the restart of all services to the SM Agent, since the SM Agent can not know which services need to be restarted.

That is correct, but I also do not see how that is `tedge`s problem in so far as that if one has several services depending on each other, a correct service management system should support restarting it and all other services (systemd at least supports this using a combination of `Part-Of` and `WantedBy` or by using a target).

(I am also not a big fan of dependency management and service management, as it would also mean that one needs to incorporate aspects that are by nature very difficult to handle. Are we ready for something this complex?)

**Comment by cstoidner** [comment]
Status of current implementation work

As of now there are both open topics

1) selfupdater process terminates when `tedge disconnect` is 
**Reasons:** Agent process stops, and:
   - a) selfupdater and agent are in the same process group id (pgid), so agents signal SIGTERM will be propagated to selfupdater process.
   - b) STDIN/STDOUT pipe is still connected to selfupdater process, but on the other end the Agent terminates. The occuring SIGPIPE can lead to process exit.

2) With last implementation state (see https://github.com/makr11st/thin-edge.io/tree/feature/759_self_update_agent) the Agent calls `tedge-selfupdater` with sudo. However `tedge-selfupdater` is not in sudoers of tedge-agent, and sudo can obviously not ask for any password due to missing terminal.
Expectation: The executable `tedge-selfupdater` shall be called by the Agent in the same way as any usual SM plugin (i.E. with or without sudo). The sudoers of tedge-agent might need to adapted accordingly.

**Next steps:**
- @cstoidner to continue on topic (1).
- Topic (2) potentially to be reassigned. 
   @makr11st , do you have enough capacity to continue on that?

**Comment by makr11st** [comment]
3. Self Updater continues update even if killing other processes fails (disconnect fails)
4. self updater to be extracted to a separate crate
