### ISSUE TITLE
As Device Owner I want to be able to install thin-edge also without Debian Package Manager

### ISSUE THREAD

**Issue by cstoidner** [thin-edge/thin-edge.io#760]
Extract installation logic from debian maintainer scripts into one installtion-script and one removal-script per each thin-edge package. Therefor consider topics below:

  - All lines from maintainer scripts that not necessarily need to be located in maintainer scripts shall be moved to those installation/removal-scripts from above.
  - If any rest was kept in some maintainer scripts reason to be stated (for later alignment).
  - Those installation/removal-scripts shall be added to according Debian packages and shall be called as appropriated in maintainer scripts.
  - Finally those installation/removal-scripts shall allow to easily create packages for other Package Managers than Debian.
    Moreover those scripts shall even allow to provide the installation as ZIPed file-tree, for installation without any Package Manager at all.
    - Installation procedure: (1) Copy filetree to „/“; (2) Execute installation script.

NOTE: See also ticket (https://github.com/thin-edge/thin-edge.io/issues/761) as second step, to move script-logic into Rust code.

AC: 
  - Installation-scripts and removal-script per thin-edge package do exist and are added to according debian packages and are called in according maintainer scripts.
  - For each lines that was kept in Maintainer scripts a statement in that tickets comment section states the reason.

**Comment by reubenmiller** [comment]
As of version [0.11.0](https://github.com/thin-edge/thin-edge.io/releases/tag/0.11.0), tarballs are now included containing the thin-edge.io components.

The tarballs can be downloaded, and the initialization can be done by just running the `<binar> --init` command.

* [tedge_0.11.0_x86_64-unknown-linux-musl.tar.gz](https://github.com/thin-edge/thin-edge.io/releases/download/0.11.0/tedge_0.11.0_x86_64-unknown-linux-musl.tar.gz)
* [tedge_0.11.0_aarch64-unknown-linux-musl.tar.gz](https://github.com/thin-edge/thin-edge.io/releases/download/0.11.0/tedge_0.11.0_aarch64-unknown-linux-musl.tar.gz)
* [tedge_0.11.0_armv7-unknown-linux-musleabihf.tar.gz](https://github.com/thin-edge/thin-edge.io/releases/download/0.11.0/tedge_0.11.0_armv7-unknown-linux-musleabihf.tar.gz)
