### ISSUE TITLE
Finalise test reporting for system-tests

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#767]
**Is your feature request related to a problem? Please describe.**

Test reporting is not finalised yet. Implementation of reporting brought up some issues that are not completely resolved yet.
This is the follow up story to finalise reporting.

See open PR:
https://github.com/thin-edge/thin-edge.io/pull/665

AC:
 * Add reporting to official system tests (with only the official runners)
 * DONE: Resolve deal-breaker: postprocessing of skipped tests makes them appear to be green
 * Configure handling of workflows that failed completely (e.g. command line switch)(old ones will be put into the report)
 * Add overall report-info: Log where do the reports come from, other meta information etc
 * DONE: Move result contents to github pages
 * Improve build script to make it more understandable
 * Run regularly for the official repo with the runners attached there

**Additional context**

Pull Request: https://github.com/thin-edge/thin-edge.io/pull/665
This is a follow up story to https://github.com/thin-edge/thin-edge.io/issues/623

**Comment by itsyitsy** [comment]
Postponed for after decission with or against Pysys

**Comment by abelikt** [comment]
Marked some AC's as DONE

**Comment by abelikt** [comment]
I regard this as solved after adding the new ci-pipeline
