### ISSUE TITLE
Use MQTT to monitor the availability of the thin-edge daemons

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#769]
This story is related to #826

**Motivation**
Thin-edge features are provided by a set of daemons - the mappers and the agent. To monitor these daemons and react to errors it would be easier to leverage MQTT. Compared to watchdogs based on local process monitoring, using MQTT enables remote monitoring and local reactions.

**Proposal**
Use retain messages and last will messages to track the current status of each thin-edge daemon.

* The monitored daemons are  `tedge-agent`, `tedge-c8y-mappert`, `tedge-az-mapper`, `tedge-collectd-mapper`.
* A topic is attached to each daemon: `tedge/monitor/{daemon}`
* The first message sent by a daemon on start is a retained message `on` published on `tedge/monitor/{daemon}`.
* The last will of a daemon is the retained message `off` to be published on  `tedge/monitor/{daemon}`.
* On `--init` the daemon publishes the `off` message, since ready but not started yet.
* On `--deinit` the daemon clears its retained status message.
* daemons react to requests by watchdog(not sending recurring health-status on its own.)
* The health messages should be produced by the same thread as the actual component

**Alternatives**
* One can add a timestamp on the `on` message. This cannot be done for the `off` message.
* In addition to its status, a daemon could publish the number of requests and errors during the last period of time (say every hour). This would be a non-retain message published on the same topic using thin-edge json.

**Comment by albinsuresh** [comment]
As per the [agreement](https://github.com/thin-edge/thin-edge.io/discussions/933#discussioncomment-2249495) in #933 , health updates by tedge processes will be published in response to an mqtt request that will be sent to `tedge/ping/{daemon}` topic. For example, the `tedge-agent` process should listen on `tedge/ping/agent` topic for any incoming health check requests and respond back with the health status on `tedge/monitor/agent` topic.

The request may have `time` field in it generated at the time of sending. The health status response can be something like this:

```json
{
    "status": "up",
    "time": "<time in ISO-8601 format>",
    .....
    <additional fields and fragments relevant for each daemon>
}
```

**Comment by albinsuresh** [comment]
Reopening as the retained health status messages and last-will messages were not implemented in the previous PR.

**Comment by albinsuresh** [comment]
Making the health status messages "retained" might lead to some misleading health updates when a user subscribes to `tedge/health/#` and receives all the previously retained messages, where some of which could be stale.

For example, if the tedge-agent responds to a health check at time `T` with a retained status message, any subscriber subscribing to `tedge/health/#` later (say `T+5` or `T+10`) will receive that health status "snapshot" taken at time `T`. But, this could be stale information which might mislead the end-user, as there's a possibility that the process may have deadlocked/frozen at `T+2` itself. Sending another health check request is not gonna help either, as the "frozen" client is not going to respond with `{"status": "down"}` as its frozen. So, the old, stale, `{"status": "up"}` will remain with the broker.

Last will messages are not gonna help either, as those will be sent only when the MQTT client disconnects from the broker. The agent could get "frozen" while still being connected  to the broker. So, the last will message won't even be sent.

Adding a `timestamp` field to the health status message could be one solution. But, then the end-user has to send a request first and then wait for a response anyway and validate the timestamp in that response. That's as good as the current non-retained request/response contract. So, using retained messages doesn't make things any anything for the end-user.

@didier-wenzek @cstoidner WDYT?

**Comment by didier-wenzek** [comment]
There are many points here.

* A client that subscribes to `tedge/health/#` will indeed received possibly stalled messages, even for dead daemons, but *only* the healthy daemons will update their status on health-check. Hence, the client can detect which are no more responding.
* Having a timestamp along the status message makes the reactions on heath check more visible.
* A daemon that is stuck will not respond to keep-alive messages and will be disconnect by the MQTT broker and the last will published.

I do think that, having retained status messages with a timestamp combined with last will retained messages, brings a value to who wants to monitor the device daemons. One doesn't have to actively request a status to have one. Sending a health check is then only a way to have fresher status.

**Comment by albinsuresh** [comment]
> * A client that subscribes to `tedge/health/#` will indeed received possibly stalled messages, even for dead daemons, but _only_ the healthy daemons will update their status on health-check. Hence, the client can detect which are no more responding.

This can be solved with last will messages, right? A dead client's last will message will come into effect once it's dead. So, that probably is sufficient to handle this case.

> * Having a timestamp along the status message makes the reactions on heath check more visible.

Definitely. For this, I'm thinking of a contract like this. The one triggering health check can include a `timestamp` in the request message itself. The daemons then will respond back with the same timestamp in their response JSON as well. Keeping them the same will make the correlation easier. If the request doesn't contain a `timestamp` field, then the daemon can autogenerate a timestamp and include it in the response.

> * A daemon that is stuck will not respond to keep-alive messages and will be disconnect by the MQTT broker and the last will published.

When I meant "stuck client", I was referring to a possibility where a daemon is taking too long to process one message. That daemon could still be connected to the broker at the MQTT protocol level. So, the broker might still think that the daemon is connected, and hence won't send the last will message on its behalf. In that state, even if we send an explicit health check request, the daemon won't respond with "updated health status" because it won't process the health check request. The last will message won't come into effect either, because the broker still thinks that the client is connected and it wouldn't know that the client is "logically stuck" in its message processing logic.

This might be a very rare corner case. But, it's still a possibility, right? Or were you suggesting that a client that can't process MQTT further messages will "somehow" get disconnected from the broker as well, triggering its last will message?

> I do think that, having retained status messages with a timestamp combined with last will retained messages, brings a value to who wants to monitor the device daemons. One doesn't have to actively request a status to have one. Sending a health check is then only a way to have fresher status.

I agree.

**Comment by didier-wenzek** [comment]
> When I meant "stuck client", I was referring to a possibility where a daemon is taking too long to process one message. That daemon could still be connected to the broker at the MQTT protocol level.

This is correct. This is why a timestamp helps: "at that time the service was up". Dynamic checks add a bit of freshness but there is still no guarantee: "the latest time we checked the service was up".

> The daemons then will respond back with the same timestamp in their response.

This is unusual. And raises questions. The timestamp can be facked by a client. This seems not compatible with a retained status. What would be the timestamp on start?

**Comment by albinsuresh** [comment]
> This is unusual. And raises questions. The timestamp can be facked by a client. This seems not compatible with a retained status. What would be the timestamp on start?

That's true. In that case we'll have the daemon generate the timestamp at the time of receipt of the health check. The health-checking client can then just check if the timestamp in the response is greater than the one in the request.

**Comment by didier-wenzek** [comment]
From my point of view, two points are missing.

* The first message sent by a daemon on start is a retained `{"status": "up"}` message with a timestamp published on `tedge/health/{daemon}`.
* The last will of a daemon is the retained `{"status": "down"}` message to be published on `tedge/health/{daemon}`.

**Comment by didier-wenzek** [comment]
The last point will be addressed by https://github.com/thin-edge/thin-edge.io/issues/1503
