### ISSUE TITLE
Measurement type is static as "ThinEdgeMeasurement"

### ISSUE THREAD

**Issue by mbay-ODW** [thin-edge/thin-edge.io#770]
**Is your feature request related to a problem? Please describe.**
The Domain Model of Measurements within Cumulocity gives three degrees of freedom for storing measurements:

1. Measurment Fragment
2. Measurement Series
3. Measurement Type

As I do understand all those three columns are indexed within the mongoDB such that it is recommended to model data in a way that all those 3 informations somehow are considered for the measurements to perform fast queries.
Why is the 3. entry of type not used within thinedge properly. However I do understand that it makes sense to have the information of "ThinEdgeMeasurement" as an information on the measurement itself but have the feeling that it should not be the type.
What are your thoughts on that?

**Describe the solution you'd like**
If something such as a type exists within the initial payload on the local MQTT broker the mapper should use that. Static types could be used if nothing such as type is provided in the payload.

**Comment by simeonthefirst** [comment]
Also discussed in  #648

**Comment by PradeepKiruvale** [comment]
Can there be multiple `custom fragments` as part of the measurement message?

**Comment by didier-wenzek** [comment]
As highlighted by https://github.com/thin-edge/thin-edge.io/pull/1911#discussion_r1164216090, this issue needs some clarifications.

- Where can be defined a measurement type?
    - Only at the top level of a measurement message as in `{  "type": "MyMeasurement",  "location": { "latitude": 32.54, "longitude": -117.67,  "altitude": 98.6 }}?
    - Inside a group of measurements as in `{ "location": { "latitude": 32.54, "longitude": -117.67,  "altitude": 98.6, "type": "MyMeasurement"  }}`?
    - Are the two previous messages equivalent? i.e. translated to the same Cumulocity Json Message?
- Where custom fragments can be added?
  - At any level? as in `{ "location": { "latitude": 32.54, "longitude": -117.67,  "altitude": 98.6, "quality": "Uncertain"  }}`
- How deep can be a custom fragment?
- How custom fragments are translated into Cumulocity Json?
   -  `{ "temperature": 23.0,  "pressure": 220.0 }` is translated into `{"type": "ThinEdgeMeasurement", "time": "2021-04-08T00:00:00+05:00", "temperature": {"temperature": {"value": 23.0}}, "pressure": {"pressure": {"value": 220.0}}}`
   - How should  `{ "temperature": 23.0,  "pressure": 220.0 , "quality": "Uncertain" }` be translated?

**Comment by reubenmiller** [comment]
The measurement type is only applicable for Cumulocity measurements, and it can only be defined on the root level, as per the following example:

```jsonc
{
    "type": "MyMeasurement",    // type should not be known in the tedge measurement format, it is just a non-value fragment
    "location": {
        "latitude": 32.54,
        "longitude": -117.67,
        "altitude": 98.6
    }
}
```

**Note:** The `type` should not be known in the tedge measurement format, it is just a non-value and should be passed on by default to the appropriate cloud mapper.

The above tedge measurement would then be mapped to a Cumulocity measurement as follows:

```jsonc
{
    "type": "MyMeasurement",    // type allows user to further group measurements
    "location": {        // location is the `valueFragmentType` in c8y terminology
        "latitude": {    // latitude is the `valueFragmentSeries` in c8y terminology
            "value": 32.54,
            "unit": ""
        },
        "longitude": {    // longitude is the `valueFragmentSeries` in c8y terminology
            "value": -117.67,
            "unit": ""
        },
        "altitude": {
            "value": 98.6,
            "unit": ""
        }
    }
}
```

The `type` fragment is normally used by Cumulocity users to further classify/group types of measurements. The [Cumulocity REST API](https://cumulocity.com/api/core/10.16.0/#operation/postMeasurementCollectionResource) allows users to query for measurements based on the `type`, `valueFragmentType` and `valueFragmentSeries`. This enables the users to be more flexible on how data is recalled and permission rules are applied.

**Comment by reubenmiller** [comment]
If it becomes difficult for tedge to detect which is is the measurement values (e.g. numeric values) and which is the meta info (such as `type`), then it might be more useful to use a reserved fragment/property name which stores all meta info, for example:

```jsonc
{
    "meta" : {  // 'meta' would be a reserved fragment/property name which holds all meta data (e.g. non-value data)
        "type": "MyMeasurement",
        "otherCustomData": {
            "something": {
                "foo": "bar"
            }
        }
    },
    "location": {
        "latitude": 32.54,
        "longitude": -117.67,
        "altitude": 98.6
    }
}
```

**Comment by gligorisaev** [comment]
checked
