### ISSUE TITLE
Tegde panics on connect

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#773]
**Describe the bug**

Trying to connect using the version `0.5.2` (build from source), I got a panic.

```
$ sudo tedge connect c8y
Checking if system V is available.

Checking if configuration for requested bridge already exists.

Validating the bridge certificates.

Creating the device in Cumulocity cloud.

thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', crates/core/tedge/src/cli/connect/c8y_direct_connection.rs:128:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

**To Reproduce**

I updated a working thin-edge device actually connected to Cumulocity.
After a disconnect / reconnect with the new version I got this panic.

**Expected behavior**
An error or a working connection.

**Screenshots**

**Environment (please complete the following information):**

```
$ tedge --version
tedge 0.5.2
$ sudo tedge config list
device.id=demo-device-008
device.key.path=/etc/tedge/device-certs/demo-device-008.key
device.cert.path=/etc/tedge/device-certs/demo-device-008.pem
c8y.url=didier.latest.stage.c8y.io
c8y.root.cert.path=/etc/ssl/certs
az.root.cert.path=/etc/ssl/certs
az.mapper.timestamp=true
mqtt.port=1883
tmp.path=/tmp
```

**Additional context**

The error is due to the private key. What are the constraints on these keys?

```
$ ls -l /etc/tedge/device-certs/demo-device-008.key
-r-------- 1 mosquitto mosquitto 1675 Dec 17 16:04 /etc/tedge/device-certs/demo-device-008.key
$ sudo cat /etc/tedge/device-certs/demo-device-008.key/device-certs/demo-device-008.key
-----BEGIN RSA PRIVATE KEY-----
...
-----END RSA PRIVATE KEY-----
```

**Comment by abelikt** [comment]
When I run "pysys.py run valid_device_id" I'm getting the error below.
Could this be related?

09:30:19 INFO  Contents of c8y_connect.err: 
09:30:19 INFO    ERROR: Io(Custom { kind: InvalidData, error: AlertReceived(CertificateUnknown) })

**Comment by PradeepKiruvale** [comment]
I think both are different. One which you have mentioned is related to the certificate sync after upload. The one Didier mentioned is related to the `rsa` certificate parse. By default, thin-edge uses the self-signed certificate, which is different.

**Comment by abelikt** [comment]
Oh yes, indeed a different issue. I solved my one again by waiting 1s until Cumulocity processed the certificate :)
