### ISSUE TITLE
Docker pull rate limit reached in system-tests/ Create release workflow

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#788]
**Describe the bug**

During out automated system-tests we are getting issues when we install and remove docker images too often.
Here is the message from the daemon:

"docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.!"

**To Reproduce**
Run system tests

**Expected behavior**
We either should test less or upgrade our rate limit.

**Screenshots**
![image](https://user-images.githubusercontent.com/75477722/150932501-6d7b1e1f-bb37-4db9-9811-a7798f2ccb02.png)

AC:

- Create seperate workflow that is only run pre release 
- Add docker plugin test to this new created workflow

**Comment by rina23q** [comment]
We stopped using the pysys system tests. This issue is no longer applicable, therefore, I would close it.
