### ISSUE TITLE
Pysys test refactoring

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#804]
**Is your feature request related to a problem? Please describe.**

This story is work in progress!
Each block of points is a topic that can be split out of this story to have smaller stories.

**Tedge Environment**

- Improve integration of class TedgeEnvironment and add more helper functions and attributes
    - remove attributes like self.sudo in each test as it is in the base class

**Code Format**

- DONE Code format with black

**Cumulocity Class**

- Improve integration of class Cumulocity, add tests for Class Cumuloicity, add type hints
    - Extend Cumulocity class with functionality from c8y python api

**Multiple pysys projects**

- Experiment with splitting pysys test projects
- Care about common code of those projects
- Update environments, in separate projects. E.g. one that connects to c8y runs all tests and then disconnects
- Alternative: find another way of grouping test cases

**Pysys Issues**

- Pysys does not print the test names if they pass (developer request)
- DONE Skipped testcases look green in the matrix report (See also here https://github.com/pysys-test/pysys-test/issues/56)

**Refactoring**

- update variable names : https://github.com/thin-edge/thin-edge.io/pull/784
-

**Comment by rina23q** [comment]
We decided to stop using pysys as system test framework, therefore, I would close this issue.
