### ISSUE TITLE
Assess thin-edge framework for system testing

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#808]
Regarding our framework for system testing, I think it's time to pause and assess:
* What did we get right? What needs to be fixed?
* What are the pros and cons of PySys ?
* What are the alternatives?
* What can we improve in our tooling and approach to testing?

I created [a discussion to collect your opinions and proposals](https://github.com/thin-edge/thin-edge.io/discussions/807).

@abelikt should not be the sole actor of this discussion. I expect feedback from all the developers.

**Comment by abelikt** [comment]
Hi all, I added a list of requirements for a system- and integration-test framework into a separate discussion: https://github.com/thin-edge/thin-edge.io/discussions/849
I hope it helps to evaluate our options.

**Comment by gligorisaev** [comment]
**1. What did we get right? What needs to be fixed?**
 - Collection existing on Github and sorted by subject in separate Folders
 - There are also another possitive things, but I would not go into details
**2. What are the pros and cons of PySys?**
 - I cannot talk about the pros having in mind I don't know the Framework
 - Cons: 
    - Tests are running on the DUT, adding additional load to the DUT
    - The support community is not big if support needed
    - Unfortunatelly I don't know the framework and can not contribute before learning it
**3. What are the alternatives?**
 - Robot Framework, which is able to cover all instances in one test (SSH, Browser, MQTT and others)
**4. What can we improve in our tooling and approach to testing?**
 - Allready started the addoption of different processes which should lead to improving, visibility, transparency and efficiency in achieving better code coverege
