### ISSUE TITLE
Replace stringy comparison with equality checks

### ISSUE THREAD

**Issue by TheNeikos** [thin-edge/thin-edge.io#822]
Once the linked issue is closed we can either fix the string checks (if it got added) or simply close this issue (if they reject the change).

I have mentioned this issue in their repository: https://github.com/bytebeamio/rumqtt/issues/340. This could be fixed once that is closed. I'll make a new issue for it.

_Originally posted by @TheNeikos in https://github.com/thin-edge/thin-edge.io/pull/819#discussion_r799345604_

**Comment by didier-wenzek** [comment]
This can be done. But `Eq` cannot be derived for `MqttError`. Hence, a bit more work than expected.

```
error[E0369]: binary operation `==` cannot be applied to type `ConnectionError`
  --> crates/common/mqtt_channel/src/errors.rs:17:29
   |
2  | #[derive(thiserror::Error, Debug, Eq, PartialEq)]
   |                                       --------- in this derive macro expansion
...
17 |     ConnectionError(#[from] rumqttc::ConnectionError),
   |                             ^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

```
