### ISSUE TITLE
Make "listener localhost" entry in tedge-mosquito.conf configurable via tedge config set

### ISSUE THREAD

**Issue by mbay-SAG** [thin-edge/thin-edge.io#823]
**Describe the bug**
As described in https://github.com/thin-edge/thin-edge.io/issues/758 thin-edge needs to be able to run in an dockerized environment. However mosquitto does not run since version 2.0 with the entry listener localhost as it is written by the tedge connect into the tedge-mosquitto.conf in a dockerized environment.
**To Reproduce**
Steps to reproduce the behavior. The more detail you add here, the better we can reproduce the bug.

Create an mosquitto container with the following config:

listener 1883 localhost
allow_anonymous true

Running the container with docker run {name} 

Would result in:

1643983742: mosquitto version 2.0.13 starting
1643983742: Config loaded from /mosquitto/config/mosquitto.conf.
1643983742: Opening ipv4 listen socket on port 1883.
1643983742: Error: Address not available

**Expected behavior**
We would like to be able to use something like:

tedge config set  mqtt.onlyLocalhost false

**Environment (please complete the following information):**
docker

**Additional context**

**Comment by rina23q** [comment]
Hi @mbay-SAG, Pradeep has merged the change by #929. Could you check if we implemented as you wanted here?

The documentation is here https://github.com/thin-edge/thin-edge.io/blob/main/docs/src/howto-guides/008_config_local_mqtt_bind_address_and_port.md.
