### ISSUE TITLE
Fix the build and clippy warnings

### ISSUE THREAD

**Issue by didier-wenzek** [thin-edge/thin-edge.io#825]
We have too many warnings, during build (unused fields) and with clippy.

```
cargo clippy 2>&1 | grep generated
warning: `json-writer` (lib) generated 1 warning
warning: `clock` (lib) generated 1 warning
warning: `tedge_apama_plugin` (bin "tedge_apama_plugin") generated 2 warnings
warning: `tedge_users` (lib) generated 1 warning
warning: `tedge_apt_plugin` (bin "tedge_apt_plugin") generated 2 warnings
warning: `thin_edge_json` (lib) generated 3 warnings
warning: `tedge_config` (lib) generated 2 warnings
warning: `mqtt_channel` (lib) generated 1 warning
warning: `download` (lib) generated 1 warning
warning: `tedge` (bin "tedge") generated 15 warnings
warning: `mqtt_tests` (lib) generated 7 warnings
warning: `agent_interface` (lib) generated 3 warnings
warning: `plugin_sm` (lib) generated 9 warnings
warning: `c8y_smartrest` (lib) generated 5 warnings
warning: `tedge_mapper` (bin "tedge_mapper") generated 22 warnings
warning: `tedge_agent` (bin "tedge_agent") generated 7 warnings
```

**Comment by matthiasbeyer** [comment]
Hi! For the following crates, I have already removed all warnings generated from clippy (not from normal `cargo c`, _only_ clippy warnings):

- [x] json-writer
- [x] clock
- [x] tedge_apama_plugin
- [x] tedge_users
- [x] tedge_apt_plugin
- [x] thin_edge_json
- [x] tedge_config
- [x] mqtt_channel
- [ ] download (no clippy warnings)
- [x] tedge (here also some non-clippy warnings)
- [ ] mqtt_tests
- [ ] agent_interface
- [ ] plugin_sm
- [ ] c8y_smartrest
- [ ] tedge_mapper
- [ ] tedge_agent

And I'm currently **down to 55 warnings from 118** (`cargo clippy 2>&1 | grep generated | rev | awk '{s+=$2} END {print s}'`).

As soon as the CLA issue is resolved, I will submit my patches, of course!

**Comment by makr11st** [comment]
Thanks @matthiasbeyer , usually I issue a maintenance PR after a minor release to get the warnings cleared, unfortunately I didn't have a chance to do it this time around.

@thin-edge/maintainers Please remember to run at least the `clippy` before you submit a commit and make sure you address the warnings. 

Now with GH warnings check enabled for Rust it should be easier even for reviewers during the process to highlight the warnings.
Bear in mind that the `clippy` is run as a part of the workflow and it was put there for convenience, but looks like no one looks there any more, maybe it is time to lower the threshold to warnings?

**Comment by matthiasbeyer** [comment]
> maybe it is time to lower the threshold to warnings?

You mean make warnings hard errors? I would approve, after my fixes are landed of course :laughing:

**Comment by TheNeikos** [comment]
A possibility is to have something akin to

```
#![cfg_attr(test, deny(warnings))]
```

which would only enable denying warnings on test builds

**Comment by matthiasbeyer** [comment]
So I would like to start to submit my patches for this issue now.

Thing is: It is a lot. Right now I have 65 patches on 16 branches (because 16 crates). Thus, my proposal would be:

* I submit one PR for clippy cleanup for each crate
* I do not submit all PRs in one go, to not kill peoples inboxes :laughing: I guess two at a time would be a good idea.
* I always request review from one person, but every time someone else. That reduces the "reviewer burden" for everyone :laughing: .

Alternatively, I could submit one big PR with 65 patches for the whole tree... that would increase the "reviewer burden" dramatically, though.

**Comment by didier-wenzek** [comment]
One PR per crate seems good. 16 open PRs is manageable.

I volunteer to review: mqtt_chanel, mqtt_tests and tedge_agent.

**Comment by didier-wenzek** [comment]
We still have a bunch of warnings

```
cargo clippy 2>&1 | grep generated
warning: `flockfile` (lib) generated 1 warning
warning: `tedge_users` (lib) generated 1 warning
warning: `tedge_config` (lib) generated 2 warnings
warning: `tedge` (bin "tedge") generated 1 warning
warning: `mqtt_channel` (lib) generated 2 warnings
warning: `tedge_agent` (bin "tedge_agent") generated 7 warnings
warning: `c8y_smartrest` (lib) generated 4 warnings
warning: `c8y_api` (lib) generated 1 warning
warning: `c8y_log_plugin` (bin "c8y_log_plugin") generated 12 warnings
warning: `tedge_mapper` (bin "tedge_mapper") generated 7 warnings
```

**Comment by didier-wenzek** [comment]
Ok fixed. There are [no more clippy warnings](https://github.com/thin-edge/thin-edge.io/runs/7006244895?check_suite_focus=true) and this enforced on each PR with the `-D warnings` is enable for `clippy` and `rustc`.
