### ISSUE TITLE
tedge_agent --init not working

### ISSUE THREAD

**Issue by mbay-SAG** [thin-edge/thin-edge.io#827]
**Describe the bug**
Since the latest commit in the post installation config for the tedge_agent there is an error that says the --init parameter is not valid for tedge_agent
![image](https://user-images.githubusercontent.com/58465677/152649431-bd3a2160-8d81-4309-948e-e53c20a9c250.png)
**To Reproduce**
Install manually via debian packages and try to start the post installation scripts  in:

https://github.com/thin-edge/thin-edge.io/tree/main/configuration/debian/tedge_agent

**Expected behavior**
Worked before the commit of  #04.02.2022.

**Comment by PradeepKiruvale** [comment]
@mbay-SAG Looks like there is a version miss-match. How did you install the mapper/agent?.

**Comment by mbay-SAG** [comment]
Installation via the debian packages:

tedge_mapper_0.5.2_arm64.deb
tedge_apt_plugin_0.5.2_arm64.deb
tedge_apama_plugin_0.5.2_arm64.deb
tedge_agent_0.5.2_arm64.deb

**Comment by PradeepKiruvale** [comment]
You built them from source code or did you download these packages?

**Comment by PradeepKiruvale** [comment]
I also downloaded the packages from https://github.com/thin-edge/thin-edge.io/releases 0.5.2 and installed them and tested them, I dint find any issue.  I tested them on my raspberry pi.

**Comment by mbay-SAG** [comment]
I used the moslc version from the GitHub due to the installation in an alpine docker container.

**Comment by PradeepKiruvale** [comment]
You mean musl version?. And used dpkg on alpine to install?

**Comment by PradeepKiruvale** [comment]
After the discussion with @mbay-SAG found that there was a difference between the tedge_mapper and tedge_agent binary version and the post install script. So, the issue showed up here. Now it is resolved.
