### ISSUE TITLE
Add GitHub self hosted runner in Azure for the official repository

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#829]
**Is your feature request related to a problem? Please describe.**

We need a self hosted runner to run thin-edge analytics and measurement post processing.
A GitHub hosted runner will not work out as we need network access.
The current approach to use Azure is blocked as we cannot create one with the company account that uses a public IP.

This is already a long running background task and this story should make sure we won't forget.

**Describe the solution you'd like**

Run analytics with a company account.
Find out how we e.g. need to ssh tunnel into the infrastructure and who is allowed to do it.

**Describe alternatives you've considered**

Workaround: Run them with a personal account

**Comment by rina23q** [comment]
I don't think it's applicable now. I would like to close the issue.

**Comment by rina23q** [comment]
I don't think it's applicable now. I would like to close the issue.
