### ISSUE TITLE
Sporadic failure of get_jwt_token_full_run

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#833]
**Describe the bug**

The `get_jwt_token_full_run` integration test in sm_c8y_mapper is failing sporadically on PR builds. Here is one such instance: https://github.com/thin-edge/thin-edge.io/runs/5104156856?check_suite_focus=true

**To Reproduce**
It's an intermittent failure. So, no clear reproducible steps.

**Comment by rina23q** [comment]
I also encountered this. It blocks merging for obvious unrelated PRs. Annoying :/
