### ISSUE TITLE
Clean up cargo build warnings

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#840]
**Describe the bug**
Clean up the `cargo build` warnings. This could be across different platforms (x86, aarch64, musl and arch32)

**To Reproduce**
cargo build
**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [e.g. 0.1.0]

**Additional context**

**Comment by matthiasbeyer** [comment]
I guess this is partly related to my work for #825. I'll mark this WIP therefore.

**Comment by rina23q** [comment]
@matthiasbeyer I saw you are working on cargo clippy. Are you also going to work on fixing compilation warnings, right?

**Comment by rina23q** [comment]
To me, I don't think we should keep both #825 and this issue. Looks duplicated. Since @matthiasbeyer has already worked on #825, can I close this issue?

**Comment by matthiasbeyer** [comment]
Yes, I'm working on all these things, with the goal to have zero warnings in both `cargo check` and `cargo clippy`, so that we can switch on `#[deny(warnings)]` at some point and make all warnings into errors.

I think this is a duplicate, I will close it.
