### ISSUE TITLE
Make log and run (lock, restart) path configurable

### ISSUE THREAD

**Issue by itsyitsy** [thin-edge/thin-edge.io#858]
AC:
* The log path of thin-edge should be configurable.
* The run path of thin-edge should be configurable.
* The current hardcoded paths should be the default.

**Comment by initard** [comment]
- agent restart path is defined [here](https://github.com/thin-edge/thin-edge.io/blob/69242dee1f85ffdf44c5a9bfef6b073eb435bc7d/crates/core/tedge_agent/src/restart_operation_handler.rs#L7)
- lock file is defined [here](https://github.com/thin-edge/thin-edge.io/blob/69242dee1f85ffdf44c5a9bfef6b073eb435bc7d/crates/common/flockfile/src/unix.rs#L44)
- and i think log path is defined [here](https://github.com/thin-edge/thin-edge.io/blob/69242dee1f85ffdf44c5a9bfef6b073eb435bc7d/crates/core/tedge_agent/src/agent.rs#L79)
