### ISSUE TITLE
configuration management

### ISSUE THREAD

**Issue by itsyitsy** [thin-edge/thin-edge.io#866]
The target of this story is to have a look at the available prototypes around configuration management. 
Find out how well these prototypes fulfill config management expectations. Find what gaps they have.

Can we reuse one of their strategies/setup for thin-edge.io?

AC:
- the configuration management should be based on file-based configuration management (ignore "text-based" configuration) to get an idea of what this can look like in the cloud refer to [link](https://cumulocity.com/guides/users-guide/device-management/#to-retrieve-and-apply-a-configuration-snapshot-to-a-device-which-supports-multiple-configuration-types)
- configuration management has a config "configuration-management.toml" that contains configuration type, and path to the configuration-files that can be managed via cloud ( place of file tbd, probably cloud specific)
- in the initial setup the configuration-management.toml is created and itself reported to the cloud as a configurable file (smartrest [119](https://cumulocity.com/guides/reference/smartrest-two/#set-supported-configurations-119))
- if the configuration-management.toml is updated from the cloud side smartrest 119 has to be triggered again
- if the configuration-management.toml is updated locally its acceptable to tell the user to restart tedge-agent
- if the configuration management receives an operation (smartrest [120](https://cumulocity.com/guides/reference/smartrest-two/#set-currently-installed-configuration-120)) does the following steps:
    - lookup path for config type in configuration-management.toml
    - if config type found download config file from url in operation and place at path from config
- the best place for configuration management is probably tedge-agent

**Comment by cstoidner** [comment]
See prototype: https://teams.microsoft.com/l/message/19:126fc8acecc14ea59613d65751b99476@thread.skype/1636630371352?tenantId=d9662eb9-ad98-4e74-a8a2-04ed5d544db6&groupId=f248dcbb-c15f-44f4-a10a-77ce46857255&parentMessageId=1636630371352&teamName=thin-edge.io&channelName=General&createdTime=1636630371352

**Comment by didier-wenzek** [comment]
The key points to keep from the prototype are:

* Use the file-based configuration management without any name re-mapping: each file is presented by its full path on the device.
* Use a "configuration-management.toml" file to list the files that can be configured from the cloud. This file is itself implied: the user don't have to add (and cannot remove) "configuration-management.toml" as one of the entries listed by "configuration-management.toml".
* On configuration update, there is no attempt to relaunch the daemons using the updated configuration. However an MQTT message (to be defined) is published on the MQTT bus, so a the daemons can react if required.

**Comment by rina23q** [comment]
The following implementation task will be addressed in https://github.com/thin-edge/thin-edge.io/issues/1030.
