### ISSUE TITLE
main CI fails, but cannot reproduce

### ISSUE THREAD

**Issue by matthiasbeyer** [thin-edge/thin-edge.io#869]
**Describe the bug**

[This CI test fails](https://github.com/thin-edge/thin-edge.io/runs/5182384115?check_suite_focus=true#step:7:718), the commit that introduced this CI fail was 69242dee1f85ffdf44c5a9bfef6b073eb435bc7d which merged #854.

I cannot reproduce this failure locally, though:

```console
$ cargo test --manifest-path crates/core/tedge_agent/Cargo.toml  agent_state_repository_exists_store

running 1 test
test state::tests::agent_state_repository_exists_store ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 7 filtered out; finished in 0.00s
```

**Expected behavior**

Tests fail both locally and on CI, or succeed both locally and on CI. Short: Tests do not differ between CI and locally.

**Comment by PradeepKiruvale** [comment]
@matthiasbeyer Does it pass if you re-run the workflow?

**Comment by matthiasbeyer** [comment]
Seems like it did so far (`install-and-use-rpi` not yet done, but `Run cargo test features` completed).

That's even worse of course!

**Comment by rina23q** [comment]
- Will have a short look
- Then if necessary, disable this test

**Comment by PradeepKiruvale** [comment]
Tried reproducing the issue, but could not reproduce it.
Summary of what the test doing is
- Create a agent/current-operations directory in /tmp directory
- Write `operation_id =  1234` into this file
- Create an AgentStateRepository using the above file
- And store the repo with operation id i.e 1234 and an operation type `SoftwareOperationVariants::List`
- Readback the string from he file
- And  `assert_eq!(data, "operation_id = \'1234\'\noperation = \'list\'\n")`

I feel no need to disable this one for now. If we find it failing once again the CI we can take a call.

**Comment by didier-wenzek** [comment]
Looking at the test, I would simply remove these two lines:

```
        // let content = "operation_id = 1234";
        // let _ = tokio::fs::write(&destination_path, content.as_bytes()).await;
```

Indeed:
* These lines are unrelated to the tests (the code under test doesn't read the former content of the file).
* They simply add a bit of randomness, since we don't know when the file is flushed.
   There is chance to over-write the content written by the code under test.
