### ISSUE TITLE
tedge_agent fails to start when there is no sm-plugins directory

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#882]
**Describe the bug**
When there is no `sm-plugins` directory in `/etc/tedge` the `tedge_agent` fails to start.
The error message is not verbose enough to say what is exactly missing.

**To Reproduce**
To reproduce, remove the `sm-plugins` directory if it already exists in `/etc/tedge` directory.
Then start the tedge_agent as `sudo tedge_agent`

**Expected behavior**
The error message must say what exactly is missing.
For example: Error: I/O error: "`/etc/tedge/sm-plugins` No such file or directory (os error 2)"

**Screenshots**
2022-02-16T05:52:34.034+00:00  INFO tedge_agent::agent: tedge_agent starting
2022-02-16T05:52:34.034+00:00  INFO sm-agent: tedge_agent::agent: Starting tedge agent
Error: I/O error: "No such file or directory (os error 2)"

**Environment (please complete the following information):**
 - OS [ubuntu]
 - Hardware [x64]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io v0.5.2

**Additional context**

AC:
- tedge_agent shouldn`t fail if sm-plugins directory is not there.
- Only print information that there are no sm-plugins installed nor loading
- tedge_agent should point to tedge_agent --init if operations or .agent folder is missing and fail.

**Comment by didier-wenzek** [comment]
There are many directories causing similar issues, not necessarily blocking the agent but letting it half running.

* One needs to list *all* these directories and files (`sm-plugins`, `operations`, `.agent` ... but also those for mosquitto, logs and locks).
* This should not be an error - just a warning - to run the agent without any plugin or operation and even no `sm-plugins` or `operations`. In such a case, there is simply no plugins or no operations.
* These files must be relative to the directory provided by the `--config-dir` option (under review, see  #814). The default location `/etc/tedge` is used when no `--config-dir` is set).
* The `--init` option of the `tedge-agent` must be updated to create these directories if missing.

**Comment by initard** [comment]
The issue is because `sm-plugins` folder is created by cargo-deb [here](https://github.com/thin-edge/thin-edge.io/blob/b73cac276ed0397db43ffe7d97b5202660394b41/plugins/tedge_apt_plugin/Cargo.toml#L12).

**Comment by initard** [comment]
tedge agent fails even if the `sm-plugins` directory is created: 

```shell
ERROR sm-agent: tedge_agent::agent: Couldn't load plugins from /etc/tedge/sm-plugins
Error: Couldn't load plugins from /etc/tedge/sm-plugins
tedge-agent.service: Main process exited, code=exited, status=1/FAILURE
tedge-agent.service: Failed with result 'exit-code'.
```

**Comment by initard** [comment]
@PradeepKiruvale, see #947 for a PR that fixes the error message when the `sm-plugins` directory **exists** but it is empty

**Comment by rina23q** [comment]
The PR is still opened! #971
