### ISSUE TITLE
Issue to connect to c8y with tedge

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#911]
**Describe the bug**

When we connect to C8y something goes wrong. Not sure what happens here in the mechanics of the agent and the mapper.
Maybe also two entities are trying to use the same client ID:

Here are the observations:

When we connect, we observe this message
![image](https://user-images.githubusercontent.com/75477722/154942635-39e3fef2-100b-4e40-8a71-a90f98a4da90.png)

(Unfortunately the return code here is 0)

In the journalctl we observe this

![image](https://user-images.githubusercontent.com/75477722/154944570-b7cad5ec-93d4-49eb-9001-dc9e523fbd57.png)

In the mosquitto log, we observe this:

![image](https://user-images.githubusercontent.com/75477722/154942963-91e4e5c3-0b9c-47ec-8879-62233f08de37.png)

There is also a missing check for return codes in the ci/ci_smoke_test_c8y.sh script (maybe a set -e detected this before). As as side effect with the return code of tedge connect the integration tests workflow passes, but shouldn't.

**To Reproduce**

Build upon main branch (a47fa354cddd558a59c70b8ea77546f00bae59dd)
`sudo tedge connect c8y`

**Expected behavior**
Works :)

**Screenshots**
see above

**Environment (please complete the following information):**
 - OS Debian Bullseye (11),  Raspberry Pi OS 10
 - System-Architecture: 5.10.0-11-rt-amd64
 - thin-edge.io version 0.5.3

**Additional context**
context

**Comment by abelikt** [comment]
Happened probably between : 
9d2122d8775509e14aa519436f86987502ffcd77 (works)
and
c593ac6ebdac0a6eade7b8ed41935684dca4466f (doesn't work)

**Comment by PradeepKiruvale** [comment]
Yes, I also did try, had the same issue.
