### ISSUE TITLE
Improvement of section "How to connect external devices" regarding needed parameters

### ISSUE THREAD

**Issue by mbie-sag** [thin-edge/thin-edge.io#926]
**Is your documentation request related to a problem? Please describe.**
The documentation does not state in a good understandable way what kind of parameters have to be set for allowing external access. 

**Describe the improvement you'd like**
A hint that external port needs to differ from the internal one would be helpful. A validation and error message when executing a not working tedge config set mqtt.external.port would also be helpful. Otherwise mosquitto will crash without a reasonable error message.
Its also not clearly described that the disconnect/connect method needs to be executing again to take over new configurations.

**Additional context**
Add any other context or screenshots about the documentation request here.

**Comment by makr11st** [comment]
Thank you for the report, we would like to invite you to help us with the readability of the documentation and maybe you could post your first Pull Request with the changes you would like to see.

Please follow [contributing guidelines](https://github.com/thin-edge/thin-edge.io#contributing).

**Comment by reubenmiller** [comment]
Closing stale ticket. Please re-open the issue if it is still relevant.
