### ISSUE TITLE
Superflous error message when sw list is larger than 16k

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#928]
**Describe the bug**

There is a leftover error message published to topic tedge/errors in case that the software list is larger than 16k.
We probably can remove it, since we are publishing the list via http.

![image](https://user-images.githubusercontent.com/75477722/155334038-1d52d5f9-4d2d-437d-a940-99013868c8ed.png)

tedge/errors The input size 16601 is too big. The threshold is 16384.

**To Reproduce**
Install many packages :)

AC:
- Don't check for the size

**Comment by rina23q** [comment]
We send software list to Cumulocity via HTTP, so it should not have the size limitation of payload. However, the mqtt payload size check applies to sending software list. This is a bug.

**Comment by albinsuresh** [comment]
Unable to reproduce this issue. PR #859 may have "accidentally" fixed this issue as wel.
