### ISSUE TITLE
Observation: System-test log_request_error_messages fails and leaves an operation in C8y behind

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#931]
**Describe the bug**
This is an observation with a not yet identified root cause:
The test log_request_error_messages fails and leaves an operation behind that we need to cancel manually.
Same thing for : log_request_num_lines -> seems to be a systematic issue.
(same issue in CI)

**To Reproduce**

Within a pysys env:
`pysys.py run log_request_error_messages`
or via
`ci/ci_run_all_tests.sh`

**Expected behavior**

Feature works and test passes :)

**Screenshots**

![image](https://user-images.githubusercontent.com/75477722/155357978-1d9b8d5f-fbd7-47d6-bfcd-7bd704dc0f4f.png)

![image](https://user-images.githubusercontent.com/75477722/155358124-3b9875a9-fe7a-47d4-8e34-f4bd9a8f03a8.png)

![image](https://user-images.githubusercontent.com/75477722/155358310-4bfb913d-11d7-4f69-a805-854452833c78.png)

**Environment (please complete the following information):**
 - OS Debian Bullseye / Rpi OS 
 - thin-edge.io version: Build on top of cae66180e676c5cc1cc94ee576c725d4df0858c5

**Additional context**
context

**Comment by initard** [comment]
Hi @abelikt, I think I know what is causing this. Can you let me know what you see when you run:

 ```shell
cat /etc/tedge/operations/c8y/c8y_LogfileRequest
```

Your output should be something like:

```shell
pi@raspberrypi:~ $ 
[exec]
topic = "c8y/s/ds"
on_message = "522"
command = "/usr/bin/tedge_logfile_request_plugin"
```
