### ISSUE TITLE
Systemd watchdog connector for thin edge

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#953]
## Discussed in https://github.com/thin-edge/thin-edge.io/discussions/933

**Is your feature request related to a problem? Please describe.**

Enable [systemd watchdog](https://www.medo64.com/2019/01/systemd-watchdog-for-any-service/) for tedge daemon processes like tedge-agent, tedge-mapper etc.

**Describe the solution you'd like**

Provide integration with systemd watchdog using a "systemd watchdog connector" daemon that checks the liveness of tedge daemons via their MQTT health endpoints (`tedge/health/<component-name>`) and sends liveness notifications(`systemd-notify` signals) to the systemd service manager at regular intervals (configured as `WatchdogSec` in the monitored services systemd definition file).

**Describe alternatives you've considered**

Building `systemd-notify` mechanism directly into the tedge daemons was ruled out to avoid a hard dependency on systemd.

**AC:**

- The watchdog should be a separate component
- The health check interval for a service is derived from the `WatchdogSec` configuration value in their systemd service definition file (recommended to use half of that value)
- The systemd definition of the tedge daemons must be updated to use these connectors instead of spawning the tedge executables directly.

**Comment by cstoidner** [comment]
> * The "health check timeout" should be configurable with a reasonable default used otherwise

I do not understand what that "health check timeout" is.
   - Which component will consider that timeout? The monitored component? Or the Watchdog connector?
   - What happens when that timeout is gone?

**Comment by matthiasbeyer** [comment]
I don't understand what the desired outcome here is. E.G. what happens if the "liveness" of a daemon is not as expected? Shouldn't [the software be fixed](https://superuser.com/a/689209) to not get "unhealthy" (whatever that means) instead of trying to shift the problem to another entity (in this case systemd)?

**Comment by albinsuresh** [comment]
> I do not understand what that "health check timeout" is.
> 
> * Which component will consider that timeout? The monitored component? Or the Watchdog connector?

The "health check timeout" was supposed to be used by the "watchdog connector" and defines the maximum time it will wait for a health update response from a daemon, after it sends the health check request.

> * What happens when that timeout is gone?

This question made me realise that this configuration parameter is indeed useless. When the connector doesn't get a response in time, it need not do anything. If it doesn't send the `systemd-notify` signal (or do nothing), it will result in the daemon getting restarted by systemd anyway. So, I guess I'll remove that useless config parameter.

**Comment by albinsuresh** [comment]
> I don't understand what the desired outcome here is. E.G. what happens if the "liveness" of a daemon is not as expected? Shouldn't [the software be fixed](https://superuser.com/a/689209) to not get "unhealthy" (whatever that means) instead of trying to shift the problem to another entity (in this case systemd)?

The goal is not to solve/mask genuine bugs in our daemons with the help of systemd (by restarting the daemon),  but to prevent a daemon from getting blocked because of external issues that are out of its control (a plugin that it triggered took too long/never responded). As the agent, is designed to execute certain operations (like software update) only sequentially and not parallelly, we don't want just one operation blocking the agent forever. So, the "declared intent" is to use this watchdog mechanism to get the agent out of such "genuine" blocked states rather than masking the bugs.

But I agree to your point that this might lead to some rare bugs escaping without getting noticed, as a restart might "magically fix things" without anyone noticing. But, I'd still consider that as a good thing, as for the end-user, he'd rather have his system functioning smoothly rather than stalling because of a rare bug. I just hope that someone at some point might notice "too many" service restarts and report it and grab our attention.
