### ISSUE TITLE
Observation: Exit code of the apt plugin when called with no arguments

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#955]
**Describe the bug**

When the apt plugin is called with no arguments the exit code is 2. According to the spec the exit code is more related to the command arguments and should probably be 1.

Exit codes:

https://thin-edge.github.io/thin-edge.io/html/references/plugin-api.html

"1: usage. The command arguments cannot be interpreted, and the command has not been launched.
2: failure. The command failed and there is no point to retry."

/etc/tedge/sm-plugins/apt

**To Reproduce**

`/etc/tedge/sm-plugins/apt`

`sudo -u tedge-agent sudo /etc/tedge/sm-plugins/apt`

`pysys.py run tedge_agent_user_sudo_access`

**Expected behavior**
Exit code is according to spec

**Screenshots**

![image](https://user-images.githubusercontent.com/75477722/156151249-c000b727-2f7e-4629-a49c-aca14e353489.png)

**Comment by PradeepKiruvale** [comment]
The `apt` plugin has been upgraded to use `clap` to parse the arguments from `structopts`
In structopts case the exit status was `1` on error. 

But in case of claps the exit status is `2`.

`Clap::parse`  parses from std::env::args_os(), exit on error

And the exit looks like below

`clap::error::Error
pub fn exit(&self) -> !
Prints the error and exits.
Depending on the error kind, this either prints to stderr and exits with a status of 2 or prints to stdout and exits with a status of 0.`
So,  I feel we should upgrade the `exit status to 2` in the tests.
