### ISSUE TITLE
Removing a software package fails when triggered from the c8y cloud

### ISSUE THREAD

**Issue by PradeepKiruvale** [thin-edge/thin-edge.io#962]
**Describe the bug**
When the request to remove a software package is triggered from c8y cloud
It fails to remove the package that is present in the system.
Once the operation is complete the response is not visible on the cloud UI.

**To Reproduce**
connect to "basic.stage.c8y.io"
Add a software package to the repository (Rolldice)
Trigger the install from the c8y UI
After successfully installed
Trigger request to `remove the package`  from the UI

**Expected behavior**
The `package remove request`  has to be completed successfully and update the UI with the result and the remaining software list should appear on the UI.

**Environment (please complete the following information):**
 - OS [incl. version]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [0.5.3]

**Additional context**

**Comment by reubenmiller** [comment]
@PradeepKiruvale Is this still an issue in tedge 0.8.0?

**Comment by PradeepKiruvale** [comment]
Not sure, Need to verify with the recent `thin-edge` version.

**Comment by PradeepKiruvale** [comment]
It's not reproducible in the 0.8.0 version. So, I will close this ticket.
