### ISSUE TITLE
Upgrading tedge_mapper pakcage stuck when mosquitto stopped

### ISSUE THREAD

**Issue by rina23q** [thin-edge/thin-edge.io#974]
**Describe the bug**
When I tried to upgrade packages from 0.5.3 to 0.5.4, the upgrading `tedge_mapper` package got stuck.

```
Unpacking tedge_mapper (0.5.4) over (0.5.4) ...
Setting up tedge_mapper (0.5.4) ...
2022-03-03T17:35:47.864337456Z  INFO tedge_mapper::c8y::mapper: Initialize tedge mapper session
```

I stoppled local mosquitto process.

**To Reproduce**
- Stop mosquitto process.
- Run `curl -fsSL https://raw.githubusercontent.com/thin-edge/thin-edge.io/main/get-thin-edge_io.sh | sudo sh -s`.

**Expected behavior**
The package installation should be successful regardless of mosquitto process status.

**Screenshots**

**Environment (please complete the following information):**
 - OS [Ubuntu 20.04, amd64]
 - Hardware [incl. revision]
 - System-Architecture [e.g. result of "uname -a"]
 - thin-edge.io version [0.5.4]

**Comment by PradeepKiruvale** [comment]
This is due to the tedge_mapper --init. MQTT broker should be running, else tedge_mapper hangs. I agree if there is no broker, it should quit.
