### ISSUE TITLE
Error: Couldn't acquire file lock.

### ISSUE THREAD

**Issue by abelikt** [thin-edge/thin-edge.io#984]
**Describe the bug**

Error message during installation of tedge-mapper-c8y:

```
2022-03-08T10:34:27.009972774Z ERROR flockfile::unix: Another instance of tedge-mapper-c8y is running.
2022-03-08T10:34:27.010008322Z ERROR flockfile::unix: Lock file path: /var/log/tedge-mapper-c8y.lock
```
Probably the directory /var/log is not the right one.

**To Reproduce**
Install tedge mapper built on top of dd607148665cbaea265211f1442c7ec8e01cc604

**Expected behavior**
Works :)

**Screenshots**

![image](https://user-images.githubusercontent.com/75477722/157224293-bfe8abdd-95fc-41a0-9dff-46dfd5c55201.png)

https://github.com/thin-edge/thin-edge.io/actions/runs/1950813139
https://github.com/abelikt/thin-edge.io/runs/5462782774?check_suite_focus=true

![image](https://user-images.githubusercontent.com/75477722/157224579-861c7c9e-c696-4ea1-bc8b-13f8902203a0.png)

**Comment by rina23q** [comment]
The file path `/var/log/tedge-mapper-c8y.lock` is wrong. Should be `/run/lock/tedge-mapper-c8y.lock`.
