### ISSUE TITLE
Software management feature not working on Ubuntu 20.04 with 0.6-rc build

### ISSUE THREAD

**Issue by albinsuresh** [thin-edge/thin-edge.io#997]
**Describe the bug**

The software list is appearing empty after `tedge connect c8y`. While checking the tedge agent journal logs, I see log messages about permission issues, but with no detail on which file/executable is lacking the permissions. I'm assuming that it's the `apt` plugin.

```
Mar 15 16:01:01 alsu-VirtualBox tedge_agent[2860]: 2022-03-15T10:31:01.678770922Z  INFO sm-agent: plugin_sm::plugin_manager: Plugin activated: /etc/tedge/sm-plugi>
Mar 15 16:01:01 alsu-VirtualBox tedge_agent[2860]: 2022-03-15T10:31:01.680103742Z ERROR sm-agent: tedge_agent::agent: Permission denied (os error 13)
```

Tracing the MQTT requests and responses, it is evident that the software list request is failing as follows:

```
[tedge/commands/req/software/list] {"id":"C5MBtKxjAGE_JkZzZoMdt"}
[tedge/commands/res/software/list] {"id":"C5MBtKxjAGE_JkZzZoMdt","status":"executing"}
[tedge/commands/res/software/list] {"id":"C5MBtKxjAGE_JkZzZoMdt","status":"failed","reason":"Permission denied (os error 13)"}
```

**To Reproduce**

Install the 0.6-rc version of tedge on an Ubuntu 20.04 machine and connect it to Cumulocity. The software list will appear empty.

**Expected behavior**

The software list should contain all apt packages.

**Environment (please complete the following information):**
 - OS [incl. version]: Ubuntu 20.04
 - Hardware [incl. revision]: Virtual machine
 - System-Architecture [e.g. result of "uname -a"]: x86_64
 - thin-edge.io version [e.g. 0.1.0]: 0.6-rc

**Comment by initard** [comment]
This is because default log path is set to /var/log. It is easily fixed if the path is changed to /var/log/tedge/agent
